DOC-261: Folders, Cloning, Debugger content
segmentio/segment-docs pull request #1919
Opened 2021-09-29 20:21 UTC by pwseg

### Proposed changes

Added new content on Folders, Cloning, and the Personas Debugger.

### Merge timing

ASAP

2021-09-29 20:25 UTC, markzegarelli reviewed
@pwseg Since these are net new, you'll need to add them to the main side nav yaml file (src/_data/sidenav/main.yml).

@stayseesong Thoughts on naming here? I know you did work previously with regards to titles and how they fit into the nav.

2021-09-29 20:42 UTC, stayseesong commented
@pwseg for the side-nav titles, I'd use: "Organizing Audiences" and "Personas Space Debugger"

2021-09-29 20:46 UTC, markzegarelli approved these changes

2021-09-29 20:47 UTC, merged

2021-09-29 20:54 UTC, stayseesong requested changes

2021-09-29 20:54 UTC, stayseesong commented on src/personas/audiences/organization.md
> +4. **Optional**: repeat Steps 2 and 3 to move multiple Audiences.
```suggestion
4. *(Optional)* Repeat Steps 2 and 3 to move multiple Audiences.
```

2021-09-29 20:54 UTC, stayseesong commented on src/personas/audiences/organization.md
> +6. **Optional**: on the next screen, connect the Audience to a Destination.  Click **Review & Create**.
```suggestion
6. *(Optional)* On the next screen, connect the Audience to a Destination.  Click **Review & Create**.
```

2021-09-29 20:54 UTC, stayseesong commented on src/personas/audiences/organization.md
> +1. Navigate to the Audiences tab within your Personas space.
```suggestion
1. Navigate to the **Audiences** tab within your Personas space.
```

2021-09-29 20:54 UTC, stayseesong commented on src/personas/audiences/organization.md
> +1. Navigate to the Audiences tab within your Personas space.
```suggestion
1. Navigate to the **Audiences** tab within your Personas space.
```

2021-09-29 20:54 UTC, stayseesong commented on src/personas/audiences/organization.md
> +1. Navigate to the Audiences tab within your Personas space.
```suggestion
1. Navigate to the **Audiences** tab within your Personas space.
```

2021-09-29 20:54 UTC, stayseesong commented on src/personas/audiences/organization.md
> +6. **Optional**: on the next screen, connect the Audience to a Destination.  Click **Review & Create**.
```suggestion
6. *(Optional)* On the next screen, connect the Audience to a Destination.  Click **Review & Create**.
```

2021-09-29 20:54 UTC, stayseesong commented on src/personas/debugger.md
> +Similar to the Connections Debugger, the Personas Debugger allows you to search through events, using information contained within the event's payload.
```suggestion
Similar to the Connections Debugger, the Personas Debugger allows you to search through events using information contained within the event's payload.
```

2021-10-01 03:32 UTC, pwseg commented on src/personas/audiences/organization.md
> +6. **Optional**: on the next screen, connect the Audience to a Destination.  Click **Review & Create**.
Only just seeing these now - great catch(es).  Committing them to our weekly fixes branch.