[index.md] rebrand Wootric to InMoment
segmentio/segment-docs pull request #1940
Opened 2021-09-30 21:12 UTC by tcgilbert

### Proposed changes

The documentation is largely similar, only changed mentions of "Wootric" to "InMoment"

### Merge timing

asap

### Related issues (optional)

Pull Request for changing the Wootric destination docs: https://github.com/segmentio/segment-docs/commit/fa6154264ed8d207263e5fbb9fe04dbfc33f7c1a

2021-09-30 21:50 UTC, stayseesong requested changes

2021-09-30 21:50 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/wootric/index.md
> +[InMoment (formerly Wootric)](https://wootric.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners) is modern customer feedback management software. Easily incorporate Voice of Customer da
```suggestion
[InMoment](https://wootric.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners) (formerly Wootric) is modern customer feedback management software. You can incorporate Voice of Customer data in your decision-making processes and marketing campaigns, and trigger customer follow-up when you send survey responses to your CRM, marketing platform or data warehouses automatically.
```

2021-09-30 21:50 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/wootric/index.md
> +This source is maintained by InMoment. For any issues with the source, [contact the InMoment support team](mailto:support@wootric.com).
```suggestion
InMoment maintains this source. For any issues, [contact the InMoment support team](mailto:support@wootric.com).
```

2021-09-30 21:50 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/wootric/index.md
>  1. From your Segment UI’s Sources page click on “Add Source”.
```suggestion
1. In Segment go to **Connections** and click **Add Source**.
```

2021-09-30 21:50 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/wootric/index.md
> +2. Search for "InMoment" within the Sources Catalog and confirm by clicking "Connect".
```suggestion
2. Search for **InMoment** in the Source Catalog and confirm by clicking **Connect**.
```

2021-09-30 21:50 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/wootric/index.md
>  3. Give the Source a nickname and follow the set up flow to "Add Source". The nickname will be used to designate the source in the Segment interface, and Segment will create a related schema name. Th
```suggestion
3. Give the Source a nickname and click **Add Source**. The nickname is used to designate the source in the Segment interface, and Segment creates a related schema name. The schema name is the namespace you query against in your warehouse. The nickname can be whatever you like, but Segment recommends using a name that reflects the source itself and distinguishes amongst your environments (eg. SourceName_Prod, SourceName_Staging, SourceName_Dev).
```

2021-09-30 21:50 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/wootric/index.md
> +4. Copy the Write key from the Segment UI and log in to your InMoment account - navigate to Settings > Integrations > Send InMoment Data > Send survey responses back to Segment and paste the key to c
```suggestion
4. Go to the **Settings > API Keys**. 
5. Copy the **Write Key** and log in to your InMoment account. 
6. Navigate to **Settings > Integrations > Send InMoment Data > Send survey responses back to Segment** and paste the write key to connect.
```

2021-09-30 21:50 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/wootric/index.md
>  Log into your downstream tools and check to see that your events are populating and they contains all the properties you expect. If all your events and properties are not showing up, refer to the Des
```suggestion
Log into your downstream tools and check to see that your events are populating and they contain all the properties you expect. If all your events and properties are not showing up, refer to the Destination docs for troubleshooting.
```

2021-09-30 21:51 UTC, stayseesong commented
@tcgilbert I noticed that "InMoment" isn't currently a search option in the Source catalog but Wootric still is

2021-10-05 15:32 UTC, markzegarelli commented
@tcgilbert Can you change the name in Partner Portal for this source so that we can merge?

2021-10-05 21:34 UTC, stayseesong approved these changes

2021-10-05 21:35 UTC, merged