Tiktok update
segmentio/segment-docs pull request #2123
Opened 2021-11-08 20:37 UTC by coreyching

### Proposed changes

### Merge timing

### Related issues (optional)

2021-11-08 21:22 UTC, markzegarelli requested changes

2021-11-08 23:13 UTC, coreyching commented on src/connections/destinations/catalog/tiktok-conversions/index.md
> +The table below shows the mapping of the Segment semantic [ecommerce](https://segment.com/docs/connections/spec/ecommerce/v2/) or custom event names to the TikTok semantic conversion event names in t
updated.

2021-11-08 23:14 UTC, coreyching commented on src/connections/destinations/catalog/tiktok-conversions/index.md
> +- Requests report events to one pixel ID. This restriction is because authorization is done at user/pixel level. See the [Authorization](https://ads.tiktok.com/marketing_api/docs?id=1701890912382977)
updated.

2021-11-09 00:58 UTC, markzegarelli approved these changes

2021-11-09 00:58 UTC, merged