Add table explaining
segmentio/segment-docs pull request #2162
Opened 2021-11-18 18:04 UTC by forstisabella

### Proposed changes

Added table explaining how arrays/objects are converted into data points in events tables. 

### Merge timing
No deadline

### Related issues (optional)
[DOC-361](https://segment.atlassian.net/browse/DOC-361)

2021-11-18 18:49 UTC, markzegarelli requested changes
@forstisabella Looks great! I left a few small requests and suggestions.

2021-11-18 18:49 UTC, markzegarelli commented on src/connections/storage/warehouses/schema.md
> +<tr>
@forstisabella If you wrap this in a `<thead>` tag, it will pick up the header styling of other tables to better match.

2021-11-18 18:49 UTC, markzegarelli commented on src/connections/storage/warehouses/schema.md
> +  ``` json
@forstisabella All the code samples have extra spaces, it seems. Can you adjust to use two spaces per tab here for these?

2021-11-18 18:49 UTC, markzegarelli commented on src/connections/storage/warehouses/schema.md
> +In order to preserve the quality of your events data, Segment uses the following methods to store objects and arrays in the event tables:
```suggestion
To preserve the quality of your events data, Segment uses the following methods to store objects and arrays in the event tables: 
```

2021-11-20 01:40 UTC, pwseg approved these changes

2021-11-22 21:58 UTC, markzegarelli approved these changes

2021-11-23 13:13 UTC, merged