Kameleoon updated their HackMD doc - updated docs accordingly
segmentio/segment-docs pull request #2254
Opened 2021-12-06 21:52 UTC by charholt

### Proposed changes

Kameleeon requested to update their docs according to a new hackmd they submitted.

### Merge timing
- ASAP once approved

2021-12-06 21:57 UTC, charholt commented
Hi—Sorry! I was trying to resolve the error, not commit the PR.

2021-12-07 16:47 UTC, stayseesong commented on src/connections/destinations/catalog/kameleoon/index.md
> +[Kameleoon](https://kameleoon.com/en) GDPR, CCPA, and HIPAA compliant, Kameleoon’s powerful and easy-to-use A/B testing, full stack, and AI-powered personalization solutions help marketers, product o
@charholt why was the word 'provides' taken out? This intro sentence reads really strange

2021-12-07 16:52 UTC, stayseesong commented on src/connections/destinations/catalog/kameleoon/index.md
> +First, you will have to request an API Key in order to use Kameleoon & Segment.io integration. You can request it to [support@kameleoon.com](mailto:support@kameleoon.com), by specifying your Kameleoo
```suggestion
Before adding Kameleoon as a destination, you first need to request an API Key in order to use the Kameleoon & Segment.io integration. Send your request it to [support@kameleoon.com](mailto:support@kameleoon.com), and be sure to specify your Kameleoon account login.
```

2021-12-07 16:54 UTC, stayseesong commented on src/connections/destinations/catalog/kameleoon/index.md
> +2. Search for "Kameleoon" in the Destinations Catalog, and select the "Kameleoon" destination.
```suggestion
2. Search for **Kameleoon** in the Destinations Catalog, and select the **Kameleoon** destination.
```

2021-12-07 16:55 UTC, stayseesong commented on src/connections/destinations/catalog/kameleoon/index.md
> +3. Choose which Source should send data to the "Kameleoon" destination.
```suggestion
3. Choose which Source should send data to the **Kameleoon** destination.
```

2021-12-07 17:00 UTC, stayseesong commented on src/connections/destinations/catalog/kameleoon/index.md
> +If you use Kameleoon Experiment or Kameleoon AI Personalization on your website, Kameleoon places a cookie that contains an anonymous unique identifier, called the Kameleoon visitorcode, randomly ass
```suggestion
If you use Kameleoon Experiment or Kameleoon AI Personalization on your website, Kameleoon places a cookie that contains an anonymous unique identifier, called the Kameleoon visitorcode. This ID is randomly assigned to a visitor and is used to uniquely identify a browser.
```

2021-12-07 17:02 UTC, stayseesong commented on src/connections/destinations/catalog/kameleoon/index.md
> +You can either pass our visitorcode in the userId property of the Segment calls to ensure Kameleoon can consolidate data and avoid any analytics discrepancies between the tools in your campaign resul
```suggestion
You can either pass Kameleoon's visitorcode in the userId property of the Segment calls to ensure Kameleoon can consolidate data and avoid any analytics discrepancies between the tools in your campaign results, OR you may specify in all Segment calls an additional user property, `k_visitorCode`, whose value is the Kameleoon visitorcode. You can retrieve the user visitorCode from the browser by using Kameleoon's [Activation API](https://developers.kameleoon.com/activation-api.html#visitor){:target="_blank"}, `Kameleoon.API.Visitor.code`
```

2021-12-07 17:07 UTC, stayseesong commented on src/connections/destinations/catalog/kameleoon/index.md
> +If you are not able to update your existing Segment tracking plan, you can also pass our visitor code in an additional Segment call as follow:`analytics.track('Kameleoon identifier', {'k_visitorCode'
```suggestion
If you are not able to update your existing Segment tracking plan, you can also pass Kameleoon's visitor code in an additional Segment call as follow:`analytics.track('Kameleoon identifier', {'k_visitorCode': Kameleoon.API.Visitor.code});Kameleoon`. This will automatically link your internal user ID or anonymous ID to Kameleoon's own visitorCode. Make sure to call it only once per session.
```

2021-12-07 17:09 UTC, stayseesong commented on src/connections/destinations/catalog/kameleoon/index.md
> +If you use Kameleoon Full Stack, please refer to the [Kameleoon SDK documentation](https://developers.kameleoon.com/sdks-overview.html){:target="_blank"}. We always recommend to use your own internal
```suggestion
If you use Kameleoon Full Stack, please refer to the [Kameleoon SDK documentation](https://developers.kameleoon.com/sdks-overview.html){:target="_blank"}. Kameleoon recommends you to use your own internal ID to identify users.
```

2021-12-07 17:11 UTC, stayseesong commented on src/connections/destinations/catalog/kameleoon/index.md
> +[Kameleoon](https://kameleoon.com/en) GDPR, CCPA, and HIPAA compliant, Kameleoon’s powerful and easy-to-use A/B testing, full stack, and AI-powered personalization solutions help marketers, product o
```suggestion
[Kameleoon’s](https://kameleoon.com/en) powerful and easy-to-use A/B testing, full stack, and AI-powered personalization solutions help marketers, product owners, and developers maximize customer engagement and conversion all from a single platform.
```

2021-12-07 17:14 UTC, stayseesong commented on src/connections/destinations/catalog/kameleoon/index.md
> +You can either pass our visitorcode in the userId property of the Segment calls to ensure Kameleoon can consolidate data and avoid any analytics discrepancies between the tools in your campaign resul
@charholt why was `Kameleoon.API.Visitor.code` added to the end of the paragraph without any context?

2021-12-07 17:17 UTC, stayseesong requested changes
@charholt left some questions that need to be addressed before merging. Thanks!

2021-12-08 17:41 UTC, charholt commented on src/connections/destinations/catalog/kameleoon/index.md
> +[Kameleoon](https://kameleoon.com/en) GDPR, CCPA, and HIPAA compliant, Kameleoon’s powerful and easy-to-use A/B testing, full stack, and AI-powered personalization solutions help marketers, product o
It is strange, and it was taken out.

2021-12-08 17:43 UTC, charholt commented on src/connections/destinations/catalog/kameleoon/index.md
> +You can either pass our visitorcode in the userId property of the Segment calls to ensure Kameleoon can consolidate data and avoid any analytics discrepancies between the tools in your campaign resul
Yes - let me connect with Kameleoon and then address your questions

2021-12-31 17:47 UTC, charholt commented
Hi @stayseesong this is all set. Thank you!

2022-01-04 17:40 UTC, stayseesong approved these changes

2022-01-04 17:40 UTC, merged