Sprig actions
segmentio/segment-docs pull request #2271
Opened 2021-12-10 23:07 UTC by markzegarelli

### Proposed changes
Internal PR for Sprig (Actions) destination

### Merge timing

### Related issues (optional)
#2266 
https://github.com/segmentio/action-destinations/pull/373

2021-12-10 23:12 UTC, markzegarelli commented
@bgila As mentioned, here is the staged PR for this documentation. I've applied the latest version of the template, which will pull data from the destination source.

2021-12-11 01:03 UTC, rchinn-segment requested changes

2021-12-11 01:03 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-sprig-web/index.md
> +## Benefits of <destination_name> (Actions) vs <destination_name> Classic
```suggestion
## Benefits of Sprig (Actions) vs Sprig Classic
```

2021-12-11 01:03 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-sprig-web/index.md
> +5. Find your Environment ID on [Sprig Dashboard > Connect > JavaScript](https://app.sprig.com/connect){:target="_blank"}. Use the Development Environment ID a testing environment, and the Production
```suggestion
5. Find your Environment ID on [Sprig Dashboard > Connect > JavaScript](https://app.sprig.com/connect){:target="_blank"}. Use the Development Environment ID in a testing environment, and the Production Environment ID for your live website environment. Use the appropriate Environment ID. 
```

2021-12-13 19:13 UTC, bgila commented on src/connections/destinations/catalog/actions-sprig-web/index.md
> +5. Find your Environment ID on [Sprig Dashboard > Connect > JavaScript](https://app.sprig.com/connect){:target="_blank"}. Use the Development Environment ID a testing environment, and the Production
Thanks for the typo fix. Can you use this wording instead though, I think it's clearer.

`5. Find your Environment ID on [Sprig Dashboard > Connect > JavaScript](https://app.sprig.com/connect){:target="_blank"}. Use the Development Environment ID for a testing environment, and the Production Environment ID for your live website environment. When configuring the destination, input the appropriate Environment ID.`

2021-12-13 19:14 UTC, bgila commented
@rchinn-segment those changes look good -- I can't update this PR myself, so feel free to make them (I suggested a different wording for one of the steps)

2021-12-13 20:45 UTC, bgila approved these changes
awesome thanks so much

2021-12-15 23:23 UTC, merged

2022-01-10 21:19 UTC, bgila reviewed
added a couple notes for requested edits/refreshing the content/tables now that the integration is deployed!

2022-01-10 21:19 UTC, bgila commented on src/connections/destinations/catalog/actions-sprig-web/index.md
> +This destination is maintained by Sprig. For any issues with the destination, contact [support@sprig.com](mailto:support@sprig.com).
Can we change this to the following, linking Sprig's documentation as well?

`This destination is maintained by Sprig. For any issues with the destination, consult [Sprig's documentation](https://docs.sprig.com/docs/segment-web) or contact [support@sprig.com](mailto:support@sprig.com).`

2022-01-10 21:19 UTC, bgila commented on src/connections/destinations/catalog/actions-sprig-web/index.md
> +{% include components/actions-fields.html %}
now that the destination has been deployed, can we refresh this so that the table/details about available actions appears?

Also, it looks like the info about pre-built subscriptions got removed from the previous version of the PR -- would be great to add it back if possible -- https://github.com/segmentio/segment-docs/pull/2266/files#diff-333652033f03db7008587a92b3df6d5678045b07fea728266cf02edc1813ba9cR50

2022-01-11 01:08 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-sprig-web/index.md
> +This destination is maintained by Sprig. For any issues with the destination, contact [support@sprig.com](mailto:support@sprig.com).
Hi @bgila, Yes we will update this as requested.

2022-01-11 01:10 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-sprig-web/index.md
> +{% include components/actions-fields.html %}
@bgila The existing content was removed, however the destination is not yet publicly available, so the programmatic content (presets, actions, etc.) is not populating. Until the destination becomes available, we will restore the existing content.

2022-01-14 20:18 UTC, bgila commented
thank you @markzegarelli and @rchinn-segment! It looks much better now. I do think the two `Available Actions` sections could be removed, because `Available Sprig Actions` already shows the list of actions, but we could revisit this after the destination becomes publicly available.