Add note to hubspot docs about event tester
segmentio/segment-docs pull request #2286
Opened 2021-12-15 21:20 UTC by kdaswani

### Proposed changes
We've been getting a lot of tickets about the Hubspot event tester not working which is expected due to how identify calls and group calls need to be sent together and in order, otherwise group calls fail. A docs update will help clarify this to customers.

### Merge timing
- ASAP once approved

### Related issues (optional)
https://segment.atlassian.net/browse/DEST-3601

2021-12-15 22:11 UTC, markzegarelli requested changes
Just some rewording of the note.

2021-12-15 22:11 UTC, markzegarelli commented on src/connections/destinations/catalog/hubspot/index.md
> +> The HubSpot destination does not work with Segment's Event Tester due to how identify and group calls must be sent in order. The Event Tester should not be used for troubleshooting the HubSpot dest
```suggestion
> The HubSpot destination is not compatible with the Segment Event Tester. The HubSpot destination does not send Identify and Group calls in order, as required by the Event tester. As result, Segment recommends using other tools to troubleshoot the HubSpot destination.
```

2021-12-15 22:20 UTC, kdaswani commented on src/connections/destinations/catalog/hubspot/index.md
> +> The HubSpot destination does not work with Segment's Event Tester due to how identify and group calls must be sent in order. The Event Tester should not be used for troubleshooting the HubSpot dest
Thanks! I think this line is incorrect `The HubSpot destination does not send Identify and Group calls in order, as required by the Event tester.` It's the opposite. Our HubSpot destination DOES send those in order, but the Event Tester cannot chain two events (you just send one at a time, so if you try to send a Group call it fails). Maybe we remove this detail.

2021-12-16 01:08 UTC, markzegarelli approved these changes

2021-12-16 01:09 UTC, merged