Friendbuy cloud destination
segmentio/segment-docs pull request #2416
Opened 2022-01-26 22:13 UTC by dhull

### Proposed changes

This PR adds documentation for the new Friendbuy cloud destination, and makes minor updates to the documentation for the Friendbuy web destination.

### Merge timing

This PR should be merged when the Friendbuy cloud destination is released.

### Related issues (optional)

This is the PR for the Friendbuy cloud destination:
https://github.com/segmentio/action-destinations/pull/428

2022-01-28 17:18 UTC, rchinn-segment requested changes

2022-01-28 17:42 UTC, rchinn-segment commented
Hi @dhull, thanks for the contribution! I couldn't make additional edits directly to the PR, so I left some suggested changes for review.

2022-01-31 21:25 UTC, rchinn-segment approved these changes

2022-02-01 21:08 UTC, jinapark202 commented
This PR can be merged now

2022-02-01 22:47 UTC, markzegarelli approved these changes

2022-02-01 22:48 UTC, markzegarelli commented
Merging to an intermediate branch for deploy.

2022-02-01 22:48 UTC, merged