Warehouse doc updates
segmentio/segment-docs pull request #2533
Opened 2022-02-23 20:30 UTC by forstisabella

### Proposed changes

Updated the warehouses documentation based on the feedback in the [_Pipeline related tickets - Docs update_ document](https://paper.dropbox.com/doc/Pipeline-related-tickets-Docs-update--BccNKPYZvwBUQ7ezTRPwgVbgAQ-9iizSIAyE9eThyAc3ZKQM)

### Merge timing
With a regular docs release, after approval. 

### Related issues (optional)
N/A

2022-02-24 17:22 UTC, markzegarelli approved these changes

2022-02-24 17:22 UTC, markzegarelli commented on src/connections/storage/warehouses/faq.md
> +Segment highly recommends scripting any sort of additions of data you might have to warehouse, so that you aren't doing one-off tasks that can be hard to recover from in the future in the case of har
```suggestion
Segment recommends scripting any sort of additions of data you might have to warehouse, so that you aren't doing one-off tasks that can be hard to recover from in the future in the case of hardware failure.
```

2022-02-24 17:22 UTC, markzegarelli commented on src/connections/storage/warehouses/faq.md
> +Segment will automatically load up to two months of your historical data when you connect a warehouse.
```suggestion
Segment loads up to two months of your historical data when you connect a warehouse.
```

2022-02-24 17:22 UTC, markzegarelli commented on src/connections/storage/warehouses/faq.md
> +If you enabled activity notifications for your storage destination, you will receive notifications in the Segment app when your warehouse syncs fail.
```suggestion
If you enabled activity notifications for your storage destination, you'll receive notifications in the Segment app when warehouse syncs fail.
```

2022-02-25 23:52 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +Below you'll find a library of some of the most useful SQL queries customers use in their Redshift warehouses. You can run these right in your Redshift instance with little to no modification.
```suggestion
Below you'll find a library of some of the most useful SQL queries customers use in their Redshift warehouses. You can run these in your Redshift instance with little to no modification.
```

2022-02-25 23:53 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +> If you're looking to improve the speed of your queries, check out Segment's [Speeding Up Redshift Queries](/docs/connections/storage/warehouses/redshift-tuning/) page!
```suggestion
> If you're looking to improve the speed of your queries, check out Segment's [Speeding Up Redshift Queries](/docs/connections/storage/warehouses/redshift-tuning/) page.
```

2022-02-25 23:53 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +The track allows you to record any actions your users perform. A track call takes three parameters: the userId, the event, and any optional properties.
Track call?

2022-02-25 23:55 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +This is because the track method (for client-side libraries) automatically includes additional properties of the event, like `event_id`, `sent_at`, and `user_id`!
```suggestion
This is because the track method (for client-side libraries) includes additional properties of the event, like `event_id`, `sent_at`, and `user_id`!
```

2022-02-25 23:56 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +That query will return a table like this:
```suggestion
That query returns a table like this:
```

2022-02-25 23:56 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +If you wanted to see how many pants and shirts were sold on each of those dates, you can query that using case statements:
```suggestion
To see the number of pants and shirts that were sold on each of those dates, you can query that using case statements:
```

2022-02-25 23:57 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +## Defining sessions
```suggestion
## Define sessions
```

2022-02-25 23:58 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +For more on why Segment doesn't collect session data at the API level, [check out a blog post here](https://segment.com/blog/facts-vs-stories-why-segment-has-no-sessions-api/)!
```suggestion
For more on why Segment doesn't collect session data at the API level, [check out a blog post here](https://segment.com/blog/facts-vs-stories-why-segment-has-no-sessions-api/){:target="_blank"}.
```
We can be formal / conversational in tone, but we should avoid using exclamation points.

2022-02-25 23:59 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +Each of Segment's SQL partners allows you to define sessions based on your specific business needs. With [Looker](https://looker.com), for example, you can take advantage of their persistent derived
```suggestion
Each of Segment's SQL partners allow you to define sessions based on your specific business needs. With [Looker](https://looker.com){:target="_blank"}, for example, you can take advantage of their persistent derived tables and LookML modeling language to layer sessionization on top of your Segment SQL data. Segment recommends [checking out Looker's approach here](https://segment.com/blog/using-sql-to-define-measure-and-analyze-user-sessions/).
```

2022-02-26 00:01 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +For defining sessions with raw SQL, a great query and explanation comes from [Mode Analytics](https://mode.com).
```suggestion
To define sessions with raw SQL, a great query and explanation comes from [Mode Analytics](https://mode.com).
```
Please avoid the gerund as much as possible.

2022-02-26 00:02 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +Here’s the query to make it happen, but definitely check Mode Analytics' [blog post](https://blog.modeanalytics.com/finding-user-sessions-sql/) as well. They walk you through the reasoning behind the
```suggestion
Here’s the query to make it happen, but read Mode Analytics' [blog post](https://blog.modeanalytics.com/finding-user-sessions-sql/) for more information. Mode walks you through the reasoning behind the query, what each portion accomplishes, how you can tweak it to suit your needs, and the kinds of further analysis you can add on top of it.
```

2022-02-26 00:02 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +## Identifying users
```suggestion
## Identify users
```

2022-02-26 00:03 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +The `identify` method ties user attributes to a `userId`.
```suggestion
The Identify method ties user attributes to a `userId`. 
```

Consistency with Track above. The format for these should be:
- Identify call
- Identify method

2022-02-26 00:04 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +If you want to see what your users looked like at a previous point in time, that data is right there in your `identifies` table! (To get this table for your users, replace ‘initech’ in the SQL query
```suggestion
If you want to see what your users looked like at a previous point in time, you can find that data in the `identifies` table. To get this table for your users, replace ‘initech’ in the SQL query with your source slug.
```

2022-02-26 00:06 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +But what if you only want to see the most recent state of the user? Luckily, you can convert the `identifies` table into a distinct users table by taking the most recent identify call for each accoun
```suggestion
But what if you only want to see the most recent state of the user? Take the most recent Identify call for each account to convert the `identifies` table into a distinct users table.
```
Took a stab at making the sentence a bit more active-voice.

2022-02-26 00:06 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +### Converting the identifies table into a users table
```suggestion
### Convert the identifies table into a users table
```

2022-02-26 00:07 UTC, markzegarelli commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +The following query will return your `identifies` table:
```suggestion
The following query returns the `identifies` table: 
```

2022-02-26 00:15 UTC, markzegarelli requested changes
Great job on this so far!

I want to point out a few things I found consistently throughout, especially in the new page:
- Inconsistency with the way in which calls and methods are formatted. It should be Track call or Track method.
- Try to avoid using the gerund as much as possible. It helps readability and makes the statement more active. For example. `For defining sessions` -> `To define sessions`.
- Please stay in the present tense. Instead of describing what something _will_ do, describe what it _does_ do.
- Please avoid exclamation points. They may exist in other areas of the documentation, but we've made a big effort to remove them over the last year plus.
- It's not always concrete, but more often than not, you can skip adverbs that end in `ly`. `definitely`, `actually`, `currently`.

2022-02-28 17:30 UTC, forstisabella commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +The track allows you to record any actions your users perform. A track call takes three parameters: the userId, the event, and any optional properties.
Fixed in commit 2c0ec6a8bb6dfeb1972843928e2933ee34c5a092.

2022-03-01 13:21 UTC, forstisabella commented on src/connections/storage/warehouses/redshift-useful-sql.md
> +But what if you only want to see the most recent state of the user? Luckily, you can convert the `identifies` table into a distinct users table by taking the most recent identify call for each accoun
(Hopefully) resolved in commit 4c1c4c2e9d996d6d95eee6a6d65f1cc84dc38a92.

2022-03-02 12:40 UTC, grazilenehan commented on src/connections/storage/warehouses/faq.md
> +## Can I be notified on warehouse sync failures?
Can we please add here that customers that sign up for notifications in the Notifications tab in app will receive notifications for partial and full failures on the 5th and 20th consecutive failures? Thanks

2022-03-02 12:41 UTC, grazilenehan commented on src/connections/storage/warehouses/faq.md
> +## How is my data formatted in my warehouse?
Can we please mention that data will always be snake cased? Thanks!

2022-03-02 12:43 UTC, grazilenehan commented on src/connections/storage/warehouses/faq.md
> +Yes! If your syncs fail, you will need to ask for a backfill, as this is a manual process.
This is incorrect. Our warehouse syncs are incremental, and we'll keep a copy of the data coming through the customer's source in our own internal buckets. Once a successful sync takes place again, we'll automatically load all of the missed data since the last successful sync, so there's no need for a backfill.

2022-03-02 12:46 UTC, grazilenehan commented on src/connections/storage/warehouses/faq.md
> +## Can I change my schema names once they've been created?
We can link this to the section where we talk about tweaking things on the warehouses side on the doc. From within the Segment app, we'll store schema names under each source's SQL Settings, and changing the name there will cause the schema to be split into two from that moment onwards. In order to change a schema name with no disruptions, these are the steps we would recommend:

Disable the warehouse in the Segment UI: Warehouse > Settings > Basic
Rename the schema in Segment in your source settings: Sources > Settings > SQL Settings
Rename the schema in your actual warehouse to the new name
Re-enable the warehouse

Thanks!

2022-03-02 12:47 UTC, grazilenehan commented on src/connections/storage/warehouses/schema.md
> +`<source>.<collection>.<property>` eg. `segment-engineering.tracks.userId`, where Source refers to the source or project name (segment-engineering), collection refers to the event (tracks), and the p
I'd probably snake_case this to `segment_engineering.tracks.user_id` instead. Thanks!

2022-03-02 12:49 UTC, grazilenehan commented on src/connections/storage/warehouses/schema.md
> +Data types are set up in your warehouse based on the first value that comes in from a source. For example, if the first value that came in from a source was a string, Segment sets the data type in th
This is great, I'd probably just add a footnote to contact support if they need a certain data type to be changed. Thanks!

2022-03-15 18:27 UTC, markzegarelli approved these changes

2022-03-16 13:41 UTC, merged