Documentation update for Android and iOS
segmentio/segment-docs pull request #2657
Opened 2022-03-25 10:26 UTC by umangmoe

### Proposed changes
Updated APIs for MoEngage Android and iOS integration.

### Merge timing
- On a specific date? 30th March 2022

### Related issues (optional)

2022-03-26 00:56 UTC, rchinn-segment requested changes
Thanks for the contribution @umangmoe! Just suggested a few small changes. 
As requested, I can merge this 3/30 and it will be deployed to our docs site the next day.

2022-03-26 00:56 UTC, rchinn-segment commented on src/connections/destinations/catalog/moengage/index.md
> + To install with SPM use the https://github.com/moengage/MoEngage-Segment-iOS.git and set the branch as master or version as 7.0.0 and above.
```suggestion
 To install with SPM use the [MoEngage-Segment-iOS](https://github.com/moengage/MoEngage-Segment-iOS.git){:target="_blank"} library and set the branch as master or version as 7.0.0 and above.
```

2022-03-26 00:56 UTC, rchinn-segment commented on src/connections/destinations/catalog/moengage/index.md
> +To make the App compliant with policies i.e,GDPR while using our SDK, follow the doc in this [link](https://developers.moengage.com/hc/en-us/articles/4403905438228-SDK-initialisation){:target="_blank
```suggestion
To make the App compliant with policies (such as GDPR) while using MoEngage's SDK, follow the instructions in this [doc](https://developers.moengage.com/hc/en-us/articles/4403905438228-SDK-initialisation){:target="_blank"}.
```

2022-03-28 10:55 UTC, umangmoe commented on src/connections/destinations/catalog/moengage/index.md
> + To install with SPM use the https://github.com/moengage/MoEngage-Segment-iOS.git and set the branch as master or version as 7.0.0 and above.
updated.

2022-03-28 10:55 UTC, umangmoe commented on src/connections/destinations/catalog/moengage/index.md
> +To make the App compliant with policies i.e,GDPR while using our SDK, follow the doc in this [link](https://developers.moengage.com/hc/en-us/articles/4403905438228-SDK-initialisation){:target="_blank
Updated.

2022-03-29 22:20 UTC, rchinn-segment approved these changes

2022-03-30 15:29 UTC, merged