Introducing the new Log Purchases Action
segmentio/segment-docs pull request #2730
Opened 2022-04-08 18:22 UTC by nielst

Ship date of the feature still pending - would love review/edit of the steps in advance

### Proposed changes

### Merge timing

Sometime in May, TBD

### Related issues (optional)

2022-05-03 22:36 UTC, stayseesong requested changes

2022-05-03 22:36 UTC, stayseesong commented on src/connections/destinations/catalog/actions-amplitude/index.md
> +4. Enable the Log Purchases mapping
```suggestion
Instances created after x/y have both Log Event and Log Purchase configured.  For instances created prior to x/y, you need to manually add the Log Purchases Action to report purchases to Amplitude. 

To manually add the Log Purchases Action: 
1. Add a new Mapping for the Log Purchases Action. The default trigger for this action is Order Completed events.
2. Modify the Trigger if you need to report purchases for any other events.
3. Modify the Trigger of Log Event to exclude these same events. This helps you to avoid sending the same event twice. 
4. Enable the Log Purchases mapping. 
```

2022-05-03 22:37 UTC, stayseesong commented on src/connections/destinations/catalog/actions-amplitude/index.md
> +4. Enable the Log Purchases mapping
@nielst I have the same question as Mark. Is `x/y` supposed to represent a date? If so, what date is it?

2022-05-03 22:47 UTC, nielst commented on src/connections/destinations/catalog/actions-amplitude/index.md
> +4. Enable the Log Purchases mapping
thanks for your help here! yup its a date, should be in a week or so

2022-08-29 23:44 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-amplitude/index.md
> +Instances created after x/y have both Log Event and Log Purchase configured.  For instances created prior to x/y, you need to manually add the Log Purchases Action to report purchases to Amplitude.
```suggestion
For instances created prior to before the Log Purchases action was released, you need to manually add the Log Purchases Action to report purchases to Amplitude. 
```

2022-08-29 23:45 UTC, markzegarelli approved these changes

2022-08-29 23:45 UTC, merged