Add Mailmodo to Segment Doc
segmentio/segment-docs pull request #2747
Opened 2022-04-13 14:28 UTC by sneha-shashidhar

### Proposed changes

Added the Segment documentation for Mailmodo, post reviewing the Dev Center integration submission. 

### Merge timing

- ASAP once approved

### Related issues (optional)

None

2022-04-20 22:19 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +[Mailmodo](https://www.mailmodo.com/){:target="_blank"} is a powerful email marketing tool focused on bringing the interactive experience of the AMP framework to emails. It allows businesses to creat
```suggestion
[Mailmodo](https://www.mailmodo.com/){:target="_blank"} is an email marketing tool that focuses on bringing the interactive experience of the AMP framework to emails. It allows businesses to create emails with web page-like interactivity right inside the user inbox, thereby increasing engagement and conversions multi-fold.
```

2022-04-20 22:20 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +This destination is maintained by Mailmodo. For any issues with the destination, [contact the Mailmodo Support team](mailto:help@mailmodo.com).
```suggestion
Mailmodo maintains this destination. For any issues with the destination, [contact the Mailmodo Support team](mailto:help@mailmodo.com).
```

2022-04-20 22:35 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +2. Search for "Mailmodo" in the Destinations Catalog, and select the "Mailmodo" destination.
```suggestion
2. Search for **Mailmodo** in the Destinations Catalog, and select the **Mailmodo** destination.
```

2022-04-20 22:36 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +3. Choose which Source should send data to the "Mailmodo" destination.
```suggestion
3. Choose which Source should send data to the Mailmodo destination.
```

2022-04-20 22:49 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +4. Go to the [Mailmodo Dashboard](https://manage.mailmodo.com/app/dashboard), navigate to **Settings > API Keys**, then create a new API Key and copy the same.
```suggestion
4. Go to the [Mailmodo Dashboard](https://manage.mailmodo.com/app/dashboard){:target="_blank"} and navigate to **Settings > API Keys**, then create a new API Key and copy it.
```

2022-04-20 22:51 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +5. Enter the "API Key" in the "Mailmodo" destination settings in Segment.
```suggestion
5. Enter the API Key in the Mailmodo destination settings in Segment.
```

2022-04-20 23:13 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +If you aren’t familiar with the Segment Spec, take a look at the [Identify method documentation](/docs/connections/spec/identify) to learn about what it does.
```suggestion
Take a look at the [Identify method documentation](/docs/connections/spec/identify) to learn about what it does.
```

2022-04-20 23:21 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +Every time you call identify with an email address included, Mailmodo:
```suggestion
Every time you make an identify call with an email address included:
```

2022-04-20 23:22 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +1.	Verifies that the email exists.
```suggestion
1.	Mailmodo verifies that the email exists.
```

2022-04-20 23:22 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +2.	If the email doesn’t exist, Mailmodo adds the user as a Contact to the Mailmodo database and matches user properties with the Segment `traits` sent in identify call payload.
```suggestion
2.	If the email doesn’t exist, Mailmodo adds the user as a contact to the Mailmodo database and matches user properties with the Segment `traits` sent in the identify call payload.
```

2022-04-20 23:30 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +3.	If the email exists, Mailmodo updates the user properties for the Contact against the Segment `traits` sent in identify call payload.
```suggestion
3.	If the email exists, Mailmodo updates the user properties for the Contact against the Segment `traits` sent in the identify call payload.
```

2022-04-20 23:43 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +All the [special traits](/docs/connections/spec/identify#traits) recognized by Segment will be translated and matched with the Mailmodo user properties for a Contact. These fields will be automatical
```suggestion
All the [special traits](/docs/connections/spec/identify#traits) recognized by Segment are translated and matched with the Mailmodo user properties for a Contact. These fields are automatically created or mapped for a Contact in Mailmodo and are available for personalization and advance segmentation.
```

2022-04-20 23:59 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +> 1. The email field is required. Identify calls without an email are dropped.
```suggestion
> * The email field is required. Mailmodo drops identify calls without an email.
```

2022-04-21 00:00 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +> 2. If different email addresses are sent against same user id in identify call, Mailmodo treats them as two different contacts.
```suggestion
> * If different email addresses are sent against the same user ID in identify call, Mailmodo treats them as two different contacts.
```

2022-04-21 00:00 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +If you aren’t familiar with the Segment Spec, take a look at the [Track method documentation](/docs/connections/spec/track) to learn about what it does. An example call would look like:
```suggestion
Take a look at the [Track method documentation](/docs/connections/spec/track) to learn about what it does. An example call looks like:
```

2022-04-21 00:01 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +Segment sends `Track` calls to Mailmodo as a Custom Event. When you call  track, Segment sends the event to Mailmodo with the event name and all properties that you specified.
```suggestion
Segment sends `Track` calls to Mailmodo as a Custom Event. When you call track, Segment sends the event to Mailmodo with the event name and all properties that you specified.
```

2022-04-21 00:01 UTC, stayseesong commented on src/connections/destinations/catalog/mailmodo/index.md
> +Be sure you send an Identify call for any user who will trigger Track calls. If Mailmodo receives a Track call for an unknown userId, the call is dropped.
```suggestion
Be sure you send an Identify call for any user who triggers Track calls. If Mailmodo receives a Track call for an unknown userId, the call drops.
```

2022-04-21 00:04 UTC, stayseesong requested changes
just a couple of suggested edits

2022-04-21 16:03 UTC, markzegarelli approved these changes

2022-04-21 16:26 UTC, stayseesong approved these changes

2022-04-21 16:27 UTC, merged