Draft of GA4 changes
segmentio/segment-docs pull request #2787
Opened 2022-04-22 22:04 UTC by kdaswani

### Proposed changes
More updates to GA4 as our integration and Google's API advances. We are making another change next week so would like to hold off on publishing this until I've got everything in here.

### Merge timing
- Depending on a specific project - TBD when we finish [this ticket](https://segment.atlassian.net/browse/STRATCONN-1315) and I update the section on users and sessions accordingly

2022-04-27 23:50 UTC, kdaswani commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
> +If you choose to integrate with Google Analytics 4 client-side (using Gtag outside of Segment) _and_ also use Segment's Google Analytics 4 destination to send events through the API, you can also tra
```suggestion
If you choose to integrate with Google Analytics 4 client-side (using Gtag outside of Segment) _and_ also use Segment's Google Analytics 4 destination to send events through the API, you can track sessions server-side. When using Gtag, [Google generates a `session_id` and `session_number` when a session begins](https://support.google.com/analytics/answer/9191807?hl=en){:target='_blank'}. The `session_id` and `session_number` can be passed as Event Parameters to Google Analytics 4 to stitch events sent through the API with the same session that was collected client-side.
```

2022-04-27 23:50 UTC, kdaswani commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
> +> warning ""
```suggestion
> warning ""
```

2022-04-27 23:52 UTC, kdaswani commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
> +If you choose to integrate with Google Analytics 4 client-side (using Gtag outside of Segment) _and_ also use Segment's Google Analytics 4 destination to send events through the API, you can also tra
Waiting on Google to update their API docs so we can add a link.

2022-04-29 22:08 UTC, kdaswani commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
> +> Google does not support passing other reserved fields, such as [predefined user dimensions](https://support.google.com/analytics/answer/9268042?hl=en&ref_topic=11151952){:target='_blank'} or device
```suggestion
> Google does not currently support passing other reserved fields, such as [predefined user dimensions](https://support.google.com/analytics/answer/9268042?hl=en&ref_topic=11151952){:target='_blank'} or device-specific information, to the Measurement Protocol API.
```

2022-04-29 22:08 UTC, kdaswani commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
> +> Google Analytics 4 does not officially support a pure server-to-server integration, however Segment continues to monitor the capabilities of the Measurement Protocol API and make updates accordingl
```suggestion
> Google Analytics 4 does not officially support a pure server-to-server integration, however Segment continues to monitor the capabilities of the Measurement Protocol API and will make updates accordingly to achieve a reasonable level of reporting for our mutual customers. Segment does not have plans to build a device-mode integration with Gtag for Google Analytics 4.
```

2022-04-29 22:10 UTC, kdaswani commented
@markzegarelli @stayseesong this is ready for review! Thank you!

2022-05-02 17:23 UTC, rchinn-segment reviewed
Looks good to me! Just left a few suggested changes.

2022-05-02 17:23 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
>  When you have Segment installed, you can use your existing tracking implementation to fulfill your data collection needs with Google Analytics 4. Segment will send your data server-side to [Google's
```suggestion
When you have Segment installed, you can use your existing tracking implementation to fulfill your data collection needs with Google Analytics 4. Segment will send your data server-side to [Google's Measurement Protocol API](https://developers.google.com/analytics/devguides/collection/protocol/ga4){:target='_blank'}.
```

2022-05-02 17:23 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
> +> Google Analytics 4 does not officially support a pure server-to-server integration, however Segment continues to monitor the capabilities of the Measurement Protocol API and will make updates accor
```suggestion
> Google Analytics 4 doesn't officially support a pure server-to-server integration. However, Segment monitors the capabilities of the Measurement Protocol API and updates accordingly to achieve a reasonable level of reporting for mutual customers. Segment doesn't plan to build a device-mode integration with Gtag for Google Analytics 4.
```

2022-05-02 17:23 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
>  > In all cases, event names in GA4 are case sensitive. The Custom Event action includes a **Lowercase Event Name** option, to ensure consistency of all events sent to Google. For more information, se
```suggestion
> In all cases, event names in GA4 are case sensitive. The Custom Event action includes a **Lowercase Event Name** option, to ensure consistency of all events sent to Google. For more information, see Google's articles [Google Analytics 4 event name rules](https://support.google.com/analytics/answer/10085872?hl=en&ref_topic=9756175#event-name-rules){:target='_blank'} and [Event name limitations](https://developers.google.com/analytics/devguides/collection/protocol/ga4/sending-events?client_type=firebase){:target="_blank"}.
```

2022-05-02 17:23 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
> +With Google Analytics 4, you must create custom dimensions and metrics within the Google Analytics 4 interface and link parameters to the corresponding dimension or metric. When creating the dimensio
```suggestion
With Google Analytics 4, you must create custom dimensions and metrics within the Google Analytics 4 interface and link parameters to the corresponding dimension or metric. When creating the dimension or metric, you can either select a parameter from the list of already collected fields or enter the name of the parameter you plan to collect in the future. Custom dimensions can be either event-scoped or user-scoped, and custom metrics must always be event-scoped. To send parameters to Google Analytics 4, use the Event Parameters or User Properties object available on every action. Only pass flat key-value pairs in the Event Parameters and User Properties objects. Google silently drops any events that include nested parameters.
```

2022-05-02 17:23 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
>  To achieve parity with Universal Analytics, you will probably want to create the same custom dimensions that you defined in Universal Analytics. Additionally, many of the values that you tracked as e
```suggestion
To achieve parity with Universal Analytics, you'll probably want to create the same custom dimensions that you defined in Universal Analytics. Additionally, many of the values that you tracked as event dimensions in Universal Analytics, particularly event category and event label, should be recreated in Google Analytics 4 as custom dimensions. For more information, see Google’s [Google Analytics 4 Custom dimensions and metrics](https://support.google.com/analytics/answer/10075209){:target='_blank'}.
```

2022-05-02 17:23 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
> +#### Tracking Active Users & Sessions
```suggestion
#### Tracking Active Users and Sessions
```

2022-05-02 17:23 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
> +> Session tracking server-side only works if you are also sending data to Google Analytics 4 client-side. This is because the `session_id` must match a value that was previously collected on the clie
```suggestion
> Session tracking server-side only works if you're also sending data to Google Analytics 4 client-side. This is because the `session_id` must match a value that was previously collected on the client. Events still have to arrive within a 48 hour window of when the client-side events arrived, for them to be stitched properly.
```

2022-05-02 17:23 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
> +> Google does not currently support passing other reserved fields, such as [predefined user dimensions](https://support.google.com/analytics/answer/9268042?hl=en&ref_topic=11151952){:target='_blank'}
```suggestion
> Google doesn't currently support passing other reserved fields, such as [predefined user dimensions](https://support.google.com/analytics/answer/9268042?hl=en&ref_topic=11151952){:target='_blank'} or device-specific information, to the Measurement Protocol API.
```

2022-05-02 17:23 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
>  #### Custom Dimensions & Metrics
```suggestion
#### Custom Dimensions and Metrics
```

2022-05-02 17:44 UTC, kdaswani commented
Thank you @rchinn-segment! Applied the changes!

2022-05-02 20:09 UTC, stayseesong requested changes

2022-05-02 20:09 UTC, stayseesong commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
> +> Session tracking server-side only works if you're also sending data to Google Analytics 4 client-side. This is because the `session_id` must match a value that was previously collected on the clien
```suggestion
> Session tracking server-side only works if you're also sending data to Google Analytics 4 client-side. This is because the `session_id` must match a value that was previously collected on the client. For events to stitch properly, they must arrive within a 48 hour window of when the client-side events arrived.
```

2022-05-02 20:30 UTC, kdaswani commented on src/connections/destinations/catalog/actions-google-analytics-4/index.md
> +> Google Analytics 4 does not officially support a pure server-to-server integration, however Segment continues to monitor the capabilities of the Measurement Protocol API and will make updates accor
Already accepted a different update to this that I think works!

2022-05-02 22:19 UTC, stayseesong approved these changes

2022-05-02 22:31 UTC, kdaswani commented
Thanks for approving @stayseesong! Can we merge this in since that it can be part of tomorrow's deploy?

2022-05-02 22:39 UTC, markzegarelli approved these changes

2022-05-02 22:45 UTC, rchinn-segment approved these changes

2022-05-02 23:20 UTC, merged