Update documentation about testing
segmentio/segment-docs pull request #2917
Opened 2022-05-18 14:30 UTC by g-normand

### Proposed changes

I add some informations about not sending to Segment while testing

2022-05-18 17:25 UTC, markzegarelli requested changes

2022-05-18 17:25 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/server/python/index.md
> +If you don't want to send Segments informations while testing, you need to add in your test:
```suggestion
If you don't want to send information to Segment during testing, add the following code to your test:
```

2022-05-18 19:49 UTC, g-normand commented on src/connections/sources/catalog/libraries/server/python/index.md
> +If you don't want to send Segments informations while testing, you need to add in your test:
Sorry, i'm not used to  github PR interface. Thanks for the review :)

2022-05-19 16:12 UTC, markzegarelli approved these changes

2022-05-19 16:13 UTC, merged