[index.md] add docs for new partner destination Skalin
segmentio/segment-docs pull request #2929
Opened 2022-05-19 17:26 UTC by tcgilbert

### Proposed changes

add docs for new partner destination Skalin

### Merge timing
asap

### Related issues (optional)

n/a

2022-05-19 20:39 UTC, stayseesong requested changes

2022-05-19 20:39 UTC, stayseesong commented on src/connections/destinations/catalog/skalin/index.md
> +Send [Page](/docs/connections/spec/page) calls to *feature*. For example:
Is it intended to say *feature* here and for the Screen and Track sections?

2022-05-19 20:39 UTC, stayseesong commented on src/connections/destinations/catalog/skalin/index.md
> +Send [Identify](/docs/connections/spec/identify) calls to *identity*. For example:
Is it right to say "calls to *identity*"?

2022-05-19 21:05 UTC, stayseesong commented
@tcgilbert I left some comments that could use some clarification

2022-05-20 14:42 UTC, tcgilbert commented
@stayseesong addressed all of your points in the last couple of commits. Please let me know if you have any other questions!

2022-05-24 15:58 UTC, stayseesong approved these changes

2022-05-24 16:44 UTC, markzegarelli approved these changes

2022-05-25 23:20 UTC, merged