adding metronome-actions docs and folder
segmentio/segment-docs pull request #3002
Opened 2022-06-07 21:17 UTC by mcough2

Proposed changes
I created new docs (segment-docs/src/connections/destinations/catalog/actions-metronome/index.md) for the new Metronome (Actions) destination

Merge timing
Depending on a specific project? These changes (adding the new docs) should be merged once the new destination is live

Related issues (optional)

2022-06-08 15:43 UTC, cozmo commented on src/connections/destinations/catalog/actions-metronome/index.md
> +- **Clearer mapping of data** Actions-based destinations enable you to define the mapping between the data Segment receives from your source, and the data Segment sends to Metronome.
This section shouldn't be needed I think because 


1. The legacy integration isn't live, so it's not visible to anyone.
2. We're migrating the clients on the legacy destination off of it as part of the rollout of the actions destination.

2022-06-08 17:51 UTC, marinhero commented on src/connections/destinations/catalog/actions-metronome/index.md
> +id:
```suggestion
id: 61a8032ea5f157ee37a720be
```

2022-06-08 18:44 UTC, markzegarelli requested changes

2022-06-08 18:44 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-metronome/index.md
> +With [Metronome](https://www.metronome.com){:target="_blank"}, you can enable product-led growth with a consistent source of truth for usage and billing. You can also freely experiment with pricing a
```suggestion
[Metronome](https://www.metronome.com){:target="_blank"} enables product-led growth with a consistent source of truth for use and billing. Freely experiment with pricing and packaging and put iteration directly in the hands of your Product team.
```

Let's avoid two consecutive sentences that start with "With Metronome..."

2022-06-08 18:44 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-metronome/index.md
> +
Will make this a table prior to deploy.

2022-06-08 18:45 UTC, markzegarelli commented
Thanks @mcough2 and @cozmo!

These look to be in a good state. I've left a few comments, but it's largely ready to go. Prior to deploy, I'll add the snippet which will build out the Settings and Actions tables.

2022-06-08 20:07 UTC, mcough2 commented on src/connections/destinations/catalog/actions-metronome/index.md
> +- **Clearer mapping of data** Actions-based destinations enable you to define the mapping between the data Segment receives from your source, and the data Segment sends to Metronome.
Made changes in the commit below

2022-06-09 21:35 UTC, markzegarelli approved these changes

2022-06-10 16:45 UTC, mcough2 commented
@markzegarelli two questions
1. Now that this is approved what is the next step to get our connection/destination live?
2. What's the best way to get this PR merged now that it is approved

2022-06-10 21:33 UTC, markzegarelli commented
> @markzegarelli two questions
> 
> 1. Now that this is approved what is the next step to get our connection/destination live?
> 2. What's the best way to get this PR merged now that it is approved

Hi @mcough2, I'll merge the docs PR today, and they will deploy with our next documentation deploy on Tuesday. 

As for the integration itself, I see that it's in Private Beta status right now. Segment Support should be able to provide guidance on next steps with regards to testing the destination to move it to Public Beta or Public Status. Once this is done, the documentation will be publicly available as well.

2022-06-10 21:39 UTC, merged