add Orb destination documentation
segmentio/segment-docs pull request #3119
Opened 2022-06-27 14:33 UTC by tcgilbert

### Proposed changes

add Orb destination documentation

### Merge timing
asap

### Related issues (optional)
n/a

2022-06-27 20:14 UTC, stayseesong commented on src/connections/destinations/catalog/orb/index.md
> +This destination is maintained by Orb. For any issues with the destination, [Contact the Orb support team](mailto:support@withorb.com).
```suggestion
Orb maintains this destination. For any issues with the destination, [contact the Orb support team](mailto:support@withorb.com).
```

2022-06-27 22:22 UTC, stayseesong requested changes

2022-06-27 22:22 UTC, stayseesong commented on src/connections/destinations/catalog/orb/index.md
> +Events ingested via the track spec will be available on the Orb admin dashboard, specifically on the [Events page](https://app.billwithorb.com/events).
```suggestion
Events ingested through the track spec are available on the Orb admin dashboard, specifically on the [Events page](https://app.billwithorb.com/events).
```

2022-06-28 16:28 UTC, markzegarelli approved these changes

2022-06-28 16:30 UTC, merged