Update Hotjar destination docs
segmentio/segment-docs pull request #3137
Opened 2022-06-29 14:00 UTC by Maguna

Reflect latest changes (events support), remove mentions of tools no longer available in Hotjar, among other updates.

### Proposed changes

### Merge timing

### Related issues (optional)

2022-06-29 20:53 UTC, stayseesong requested changes

2022-06-29 20:53 UTC, stayseesong commented on src/connections/destinations/catalog/hotjar/index.md
> +3. Automatically send [custom events](https://help.hotjar.com/hc/en-us/articles/4405109971095-Events-API-Reference) to Hotjar by connecting your Segment `track` calls with Hotjar's own Events API.
```suggestion
1. Automatically install the [Hotjar Tracking Code](https://help.hotjar.com/hc/en-us/articles/115011639927){:target="_blank"}.
2. Automatically send [user attributes](https://help.hotjar.com/hc/en-us/articles/360033640653-Identify-API-Reference){:target="_blank"} to Hotjar by connecting your Segment `identify` calls with Hotjar's own Identify API.
3. Automatically send [custom events](https://help.hotjar.com/hc/en-us/articles/4405109971095-Events-API-Reference){:target="_blank"} to Hotjar by connecting your Segment `track` calls with Hotjar's own Events API.
```

2022-06-29 20:53 UTC, stayseesong commented on src/connections/destinations/catalog/hotjar/index.md
> +Knowing who your users are and what they're doing unlocks much more advanced filtering and targeting capabilities across all of Hotjar's tools, helping you find meaningful insights much faster.
```suggestion
Knowing who your users are and what they're doing unlocks more advanced filtering and targeting capabilities across all of Hotjar's tools, helping you find meaningful insights faster.
```

2022-06-29 20:53 UTC, stayseesong commented on src/connections/destinations/catalog/hotjar/index.md
> +1. From the Segment web app, click **Catalog**;
```suggestion
1. Navigate to **Connections** and click **Add Destination** From the Segment web app.
```

2022-06-29 20:53 UTC, stayseesong commented on src/connections/destinations/catalog/hotjar/index.md
> +2. Search for "Hotjar" in the Catalog, select it, and choose which of your Javascript sources to connect the destination to;
```suggestion
2. Search for *Hotjar* in the Catalog, select it, and choose the Javascript source you want to connect the destination to.
```

2022-06-29 20:53 UTC, stayseesong commented on src/connections/destinations/catalog/hotjar/index.md
> +3. Add your **Hotjar Site ID** to your Destination settings. You can find this ID (e.g. 123456) in Account settings > Sites & Organizations;
```suggestion
3. Add your **Hotjar Site ID** to your Destination settings. You can find this ID in Account settings > Sites & Organizations.
```

2022-06-29 20:53 UTC, stayseesong commented on src/connections/destinations/catalog/hotjar/index.md
> +The Hotjar destination will automatically ingest a User ID and any values sent over your Identify spec as [traits](/docs/connections/spec/identify/#traits), as long as session capture and user attrib
```suggestion
The Hotjar destination automatically ingests a User ID and any values sent over your Identify spec as [traits](/docs/connections/spec/identify/#traits), as long as session capture and user attributes are both enabled in Hotjar.
```

2022-06-29 20:53 UTC, stayseesong commented on src/connections/destinations/catalog/hotjar/index.md
> +As of July 2022, the Hotjar Identify API does not yet support ingesting values passed as nested objects or lists over your identify Spec:
Do we need to call out the date? Can't we just have it say: 
"The Hotjar Identify API doesn't support ingesting values passed as nested objects or lists over your identify Spec."

2022-06-29 20:53 UTC, stayseesong commented on src/connections/destinations/catalog/hotjar/index.md
> +In the example above, Hotjar would reject all the values in the `address` field.
```suggestion
In the example above, Hotjar rejects all the values in the `address` field.
```

2022-06-29 20:53 UTC, stayseesong commented on src/connections/destinations/catalog/hotjar/index.md
> +The Hotjar destination will automatically ingest any user actions tracked over your Track spec as [events](/docs/connections/spec/track/), as long as session capture is enabled in Hotjar.
```suggestion
The Hotjar destination automatically ingests any user actions tracked over your Track spec as [events](/docs/connections/spec/track/), as long as session capture is enabled in Hotjar.
```

2022-06-30 16:55 UTC, Maguna commented on src/connections/destinations/catalog/hotjar/index.md
> +As of July 2022, the Hotjar Events API does not yet support ingesting event properties:
What about something like "Currently, the Hotjar Events API doesn't support ingesting event properties:"

But don't feel strongly about it

2022-06-30 16:56 UTC, Maguna reviewed
All looks good, thanks for the quick review 👍

2022-07-01 10:12 UTC, Maguna commented on src/connections/destinations/catalog/hotjar/index.md
> +As of July 2022, the Hotjar Identify API does not yet support ingesting values passed as nested objects or lists over your identify Spec:
Updated the copy

2022-07-01 22:43 UTC, markzegarelli approved these changes

2022-07-01 22:43 UTC, markzegarelli commented
Thanks @Maguna! We'll roll these changes out with our next deploy on July 5.

2022-07-01 22:45 UTC, markzegarelli approved these changes

2022-07-01 22:51 UTC, merged

2022-07-06 09:10 UTC, Maguna commented
@markzegarelli hey quick question could we remove this as well from the page - and ideally from the in-app wizard as well? We don't support it anymore.
<img width="626" alt="image" src="https://user-images.githubusercontent.com/22102349/177513289-82933d10-c4aa-4a9c-802c-4863e2a289de.png">