rokt destination docs
segmentio/segment-docs pull request #3198
Opened 2022-07-11 13:26 UTC by tcgilbert

### Proposed changes

add docs for new destination

### Merge timing
asap

### Related issues (optional)
n/a

2022-07-11 23:10 UTC, stayseesong requested changes

2022-07-11 23:10 UTC, stayseesong commented on src/connections/destinations/catalog/rokt-integration/index.md
> +The Rokt-Segment destination optimizes campaign performance by integrating conversion attribution for Rokt Ads. By integrating this conversion data, you’ll unlock a suite of intelligent tools that le
```suggestion
The Rokt destination optimizes campaign performance by integrating conversion attribution for Rokt Ads. By integrating this conversion data, you’ll unlock a suite of intelligent tools that learn from every conversion, constantly making adjustments to improve campaign targeting and bidding.
```

2022-07-11 23:10 UTC, stayseesong commented on src/connections/destinations/catalog/rokt-integration/index.md
> +This destination is maintained by Rokt. If you have any issues, please contact [Rokt support team](https://rokt.atlassian.net/servicedesk/customer/portal/20/group/98).
```suggestion
This destination is maintained by Rokt. If you have any issues, please contact the [Rokt support team](https://rokt.atlassian.net/servicedesk/customer/portal/20/group/98){:target="_blank"}.
```

2022-07-11 23:10 UTC, stayseesong commented on src/connections/destinations/catalog/rokt-integration/index.md
> +2. Search for “Rokt” in the Destinations Catalog. Select the “Rokt Integration” destination.
```suggestion
2. Search for “Rokt” in the Destinations Catalog, and select the integration.
```

2022-07-11 23:10 UTC, stayseesong commented on src/connections/destinations/catalog/rokt-integration/index.md
> +3. Choose which source should send data to the “Rokt Integration” destination.
```suggestion
3. Choose which source should send data to the Rokt destination.
```

2022-07-11 23:10 UTC, stayseesong commented on src/connections/destinations/catalog/rokt-integration/index.md
> +Once you've entered the API credentials for Rokt, the chosen source will send data through to Rokt's API.
```suggestion
Once you've entered the API credentials for Rokt, the chosen source sends data through to Rokt's API. 
```

2022-07-11 23:10 UTC, stayseesong commented on src/connections/destinations/catalog/rokt-integration/index.md
> +The `track` API call is how you record any actions your users perform, along with any properties that describe the action. Read more [here](https://segment.com/docs/connections/spec/track/).
```suggestion
The `track` API call is how you record any actions your users perform, along with any properties that describe the action. [Learn more about the track call](/docs/connections/spec/track/). 
```

2022-07-12 13:43 UTC, tcgilbert commented on src/connections/destinations/catalog/rokt-integration/index.md
> +2. Search for “Rokt” in the Destinations Catalog. Select the “Rokt Integration” destination.
@stayseesong so I agree that "Rokt Integration" does not flow well, but this is actually the name for this destination on our backend. Meaning they will see "Rokt Integration"  show up when searching for this in a segment workspace. 

With that in mind I think we should keep it as is, but I am open to suggestions.

2022-07-12 16:04 UTC, markzegarelli commented on src/connections/destinations/catalog/rokt-integration/index.md
> +2. Search for “Rokt” in the Destinations Catalog. Select the “Rokt Integration” destination.
@tcgilbert Do you know if this naming was intentional? It does not match the format of other integration names in the system. I agree that the article should match the actual name of the destination, but we may want to suggest a rename here.

2022-07-12 21:15 UTC, markzegarelli commented on src/connections/destinations/catalog/rokt-integration/index.md
> +2. Search for “Rokt” in the Destinations Catalog. Select the “Rokt Integration” destination.
@tcgilbert Got it, thanks for the background. I don't want to delay this for docs reasons, was just curious.

2022-07-12 21:20 UTC, tcgilbert commented on src/connections/destinations/catalog/rokt-integration/index.md
> +2. Search for “Rokt” in the Destinations Catalog. Select the “Rokt Integration” destination.
@markzegarelli Gotcha. yeah they are keen on launching this sooner than later. 

we can go ahead and go with this name, and if they want to change in the future, I can come back and update this.

2022-07-13 16:56 UTC, stayseesong approved these changes

2022-07-13 17:08 UTC, merged