Typewriter 2.0 [DOC-557]
segmentio/segment-docs pull request #3253
Opened 2022-07-20 22:24 UTC by stayseesong

### Proposed changes

### Merge timing
When the feature goes out

### Related issues (optional)

2022-07-20 23:10 UTC, stayseesong commented
@oscb Under the [Editor Configuration](https://deploy-preview-3253--segment-docs.netlify.app/protocols/apis-and-extensions/typewriter/) section, should the iOS and Android headers be changed to Swift and Kotlin?

2022-07-20 23:52 UTC, markzegarelli reviewed
Good draft!

I left a few comments  / suggestions related to active vs passive voice, but content-wise, lgtm.

There is also an instance of we / our on line 473, which I couldn't comment on directly because it's not part of the diff.

2022-07-20 23:52 UTC, markzegarelli commented on src/protocols/apis-and-extensions/typewriter.md
> +Typewriter uses the event to generate a typed analytics call in different languages:
I like this edit, but it makes the statement on line 8 incomplete.

2022-07-20 23:52 UTC, markzegarelli commented on src/protocols/apis-and-extensions/typewriter.md
> +To help you minimize your bundle size, Typewriter supports [tree-shaking](https://webpack.js.org/guides/tree-shaking/){:target="_blank"} using named exports. All generated analytics calls are automat
```suggestion
To help you minimize your bundle size, Typewriter supports [tree-shaking](https://webpack.js.org/guides/tree-shaking/){:target="_blank"} using named exports. All generated analytics calls generate and export automatically, so you can import them like so:
```
Just a thought, I think you can make the sentence more active and remove an adjective.

2022-07-20 23:52 UTC, markzegarelli commented on src/protocols/apis-and-extensions/typewriter.md
> +Typewriter wraps your analytics calls in an [ES6 `Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy){:target="_blank"}, which helps protect your applicati
```suggestion
Typewriter wraps your analytics calls in an [ES6 `Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy){:target="_blank"}, which helps protect your application from crashing if you make analytics calls with a generated function that doesn't exist. For example, if an `Order Completed` event didn't exist in your Tracking Plan in the first example above, then your app would crash with a `TypeError: typewriter.orderCompleted is not a function`. However, since `typewriter` dynamically proxies the underlying function calls, it can detect if a function doesn't exist, and handle it for you. Typewriter logs a warning message, then fires an `Unknown Analytics Call Fired` event into your source. This is useful when you migrate JavaScript projects to Typewriter in bulk, since it gives Segment confidence that Segment won't introduce regressions that crash the application. Keep in mind that proxying does not work with named exports.
```

"...it gives Segment confidence that Segment won't..." Is this correct? It reads as confusing to me that Segment needs to give it self confidence.

2022-07-20 23:52 UTC, markzegarelli commented on src/protocols/apis-and-extensions/typewriter.md
> +Typewriter wraps your analytics calls in an [ES6 `Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy), which helps protect your application from crashing i
Same as above

2022-07-20 23:52 UTC, markzegarelli commented on src/protocols/apis-and-extensions/typewriter.md
> +After adding the generated client to your Xcode Project you will be able to use it from Swift as extension methods on any Analytics client object:
```suggestion
When you add the generated client to your Xcode Project you can use as a Swift extension method on any Analytics client object:
```

Active voice.

2022-07-20 23:52 UTC, markzegarelli commented on src/protocols/apis-and-extensions/typewriter.md
> +3. Typewriter comes with a quickstart wizard that generates a [`typewriter.yml`](#configuration-reference) configuration, along with your first Typewriter client. Running the command creates a `typew
```suggestion
3. Typewriter comes with a quickstart wizard that generates a [`typewriter.yml`](#configuration-reference) configuration, along with your first Typewriter client. The command creates a `typewriter.yml` file in your repo. For more information on the format of this file, see the [Typewriter Configuration Reference](#configuration-reference). To use this wizard, run:
```
It might also read more clearly to list the command first, since you reference it in the step, and then explain what it does.

2022-07-20 23:52 UTC, markzegarelli commented on src/protocols/apis-and-extensions/typewriter.md
> +By default Typewriter creates the class file with a package name of `typewriter`. Segment recommends you to set up the right package name during `npx typewriter init` by choosing to review the additi
```suggestion
Typewriter creates the class file with a package name of `typewriter`. Segment recommends you to set up the right package name during `npx typewriter init` by choosing to review the additional options for Kotlin. You can also set up the right package name directly in `typewriter.yml`:
```
Nitpicking a bit here, is the package name something that someone simply enters in the config wizard? If so, it might be more clear to say `Segment recommends that you enter the correct package name...` rather than `set up the right package name`

2022-07-20 23:52 UTC, markzegarelli commented on src/protocols/apis-and-extensions/typewriter.md
> +You can regenerate your Typewriter client by running `npx typewriter`. You need to do this each time you update your Tracking Plan. Running the command creates a `typewriter.yml` file in your repo. F
```suggestion
Run `npx typewriter` to regenerate your Typewriter client. You need to do this each time you update your Tracking Plan. This command creates a `typewriter.yml` file in your repo. For more information on the format of this file, see the [Typewriter Configuration Reference](#configuration-reference). The command also adds a new Typewriter / Segment client in `./analytics` (or whichever path you configured). You can use this interchangeably as a normal React Native Segment client. It contains additional methods for your tracking plan:
```

Active voice

2022-07-20 23:52 UTC, markzegarelli commented on src/protocols/apis-and-extensions/typewriter.md
> +Typewriter requires a Segment API token to fetch Tracking Plans from the [Segment Public API](https://api.segmentapis.com/docs/).
Does this update work only with PAPI? If not, we should list both options, and explain that PAPI is in beta.

2022-07-20 23:52 UTC, markzegarelli commented on src/protocols/apis-and-extensions/typewriter.md
> +> If you're using the previous version of Typewriter that fetches tracking plans from the [Segment Config API](/docs/config-api/) and would like to upgrade to the new version of Typewriter, generate
```suggestion
> If you use a previous version of Typewriter that fetches tracking plans from the [Segment Config API](/docs/config-api/) and would like to upgrade to the new version of Typewriter, generate a new API token by following the steps below.
```

2022-07-20 23:52 UTC, markzegarelli commented on src/protocols/apis-and-extensions/typewriter.md
> +You configure this by creating a token script called `scripts.token` in your `typewriter.yml`. This script is a string that contains a shell command that, when executed, outputs a valid Segment API t
```suggestion
To configure this, create a token script called `scripts.token` in your `typewriter.yml`. This script is a string that contains a shell command that, when executed, outputs a valid Segment API token. Here's an **insecure**, example:
```

2022-07-20 23:52 UTC, markzegarelli commented on src/protocols/apis-and-extensions/typewriter.md
> +Typewriter currently only supports `track` calls. However, you can continue to use the underlying (untyped) analytics instance to perform `identify`, `group`, `page`, `screen`, and `alias` calls.
```suggestion
Typewriter supports `track` calls. However, you can continue to use the underlying (untyped) analytics instance to perform `identify`, `group`, `page`, `screen`, and `alias` calls.
```

2022-07-20 23:52 UTC, markzegarelli commented on src/protocols/apis-and-extensions/typewriter.md
> +Segment is always curious about any feedback you have on your experience with Typewriter! To contact Segment, [open an issue on GitHub](https://github.com/segmentio/typewriter/issues/new).
Can you rewrite this to get rid of the `!`?

"Segment welcomes feedback you may have on your experience with Typewriter." or something.

2022-07-21 17:59 UTC, oscb approved these changes

2022-07-21 23:13 UTC, stayseesong commented on src/protocols/apis-and-extensions/typewriter.md
> +Segment is always curious about any feedback you have on your experience with Typewriter! To contact Segment, [open an issue on GitHub](https://github.com/segmentio/typewriter/issues/new).
```suggestion
Segment welcomes feedback you may have on your experience with Typewriter. To contact Segment, [open an issue on GitHub](https://github.com/segmentio/typewriter/issues/new).
```

2022-07-25 18:55 UTC, stayseesong commented on src/protocols/apis-and-extensions/typewriter.md
> +3. Typewriter comes with a quickstart wizard that generates a [`typewriter.yml`](#configuration-reference) configuration, along with your first Typewriter client. Running the command creates a `typew
```suggestion
3. Run `npx typewriter init`. This command enables you to use the Typewriter quickstart wizard that generates a [`typewriter.yml`](#configuration-reference) configuration, along with your first Typewriter client. The command creates a `typewriter.yml` file in your repo. For more information on the format of this file, see the [Typewriter Configuration Reference](#configuration-reference).
```

2022-07-25 18:56 UTC, stayseesong commented on src/protocols/apis-and-extensions/typewriter.md
> +3. Typewriter comes with a quickstart wizard that generates a [`typewriter.yml`](#configuration-reference) configuration, along with your first Typewriter client. Running the command creates a `typew
@oscb how's this 👆

2022-07-25 19:22 UTC, stayseesong commented on src/protocols/apis-and-extensions/typewriter.md
> +By default Typewriter creates the class file with a package name of `typewriter`. Segment recommends you to set up the right package name during `npx typewriter init` by choosing to review the additi
```suggestion
Typewriter creates the class file with the package name `typewriter`. Segment recommends you to enter the right package name during `npx typewriter init` by choosing to review the Advanced Options for Kotlin. You can also set up the right package name directly in `typewriter.yml`:
```

2022-07-25 19:22 UTC, stayseesong commented on src/protocols/apis-and-extensions/typewriter.md
> +By default Typewriter creates the class file with a package name of `typewriter`. Segment recommends you to set up the right package name during `npx typewriter init` by choosing to review the additi
how's this @oscb

2022-07-26 22:35 UTC, stayseesong commented on src/protocols/apis-and-extensions/typewriter.md
>  Not all languages support run-time validation. Currently, `analytics.js` and `analytics-node` support it using [AJV](https://github.com/epoberezkin/ajv) (both for JavaScript and TypeScript projects)
@oscb does Swift and Kotlin support run-time validation?

2022-07-26 22:39 UTC, stayseesong commented on src/protocols/apis-and-extensions/typewriter.md
> +> into ""
```suggestion
> info ""
```

2022-07-26 23:40 UTC, oscb commented on src/protocols/apis-and-extensions/typewriter.md
>  Not all languages support run-time validation. Currently, `analytics.js` and `analytics-node` support it using [AJV](https://github.com/epoberezkin/ajv) (both for JavaScript and TypeScript projects)
No, they don't at the moment. The comment is still valid: only analytics.js and analytics-node have runtime validation

2022-07-26 23:41 UTC, oscb approved these changes
We're targeting release for this Thursday. If all looks good I think we can sync on the release of the new docs!

2022-07-27 05:18 UTC, stayseesong commented on src/protocols/apis-and-extensions/typewriter.md
>  Not all languages support run-time validation. Currently, `analytics.js` and `analytics-node` support it using [AJV](https://github.com/epoberezkin/ajv) (both for JavaScript and TypeScript projects)
Then should I replace analytics-ios and analytics-android with analytics-swift and analytics-kotlin?

2022-07-27 17:41 UTC, oscb commented on src/protocols/apis-and-extensions/typewriter.md
>  Not all languages support run-time validation. Currently, `analytics.js` and `analytics-node` support it using [AJV](https://github.com/epoberezkin/ajv) (both for JavaScript and TypeScript projects)
Ah yes, good point! let's replace those with swift and kotlin

2022-07-27 17:57 UTC, stayseesong commented on src/protocols/apis-and-extensions/typewriter.md
>  Not all languages support run-time validation. Currently, `analytics.js` and `analytics-node` support it using [AJV](https://github.com/epoberezkin/ajv) (both for JavaScript and TypeScript projects)
```suggestion
Not all languages support run-time validation. Currently, `analytics.js` and `analytics-node` support it using [AJV](https://github.com/epoberezkin/ajv){:target="_blank"} (both for JavaScript and TypeScript projects) while `analytics-swift` and `analytics-kotlin` don't support run-time validation. Typewriter also doesn't support run-time validation using Common JSON Schema.
```

2022-08-01 23:03 UTC, oscb approved these changes

2022-08-05 18:13 UTC, markzegarelli requested changes
Few small changes, otherwise, LGTM!

2022-08-05 20:58 UTC, stayseesong commented on src/protocols/apis-and-extensions/typewriter.md
> +4. Run `npx typewriter init` to use the Typewriter quickstart wizard that generates a [`typewriter.yml`](#configuration-reference) configuration, along with your first Typewriter client. When you run
@oscb is this correct?

2022-08-05 22:22 UTC, merged