Clarify retry policies
segmentio/segment-docs pull request #3319
Opened 2022-08-02 22:53 UTC by tysonmote

### Proposed changes

This commit makes the verbiage around our retry policies more accurate because claims around attempt counts are currently out-of-date.

### Merge timing

When approved.

### Related issues (optional)

N/A

2022-08-02 23:04 UTC, markzegarelli requested changes
Thanks @tysonmote!

2022-08-02 23:04 UTC, markzegarelli commented on src/connections/functions/source-functions.md
> +Segment retries invocations that throw RetryError or Timeout errors up to 6 times. After 6 attempts, the request is dropped.
```suggestion
Segment retries invocations that throw RetryError or Timeout errors up to 6 times. After six attempts, the request is dropped.
```

2022-08-02 23:04 UTC, markzegarelli commented on src/partners/faqs.md
> +Segment retries requests for up to 4 hours if they fail due to temporary errors like timeouts, 429 Too Many Request status codes, and 5xx status codes. Segment does not retry requests that fail due t
```suggestion
Segment retries requests for up to four hours if they fail due to temporary errors like timeouts, 429 Too Many Request status codes, and 5xx status codes. Segment does not retry requests that fail due to permanent errors like authentication failures or 4xx status codes.
```

2022-08-02 23:43 UTC, markzegarelli approved these changes

2022-08-03 00:04 UTC, stayseesong commented on src/connections/destinations/catalog/webhooks/index.md
> +Segment will retry any request that fails due to temporary errors like timeouts and 5xx status codes for up to four hours.
```suggestion
Segment retries any request that fails due to temporary errors like timeouts and 5xx status codes for up to four hours.
```

2022-08-03 00:04 UTC, stayseesong approved these changes

2022-08-03 01:04 UTC, merged