Add alias for Swift docs
segmentio/segment-docs pull request #3324
Opened 2022-08-03 15:12 UTC by niallzato

### Proposed changes
A customer wrote in that we do not list the Alias method in our docs. We do mention it in the migration guide, but we are lacking a definition in the main docs: https://segment.com/docs/connections/sources/catalog/libraries/mobile/swift-ios/migration/

2022-08-03 16:28 UTC, stayseesong requested changes

2022-08-03 16:28 UTC, stayseesong commented on src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
> +The [Alias](/docs/connections/spec/alias/) method is used to merge two user identities, effectively connecting two sets of user data as one. When this method is called the `newId` value will overwrit
```suggestion
The [Alias](/docs/connections/spec/alias/) method is used to merge two user identities, effectively connecting two sets of user data as one. When this method is called, the `newId` value overwrites the old `userId`. If no `userId` is currently set, the `newId` associates with future events as the `userId`. This is an advanced method and may not be supported across the entire destination catalog. 
```

2022-08-03 16:53 UTC, stayseesong approved these changes

2022-08-03 16:54 UTC, stayseesong commented
@niallzato I edited the description of alias a bit, lmk what you think

2022-08-04 09:01 UTC, niallzato commented
> 

LGTM ! @stayseesong  you good to merge this?

2022-08-04 16:31 UTC, merged