Segment Datalakes Azure Document Changes.
segmentio/segment-docs pull request #3495
Opened 2022-09-14 19:22 UTC by hrdamani

### Proposed changes

### Merge timing

### Related issues (optional)

2022-09-14 20:40 UTC, Lfdelossantos commented
Change Step 6 bullet point 1 and 2. They shouldn't be sep steps.  
Maybe something like this 

1. Connect to a [Hive metastore](https://docs.databricks.com/data/metastores/external-hive-metastore.html) on your Databricks cluster. The easiest way to do that is by copying the following Spark configuration...

2022-09-14 22:01 UTC, markzegarelli requested changes

2022-09-14 22:01 UTC, markzegarelli commented on src/connections/storage/catalog/data-lakes/index.md
> +Segment supports two type of data-lakes as of now:
```suggestion
Segment supports two type of data-lakes:
```

2022-09-14 22:01 UTC, markzegarelli commented on src/connections/storage/catalog/data-lakes/index.md
> +- [AWS Data Lakes](https://segment.com/docs/connections/storage/catalog/data-lakes/#set-up-segment-data-lakes)
```suggestion
- [AWS Data Lakes](/docs/connections/storage/catalog/data-lakes/#set-up-segment-data-lakes)
```

2022-09-14 22:01 UTC, markzegarelli commented on src/connections/storage/catalog/data-lakes/index.md
> +- [Azure Data Lakes](https://segment.com/docs/connections/storage/catalog/data-lakes/#set-up-azure-data-lakes)
```suggestion
- [Azure Data Lakes](/docs/connections/storage/catalog/data-lakes/#set-up-azure-data-lakes)
```

2022-09-15 16:40 UTC, markzegarelli approved these changes

2022-09-15 16:40 UTC, merged