Scaffold docs for Intercom Web and Cloud Actions
segmentio/segment-docs pull request #3511
Opened 2022-09-15 21:56 UTC by kdaswani

### Proposed changes
Intercom Web (Actions) and Intercom Cloud Mode (Actions) are in private beta. We have not invited any customers yet as Intercom is going to test themselves first. This is just the first version to scaffold the docs. I may make a couple more changes before next Tues (9/20) deploy but otherwise would be great to get this deployed next Tues.

Since these two destinations are in Private Beta, can we make sure that the dossier and other tables (other versions of destination, settings, actions, fields) get pre-populated? Thank you!!

### Merge timing
- On a specific date? 9/19 or 9/20 before 9/20 deploy

2022-09-16 18:13 UTC, stayseesong requested changes

2022-09-16 18:13 UTC, stayseesong commented on src/connections/destinations/catalog/actions-intercom-web/index.md
> +Intercom is a customer communications platform. It shows you who is using your product and makes it easy to personally communicate with your users with targeted content, behavior-driven messages, and
```suggestion
Intercom is a customer communications platform that shows you who is using your product. Intercom also allows you to personally communicate with your users with targeted content, behavior-driven messages, and conversational support.
```

2022-09-16 18:13 UTC, stayseesong commented on src/connections/destinations/catalog/actions-intercom-web/index.md
> +When you use the Intercom Web (Actions) destination, Segment will load the [Intercom JavaScript library](https://developers.intercom.com/installing-intercom/docs/intercom-for-web){:target="_blank"} f
```suggestion
When you use the Intercom Web (Actions) destination, Segment loads the [Intercom JavaScript library](https://developers.intercom.com/installing-intercom/docs/intercom-for-web){:target="_blank"} for you. The Intercom library enables you to track your user’s events on your website and interact with the Intercom messenger window.
```

2022-09-16 18:13 UTC, stayseesong commented on src/connections/destinations/catalog/actions-intercom-web/index.md
> +- **Granular control over data sent.** You can customize the conditions under which the events will be sent to Intercom.
```suggestion
- **Granular control over data sent.** You can customize the conditions under which the events are sent to Intercom. 
```

2022-09-16 18:13 UTC, stayseesong commented on src/connections/destinations/catalog/actions-intercom-web/index.md
> +1. From the Segment web app, click **Catalog**.
```suggestion
1. From the Segment web app, navigate to **Connections > Catalog**.
```

2022-09-16 18:13 UTC, stayseesong commented on src/connections/destinations/catalog/actions-intercom-web/index.md
> +- **Selectively show the Intercom chat widget.**
```suggestion
- **Selectively shows the Intercom chat widget.**
```

2022-09-19 20:08 UTC, kdaswani commented
@stayseesong thanks for your review! I added a couple of FAQs to the Intercom Cloud Mode docs based on some things we found in testing. This is ready to go for tomorrow's deploy please!

2022-09-19 23:10 UTC, stayseesong approved these changes

2022-09-19 23:10 UTC, stayseesong commented on src/connections/destinations/catalog/actions-intercom-cloud/index.md
> +## FAQ & Troubleshooting
```suggestion
## FAQs 
```

2022-09-19 23:10 UTC, stayseesong commented on src/connections/destinations/catalog/actions-intercom-cloud/index.md
> +If a company is created without an attached user, the company will not appear on Intercom's dashboard. This is expected. Once a user is attached to the company, it should appear in the list of compan
```suggestion
If a company is created without an attached user, the company won't appear on Intercom's dashboard. This is expected. Once a user is attached to the company, the company appears in the list of companies.
```

2022-09-19 23:10 UTC, stayseesong commented on src/connections/destinations/catalog/actions-intercom-cloud/index.md
> +When using the Identify Company action, Segment will first create or update a company. In the same action, Segment will also attach the user in your group call to that company. If the user does not e
```suggestion
When using the Identify Company action, Segment first creates or updates a company. In the same action, Segment also attaches the user in your group call to that company. If the user does not exist in Intercom when the action runs, Segment will create and update the company but not attach the user. Please ensure the user is created in Intercom first.
```

2022-09-19 23:14 UTC, merged