Clarify the Identify device-mode functioning
segmentio/segment-docs pull request #3520
Opened 2022-09-19 15:23 UTC by LionelPaulus

### Proposed changes
Clarify that, for an Identify call to create an HubSpot contact, the Page or Track call needs to be done after the Identify one.

### Merge timing
ASAP once approved

### Related issues (optional)

2022-09-19 15:37 UTC, ClementParis016 approved these changes
Good catch 👍🏻

2022-09-19 17:00 UTC, stayseesong requested changes

2022-09-19 17:00 UTC, stayseesong commented on src/connections/destinations/catalog/hubspot/index.md
> +> HubSpot's device-mode integration has two conditions for Identify to create or update a contact. Identify calls must include a `traits.email` value and need to go with a Page or Track call (after t
```suggestion
> HubSpot's device-mode integration has two conditions for Identify to create or update a contact: 1) Identify calls must include a `traits.email` value. 2) A Page or Track call must follow an Identify call. You can read more from [HubSpot's documentation](https://developers.hubspot.com/docs/methods/tracking_code_api/identify_visitor){:target="_blank"}. If you are using HubSpot's cloud-mode integration, an Identify call updates records without the need for a Page or Track call.
```

2022-09-20 21:25 UTC, stayseesong approved these changes

2022-09-22 16:12 UTC, merged