Update Shopify Littledata - Deploy
segmentio/segment-docs pull request #3543
Opened 2022-09-22 16:28 UTC by markzegarelli

### Proposed changes

### Merge timing

### Related issues (optional)
Deploy PR for #3539

2022-09-22 17:14 UTC, stayseesong requested changes

2022-09-22 17:14 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
> +You can customize Littledata's Shopify source from the [data pipeline settings](https://help.littledata.io/posts/data-pipeline-settings/) in the Littledata admin. The general settings affect how we h
Does "we" refer to Segment or Littledata?

2022-09-23 00:29 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
> +You can customize Littledata's Shopify source from the [data pipeline settings](https://help.littledata.io/posts/data-pipeline-settings/) in the Littledata admin. The general settings affect how we h
```suggestion
You can customize Littledata's Shopify source from the [data pipeline settings](https://help.littledata.io/posts/data-pipeline-settings/) in the Littledata admin. The general settings affect how Littledata handles details such as orders, products and pageviews. The more advanced settings include:
```

2022-09-23 00:35 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
> +During the [installation process](https://help.littledata.io/posts/segment-installation-guide/){:target="\_blank"}:
```suggestion
After the [installation process](https://help.littledata.io/posts/segment-installation-guide/){:target="\_blank"}:
```

2022-09-23 00:35 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
>  - Segment's Analytics.js 2.0 library is loaded on all pages, except for the checkout
```suggestion
- Segment's Analytics.js 2.0 library loads on all pages, except for the checkout.
```

2022-09-23 00:36 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
>  - Includes a LittledataLayer data layer for all pages
```suggestion
- All pages Include a LittledataLayer data layer.
```

2022-09-23 00:39 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
> +- All pages Include a LittledataLayer data layer.
```suggestion
- All pages include a LittledataLayer data layer.
```

2022-09-23 00:40 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
>  1. **Login** to your Shopify Store account.
```suggestion
1. **Log in** to your Shopify Store account.
```

2022-09-23 00:41 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
>  7. Segment's **Analytics.js** library, Littledata **tracking script** and **webhooks** will be automatically applied to the store and the installation process will then be complete.
```suggestion
7. Segment's **Analytics.js** library, Littledata **tracking script** and **webhooks** automatically apply to the store and the installation process will then be complete.
```

2022-09-23 00:42 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
>  This data import will include all the [event properties](#event-properties) usually sent with an `Order Completed` event, including the [customer traits](#identify-calls).
```suggestion
This data import includse all the [event properties](#event-properties) usually sent with an `Order Completed` event, including the [customer traits](#identify-calls).
```

2022-09-23 16:23 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
>  Littledata is available as an independent [Shopify App](https://apps.shopify.com/segment-com-by-littledata).
```suggestion
Littledata is available as an independent [Shopify App](https://apps.shopify.com/segment-com-by-littledata){:target="\_blank"}.
```

2022-09-23 16:46 UTC, edwardupton commented on src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
>  This data import will include all the [event properties](#event-properties) usually sent with an `Order Completed` event, including the [customer traits](#identify-calls).
typo in `includse`

2022-09-23 16:47 UTC, edwardupton commented
Just one typo fix and then looks good to me

2022-09-23 18:14 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
>  - Segment's anonymous ID and Google Analytics' client ID is passed to our servers to ensure consistent user journey tracking
```suggestion
- Pages Load a minified tracking script, hosted on a content delivery network (CDN)
- Device-mode e-commerce events can send to all Segment destinations
- Segment's anonymous ID and Google Analytics' client ID passes to Littledata's servers to ensure consistent user journey tracking
```

2022-09-23 18:22 UTC, stayseesong approved these changes

2022-09-26 21:25 UTC, stayseesong approved these changes

2022-09-26 21:25 UTC, merged