Updated Classic and Actions MoEngage Destination.
segmentio/segment-docs pull request #3557
Opened 2022-09-26 12:45 UTC by aekanshd

### Proposed changes

- Updated details on Actions Destination
- Restructured and added more information on the Classic Destination

### Merge timing
ASAP Once Approved

### Related issues (optional)

Refer to related PRs: 
1. https://github.com/segmentio/segment-docs/pull/3395
2. https://github.com/segmentio/segment-docs/pull/3405

2022-09-26 16:23 UTC, markzegarelli requested changes

2022-09-26 16:23 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-moengage/index.md
> +hidden: true
```suggestion
```

2022-09-26 16:23 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-moengage/index.md
> +private: true
```suggestion
```

This destination is publicly available, so we do not want to hide the doc or show private metadata.

2022-09-27 03:02 UTC, aekanshd reviewed
Resolved all changes. Please review.

2022-09-28 22:20 UTC, markzegarelli approved these changes

2022-09-28 22:20 UTC, merged