Update index.md new sprig content
segmentio/segment-docs pull request #3589
Opened 2022-09-30 14:51 UTC by nilssprig

### Proposed changes

### Merge timing

### Related issues (optional)

2022-09-30 20:38 UTC, markzegarelli requested changes

2022-09-30 20:38 UTC, markzegarelli commented on src/connections/destinations/catalog/sprig-cloud/index.md
> +Segment has placed the Classic destination framework in maintenance mode. Sprig encourages all customers to move to the [Sprig Actions](https://segment.com/docs/connections/destinations/catalog/sprig
```suggestion
Segment has placed the Classic destination framework in maintenance mode. Sprig encourages all customers to move to the [Sprig Actions](/docs/connections/destinations/catalog/sprig-web/) destination framework when convenient. 
```

Please use relative URLs for links to other Segment Docs pages.

2022-09-30 20:38 UTC, markzegarelli commented on src/connections/destinations/catalog/sprig-cloud/index.md
> +6. Type in the Environment ID and click Save Changes. You your Environment ID can be found in [Connect > JavaScript](https://app.sprig.com/connect). For for information, click [here](https://docs.spr
```suggestion
6. Type in the Environment ID and click Save Changes. You your Environment ID can be found in [Connect > JavaScript](https://app.sprig.com/connect){:target="_blank". For for information, click [here](https://docs.sprig.com/docs/products-and-environments#environments){:target="_blank"}.
```

2022-09-30 20:38 UTC, markzegarelli commented on src/connections/destinations/catalog/sprig-cloud/index.md
> +[Sprig](https://sprig.com/?&utm_source=segmentio&utm_medium=docs_actions&utm_campaign=integration) is an in-context user research platform that makes it fast and effortless for product teams to learn
```suggestion
[Sprig](https://sprig.com/?&utm_source=segmentio&utm_medium=docs_actions&utm_campaign=integration){:target="_blank"} is an in-context user research platform that makes it fast and effortless for product teams to learn from their actual customers in real-time, through In-Product Surveys, Concept and Usability tests.
```

For links away from Segment Docs, please open them in a new tab.

2022-09-30 21:39 UTC, stayseesong requested changes

2022-09-30 21:39 UTC, stayseesong commented on src/connections/destinations/catalog/sprig-cloud/index.md
>  Sprig maintains this destination. For any issues with the destination, consult [Sprig's documentation](https://docs.sprig.com/docs/segment) or contact [support@sprig.com](mailto:support@sprig.com).
```suggestion
Sprig maintains this destination. For any issues with the destination, consult [Sprig's documentation](https://docs.sprig.com/docs/segment){:target="_blank"} or contact [support@sprig.com](mailto:support@sprig.com).
```

2022-09-30 21:39 UTC, stayseesong commented on src/connections/destinations/catalog/sprig-cloud/index.md
> +1. In the Segment web app, click **Catalog**, then click **Destinations**.
```suggestion
1. In the Segment web app, navigate to **Catalog > Destinations**.
```

2022-09-30 21:39 UTC, stayseesong commented on src/connections/destinations/catalog/sprig-cloud/index.md
> +2. Type Sprig in the **Filter Destinations** field.
```suggestion
2. Type *Sprig* in the **Filter Destinations** field.
```

2022-09-30 21:39 UTC, stayseesong commented on src/connections/destinations/catalog/sprig-cloud/index.md
> +5. Type in a **Destination name**, Select **Classic**, and click **Save**.
```suggestion
5. Enter a **Destination name**, select **Classic**, and click **Save**.
```

2022-10-04 16:42 UTC, stayseesong approved these changes

2022-10-04 16:42 UTC, merged