destination filters [DOC-589]
segmentio/segment-docs pull request #3598
Opened 2022-10-03 21:08 UTC by stayseesong

### Proposed changes

### Merge timing
Oct 18

### Related issues (optional)

2022-10-03 21:25 UTC, markzegarelli requested changes

2022-10-03 21:25 UTC, markzegarelli commented on src/connections/destinations/destination-filters.md
> +You can configure destination filters on cloud-mode destinations as well as on mobile and web device-mode destinations.  With device-mode destinations, you can use the same user interface or API mech
```suggestion
You can configure destination filters on cloud-mode, mobile, and web device-mode destinations.  With device-mode destinations, you can use the same user interface or API mechanism that you use for your cloud-mode destinations, and have those filters acted upon for device-mode destinations on web and mobile.
```

The first sentence here is a bit long

2022-10-03 21:25 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
> +The example projects contain sample [plugins](https://github.com/segmentio/analytics-kotlin/tree/main/samples/kotlin-android-app/src/main/java/com/segment/analytics/next/plugins){:target="_blank"} an
```suggestion
The example projects contain sample [plugins](https://github.com/segmentio/analytics-kotlin/tree/main/samples/kotlin-android-app/src/main/java/com/segment/analytics/next/plugins){:target="_blank"} and [destination plugins](https://github.com/segmentio/analytics-kotlin/tree/main/samples/kotlin-android-app-destinations/src/main/java/com/segment/analytics/destinations/plugins){:target="_blank"} you can use.
```

2022-10-03 21:25 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
> +You can set up [destination filters](docs/connections/destinations/destination-filters/) on your mobile device-mode destinations by using Analytics Kotlin (Android).
```suggestion
You can set up [destination filters](docs/connections/destinations/destination-filters/) on your mobile device-mode destinations by using Analytics Kotlin (Android). Use Analytics Kotlin (Android) to configure [destination filters](docs/connections/destinations/destination-filters/) on your mobile device-mode destinations.
```

Active voice

2022-10-03 21:25 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
> +1. Download and install the dependency.
I assume the `x.x.x` below is a version number? We should call that out and point to the latest version, if we can.

2022-10-03 21:25 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
> +You can set up [destination filters](docs/connections/destinations/destination-filters/) on your mobile device-mode destinations by using Analytics Swift.
Same as above regarding active voice

2022-10-03 21:25 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
> +1. Add the plugin dependency to your application by adding the Swift package `git@github.com:segmentio/DestinationFilters-Swift.git` as a dependency through either of these 2 options:
This reads a bit weird to me, I think because it mentions adding dependencies twice, even though just one thing needs to be added to the application.

2022-10-03 21:25 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
> +    After installing the package, you can reference the Destination Filters plugin by importing the package with `import DestinationFilters_Swift`.
```suggestion
    After you install the package, import the package with `import DestinationFilters_Swift` to reference the Destination Filters plugin.
```

Active voice again

2022-10-03 23:04 UTC, stayseesong commented on src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
> +You can set up [destination filters](docs/connections/destinations/destination-filters/) on your mobile device-mode destinations by using Analytics Swift.
```suggestion
Use Analytics Swift to set up [destination filters](docs/connections/destinations/destination-filters/) on your mobile device-mode destinations.
```

2022-10-03 23:10 UTC, stayseesong commented on src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
> +1. Add the plugin dependency to your application by adding the Swift package `git@github.com:segmentio/DestinationFilters-Swift.git` as a dependency through either of these 2 options:
```suggestion
1. Add the Swift package `git@github.com:segmentio/DestinationFilters-Swift.git` as a dependency through either of these 2 options:
```

2022-10-05 00:43 UTC, prayansh commented on src/connections/destinations/destination-filters.md
> +You can configure destination filters on cloud-mode, mobile, and web device-mode and actions-based destinations.  With device-mode destinations, you can use the same user interface or API mechanism t
not sure how true it is about actions-based destinations, so i would recheck with @tlalfano

2022-10-17 22:58 UTC, merged