Update Castle destination docs
segmentio/segment-docs pull request #3610
Opened 2022-10-05 18:35 UTC by wallin

### Proposed changes
Updating docs to match the latest technical changes
https://github.com/segmentio/analytics.js-integrations/pull/671

### Merge timing
ASAP once approved

### Related issues (optional)

2022-10-05 22:27 UTC, stayseesong requested changes

2022-10-05 22:27 UTC, stayseesong commented on src/connections/destinations/catalog/castle/index.md
> +**NOTE**: Castle only supports web integrations via Segment, but we are working on mobile support so please stay tuned.
```suggestion
> info ""
> Castle only supports web integrations through Segment, but is in the process of working on mobile support.
```

2022-10-05 22:27 UTC, stayseesong commented on src/connections/destinations/catalog/castle/index.md
> +If you're not familiar with the Segment Specs, take a look to understand what the [`page` method](https://segment.com/docs/connections/spec/page/) does. An example call would look like:
```suggestion
Take a look to understand what the [Page method](/docs/connections/spec/page/) does. An example call looks like:
```

2022-10-05 22:27 UTC, stayseesong commented on src/connections/destinations/catalog/castle/index.md
> +`page` calls will be sent to Castle as `$page` events.
```suggestion
`page` send to Castle as `$page` events.
```

2022-10-05 22:27 UTC, stayseesong commented on src/connections/destinations/catalog/castle/index.md
> +`track` calls will be sent to Castle as a `$custom` events.
```suggestion
`track` calls send to Castle as a `$custom` events.
```

2022-10-05 22:27 UTC, stayseesong commented on src/connections/destinations/catalog/castle/index.md
> +In order to prevent user information from being spoofed by a bad actor, it is highly recommended to send the user information as a signed JWT when Castle.js is used in production.
```suggestion
In order to prevent user information from being spoofed by a bad actor, Castle recommends you to send the user information as a signed JWT when Castle.js is used in production.
```

2022-10-05 22:27 UTC, stayseesong commented on src/connections/destinations/catalog/castle/index.md
> +From your backend code, you need to encode the user as a JWT and sign it using your Castle "API Secret". Then, when Castle receives the JWT, the integrity of the user data will be verified to ensure
```suggestion
From your backend code, you need to encode the user as a JWT and sign it using your Castle **API Secret**. Then, when Castle receives the JWT, the integrity of the user data will be verified to ensure that the data isn't being tampered with.
```

2022-10-05 22:27 UTC, stayseesong commented on src/connections/destinations/catalog/castle/index.md
> +When Castle receives a JWT version of the user object, its contents will override the user object sent the standard Segment way.
```suggestion
When Castle receives a JWT version of the user object, its contents override the user object sent the standard Segment way.
```

2022-10-05 22:27 UTC, stayseesong commented on src/connections/destinations/catalog/castle/index.md
> +**NOTE**: Castle will only ingest Segment _client-side_ events at this point. Server-side events will be dropped and not processed.
```suggestion
> warning ""
> Castle only ingests Segment _client-side_ events at this point. Server-side events are dropped and won't be processed.
```

2022-10-05 22:38 UTC, markzegarelli requested changes
Thanks @wallin!

I've requested some changes to help this doc fit in with the rest of our docset.

2022-10-05 22:38 UTC, markzegarelli commented on src/connections/destinations/catalog/castle/index.md
> +3. Enter the "Publishable Key" into your Segment Settings UI which you can find in your property in the [Castle dashboard](https://dashboard.castle.io).
```suggestion
3. Enter the "Publishable Key" the Publishable Key field. Find the Publishable Key on the Castle dashboard.
```

2022-10-05 22:38 UTC, markzegarelli commented on src/connections/destinations/catalog/castle/index.md
> +**NOTE**: Castle will only ingest Segment _client-side_ events at this point. Server-side events will be dropped and not processed.
```suggestion
> info ""
> Castle ingests Segment Client-side events. Server-side events are dropped and not processed.
> Castle supports Segment web integrations.
```

Add info callout, use active voice, consolidate with note below.

2022-10-05 22:38 UTC, markzegarelli commented on src/connections/destinations/catalog/castle/index.md
> +**NOTE**: Castle only supports web integrations via Segment, but we are working on mobile support so please stay tuned.
```suggestion

```

Remove this line and add to info callout above.

2022-10-05 22:38 UTC, markzegarelli commented on src/connections/destinations/catalog/castle/index.md
> +***
```suggestion
```

2022-10-05 22:38 UTC, markzegarelli commented on src/connections/destinations/catalog/castle/index.md
> +If you're not familiar with the Segment Specs, take a look to understand what the [`page` method](https://segment.com/docs/connections/spec/page/) does. An example call would look like:
```suggestion
If you're not familiar with the Segment Specs, take a look to understand what the [Page call](/docs/connections/spec/page/) does. An example call looks like:
```

Relative URLs for other docs pages

2022-10-05 22:38 UTC, markzegarelli commented on src/connections/destinations/catalog/castle/index.md
> +`page` calls will be sent to Castle as `$page` events.
```suggestion
Segment sends Page calls to Castle as `$page` events.
```
Formatting for Segment methods / calls, and active voice.

2022-10-05 22:38 UTC, markzegarelli commented on src/connections/destinations/catalog/castle/index.md
> +If you're not familiar with the Segment Specs, take a look to understand what the [Track method](https://segment.com/docs/connections/spec/track/) does. An example call would look like:
```suggestion
If you're not familiar with the Segment Specs, take a look to understand what the [Track method](/docs/connections/spec/track/) does. An example call looks like:
```

2022-10-05 22:38 UTC, markzegarelli commented on src/connections/destinations/catalog/castle/index.md
> +`track` calls will be sent to Castle as a `$custom` events.
```suggestion
Segment sends Track calls to Castle as a `$custom` events.
```

2022-10-05 22:38 UTC, markzegarelli commented on src/connections/destinations/catalog/castle/index.md
> +In order to prevent user information from being spoofed by a bad actor, it is highly recommended to send the user information as a signed JWT when Castle.js is used in production.
```suggestion
Send user information as a signed JWT when you use Castle in production. This prevents bad actors from spoofing any user information.
```
Simplify the wording here.

2022-10-05 22:38 UTC, markzegarelli commented on src/connections/destinations/catalog/castle/index.md
> +From your backend code, you need to encode the user as a JWT and sign it using your Castle "API Secret". Then, when Castle receives the JWT, the integrity of the user data will be verified to ensure
```suggestion
In your backend code, encode the user as a JWT and sign it using your Castle "API Secret". When Castle receives the JWT, the integrity of the user data is verified to ensure that the data wasn't tampered with.
```

2022-10-05 22:38 UTC, markzegarelli commented on src/connections/destinations/catalog/castle/index.md
> +You then need to transfer the `user_jwt` object to your frontend either via a separate API call, or by injecting the code using a templating language:
```suggestion
Transfer the `user_jwt` object to your frontend through a separate API call, or by injecting the code using a templating language:
```

2022-10-05 22:38 UTC, markzegarelli commented on src/connections/destinations/catalog/castle/index.md
> +When Castle receives a JWT version of the user object, its contents will override the user object sent the standard Segment way.
```suggestion
When Castle receives a JWT version of the user object, its contents override the user object sent the standard Segment way.
```

2022-10-06 12:20 UTC, wallin commented on src/connections/destinations/catalog/castle/index.md
> +This destination is maintained by Castle.
```suggestion
Castle maintains this destination. For any issues with the destination, contact the [Castle support team](mailto:support@castle.io).
```

2022-10-06 12:21 UTC, wallin commented on src/connections/destinations/catalog/castle/index.md
> +**NOTE**: Castle will only ingest Segment _client-side_ events at this point. Server-side events will be dropped and not processed.
```suggestion
> info ""
> Castle ingests Segment Client-side events. Server-side events are dropped and not processed.
> Castle only supports web integrations through Segment, but is in the process of working on mobile support.
```

2022-10-06 12:23 UTC, wallin commented
Thank you for great feedback @markzegarelli @stayseesong! I've now updated the PR and hopefully addressed all your comments

2022-10-06 15:53 UTC, merged

2022-10-07 07:26 UTC, wallin commented
@markzegarelli @stayseesong Thanks for merging this. How do I update the available options in the settings section here: https://segment.com/docs/connections/destinations/catalog/castle/