Mailchimp Destination updates
segmentio/segment-docs pull request #3671
Opened 2022-10-17 21:13 UTC by rchinn-segment

### Proposed changes

- Added clarification regarding configuring merge fields in Mailchimp
- Added detail and links to the Engage section
- Vale edits
- Updated instances of `MailChimp` to `Mailchimp`
### Merge timing

- Once approved
### Related issues (optional)

Resolves #3626, #3640, and #3661

2022-10-17 21:20 UTC, stayseesong commented on src/connections/destinations/catalog/mailchimp/index.md
>  1. From the Segment web app, click **Catalog**.
```suggestion
1. From the Segment web app, navigate to **Connections > Catalog** and go to the **Destinations** tab of the catalog.
```

2022-10-17 21:23 UTC, stayseesong commented on src/connections/destinations/catalog/mailchimp/index.md
> +2. Search for "Mailchimp" in the Catalog, select it, and choose which of your sources to connect the destination to.
```suggestion
2. Search for *Mailchimp*, select it, and click **Configure Mailchimp**. 
```

2022-10-17 21:59 UTC, stayseesong requested changes

2022-10-17 21:59 UTC, stayseesong commented on src/connections/destinations/catalog/mailchimp/index.md
> +5. Enter your Mailchimp "[Datacenter ID](#datacenter-id)" into the connection settings.
```suggestion
3. Choose the source to connect the destination to.
4. In the destination settings, enter your Mailchimp "API key" into the connection settings.
   You should create a new API key for the Segment destination. Mailchimp restricts each API key to a maximum of 10 concurrent requests, so creating a dedicated one for Segment ensures maximum throughput for outgoing calls. You can read more about API keys on [Mailchimp's docs](http://kb.mailchimp.com/integrations/api-integrations/about-api-keys){:target="_blank"}.
4. Enter your Mailchimp "[Audience ID](#audience-id)" into the connection settings.
5. Enter your Mailchimp "[Datacenter ID](#datacenter-id)" into the connection settings.
```

2022-10-17 21:59 UTC, stayseesong commented on src/connections/destinations/catalog/mailchimp/index.md
> +Every time you call [identify](/docs/connections/spec/identify/) with an email address included, Segment will:
```suggestion
Every time you call [identify](/docs/connections/spec/identify/) with an email address included, Segment:
```

2022-10-17 21:59 UTC, stayseesong commented on src/connections/destinations/catalog/mailchimp/index.md
> +1. First ask Mailchimp if that email exists and what their subscriber status is for the `listId` you've provided in the destination settings.
```suggestion
1. First asks Mailchimp if that email exists and what their subscriber status is for the `listId` you've provided in the destination settings.
```

2022-10-17 21:59 UTC, stayseesong commented on src/connections/destinations/catalog/mailchimp/index.md
> +2. If they don't exist, Segment will **subscribe** that user to the list immediately. If you have `doubleOptIn` setting enabled, it will send a confirmation email to that user before subscribing them
```suggestion
2. If they don't exist, Segment **subscribes** that user to the list immediately. If you enabled the `doubleOptIn` setting, it sends a confirmation email to that user before subscribing them, and that email won't be tagged with a subscriber status of `pending`.
```

2022-10-17 21:59 UTC, stayseesong commented on src/connections/destinations/catalog/mailchimp/index.md
> +3. If they already have a subscriber status such as `pending`, `subscribed`, `unsubscribed`, or `cleaned`, Segment will **NOT** resubscribe them but simply update their user `traits`.
```suggestion
3. If they already have a subscriber status such as `pending`, `subscribed`, `unsubscribed`, or `cleaned`, Segment doesn't resubscribe them, but updates their user `traits`.
```

2022-10-17 21:59 UTC, stayseesong commented on src/connections/destinations/catalog/mailchimp/index.md
> +It's very important that when you set up your merge tags in Mailchimp, your `Merge Tags` are the first 10 characters (excluding whitespace or special characters) of its `Field Label` (if it's over 10
```suggestion
It's important that when you set up your merge tags in Mailchimp, your `Merge Tags` are the first 10 characters (excluding whitespace or special characters) of its `Field Label` (if it's over 10 characters).
```

2022-10-17 21:59 UTC, stayseesong commented on src/connections/destinations/catalog/mailchimp/index.md
> +For example, if your `Field Label` was `Way Too-Long123`, your `Merge Tag` should be `WAYTOOLONG`. And the `user.trait` inside your `.identify()` call would be `Way Too-Long123` since Segment will co
```suggestion
For example, if your `Field Label` was `Way Too-Long123`, your `Merge Tag` should be `WAYTOOLONG`. And the `user.trait` inside your `.identify()` call would be `Way Too-Long123` since Segment converts that to `WAYTOOLONG` before sending it to Mailchimp.
```

2022-10-17 21:59 UTC, stayseesong commented on src/connections/destinations/catalog/mailchimp/index.md
> +For any other custom `traits` just add a Mailchimp custom merge field inside of Mailchimp with a tag that matches the key you are using in your `identify` call. In the example these `traits` are **co
```suggestion
For any other custom `traits`, add a Mailchimp custom merge field inside of Mailchimp with a tag that matches the key you're using in your `identify` call. In the example, these `traits` are **company** and **employees**. They will be shown as **COMPANY** and **EMPLOYEES** in Mailchimp, but you can record them in lower-case to `identify` and they will still populate.
```

2022-10-18 16:25 UTC, stayseesong approved these changes

2022-10-18 16:32 UTC, pwseg approved these changes

2022-10-20 16:49 UTC, merged