Fix protocols faq
segmentio/segment-docs pull request #3679
Opened 2022-10-18 22:00 UTC by ranand

### Proposed changes
- We shipped Duplicate Tracking Plans and Libraries in Q3 (Public Beta) and moving to GA in Q4. 
- PRD: https://docs.google.com/document/d/1b6jr7CsBk_YNJAvcATNOVi8bgCQi6P0ZtlVWkL5GxAk/edit#heading=h.vv9txf1zeg8
- In this PR, I propose that we fix the FAQ for Protocols to ensure we call out the ability to copy/duplicate tracking plans.

### Merge timing
- ASAP once approved

2022-10-19 00:11 UTC, stayseesong requested changes

2022-10-19 00:11 UTC, stayseesong commented on src/protocols/faq.md
> +You can duplicate Tracking Plans in the Segment web app. Here are the instructions to [copy a tracking plan](/docs/protocols/tracking-plan/create/#copy-a-tracking-plan). You can also use the [Trackin
```suggestion
Yes, you can duplicate Tracking Plans in the Segment web app by following the [instructions to copy a tracking plan](/docs/protocols/tracking-plan/create/#copy-a-tracking-plan). You can also use the [Tracking Plan API](/docs/protocols/apis-and-extensions/) to copy the underlying JSON schema from one Tracking Plan to another.
```

2022-10-19 00:18 UTC, stayseesong commented on src/protocols/faq.md
> +You can duplicate Tracking Plans in the Segment web app. Here are the instructions to [copy a tracking plan](/docs/protocols/tracking-plan/create/#copy-a-tracking-plan). You can also use the [Trackin
@ranand is the feature to duplicate tracking plans currently in beta or did it already go to GA. If it's in public beta, we'll need to call that out here. When's it going to GA?

2022-10-19 17:31 UTC, stayseesong commented
@ranand, just to clarify, the feature is going to GA on 10/31?

2022-10-19 17:36 UTC, stayseesong approved these changes

2022-10-19 17:44 UTC, ranand commented
> @ranand, just to clarify, the feature is going to GA on 10/31?

It is going GA on 10/31, yes.

2022-10-21 14:44 UTC, ranand commented
@stayseesong - fixed the date to reflect the correct date. It is going GA on 10/25.

2022-10-24 16:21 UTC, stayseesong commented
@ranand ok, will get that merged in for you by eod today

2022-10-24 23:11 UTC, merged