Scaffold docs for HubSpot Web and Cloud Actions
segmentio/segment-docs pull request #3719
Opened 2022-10-26 00:15 UTC by kdaswani

### Proposed changes
HubSpot Web (Actions) and HubSpot Cloud Mode (Actions) are in private beta. We have not invited any customers yet as we plan to open up to public beta soon. This is just the first version to scaffold the docs and keep them hidden until public beta. 

Since these two destinations are in Private Beta, can we make sure that the dossier and other tables (other versions of destination, settings, actions, fields) get pre-populated upon deploy? Thank you!

### Merge timing
- ASAP once approved

### Related issues (optional)
https://segment.atlassian.net/browse/HGI-62
https://segment.atlassian.net/browse/HGI-96

2022-10-26 16:33 UTC, stayseesong requested changes

2022-10-26 16:33 UTC, stayseesong commented on src/connections/destinations/catalog/actions-hubspot-cloud/index.md
> +- **OAuth 2.0 support**. Authentication with HubSpot leverages OAuth 2.0 instead of an API key.
```suggestion
- **OAuth 2.0 support**. Authentication with HubSpot uses OAuth 2.0 instead of an API key.
```

2022-10-26 16:33 UTC, stayseesong commented on src/connections/destinations/catalog/actions-hubspot-cloud/index.md
> +- **Support for custom behavioral events**. Send [custom behaviorial events](https://developers.hubspot.com/docs/api/analytics/events){:target="_blank"} and event properties to HubSpot.
```suggestion
- **Support for custom behavioral events**. Send [custom behavioral events](https://developers.hubspot.com/docs/api/analytics/events){:target="_blank"} and event properties to HubSpot.
```

2022-10-26 16:33 UTC, stayseesong commented on src/connections/destinations/catalog/actions-hubspot-web/index.md
> +- **Support for custom behavioral events**. Send [custom behaviorial events](https://developers.hubspot.com/docs/api/events/tracking-code#tracking-custom-behavioral-events-marketing-hub-enterprise-on
```suggestion
- **Support for custom behavioral events**. Send [custom behavioral events](https://developers.hubspot.com/docs/api/events/tracking-code#tracking-custom-behavioral-events-marketing-hub-enterprise-only-){:target="_blank"} and event properties to HubSpot.
```

2022-10-26 16:33 UTC, stayseesong commented on src/connections/destinations/catalog/actions-hubspot-cloud/index.md
> +HubSpot is an all-in-one marketing tool that helps attract new leads and convert them into paying customers, with features like landing page creation and email automation.
```suggestion
HubSpot is an all-in-one marketing tool that helps attract new leads and converts them into paying customers, with features like landing page creation and email automation.
```

2022-10-26 16:36 UTC, kdaswani commented on src/connections/destinations/catalog/actions-hubspot-cloud/index.md
> +- **Support for custom behavioral events**. Send [custom behaviorial events](https://developers.hubspot.com/docs/api/analytics/events){:target="_blank"} and event properties to HubSpot.
thanks for catching this typo!

2022-10-27 16:05 UTC, stayseesong approved these changes

2022-10-27 16:14 UTC, merged