Update source schema export page
segmentio/segment-docs pull request #3825
Opened 2022-11-15 18:40 UTC by ranand

### Proposed changes
- We worked on updating the source schema export page to include:
  - properties with Track event exports
  - Download CSV capability for Identify & Group
  - Epic: https://segment.atlassian.net/browse/PROT-3830

### Merge timing
- 11/22/2022 (Tuesday)

2022-11-15 19:47 UTC, markzegarelli requested changes

2022-11-15 19:47 UTC, markzegarelli commented on src/connections/destination-data-control.md
> +The Track event CSV file will contain the following columns:
```suggestion
The Track event CSV file contains the following columns:
```

2022-11-15 19:47 UTC, markzegarelli commented on src/connections/destination-data-control.md
> +Segment allows you to download your Source Schema as a CSV file, maximizing portability and access to event data. You can download a copy of your schema by visiting the Source Schema page. This is su
```suggestion
Segment allows you to download your Source Schema as a CSV file, maximizing portability and access to event data. You can download a copy of your schema by visiting the Source Schema page. This is supported for Track, Identify, and Group events. Track, Identify, and Group events support Source Schema export.
```

2022-11-15 19:47 UTC, markzegarelli commented on src/connections/destination-data-control.md
> +The Identify & Group CSV file will contain the following columns:
```suggestion
The Identify & Group CSV file contains the following columns:
```

2022-11-15 20:19 UTC, ranand commented on src/connections/destination-data-control.md
> +The Track event CSV file will contain the following columns:
done!

2022-11-15 20:19 UTC, ranand commented on src/connections/destination-data-control.md
> +Segment allows you to download your Source Schema as a CSV file, maximizing portability and access to event data. You can download a copy of your schema by visiting the Source Schema page. This is su
done!

2022-11-15 20:19 UTC, ranand commented on src/connections/destination-data-control.md
> +The Identify & Group CSV file will contain the following columns:
done!

2022-11-16 21:47 UTC, markzegarelli approved these changes

2022-11-16 21:47 UTC, merged

2022-11-16 21:49 UTC, markzegarelli commented
Will merge this on Friday to ensure it makes it on 11/22