Reverse ETL
segmentio/segment-docs pull request #3851
Opened 2022-11-18 22:01 UTC by stayseesong

First draft build 

### Proposed changes

### Merge timing

### Related issues (optional)

2022-11-29 00:25 UTC, markzegarelli requested changes

2022-11-29 00:25 UTC, markzegarelli commented on src/reverse-etl/reverse-etl.md
> +4. Add in the account information for your source.
```suggestion
4. Add the account information for your selected source.  
```

2022-11-29 00:25 UTC, markzegarelli commented on src/reverse-etl/reverse-etl.md
> +2. Click **SQL Editor** as your modeling method. (Note: Segment will add more modeling methods in the future)
```suggestion
2. Click **SQL Editor** as your modeling method. (Segment will add more modeling methods in the future)
```

This could be a good situation to include the feedback link, if product agrees.

2022-11-29 00:25 UTC, markzegarelli commented on src/reverse-etl/reverse-etl.md
> +Once you’ve added a model, you need to add a destination. In Reverse ETL, destinations are the business tools or apps you use that Segment syncs the data from your warehouse to.
Does Reverse ETL support multiple destinations? If so, you could update the instruction to something like "...add your first destination"

2022-11-29 00:25 UTC, markzegarelli commented on src/reverse-etl/reverse-etl.md
> +> Reverse ETL only supports [Actions destinations](/docs/connections/destinations/actions/). Depending on the destination, you may need to know certain endpoints and have specific credentials to add
```suggestion
> Reverse ETL only supports [Actions destinations](/docs/connections/destinations/actions/). Depending on the destination, you may need to know certain endpoints and have specific credentials to configure the destination.  
```

I think anyone can add a destination, and destinations don't need to work to be added.

2022-11-29 00:25 UTC, markzegarelli commented on src/reverse-etl/reverse-etl.md
> +After you've followed [all four steps](/docs/reverse-etl/reverse-etl/#getting-started) and set up your source, model, destination, and mappings for Reverse ETL, your data will extract and will sync t
```suggestion
After you've followed [all four steps](/docs/reverse-etl/reverse-etl/#getting-started) and set up your source, model, destination, and mappings for Reverse ETL, your data will extract and sync to your destination(s) right away if you chose an interval schedule. If you set your data to extract at a specific day and time, the extraction will take place then.
```

2022-11-29 00:25 UTC, markzegarelli commented on src/reverse-etl/snowflake-setup.md
> +At a high level, when you set up Snowflake for Reverse ETL,  the configured user/role needs read permissions for any resources (databases, schemas, tables) the query needs to access. Segment keeps tr
```suggestion
At a high level, when you set up Snowflake for Reverse ETL,  the configured user/role needs read permissions for any resources (databases, schemas, tables) the query needs to access. Segment keeps track of changes to your query results with a managed schema (`__SEGMENT_REVERSE_ETL`), which requires the configured user to allow write permissions for that schema.
```

If I understand this correctly, READ is required for everything _except_ `__SEGMENT_REVERSE_ETL`, for which they will need write access as well?

2022-11-29 00:25 UTC, markzegarelli commented on src/reverse-etl/bigquery-setup.md
> +`bigquery.jobs.create` | This allows Segment to execute queries on any datasets/tables your model query references, in addition to managing our tables for tracking state
```suggestion
`bigquery.jobs.create` | This allows Segment to execute queries on any datasets/tables your model query references and manage tables that Segment uses for tracking
```

2022-11-29 17:14 UTC, stayseesong commented on src/reverse-etl/index.md
> +> Reverse ETL currently only supports BigQuery and Snowflake as sources and is actively working on adding more. If you'd like to request Segment to add a particular source, please note it on the [fee
```suggestion
> Reverse ETL supports BigQuery and Snowflake as sources and is actively working on adding more. If you'd like to request Segment to add a particular source, please note it on the [feedback form](https://airtable.com/shrdu5cW06LsuZvXN){:target="_blank"}.
```

2022-11-29 17:14 UTC, stayseesong commented on src/reverse-etl/index.md
> +You can add multiple models to your source. Repeat steps 1-10 above to add more.
```suggestion
To add multiple models to your source, repeat steps 1-10 above.
```

2022-11-29 17:16 UTC, stayseesong commented on src/reverse-etl/index.md
> +You can add multiple mappings from your warehouse to your destination. To add more mappings, repeat steps 1-9 above.
```suggestion
To add multiple mappings from your warehouse to your destination, repeat steps 1-9 above.
```

2022-12-01 23:08 UTC, markzegarelli approved these changes

2022-12-01 23:19 UTC, merged