add section for api token security [SECFEAT-1021]
segmentio/segment-docs pull request #3921
Opened 2022-12-08 02:36 UTC by salolivares

### Proposed changes
This PR adds a section under the public api page in order to describe a new feature that is being rolled out (exposed papi token service, see sdd [here](https://paper.dropbox.com/doc/SDD-GitHubLab-token-scanning--BuUoS~Py32zurYUtRDgWxRPWAg-9H5ol1zdKPdm5MbCc4wyv)). 

### Merge timing
This depends on https://github.com/segmentio/exposed-papi-token-service being shipped to production. We're aiming for an early January release.

2022-12-09 00:26 UTC, stayseesong requested changes

2022-12-13 01:20 UTC, stayseesong commented
@salolivares when you get an exact date for when this is being shipped to production, can you let me know? Want to make sure this goes out on the right date. Thanks!

2022-12-27 23:53 UTC, salolivares commented
@stayseesong will do! We're aiming for a early January release. I'll ping once we figure out a hard date.

2023-01-13 22:40 UTC, salolivares commented
@stayseesong the feature has going live! when can we have the docs published?

2023-01-17 17:12 UTC, stayseesong commented
@salolivares when is it going live?

2023-01-17 17:24 UTC, stayseesong approved these changes

2023-01-17 17:24 UTC, merged