Ripe destination docs
segmentio/segment-docs pull request #3952
Opened 2022-12-13 22:14 UTC by markzegarelli

- Add Ripe destination documentation
- Edits and actions metadata

### Proposed changes
Moving Ripe docs to this PR so we can push edits and updates

@simpajj I've hidden the SDK information now that we've pulled the metadata to generate docs for the 
Available actions and presets. If there is relevant information here, I recommend that you add it to 
the description field of the relevant action. For example, the Group action 
[here](https://github.com/segmentio/action-destinations/pull/921/files#diff-d6f42630d09c3023d9b68f43134db76725480bee9d6b57eb72bf13f647352496R7)

I will close #3934, and we'll deploy this in our next deploy on Thursday.

### Merge timing

### Related issues (optional)
#3934

2022-12-14 05:38 UTC, simpajj commented
Thanks @markzegarelli!

2022-12-14 20:02 UTC, stayseesong requested changes

2022-12-15 17:54 UTC, stayseesong approved these changes

2022-12-15 17:55 UTC, stayseesong approved these changes

2022-12-15 17:56 UTC, merged