Add Ripe cloud mode docs
segmentio/segment-docs pull request #3991
Opened 2023-01-04 08:51 UTC by simpajj

### Proposed changes

Added documentation for the Ripe cloud mode integration and updated the documentation for the device mode integration accordingly. See the cloud mode PR for reference: https://github.com/segmentio/action-destinations/pull/952

The device mode integration has been renamed to `Ripe Web Destination (Actions)` for clarity, and the new cloud mode one is called `Ripe Cloud Destination (Actions)`.

### Merge timing
<!-- When should this get merged/published?
- ASAP once approved

### Related issues (optional)

https://github.com/segmentio/action-destinations/pull/952

2023-01-04 17:48 UTC, stayseesong requested changes

2023-01-04 17:48 UTC, stayseesong commented on src/connections/destinations/catalog/actions-ripe-cloud/index.md
> +title: Ripe Cloud Destination (Actions)
```suggestion
title: Ripe Cloud (Actions) Destination 
```

2023-01-04 17:48 UTC, stayseesong commented on src/connections/destinations/catalog/actions-ripe-web/index.md
> +title: Ripe Web Destination (Actions)
```suggestion
title: Ripe Web (Actions) Destination 
```

2023-01-21 00:46 UTC, stayseesong commented
@simpajj I'll merge this in once the source is available in the catalog

2023-01-24 17:42 UTC, markzegarelli commented
Moved this to #4118

2023-01-24 17:42 UTC, closed without merging