Add section highlighting User Data parameter mappings
segmentio/segment-docs pull request #4025
Opened 2023-01-10 19:17 UTC by bobbyatsegment

### Proposed changes

Customers have previously expressed confusion on how user data fields are mapped to Facebook; a recent customer wrote the following:

> Unfortunately, we are unable to attribute purchases to users because there appears to be a mismatch between Segment's destination and what the Conversions API expects. Facebook's API expects a key of `em` for email; whereas the Segment destination sends in a key of `email` instead. This is unable to be changed in Segment.

Added a section on User Data Parameters with a table that highlights how user data fields are mapped to their corresponding parameters as expected by Facebook, which should help to alleviate future confusion on this topic.

### Merge timing

### Related issues (optional)

2023-01-11 17:02 UTC, spencerattick approved these changes

2023-01-11 21:48 UTC, markzegarelli requested changes

2023-01-12 16:30 UTC, bobbyatsegment commented on src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
> +Segment automatically maps User Data fields to their corresponding parameters [as expected by the Conversions API](https://segment.com/docs/connections/destinations/catalog/actions-facebook-conversio
Thanks for clarifying! My mistake, the link should point to https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/customer-information-parameters/

I was so focused on the formatting for the outside docs link that I forgot to update the link itself 😅

2023-01-12 16:58 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
> +Segment automatically maps User Data fields to their corresponding parameters [as expected by the Conversions API](https://segment.com/docs/connections/destinations/catalog/actions-facebook-conversio
@bobbyatsegment No problem!

I updated the link in the suggestion. If it looks good to you, you can just click `Commit suggestion`.

2023-01-13 18:50 UTC, markzegarelli approved these changes

2023-01-13 18:51 UTC, merged