Updating to exclude authenticating via email/token because it doesn't work
segmentio/segment-docs pull request #4045
Opened 2023-01-12 21:12 UTC by saitwilio

### Proposed changes
Updated Zendesk docs to exclude authenticating via email/token because several customers have reported it doesn't work.

### Merge timing
Once approved

### Related issues (optional)

2023-01-12 21:19 UTC, markzegarelli requested changes

2023-01-12 21:19 UTC, markzegarelli commented on src/connections/destinations/catalog/zendesk/index.md
> +3. Enter your Zendesk domain and click the 'Connect' button - you'll be redirected to Zendesk OAuth. Use the standard email and password you use to Sign In to your Zendesk account. In the Zendesk set
```suggestion
3. Enter your Zendesk domain and click **Connect**. The Zendesk OAuth login opens in a new tab. Sign in with your Zendesk credentials to authenticate. In the Zendesk settings, add your email in the **Email** setting and your password in the **Password** setting.
```
@saitwilio 
Reworded slightly for clarity.

Is the sentence that begins with "In the Zendesk settings..." still applicable if using OAuth? I don't see fields for these in the destination settings in Segment.

2023-01-12 21:28 UTC, saitwilio commented on src/connections/destinations/catalog/zendesk/index.md
> +3. Enter your Zendesk domain and click the 'Connect' button - you'll be redirected to Zendesk OAuth. Use the standard email and password you use to Sign In to your Zendesk account. In the Zendesk set
You're right.. that sentence needs to be taken out. Good catch!

2023-01-12 21:33 UTC, markzegarelli commented on src/connections/destinations/catalog/zendesk/index.md
> +3. Enter your Zendesk domain and click **Connect**. The Zendesk OAuth login opens in a new tab. Sign in with your Zendesk credentials to authenticate. In the Zendesk settings, add your email in the *
> In the Zendesk settings, add your email in the **Email** setting and your password in the **Password** setting.

@saitwilio Can you clarify a bit on where these fields are supposed to be? I'm not following the step as described here. Once authentication with OAuth is done, is there still a need to add Email and Password?

2023-01-13 00:51 UTC, saitwilio commented on src/connections/destinations/catalog/zendesk/index.md
> +3. Enter your Zendesk domain and click **Connect**. The Zendesk OAuth login opens in a new tab. Sign in with your Zendesk credentials to authenticate. In the Zendesk settings, add your email in the *
Hi @markzegarelli I'm not sure what the steps look like exactly - I'm changing the docs requested by someone else, let me get on a chat with them to confirm.

2023-01-18 16:32 UTC, markzegarelli approved these changes

2023-01-18 18:18 UTC, merged