Update index.md
segmentio/segment-docs pull request #4053
Opened 2023-01-13 18:55 UTC by sarahrudy

Add info block about whether customer should set up one source or multiple sources

### Proposed changes

Add info block about whether customer should set up one source or multiple sources

### Merge timing
- ASAP once approved?

2023-01-18 23:12 UTC, markzegarelli requested changes

2023-01-18 23:12 UTC, markzegarelli commented on src/connections/sources/index.md
> +> **One source or multiple sources?**
```suggestion
```

2023-01-18 23:12 UTC, markzegarelli commented on src/connections/sources/index.md
> +> info ""
```suggestion
> info "One source or multiple sources?"
```

2023-01-18 23:12 UTC, markzegarelli commented on src/connections/sources/index.md
> +> Ultimately, it's up to you, but it really depends on how you want to organize your data. We suggest that you create one source for each type of data you want to collect. For example, a customer mig
```suggestion
> Segment suggests that you create one source for each type of data you want to collect. For example, a you might have one source for all of their website tracking and a different source for any mobile tracking. Creating one source per data type provides the following benefits:
```

2023-01-18 23:12 UTC, markzegarelli commented on src/connections/sources/index.md
> +> Ultimately, it's up to you, but it really depends on how you want to organize your data. We suggest that you create one source for each type of data you want to collect. For example, a customer mig
Important to remember that we're our customers and prospects are the main audience for our docs. We typically just use `you` as opposed to `a customer`.

2023-01-19 00:12 UTC, sarahrudy commented on src/connections/sources/index.md
> +> Ultimately, it's up to you, but it really depends on how you want to organize your data. We suggest that you create one source for each type of data you want to collect. For example, a customer mig
Thank you for pointing that out!

2023-01-19 17:06 UTC, markzegarelli approved these changes

2023-01-19 17:06 UTC, merged