Update FAQ for custom objects clarification over associations
segmentio/segment-docs pull request #4061
Opened 2023-01-17 14:54 UTC by volneyvj

### Proposed changes

Not clear if it's possible to associate a contact/company to a custom Object inside HubSpot, ex. deals or tickets.

### Merge timing

### Related issues (optional)

2023-01-19 16:47 UTC, stayseesong requested changes

2023-01-19 16:47 UTC, stayseesong commented on src/connections/destinations/catalog/actions-hubspot-cloud/index.md
> +Segment provides prebuilt mappings for contacts and companies. If there are other standard objects you would like to create records in, please use the **Create Custom Object Record** action. For exam
```suggestion
Segment provides prebuilt mappings for contacts and companies. If there are other standard objects you would like to create records in, please use the **Create Custom Object Record** action. For example, to create a deal in HubSpot, add a mapping for Create Custom Object Record, set up your Event Trigger criteria, and input a literal string of "deals" as the Object Type. You can use the Properties object to add fields that are in the [deals object](https://developers.hubspot.com/docs/api/crm/deals){:target="_blank"}, such as `dealname` and `dealstage`. The same can be done with other object types (for example, tickets, quotes, etc). Ending fields that are to go to HubSpot outside of the properties object isn't supported. This includes sending [associations](https://developers.hubspot.com/docs/api/crm/associations){:target="_blank"}.  Please note, Segment only supports creating new records in these cases; updates to existing records are only supported for contacts and companies. 
```

2023-01-19 17:17 UTC, volneyvj commented on src/connections/destinations/catalog/actions-hubspot-cloud/index.md
> +Segment provides prebuilt mappings for contacts and companies. If there are other standard objects you would like to create records in, please use the **Create Custom Object Record** action. For exam
i guess i must misspelled here:
Ending fields that are to go to HubSpot outside of the properties object isn't supported.

2023-01-25 23:39 UTC, markzegarelli approved these changes

2023-01-26 13:14 UTC, spencerattick approved these changes

2023-01-26 17:05 UTC, merged