Update actions.md
segmentio/segment-docs pull request #4073
Opened 2023-01-18 18:14 UTC by sarahrudy

Add info about coalesce function for Destination Actions

### Proposed changes

Add info about coalesce function for Destination Actions

### Merge timing
- ASAP once approved

2023-01-19 23:50 UTC, stayseesong requested changes

2023-01-19 23:50 UTC, stayseesong commented on src/connections/destinations/actions.md
> +### Coalesce Function
```suggestion
### Coalesce function
```

2023-01-19 23:50 UTC, stayseesong commented on src/connections/destinations/actions.md
> +The coalesce function will take a primary value and use that one if it is available. In the case it is not, it will use the fallback value.
```suggestion
The coalesce function takes a primary value and uses it if it is available. If the value isn't available, the function uses the fallback value instead. 
```

2023-01-19 23:50 UTC, stayseesong commented on src/connections/destinations/actions.md
> +![coalesce](https://user-images.githubusercontent.com/78389005/213260648-a9eda0c8-fd88-4a0b-b4c6-682380ce2328.png)
```suggestion
```

2023-01-19 23:50 UTC, stayseesong commented on src/connections/destinations/actions.md
> +![coalesce](https://user-images.githubusercontent.com/78389005/213260648-a9eda0c8-fd88-4a0b-b4c6-682380ce2328.png)
I don't think we need to include a screenshot to this as it doesn't add any value

2023-01-19 23:50 UTC, stayseesong commented on src/connections/destinations/actions.md
> +### Coalesce Function
@sarahrudy how do you access the coalesce function? I don't see it in the UI

2023-01-25 23:37 UTC, markzegarelli approved these changes

2023-02-02 17:30 UTC, stayseesong approved these changes

2023-02-02 17:30 UTC, merged