DOC 641 stripe update
segmentio/segment-docs pull request #4089
Opened 2023-01-20 00:23 UTC by markzegarelli

- Release 23.3.2 (#4071)
- Update collections to reflect updated API [netlify-build]

### Proposed changes

### Merge timing

### Related issues (optional)
DOC-641

2023-01-20 16:38 UTC, pwseg commented on src/connections/sources/catalog/cloud-apps/stripe/index.md
> +The Stripe source is built with a sync component, which means Segment make requests to the Stripe API on your behalf on a 3 hour interval to pull the latest data into Segment. In the initial sync, Se
```suggestion
The Stripe source is built with a sync component, which means Segment make requests to the Stripe API on your behalf on a three hour interval to pull the latest data into Segment. In the initial sync, Segment grabs all the Stripe objects (and their corresponding properties) according to the Collections Table below. The objects are written into a separate schema, corresponding to the source instance's schema name you designated upon creation (for example, `stripe_prod.charges`).
```

2023-01-20 16:38 UTC, pwseg commented on src/connections/sources/catalog/cloud-apps/stripe/index.md
> +The source syncs and warehouse syncs are independent processes. Source runs pull your data into the Segment Hub, and warehouse runs flush that data to your warehouse. Sources will sync with Segment e
```suggestion
The source syncs and warehouse syncs are independent processes. Source runs pull your data into the Segment Hub, and warehouse runs flush that data to your warehouse. Sources will sync with Segment every three hours. Depending on your Warehouses plan, Segment pushes the Source data to your warehouse on the interval associated with your billing plan.
```

2023-01-20 16:39 UTC, pwseg approved these changes

2023-01-25 09:21 UTC, vivek-26 requested changes

2023-01-25 09:21 UTC, vivek-26 commented on src/connections/sources/catalog/cloud-apps/stripe/index.md
> +### tax_rates
Tax rates collection is not rendered as a table in the [preview](https://deploy-preview-4089--segment-docs.netlify.app/docs/connections/sources/catalog/cloud-apps/stripe).

2023-01-26 18:04 UTC, markzegarelli commented on src/connections/sources/catalog/cloud-apps/stripe/index.md
> +### tax_rates
Fixed this and rebuilding the preview now.

2023-01-31 16:55 UTC, merged