Add link to schema limits FAQ
segmentio/segment-docs pull request #4096
Opened 2023-01-20 18:51 UTC by ashton-huxtable

### Proposed changes

Added a link to take customers to the schema limits FAQ for easier navigation and continuity of information. 

### Merge timing

- ASAP once approved

### Related issues (optional)

n/a

2023-01-23 19:50 UTC, stayseesong requested changes

2023-01-23 19:50 UTC, stayseesong commented on src/connections/destination-data-control.md
>  > Export Schema doesn't include any actual values (for example, personal data) for the events, properties, and traits you are tracking for a specific source.
```suggestion
> info ""
> The export schema doesn't include actual values (for example, personal data) for the events, properties, and traits you are tracking for a specific source.
```

2023-01-23 19:50 UTC, stayseesong commented on src/connections/destination-data-control.md
> +For more information on how to manage the Source Schema page, please visit [this page](https://segment.com/docs/connections/schema-unique-limits/)
```suggestion
See the [Segment Schema Limits](/docs/connections/schema-unique-limits/) for more information on how to manage the Source Schema. 
```

2023-01-26 17:04 UTC, markzegarelli approved these changes

2023-02-02 17:31 UTC, stayseesong approved these changes

2023-02-02 17:31 UTC, merged