Update how to navigate to custom field names
segmentio/segment-docs pull request #4107
Opened 2023-01-23 21:34 UTC by bobbyatsegment

### Proposed changes

Under the section for Identify calls, the current information on finding/setting custom field names for contact properties does not lead anywhere, it should be updated to navigate to the correct place: Settings > Data Management > Objects > Contacts > Manage contact properties
![Screen Shot 2023-01-23 at 4 29 57 PM](https://user-images.githubusercontent.com/93934274/214154659-8f77164b-4506-44bc-acc5-747e374dd0f9.png)

### Merge timing

### Related issues (optional)

2023-01-26 13:06 UTC, spencerattick approved these changes

2023-01-26 16:50 UTC, stayseesong requested changes

2023-01-26 16:50 UTC, stayseesong commented on src/connections/destinations/catalog/hubspot/index.md
> +HubSpot removes from the request any traits that aren't contact fields in HubSpot. To find out which fields you can set, check out the custom field names in **Settings > Data Management > Objects > C
```suggestion
HubSpot removes from the request any traits that aren't contact fields in HubSpot. To find out which fields you can set, navigate to **Settings > Data Management > Objects > Contacts** and select **Manage contact properties** under the **Setup** tab. Example field names are `firstname`, `lastname`, `company`, and `phone`.
```

2023-02-02 17:29 UTC, stayseesong approved these changes

2023-02-02 17:29 UTC, merged