Add useful links to Full Segment Implementation
segmentio/segment-docs pull request #4110
Opened 2023-01-23 23:54 UTC by sarahrudy

Add useful links to Full Segment Implementation

### Proposed changes
- Added some useful links where they belong next to identify and track calls, respectively 
- Kept naming convention of `track`, `identify`, `screen`, `page` consistent throughout page

### Merge timing
- ASAP once approved

2023-01-24 23:10 UTC, markzegarelli commented
Hey @sarahrudy. In our [Style Guide](https://github.com/segmentio/segment-docs/blob/develop/styleguide.md#styling-the-segment-methods), we have guidance around how to refer to specific methods (Track call, not `track`).

Can you update this PR to remove instances where you've made these changes?

2023-01-25 19:42 UTC, sarahrudy commented
Hi @markzegarelli, I just made those changes you requested and committed them to `sarahrudy-patch-4`.

2023-01-25 23:36 UTC, markzegarelli requested changes
We like to use relative URLs in links to other pages on Segment Docs. This make things easier if we ever change the site's domain.

2023-01-25 23:36 UTC, markzegarelli commented on src/getting-started/04-full-install.md
> +> **Tip**! Segment recommends that you always use the Page and Screen calls when recording a page-view, rather than creating a "Page Viewed" Track event, because the Page/Screen calls automatically c
```suggestion
> Segment recommends that you always use the Page and Screen calls when recording a page-view, rather than creating a "Page Viewed" Track event, because the Page/Screen calls automatically collect more contextual information.
```

2023-01-25 23:36 UTC, markzegarelli commented on src/getting-started/04-full-install.md
> +These are called [traits](https://segment.com/docs/connections/spec/identify/#traits)for Identify calls, and [properties](https://segment.com/docs/connections/spec/track/#properties) for all other me
```suggestion
These are called [traits](/docs/connections/spec/identify/#traits)for Identify calls, and [properties](/docs/connections/spec/track/#properties) for all other methods.
```

2023-01-25 23:36 UTC, markzegarelli commented on src/getting-started/04-full-install.md
> +[Properties](https://segment.com/docs/connections/spec/track/#properties) are powerful. They enable you to capture as much context about the event as you'd like, and then cross-tabulate or filter you
```suggestion
[Properties](/docs/connections/spec/track/#properties) are powerful. They enable you to capture as much context about the event as you'd like, and then cross-tabulate or filter your downstream tools. For example, let's say an eLearning website is tracking whenever a user bookmarks an educational article on a page. Here's what a robust analytics.js Track call could look like:
```

2023-01-26 17:02 UTC, markzegarelli approved these changes

2023-01-26 17:03 UTC, merged