add support clarification for simple_segment
segmentio/segment-docs pull request #4121
Opened 2023-01-24 19:57 UTC by spencerattick

### Proposed changes
I'm proposing an update to let customers know that we can't offer direct support for simple_segment as it isn't owned by Segment.

### Merge timing
ASAP once approved is fine

2023-01-25 18:02 UTC, stayseesong requested changes

2023-01-25 18:02 UTC, stayseesong commented on src/connections/sources/catalog/libraries/server/ruby/index.md
> +> The analytics-ruby gem makes requests asynchronously, which can sometimes be suboptimal and difficult to debug if you're pairing it with a queuing system like Sidekiq/delayed job/sucker punch/resqu
```suggestion
> The analytics-ruby gem makes requests asynchronously, which can sometimes be suboptimal and difficult to debug if you're pairing it with a queuing system like Sidekiq/delayed job/sucker punch/resqueue. If you prefer to use a gem that makes requests synchronously, you can use [`simple_segment`](https://github.com/whatthewhat/simple_segment){:target="_blank"} , an API-compatible drop-in replacement for the standard gem that does its work synchronously inline. If you choose to use `simple_segment`, please note that because the `simple_segment` package isn't owned and maintained directly by Segment, Segment wont' be able to provide support for it. 
```

2023-01-31 17:06 UTC, markzegarelli approved these changes

2023-02-02 17:27 UTC, stayseesong approved these changes

2023-02-02 17:27 UTC, merged