Fixed spelling/grammar errors
segmentio/segment-docs pull request #4131
Opened 2023-01-26 05:04 UTC by senabon

lines 494 and 497

### Proposed changes

I fixed a spelling error and a grammar issue, so the document is easier to read.

### Merge timing

### Related issues (optional)

2023-01-26 13:09 UTC, spencerattick approved these changes

2023-02-24 23:07 UTC, markzegarelli requested changes

2023-02-24 23:07 UTC, markzegarelli commented on src/connections/destinations/catalog/adobe-analytics/settings.md
> +> **Note**: The context data value cannot be an object or an array as this is not an Adobe accepted data type by Adobe Analytics.
```suggestion
> The context data value cannot be an object or an array as this is not an Adobe accepted data type by Adobe Analytics.
```

2023-02-24 23:07 UTC, markzegarelli commented on src/connections/destinations/catalog/adobe-analytics/settings.md
> +Segment will automatically sends all event properties as context data on specced eccommerce events, `page()`, `track()`, and `screen()` calls if you are using a device-mode ("bundled") destination fo
```suggestion
Segment automatically sends event properties as context data on the following:
- ecommerce events that adhere to the [Ecommerce Spec](/docs/connections/spec/ecommerce/v2/)
- Page calls
- Track calls
- Screen calls if you are using a device-mode ("bundled") destination for Analytics.js, or if you are sending unbundled events from a [Server library](/docs/connections/sources/catalog/). 

If you want to send additional context data from the context data object in the Segment payload, configure the Context Data Variables mapping in the destination's settings to tell Segment which context variables to send to Adobe as context data.
```

@senabon Updating this for easier readability. For screen calls, are they conditional based on the criteria as written, or is "sending unbundled events from a Server library a separate case?

2023-02-24 23:07 UTC, markzegarelli commented on src/connections/destinations/catalog/adobe-analytics/settings.md
>  > note ""
```suggestion
> info ""
```

2023-05-31 19:14 UTC, markzegarelli approved these changes

2023-05-31 19:14 UTC, merged