PlayerZero Web Docs (Deploy)
segmentio/segment-docs pull request #4136
Opened 2023-01-26 19:36 UTC by markzegarelli

- Docs Commit for PlayerZero Web
- Insert actions block

### Proposed changes

### Merge timing

### Related issues (optional)
Duplicates #4135

2023-01-26 19:43 UTC, AnimeshKoratana commented
Thanks @markzegarelli 🙌 ! 
I missed the actions block part

2023-01-26 20:16 UTC, stayseesong requested changes

2023-01-26 20:16 UTC, stayseesong commented on src/connections/destinations/catalog/actions-playerzero-web/index.md
> +2. Find the Destinations Actions item in the left navigation, and click it.
```suggestion
2. Under **Categories** select **Destination Actions**.
```

2023-01-26 21:45 UTC, AnimeshKoratana commented
These changes look great, thanks @stayseesong
@markzegarelli can you accept them? I think since you're the PR author, I can't accept the suggested changes.

Also happy to go in and make the changes directly on the file itself if faster.

2023-01-30 19:47 UTC, AnimeshKoratana commented
@stayseesong @markzegarelli is there anything else to be done on our end before the deploy?

2023-01-31 17:21 UTC, stayseesong approved these changes

2023-01-31 17:23 UTC, merged