Add note mentioning need to configure at least one mapping
segmentio/segment-docs pull request #4159
Opened 2023-01-31 15:41 UTC by bobbyatsegment

### Proposed changes

Since this destination does not currently offer pre-configured mappings upon creating a new destination instance, add note to Getting Started steps that mentions the need for at least one configured and enabled mapping in an Actions framework destination in order for data to reach downstream. 

### Merge timing

### Related issues (optional)

2023-02-02 15:48 UTC, spencerattick approved these changes

2023-02-03 19:00 UTC, markzegarelli requested changes

2023-02-03 19:00 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-hubspot-cloud/index.md
> +> At least one mapping to handle a connected source's event(s) must be configured and enabled in an Actions-framework destination in order for data to be sent downstream.
```suggestion
> At least one mapping to handle a connected source's event(s) must be configured and enabled in an Actions-framework destination in order for data to be sent downstream.
To ensure that data is sent downstream, configure and enable at least one mapping to handle a connected sources event(s)
```
Passive voice to active voice

2023-02-03 19:16 UTC, stayseesong requested changes

2023-02-03 19:16 UTC, stayseesong commented on src/connections/destinations/catalog/actions-hubspot-cloud/index.md
> +> At least one mapping to handle a connected source's event(s) must be configured and enabled in an Actions-framework destination in order for data to be sent downstream.
```suggestion
> You must configure and enable at least one mapping to handle a connected source's event in an Actions framework destination in order for data to be sent downstream. 
```

2023-02-21 19:03 UTC, stayseesong approved these changes

2023-02-21 19:03 UTC, merged