Updating docs for Facebook Lead ads
segmentio/segment-docs pull request #4168
Opened 2023-02-01 17:32 UTC by saitwilio

### Proposed changes

Updating Facebook Lead Ads permissions section as they have changed via FB updates

### Merge timing
ASAP once approved

2023-02-01 22:57 UTC, rchinn-segment requested changes

2023-02-01 22:57 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
> +The following permissions are used to access the page information for the page dropdown, and the lead information for enrichment purposes inside FB leads ads service. More info [here] (https://develo
```suggestion
Use the following permissions to access the page and lead information for enrichment purposes with Facebook lead ads. You must have the following permissions to set this source up:
```

2023-02-01 22:57 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
```suggestion
Learn more about permissions [here] (https://developers.facebook.com/docs/marketing-api/guides/lead-ads/retrieving){:target="_blank"}.
```

2023-02-01 22:57 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
>  Leads Access Permissions are required to retrieve leads generated by Facebook Lead Ads. This is the default permissions for most roles. Learn more about permissions by [following this link](https://w
```suggestion
Leads Access Permissions are required to retrieve leads generated by Facebook Lead Ads. This is the default permissions for most roles. Learn more about permissions by [following this link](https://www.facebook.com/business/help/1440176552713521){:target="_blank"}.
```

2023-02-02 16:21 UTC, markzegarelli approved these changes

2023-02-02 16:21 UTC, merged