[CHA-1585] add user deletion, cart clearing, email under traits
segmentio/segment-docs pull request #4207
Opened 2023-02-09 21:43 UTC by scshull119

### Proposed changes

We would like to update the Sailthru V2 documentation to reflect recent additions to the Sailthru Destination API.  Newly documented functionality includes:
* The ability to trigger user deletion
* The ability to pass email under `context.traits`
* The ability to clear stale items from a shopping cart before new cart additions or removals are applied

### Merge timing
ASAP once approved

2023-02-10 01:29 UTC, stayseesong requested changes

2023-02-10 01:29 UTC, stayseesong commented on src/connections/destinations/catalog/sailthru-v2/index.md
> +Email address passed at top level:
```suggestion
Pass an email address at the top level using the `identify` call:
```

2023-02-10 01:29 UTC, stayseesong commented on src/connections/destinations/catalog/sailthru-v2/index.md
> +Email passed under context.traits:
```suggestion
Pass an email under `context.traits` using the identify call:
```

2023-02-10 01:29 UTC, stayseesong commented on src/connections/destinations/catalog/sailthru-v2/index.md
> +**Note:** Sailthru will also search for the email address in the identify call() under context.traits if not provided at the top-level.
```suggestion
> note ""
> **NOTE:** Sailthru searches for the email address in the `identify` call under `context.traits` if it isn't provided at the top-level.
```

2023-02-10 01:29 UTC, stayseesong commented on src/connections/destinations/catalog/sailthru-v2/index.md
> +For user deletion, the email needs to be included in the userId or context.traits track call, in a call like the following:
```suggestion
To delete a user, the email needs to be included in the `userId` or `context.traits` track call, in a call like the following:
```

2023-02-10 01:29 UTC, stayseesong commented on src/connections/destinations/catalog/sailthru-v2/index.md
> +The timestamp of the last payload received (purchase_incomplete.time) will be compared with the clearIncompleteCartAfterNHours value to determine if cart is expired. If the cart is determined to be e
```suggestion
To determine if the cart is expired, the timestamp of the last payload received (`purchase_incomplete.time`) is compared with the `clearIncompleteCartAfterNHours` value. If the cart is expired, any pre-existing products in the cart will be removed.
```

2023-02-10 15:12 UTC, scshull119 commented
Thank you for the review!

2023-02-14 16:54 UTC, markzegarelli approved these changes

2023-02-14 23:39 UTC, stayseesong requested changes

2023-02-14 23:39 UTC, stayseesong commented on src/connections/destinations/catalog/sailthru-v2/index.md
> +To delete a user, the email needs to be included in the `userId` or `context.traits` track call, in a call like the following:
```suggestion
To delete a user, you need to include the email in the `userId` or `context.traits` track call, in a call like the following:
```

2023-02-14 23:39 UTC, stayseesong commented on src/connections/destinations/catalog/sailthru-v2/index.md
> +* Only whole positive numbers are supported. If fractional numbers are included, the number will be truncated (e.g. 1.5 will be 1)
```suggestion
* Only whole positive numbers are supported. If fractional numbers are included, the number will be truncated (for example, 1.5 will be 1)
```

2023-02-14 23:39 UTC, stayseesong commented on src/connections/destinations/catalog/sailthru-v2/index.md
> +* If a number is passed in a string format such as "1", it will be parsed and converted to integer
```suggestion
* If a number is passed in a string format such as `1`, it will be parsed and converted to an integer
```

2023-02-14 23:39 UTC, stayseesong commented
@scshull119 a few more changes and then I can merge this in

2023-02-15 16:46 UTC, scshull119 commented on src/connections/destinations/catalog/sailthru-v2/index.md
> +* If a number is passed in a string format such as "1", it will be parsed and converted to integer
I changed it to `"1"`.  We'd like to keep the double quotes to make clear that this a is a string representation of a number, not a number literal.  I adopted your suggestion to use code formatting though.

2023-02-15 18:16 UTC, stayseesong approved these changes

2023-02-15 18:18 UTC, merged