Adding Launchpad documentation
segmentio/segment-docs pull request #4216
Opened 2023-02-10 19:08 UTC by SSabev

### Proposed changes

Adding documentation for the Launchpad integration. 

### Merge timing
- ASAP Once approved

### Related issues (optional)

The integration is merged in private Beta already. PR is here -> https://github.com/segmentio/action-destinations/pull/1010

2023-02-11 00:40 UTC, stayseesong requested changes

2023-02-11 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/launchpad/index.md
> +[<Launchpad>](https://www.launchpad.pm/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners)  is Mission Control for growing product-led companies. It helps you monitor projects and outcomes i
```suggestion
[Launchpad](https://www.launchpad.pm/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} is mission control for growing product-led companies. Launchpad helps you monitor projects and outcomes in one place so that you can keep your business on track.
```

2023-02-11 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/launchpad/index.md
> +> (delete after reading) Update your company name and support email address.
```suggestion
```

2023-02-11 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/launchpad/index.md
> +This destination is maintained by <Launchpad>. For any issues with the destination, [contact our Support team](mailto:support@launchpad.pm).
```suggestion
Launchpad maintains this destination. For any issues with the destination, [contact the Launchpad Support team](mailto:support@launchpad.pm).
```

2023-02-11 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/launchpad/index.md
> +1. From the Segment web app, click **Catalog**, then click **Destinations**.
```suggestion
1. From the Segment web app, navigate to **Connections > Catalog** and click **Destinations**.
```

2023-02-11 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/launchpad/index.md
> +2. Find the Destinations Actions item in the left navigation, and click it.
```suggestion
2. Select Destinations Actions under **Categories** from the left navigation.
```

2023-02-11 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/launchpad/index.md
> +3. Click **Configure Launchpad**.
```suggestion
3. Search for **Launchpad (Actions)** and click **Configure Launchpad**.
```

2023-02-11 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/launchpad/index.md
> +5. Copy your API Key from Launchpad. You can find that in the settings of the app.
```suggestion
5. Copy your API Key from Launchpad. You can find the API key in the settings of the Launchpad app. 
```

2023-02-11 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/launchpad/index.md
> +This destination is meant to work a standard Segment integration. We work with track, identify and group events to showcase launch performance and help you better understand your customers.
```suggestion
Launchpad works with track, identify and group events to showcase launch performance and help you better understand your customers.
```

2023-02-11 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/launchpad/index.md
> +---
```suggestion
```

2023-02-11 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/launchpad/index.md
> +## title:Launchpad Destination
```suggestion
---
title: Launchpad (Actions) Destination
---
```

2023-02-11 16:32 UTC, SSabev commented
@stayseesong Thanks for the suggestions, all implemented!

2023-02-13 20:17 UTC, stayseesong commented
@SSabev I'm closing this PR as I created PR #4223 to be able to edit the documentation with changes. I will merge the docs in once the destination is available in the catalog

2023-02-13 20:17 UTC, closed without merging