add event names that TikTok supports
segmentio/segment-docs pull request #4217
Opened 2023-02-10 19:20 UTC by spencerattick

### Proposed changes

TikTok doesn't support all event names, just their standard ones: https://ads.tiktok.com/marketing_api/docs?id=1727541103358977). This update makes customers aware of that.

### Merge timing
ASAP is fine

2023-02-10 22:57 UTC, stayseesong requested changes

2023-02-10 22:57 UTC, stayseesong commented on src/connections/destinations/catalog/tiktok-conversions/index.md
> +Please be aware that TikTok only supports [these event names]([url](https://ads.tiktok.com/marketing_api/docs?id=1727541103358977)).
```suggestion
Please be aware that TikTok only supports [these event names](https://ads.tiktok.com/marketing_api/docs?id=1727541103358977){:target="_blank"}.
```

2023-02-14 16:53 UTC, markzegarelli approved these changes

2023-02-21 19:05 UTC, stayseesong approved these changes

2023-02-21 19:05 UTC, merged