Upollo pr
segmentio/segment-docs pull request #4240
Opened 2023-02-16 03:39 UTC by stephennancekivell

Hi. This PR adds the documentation to go along with our new [integration](https://github.com/segmentio/action-destinations/pull/1050)

### Proposed changes

Add the Upollo Destination documentation to go along with our new integration.

### Merge timing
- After https://github.com/segmentio/action-destinations/pull/1050
- ASAP once approved?

### Related issues (optional)
- https://github.com/segmentio/action-destinations/pull/1050

2023-02-17 23:25 UTC, stayseesong requested changes

2023-02-17 23:25 UTC, stayseesong commented on src/connections/destinations/catalog/upollo/index.md
> +11% of users signing up for free trials have [already used one](https://upollo.ai/blog/turn-repeated-trials-into-growth?utm_source=segmentio&utm_medium=docs&utm_campaign=partners), and up to 45% of u
@stephennancekivell what do you mean by "have already used one?"

2023-02-17 23:25 UTC, stayseesong commented on src/connections/destinations/catalog/upollo/index.md
> +This destination is maintained by Upollo. For any questions or issues with the destination, please [contact the Upollo team](https://upollo.ai/contact?utm_source=segmentio&utm_medium=docs&utm_campaig
```suggestion
This destination is maintained by Upollo. For any questions or issues with the destination, please [contact the Upollo team](https://upollo.ai/contact?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"}.
```

2023-02-17 23:25 UTC, stayseesong commented on src/connections/destinations/catalog/upollo/index.md
> +title: Upollo Destination
```suggestion
title: Upollo (Actions) Destination
```

2023-02-17 23:25 UTC, stayseesong commented on src/connections/destinations/catalog/upollo/index.md
> +2. Add that to the segment configuration
```suggestion
```

2023-02-17 23:25 UTC, stayseesong commented on src/connections/destinations/catalog/upollo/index.md
> +1. From the Segment web app, click **Catalog**, then click **Destinations**.
```suggestion
1. From the Segment web app, navigate to **Connections > Catalog**, and select the **Destinations** tab. 
```

2023-02-17 23:25 UTC, stayseesong commented on src/connections/destinations/catalog/upollo/index.md
> +2. Find the Destinations Actions item in the left navigation, and click it.
```suggestion
2. Select **Destinations Actions** under **Categories** in the left navigation.
```

2023-02-17 23:25 UTC, stayseesong commented on src/connections/destinations/catalog/upollo/index.md
> +5. Get your **Public API key** from the [Upollo dashboard](https://upollo.ai/app/settings/access-and-keys?utm_source=segmentio&utm_medium=docs&utm_campaign=partners).
```suggestion
5. Get your **Public API key** from the [Upollo dashboard](https://upollo.ai/app/settings/access-and-keys?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"}.
```

2023-02-17 23:25 UTC, stayseesong commented on src/connections/destinations/catalog/upollo/index.md
> +Upollo uses segments identify call to analyse users on your platform. If the same person is using mulitple accounts or if different people are sharing an account they will be flagged and shown in the
```suggestion
Upollo uses the `identify` call to analyze users on your platform. If the same person is using multiple accounts or if different people are sharing an account, they are flagged and shown in the Upollo dashboard.
```

2023-02-17 23:25 UTC, stayseesong commented on src/connections/destinations/catalog/upollo/index.md
> +For more see the [Identify API documentation](/docs/connections/spec/identify/).
```suggestion
Learn more about the [Identify call](/docs/connections/spec/identify/).
```

2023-02-17 23:25 UTC, stayseesong commented on src/connections/destinations/catalog/upollo/index.md
> +In the `identify` call provide any available information.
```suggestion
The `identify` call provides any available information about the user.
```

2023-02-19 22:09 UTC, stephennancekivell commented on src/connections/destinations/catalog/upollo/index.md
> +title: Upollo Destination
Hi @stayseesong. Thanks for your help.

2023-02-19 22:31 UTC, stephennancekivell commented on src/connections/destinations/catalog/upollo/index.md
> +11% of users signing up for free trials have [already used one](https://upollo.ai/blog/turn-repeated-trials-into-growth?utm_source=segmentio&utm_medium=docs&utm_campaign=partners), and up to 45% of u
Hi @stayseesong, normally when a company offers a free trial its offered so that you get one free trial then you need to upgrade to paid plan. Lots of users get additional free trials with a few tricks.

Im not sure if theres a concise way to make that clearer here. I dont think we want to get into too much detail in this summary.

We might change "already used one" to "already had one".

Thanks for your help.

2023-02-22 18:47 UTC, stayseesong commented
@stephennancekivell I'm closing this PR out as I made an editable version of this PR for the docs team here #4273

2023-02-22 18:47 UTC, closed without merging

2023-02-22 21:46 UTC, stephennancekivell commented
Thanks @stayseesong