Adding qualtircs source documentation
segmentio/segment-docs pull request #4241
Opened 2023-02-16 13:55 UTC by carlmlee

### Proposed changes

Adding the initial Qualtrics source documentation

### Merge timing
To align with readiness of the source for public beta.

2023-02-16 17:40 UTC, rchinn-segment requested changes
Thanks for submitting, @carlmlee! Just a few requested changes to align this with our style guide.

2023-02-16 17:40 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/qualtrics/index.md
>  hidden: true
```suggestion
hidden: true
beta: true
```

2023-02-16 17:40 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/qualtrics/index.md
> +[Qualtrics](https://qualtrics.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners) [Qualtrics]() is an Experience Management platform that allows companies to design and improve customer
```suggestion
[Qualtrics](https://qualtrics.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} is an Experience Management platform that allows companies to design and improve customer and employee experiences through listening, analysis, and action.
```

2023-02-16 17:40 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/qualtrics/index.md
> +This source is maintained by Qualtrics. For any issues with the source, [contact their Support team](mailto:support@qualtrics.com).
```suggestion
Qualtrics maintains this source. For any issues with the source, [contact the Qualtrics Support team](mailto:support@qualtrics.com).
```

2023-02-16 17:40 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/qualtrics/index.md
> +---
```suggestion

```

2023-02-16 17:40 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/qualtrics/index.md
> +   - The nickname is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The nickname can be anything, but we recommend using something that reflects the
```suggestion
   - The nickname is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The nickname can be anything, but Segment recommends using something that reflects the source itself and distinguishes amongst your environments (for example, SourceName_Prod, SourceName_Staging, or SourceName_Dev).
```

2023-02-16 17:40 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/qualtrics/index.md
> +
```suggestion
```

2023-02-16 17:40 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/qualtrics/index.md
> +
```suggestion
```

2023-02-16 17:40 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/qualtrics/index.md
> +7. See more information on the Qualtrics Segment task at the following [Qualtrics support page](https://www.qualtrics.com/support/integrations/twilio-segment/twilio-segment-task/)
```suggestion
7. For more information on the Qualtrics Segment task, view the [Qualtrics support page](https://www.qualtrics.com/support/integrations/twilio-segment/twilio-segment-task/){:target="_blank"}.
```

2023-02-16 17:40 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/qualtrics/index.md
> +- `Track` events allow you to define the `properties` object
```suggestion
- Use `Track` events to define the `properties` object
```

2023-02-16 17:40 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/qualtrics/index.md
> +- `Identify` events allow you to define the `traits` object
```suggestion
- Use `Identify` events to define the `traits` object
```

2023-02-16 17:40 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/qualtrics/index.md
> +This source is maintained by Qualtrics. For any issues with the source, [contact their Support team](mailto:support@qualtrics.com).
Passive > Active voice

2023-02-16 17:40 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/qualtrics/index.md
> +   - The nickname is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The nickname can be anything, but we recommend using something that reflects the
we > Segment and eg. > for example

2023-02-16 23:35 UTC, rchinn-segment approved these changes
Looks good, @tcgilbert - Is there a specific date that we want to merge this? If so, I'll update the pr.

2023-02-21 15:02 UTC, tcgilbert approved these changes
looks good!

2023-02-21 15:03 UTC, merged