Update documentation on CSP
segmentio/segment-docs pull request #4248
Opened 2023-02-16 21:13 UTC by sarahrudy

### Proposed changes
- Add whitelisting approved domains
- Add info section about support we're able to provide around CSP issues

### Merge timing
- ASAP once approved?

### Related issues (optional)
N/A

2023-02-16 23:51 UTC, pwseg commented on src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
> +Your CSP may also require whitelisting approved domains, in which case you'll want to allow the following endpoints:
```suggestion
Your CSP may also require you to allowlist approved domains, in which case you'll want to allow the following endpoints: 
```

Just a heads up: in the docs, we use **allowlist** instead of **whitelist**.

2023-02-16 23:51 UTC, pwseg requested changes
Just the small allowlist/whitelist thing to fix.  Thanks!

2023-02-17 20:56 UTC, sarahrudy commented
Thank you, @pwseg!

2023-02-17 22:06 UTC, pwseg approved these changes

2023-02-23 18:06 UTC, merged