Update roles.md
segmentio/segment-docs pull request #4251
Opened 2023-02-17 04:40 UTC by terence1988

### Proposed changes
Add explanation for Privacy Portal. When user need to access the Privacy Portal, it will require the 'Workspace Owner' role. Granting all other roles doesn't provide enough permission.

### Merge timing

2023-02-24 11:54 UTC, dineshraj-arunmozhi approved these changes
Approved

2023-02-27 19:36 UTC, stayseesong requested changes

2023-02-27 19:36 UTC, stayseesong commented on src/segment-app/iam/roles.md
> +## Role for Privacy Portal
```suggestion
## Roles for Privacy Portal
```

2023-02-27 19:36 UTC, stayseesong commented on src/segment-app/iam/roles.md
> +To **view, create or edit** PII related configurations in Privacy Portal, you need to have `Workspace Owner` role.
```suggestion
To **view, create or edit** PII related configurations in Privacy Portal, you need to have the `Workspace Owner` role.
```

2023-02-27 19:37 UTC, stayseesong approved these changes

2023-02-27 19:38 UTC, merged