Remove beta note and update Segment Connections destination name
segmentio/segment-docs pull request #4257
Opened 2023-02-17 22:42 UTC by kdaswani

### Proposed changes
Remove Beta note at top of doc as the Segment Connections destination **will move to GA on February 27**. Please don't merge in until Feb 27; totally fine if this goes out during the Feb 28 deploy.

This also updates the name. It was previously just Segment destination; now it is Segment Connections destination as we will be rolling out a separate Segment Profiles destination soon.

### Merge timing
- On a specific date? February 27

2023-02-22 18:57 UTC, stayseesong requested changes

2023-02-22 18:57 UTC, stayseesong commented on src/connections/destinations/catalog/actions-segment/index.md
> +**The Segment Connections destination can be connected to Reverse ETL warehouse sources only.**
```suggestion
**You can only connect the Segment Connections destination to Reverse ETL warehouse sources.**
```

2023-02-22 18:57 UTC, stayseesong commented on src/connections/destinations/catalog/actions-segment/index.md
>  2. Click **Add Destination** in top-right corner.
```suggestion
2. Click **Add Destination**.
```

2023-02-24 23:53 UTC, kdaswani commented
@stayseesong for some reason, I can't commit your suggestions but they look good to me. Can you apply them and approve?

2023-02-27 19:06 UTC, stayseesong approved these changes

2023-02-27 19:16 UTC, merged