Update index.md
segmentio/segment-docs pull request #4262
Opened 2023-02-21 06:41 UTC by tanjinhong72

### Proposed changes

Modify the "Recording userId" section, add in information to indicate userId should not be pass as 'Id' in trait as trait.id is a reserved trait. Customer has tried to pass 'userId' as 'Id' in trait and it does not get sent to MailChimp. 

Added in the following sentences to "Recording UserId" section: "One thing to take note is not to pass 'userId' as 'id' in trait as trait.id is a reserved trait. You can pass 'userId' in a trait name with a corresponding merge field in MailChimp."

### Merge timing

### Related issues (optional)

[](https://segment.zendesk.com/agent/tickets/497343)

2023-03-13 18:15 UTC, stayseesong requested changes

2023-03-13 18:15 UTC, stayseesong commented on src/connections/destinations/catalog/mailchimp/index.md
> +To record a Segment `userId` in Mailchimp, you must pass the userID as a trait on your `identify()` calls. One thing to take note is not to pass 'userId' as 'id' in trait as trait.id is a reserved tr
```suggestion
To record a Segment `userId` in Mailchimp, pass the user ID as a trait on your `identify()` calls. Don't pass the `userId` as a trait ID because the  `trait.id` is a reserved trait. Instead, pass the `userId` in a trait name with the corresponding merge field in Mailchimp. Segment doesn't automatically map the user ID to a Mailchimp property.
```

2023-03-14 15:47 UTC, markzegarelli approved these changes

2023-03-14 16:26 UTC, stayseesong approved these changes

2023-03-14 16:27 UTC, merged