Add flag for token collection
segmentio/segment-docs pull request #4282
Opened 2023-02-23 12:04 UTC by niallzato

### Proposed changes
Add flag for token collection as it is a required parameter.

2023-02-23 17:05 UTC, markzegarelli commented on src/connections/destinations/catalog/customer-io-actions/index.md
> +Segment does not automatically collect push notification tokens. These parameters are required by Customer.io, requiring logic to be implemented to collect these values.
@niallzato So users of Customer.io Actions need to implement collection of push notification tokens? Is there an example we can provide for how to handle this?

2023-03-28 11:09 UTC, niallzato commented on src/connections/destinations/catalog/customer-io-actions/index.md
> +Segment does not automatically collect push notification tokens. These parameters are required by Customer.io, requiring logic to be implemented to collect these values.
Hey @markzegarelli I added more context and a link to a repo. Let me know if that looks good!

2023-04-11 16:17 UTC, stayseesong requested changes

2023-04-11 16:18 UTC, stayseesong approved these changes

2023-04-11 16:28 UTC, markzegarelli approved these changes

2023-04-11 17:25 UTC, merged