add docs for toplyne destination action
segmentio/segment-docs pull request #4294
Opened 2023-02-24 12:31 UTC by ankitjena

### Proposed changes
- Added documentation for Toplyne destination action in segment

### Merge timing
- Depends on the Toplyne destination action PR on `action-destinations` repo.

### Related issues (optional)
https://github.com/segmentio/action-destinations/pull/1068

2023-02-24 18:02 UTC, markzegarelli commented on src/connections/destinations/catalog/toplyne/index.md
> +title: <destination_name>
```suggestion
title: Toplyne (Actions) Destination
```

2023-02-24 18:06 UTC, markzegarelli requested changes

2023-02-24 18:06 UTC, markzegarelli commented on src/connections/destinations/catalog/toplyne/index.md
> +[Toplyne](https://www.toplyne.io/) is a headless Sales AI for revenue teams. Our AI captures and understands every user click stored in your Segment and enriches it with demographic data (through 3rd
```suggestion
[Toplyne](https://www.toplyne.io/) is a headless Sales AI for revenue teams. Toplyne's AI captures and understands every user click passed through Segment and enriches it with demographic data (through 3rd party enrichment tools). Toplyne then delivers opportunities for expansion and conversion into your existing CRM without involving your data and engineering teams.
```

2023-03-09 17:00 UTC, stayseesong requested changes

2023-03-09 17:00 UTC, stayseesong commented on src/connections/destinations/catalog/toplyne/index.md
> +9. Enable the destination and save changes
```suggestion
9. Save your changes and enable the destination.
```

2023-03-09 17:25 UTC, stayseesong commented
@ankitjena I'm closing this PR out as I created an editable version for the docs team at #4387  so that we can get this out today

2023-03-09 17:25 UTC, closed without merging