Draft: Segment Profiles
segmentio/segment-docs pull request #4329
Opened 2023-03-01 04:50 UTC by sayan-das-in

### Proposed changes
This PR adds usage docs for Segment Profiles Destination.

### Merge timing
- When Segment Profiles Destination goes Public Beta.

2023-03-01 05:45 UTC, kdaswani approved these changes
Made some updates. Approved by me! Passing to docs team @markzegarelli @stayseesong for final review before March 7 docs deploy.

FYI I will be OOO March 1-6 so please feel free to commit any changes you see fit and merge this in ahead of the March 7 deploy. Thanks!

2023-03-01 22:26 UTC, markzegarelli requested changes

2023-03-01 22:26 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-segment-profiles/index.md
> +**You can only connect the Segment Profiles destination to Reverse ETL warehouse sources.**
```suggestion
> success "Source compatibility"
> This destination supports connections from Reverse ETL warehouse sources, and is not compatible with other source types.
```

2023-03-01 22:26 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-segment-profiles/index.md
> +To use this destination, you must have an active Segment Profile space. If you have not yet created a Segment Profile space, please follow the steps on the [Profiles Onboarding Guide](/docs/profiles/
```suggestion
To use this destination, you must have an active Segment Profile space. If you have not yet created a Segment Profile space, please follow the steps in the [Profiles Onboarding Guide](/docs/profiles/quickstart/).
```

2023-03-01 22:26 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-segment-profiles/index.md
> +In order for the Segment Profiles destination to send data to an existing Profile space, you must provide an authentication token for the Segment Public API. See [Segment's Public API documentation](
```suggestion
To enable the Segment Profiles destination to send data to an existing Profile space, provide an authentication token for the Segment Public API. See [Segment's Public API documentation](https://docs.segmentapis.com/tag/Getting-Started#section/Get-an-API-token){:target="_blank"} for information on how to create a token. The token must include Source Admin permissions. You will need this token in the below steps.
```

2023-03-06 20:04 UTC, kdaswani commented
@markzegarelli made the suggested changes! Is this good to go out in tomorrow's deploy? Thanks!

2023-03-06 20:44 UTC, markzegarelli approved these changes

2023-03-06 20:44 UTC, markzegarelli commented
@kdaswani 🚢

2023-03-06 20:45 UTC, merged