Update Transformation doc
segmentio/segment-docs pull request #4376
Opened 2023-03-08 07:01 UTC by vanand17

Update a line to provide example and clarify what we are explaining in our docs to avoid confusion.

### Merge timing
NA

### Related issues (optional)

NA

2023-03-17 10:06 UTC, forstisabella requested changes
looks good to me pending a few small changes!

2023-03-17 10:06 UTC, forstisabella commented on src/protocols/transform/index.md
> +In this scenario, we do not support the transformation of product_id.
```suggestion
```

2023-03-17 10:06 UTC, forstisabella commented on src/protocols/transform/index.md
> +If you rename properties or traits within a selected event, click **+ Add Property**. The dropdown that appears contains the properties or traits sent with the selected event. Segment supports JSON P
```suggestion
If you rename properties or traits within a selected event, click **+ Add Property**. The dropdown that appears contains the properties or traits sent with the selected event. Segment supports JSON Path notation to select nested objects up to four levels deep. For example, `order.id` selects the `id` property in the `order` object. Segment does not support `.$.` notation to select a property from an array of objects. For example, the following event would be unable to generate products.$.product_id:
```

2023-03-20 06:33 UTC, vanand17 commented on src/protocols/transform/index.md
> +If you rename properties or traits within a selected event, click **+ Add Property**. The dropdown that appears contains the properties or traits sent with the selected event. Segment supports JSON P
Hi @forstisabella Thanks for your feedback about the code block, will remember that for future changes.
Regarding your proposed line here, "For example, the following event would be unable to generate products.$.product_id"
That might not be in line with what we are saying. We are providing an example to let them know that is how a nested property would look in a payload, and that this is currently not supported in Transformations.
Hence, we are saying the following event will generate products.$.product_id , and after the code block, we mention that this product_id will not be supported in Transformations.

Let me know if I have misunderstood anything here.

2023-03-20 19:58 UTC, forstisabella commented on src/protocols/transform/index.md
> +If you rename properties or traits within a selected event, click **+ Add Property**. The dropdown that appears contains the properties or traits sent with the selected event. Segment supports JSON P
Hi @vanand17 - if Segment does not currently support something, I might avoid including an example to minimize confusion. Reading "_For example, the following event will generate products.$.product_id:_" and then seeing immediately after the example that it's not supported is confusing!

You could try including info about what Segment **doesn't** support in a `warning` callout brings it to the user's attention and sets it apart from the surrounding content. 

Also - what happens if a user tries to use a nested Transformation?

2023-03-22 06:37 UTC, vanand17 commented on src/protocols/transform/index.md
> +If you rename properties or traits within a selected event, click **+ Add Property**. The dropdown that appears contains the properties or traits sent with the selected event. Segment supports JSON P
Hi @forstisabella I agree, however some customers are confused about the nested property, hence we thought providing an example would be a good way to clear that up. For example, they think product.product_id is the same as order.id
I hope that example explains the confusion we typically see with customers.
Users will not be able to select a nested property in transformation as it is not supported.

2023-03-24 20:31 UTC, forstisabella reviewed
Looks good to me pending one more change.

2023-03-24 20:31 UTC, forstisabella commented on src/protocols/transform/index.md
> +If you rename properties or traits within a selected event, click **+ Add Property**. The dropdown that appears contains the properties or traits sent with the selected event. Segment supports JSON P
```suggestion
To rename properties or traits within a selected event, click **+ Add Property**. The dropdown that appears contains the properties or traits sent with the selected event. Segment supports JSON Path notation to select nested objects up to four levels deep. For example, `order.id` selects the `id` property in the `order` object. Segment does not support `.$.` notation to select a property from an array of objects. For example, the following event, which generates `products.$.product_id`, is unsupported.
```

2023-03-27 03:56 UTC, vanand17 commented
Looks good to me, thank you!

2023-03-30 16:37 UTC, forstisabella approved these changes

2023-03-30 16:37 UTC, merged