Added details about Hashing emails
segmentio/segment-docs pull request #4379
Opened 2023-03-08 19:13 UTC by pharika31

### Proposed changes

Updated documentation to include the "hash Emails" option in actions mapping settings.
This is to align with the code change in this PR: https://github.com/segmentio/action-destinations/pull/1077

### Merge timing
Can you merge this after the PR https://github.com/segmentio/action-destinations/pull/1077 is merged?

2023-03-08 19:26 UTC, markzegarelli requested changes

2023-03-08 19:26 UTC, markzegarelli commented on src/connections/destinations/catalog/criteo-audiences/index.md
> +8. In the **Mappings** tab, click **New Mapping** and select **Add Users to Audience**. If you wish your emails to be hashed before sending to Criteo, please select "yes" from the dropdown under "Has
```suggestion
8. In the **Mappings** tab, click **New Mapping** and select **Add Users to Audience**. If you wish your emails to be hashed before sending to Criteo, please select "yes" from the dropdown under "Hash Emails". Otherwise, do not change any default settings. By Default, emails are not hashed before sending to Criteo - Criteo hashes emails before storing them. To hash emails before you send them to Criteo, select **yes** in the **Hash Emails** dropdown. By default, Criteo does not hash emails before sending them, but does hash emails before storing them.
```

2023-03-15 18:28 UTC, pharika31 commented on src/connections/destinations/catalog/criteo-audiences/index.md
> +8. In the **Mappings** tab, click **New Mapping** and select **Add Users to Audience**. If you wish your emails to be hashed before sending to Criteo, please select "yes" from the dropdown under "Has
Hey @markzegarelli 
What I see above seems repetitive. Can we do this instead?

`In the **Mappings** tab, click **New Mapping** and select **Add Users to Audience**. To hash emails before you send them to Criteo, select **yes** in the **Hash Emails** dropdown. By default, emails are not hashed before you send them to Criteo; however, Criteo will hash the emails before storing them in our system. DO NOT change any other default settings. `

2023-03-23 18:35 UTC, markzegarelli commented on src/connections/destinations/catalog/criteo-audiences/index.md
> +8. In the **Mappings** tab, click **New Mapping** and select **Add Users to Audience**. If you wish your emails to be hashed before sending to Criteo, please select "yes" from the dropdown under "Has
```suggestion
8. In the **Mappings** tab, click **New Mapping** and select **Add Users to Audience**. To hash emails before you send them to Criteo, select **yes** in the **Hash Emails** dropdown. By default, emails are not hashed before you send them to Criteo; however, Criteo will hash the emails before storing them in our system. DO NOT change any other default settings. 
```

2023-03-29 13:36 UTC, tcgilbert approved these changes

2023-03-29 13:37 UTC, tcgilbert commented
@markzegarelli are we good to go with this one?

2023-04-24 15:59 UTC, markzegarelli approved these changes

2023-04-24 15:59 UTC, merged