Add Intro & Getting Started sections to Eloqua docs
segmentio/segment-docs pull request #4381
Opened 2023-03-09 01:07 UTC by sarahrudy

### Proposed changes

This particular destination didn't have much of an intro or setup instructions. I added an Intro and Getting Started section to the top of the page. 

### Merge timing
- ASAP once approved?

2023-03-13 18:40 UTC, stayseesong requested changes

2023-03-13 18:40 UTC, stayseesong commented on src/connections/destinations/catalog/eloqua/index.md
> +With Segment, all the customer data you’re collecting from your websites, mobile apps, or servers gets sent directly into Eloqua, utilizing your existing Segment implementation. That means you don’t
```suggestion
With Segment, all the customer data you’re collecting from your websites, mobile apps, or servers sends directly into Eloqua, using your existing Segment implementation. This means you don’t need to write any custom code or create duplicate event tracking, but you can start using Eloqua with a simplified setup effort. 
```

2023-03-13 18:40 UTC, stayseesong commented on src/connections/destinations/catalog/eloqua/index.md
> +1. From the Segment web app, navigate to **Connections > Catalog**.
```suggestion
1. From the Segment web app, navigate to **Connections > Catalog** and select the **Destinations** tab within the catalog.
```

2023-03-13 18:40 UTC, stayseesong commented on src/connections/destinations/catalog/eloqua/index.md
> +2. Search for **Eloqua** in the Destinations Catalog, and select the destination.
```suggestion
2. Search for **Eloqua** and select the destination.
```

2023-03-13 18:40 UTC, stayseesong commented on src/connections/destinations/catalog/eloqua/index.md
> +When you enable Eloqua in your Segment integrations page, Segment will automatically load Eloqua’s JavaScript libraries onto your web pages. For mobile and server-side events, Segment will route your
```suggestion
When you enable Eloqua in your Segment integrations page, Segment automatically loads Eloqua’s JavaScript libraries onto your web pages. For mobile and server-side events, Segment routes your event data directly through Eloqua's servers, eliminating the need for any Eloqua code to be loaded in your applications.
```

2023-03-14 15:46 UTC, markzegarelli approved these changes

2023-03-14 15:52 UTC, stayseesong approved these changes

2023-03-14 15:53 UTC, merged