Sentry destination update
segmentio/segment-docs pull request #4415
Opened 2023-03-14 23:19 UTC by vanand17

### Proposed changes

We have had multiple cases of customers questioning how Sentry destination works when added as a destination since it doesn't report errors out of the box. Since it is an error tracking tool, I feel we could have the following section in our docs for clarification.

### Merge timing
NA

### Related issues (optional)
NA

2023-03-21 16:04 UTC, stayseesong requested changes

2023-03-21 16:04 UTC, markzegarelli commented
@vanand17 can you send a full screen, not marked up version of the screenshot you've added to me Slack? I think GitHub may have compressed or shrunk it.

2023-03-21 16:07 UTC, stayseesong requested changes
@vanand17 is it ok if we remove the image? Is it necessary to have?

2023-03-27 18:29 UTC, markzegarelli commented on src/connections/destinations/catalog/sentry/index.md
> + ![image](https://user-images.githubusercontent.com/96406241/226262825-d038a0c6-acbc-4b20-87bb-558c622a2be5.png)
@stayseesong I think the image is ok to include here, since it's not specific to any UI, but rather shows where to find an event_id in the chrome inspector.

@vanand17 Can you supply a full resolution image that is not marked up?

2023-03-28 05:46 UTC, vanand17 commented
Hi @markzegarelli and @stayseesong I did not want to add the entire page as it has my test website name on it, and we thought it would be better to avoid having it in Public documentation.

Is there any other way I can provide you with the screenshot?

2023-03-30 16:08 UTC, markzegarelli commented
@vanand17 We will crop the screenshot to a final size, we just want the original size to start with.

2023-03-31 04:35 UTC, vanand17 commented
Thanks. Here is the screenshot from my laptop screens and not my external monitor.
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/96406241/229023481-9a8276f7-869b-427b-bb32-2bfc9cd9fe4a.png">

Please let me know if I need to update it in the PR itself

2023-04-11 16:33 UTC, markzegarelli approved these changes

2023-04-11 16:33 UTC, merged