update info on creating eu-workspaces
segmentio/segment-docs pull request #4454
Opened 2023-03-22 05:20 UTC by muhammadatifjav

### Proposed changes

Currently, Segment order mgmt and provisioning team needs to provision a customer for access to enable users to create EU workspaces. This is not mentioned in the docs, and docs only mentions the post-provisioning steps.

### Merge timing
<!-- When should this get merged/published?
ASAP once approved

### Related issues (optional)

https://segment.atlassian.net/browse/KCS-206

2023-03-22 21:13 UTC, pmbasco approved these changes

2023-03-28 15:59 UTC, stayseesong requested changes

2023-03-28 15:59 UTC, stayseesong commented on src/guides/regional-segment.md
> +To create a workspace with a different data processing region, you can reach out to the Segment Support team, and they will be able to assist with enabling the feature on request. Once the feature ha
```suggestion
To create a workspace with a different data processing region, reach out to the Segment Support team, and they will assist you with enabling the feature. Once the feature has been enabled, you'll be able to self-serve and create a new workspace in a different data processing region by following these steps:
```

2023-03-29 20:15 UTC, stayseesong approved these changes

2023-03-29 20:16 UTC, merged