Add flush policy docs
segmentio/segment-docs pull request #4480
Opened 2023-03-27 16:16 UTC by niallzato

### Proposed changes

Add flush policy docs, copied from here: https://github.com/segmentio/analytics-react-native#controlling-upload-with-flush-policies

2023-03-27 23:33 UTC, rchinn-segment requested changes
Hey @niallzato - thanks for submitting this. I've left some comments (and a few questions) to align this a bit more with our [style guide](https://github.com/segmentio/segment-docs/blob/develop/styleguide.md). After that, we'll add this to our docs!

2023-03-27 23:33 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +You can create a custom FlushPolicy special for your application needs by implementing the  `FlushPolicy` interface. You can also extend the `FlushPolicyBase` class that already creates and handles t
```suggestion
You can create a custom FlushPolicy for your application needs by implementing the  `FlushPolicy` interface. You can also extend the `FlushPolicyBase` class that already creates and handles the `shouldFlush` value reset.
```

2023-03-27 23:33 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +A `FlushPolicy` only needs to implement 2 methods:
```suggestion
A `FlushPolicy` only needs to implement two methods:
```

2023-03-27 23:33 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +- `onEvent(event: SegmentEvent)`: Gets called on every event tracked by your client
```suggestion
- `onEvent(event: SegmentEvent)`: Called on every event tracked by your client
```

2023-03-27 23:33 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +- `reset()`: Called after a flush is triggered (either by your policy, by another policy or manually)
```suggestion
- `reset()`: Called after a flush is triggered (either by your policy, by another policy, or manually)
```

2023-03-27 23:33 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +They also have a `shouldFlush` observable boolean value. When this is set to true the client will attempt to upload events. Each policy should reset this value to `false` according to its own logic,
```suggestion
Your policies also have a `shouldFlush` observable boolean value. When this is set to true the client attempts to upload events. Each policy should reset this value to `false` according to its own logic, although it's common to do it inside the `reset` method.
```

2023-03-27 23:33 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +We have several standard FlushPolicies:
Not sure if it needs to be `FlushPolicies`, as it's written as `Flush Policies` above. Just want to try and make this as consistent as possible.

2023-03-27 23:33 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +// If we detect the user disconnects from the network remove all flush policies,
Do the instances of `we` in lines 377-380 all refer to `Segment`?

2023-03-27 23:33 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +One of the main advantages of FlushPolicies is that you can add and remove policies on the fly. This is very powerful when you want to reduce or increase the amount of flushes.
```suggestion
One of the main advantages of Flush Policies is that you can add and remove policies on the fly. This is very powerful when you want to reduce or increase the amount of flushes. 
```

2023-03-27 23:33 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +You can create a custom FlushPolicy special for your application needs by implementing the  `FlushPolicy` interface. You can also extend the `FlushPolicyBase` class that already creates and handles t
```suggestion
You can create a custom Flush Policy special for your application needs by implementing the  `FlushPolicy` interface. You can also extend the `FlushPolicyBase` class that already creates and handles the `shouldFlush` value reset.
```

2023-03-28 10:18 UTC, niallzato commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +// If we detect the user disconnects from the network remove all flush policies,
@rchinn-segment thanks for all the suggestions. Correct, we are referring to Segment for these instances. Specifically, the Segment library initialized in the app. We could say something like the [following](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/#:~:text=method%2C%20and%20the-,Segment%20client,-should%20be%20initialized), perhaps:

`// that way the Segment client won't keep attempting to send events to Segment, but they will still 
// be stored for future upload.
// If the network comes back up, the Segment client adds the policies back`

2023-03-28 16:29 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +// that way we won't keep attempting to send events to segment but we will still
```suggestion
// That way the Segment client won't keep attempting to send events to Segment but will still 
```

2023-03-28 16:29 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +// If the network comes back up we add the policies back
```suggestion
// If the network comes back up, the Segment client adds the policies back. 
```

2023-03-28 16:29 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +// If we detect the user disconnects from the network remove all flush policies,
```suggestion
// If Segment detects the user disconnect from the network, Segment removes all flush policies. 
```

2023-03-28 16:48 UTC, merged