Blend-AI new action destination docs
segmentio/segment-docs pull request #4516
Opened 2023-04-02 13:42 UTC by yuvlaz

### Proposed changes
Blend-AI new actions destination docs

### Merge timing
ASAP once approved

2023-04-03 22:01 UTC, stayseesong requested changes

2023-04-03 22:01 UTC, stayseesong commented on src/connections/destinations/catalog/actions-blend-ai/index.md
> +{% include components/actions-fields.html %}
```suggestion
---
title: Blend-AI (Actions) Destination
hide-boilerplate: true
hide-dossier: false
private: true
hidden: true
id: 

{% include content/plan-grid.md name="actions" %}

[Blend-AI](https://blnd.ai/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} identifies the most valuable product interaction in your product data and cross references it with new incoming leads.

Blend-AI maintains this destination. For any issues with the destination, [contact their Support 
team](mailto:support@blnd.ai).

{% include content/ajs-upgrade.md %}

## Getting started

1. From the Segment web app, navigate to **Connections > Catalog**, then select the **Destinations** tab in the catalog. 
2. Search for *Blend-AI* and select it.
3. Click **Configure Blend-AI**.
4. Select an existing Source to connect to Blend-AI (Actions).
5. Give the destination a name that is recognizable and detailed.
6. Paste your Blend's API key (found on Blend's integration page under the Segment section).
7. Enable the destination by changing the bottom **Enable Destination** toggle to active.
8. Click **Save Changes**. 

{% include components/actions-fields.html %}
```

2023-04-04 21:07 UTC, markzegarelli approved these changes

2023-04-04 21:51 UTC, stayseesong approved these changes

2023-04-04 21:51 UTC, merged