June Actions segment docs
segmentio/segment-docs pull request #4518
Opened 2023-04-03 13:19 UTC by ferrucc-io

### Proposed changes
Adding in documentation for the June Actions destination

### Merge timing
Whenever it's approved!

### Related issues (optional)

2023-04-03 13:24 UTC, ferrucc-io commented on src/connections/destinations/catalog/actions-june/index.md
> +id: ????
What should the ID be here?

2023-04-03 15:20 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-june/index.md
> +id: ????
id: 6419fce5b6e12cf44efbd34c

2023-04-03 15:30 UTC, ferrucc-io commented on src/connections/destinations/catalog/actions-june/index.md
> +id: ????
Thanks!

2023-04-03 21:33 UTC, stayseesong requested changes

2023-04-03 21:33 UTC, stayseesong commented on src/connections/destinations/catalog/actions-june/index.md
> +This destination is maintained by June. For any issues with the destination, [contact the June Support team](mailto:ferruccio@june.so).
```suggestion
June maintains this destination. For any issues with the destination, [contact the June Support team](mailto:ferruccio@june.so).
```

2023-04-03 21:33 UTC, stayseesong commented on src/connections/destinations/catalog/actions-june/index.md
> +1. Go to the [June settings page](https://app.june.so/redirect-to-my-workspace/settings), click **Add your first source**. To add more instances of the June Destination, click on the Segment integrat
```suggestion
1. Go to the [June settings page](https://app.june.so/redirect-to-my-workspace/settings){:target="_blank"} and click **Add your first source**. To add more instances of the June Destination, click on the Segment integration card and click on **Create new key** and copy the key.
```

2023-04-03 21:33 UTC, stayseesong commented on src/connections/destinations/catalog/actions-june/index.md
> +2. From the Segment web app, click **Catalog**, then click **Destinations**.
```suggestion
2. From the Segment web app, navigate to **Connections > Catalog**, and select the **Destinations** tab in the catalog.
```

2023-04-03 21:33 UTC, stayseesong commented on src/connections/destinations/catalog/actions-june/index.md
> +### Connection Modes for June (Actions) destination
```suggestion
### Connection modes for June (Actions) destination
```

2023-04-03 21:33 UTC, stayseesong commented on src/connections/destinations/catalog/actions-june/index.md
> +The June (Actions) destination does not offer a device-mode connection mode. If you're using one of Segment's new libraries ([Analytics.js 2.0](/docs/connections/sources/catalog/libraries/website/jav
```suggestion
The June (Actions) destination does not offer a device-mode connection mode. If you're using one of Segment's new libraries ([Analytics.js 2.0](/docs/connections/sources/catalog/libraries/website/javascript/){:target="_blank"}, [Swift](https://github.com/segmentio/analytics-swift){:target="_blank"} or [Kotlin](https://github.com/segmentio/analytics-kotlin){:target="_blank"}) with the Actions-framework version of the destination, you do not need the device-mode connection.
```

2023-04-03 21:33 UTC, stayseesong commented on src/connections/destinations/catalog/actions-june/index.md
> +Assuming you're already using Segment Cloud-mode, the June (Actions) destination is expected to have no breaking changes when upgrading. With the exception of a few new properties added to your event
```suggestion
If you're already using Segment cloud-mode, you're not expected to have breaking changes when upgrading to the June (Actions) destination. With the exception of a few new properties added to your events in the new Actions destination, there's no difference in the data received in June when using either of the June destinations.
```

2023-04-03 21:33 UTC, stayseesong commented on src/connections/destinations/catalog/actions-june/index.md
> +If you want to confirm, you can configure the new destination to point to a different June workspace and connect it to the same source(s) as the Classic destination and manually verify before fully s
```suggestion
You can configure the new destination to point to a different June workspace and connect it to the same source(s) as the Classic destination and manually verify it before fully switching over.
```

2023-04-05 16:57 UTC, stayseesong commented
@ferrucc-io would you be able to incorporate the edits I suggested? Thank you!

2023-04-07 16:55 UTC, ferrucc-io commented
@stayseesong it should be good to go now!

2023-04-11 16:20 UTC, stayseesong approved these changes

2023-04-11 16:23 UTC, markzegarelli approved these changes

2023-04-13 12:46 UTC, joe-ayoub-segment requested changes
hi @markzegarelli and @ferrucc-io, 

I just had a quick read through the doc, as I was the person who assisted @ferrucc-io with the PR when he was building the Integration. 

I just have a couple of comments/questions which have been left inline.

2023-04-13 12:46 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-june/index.md
> +5. Select the source you want to connect the destination to. (You can connect more sources to the destination later.)
You can't connect more Sources to a Destination. For other Sources, you can connect a new Destination, and optionally copy over the same Destination config if you like. 

```suggestion
5. Select the source you want to connect the destination to. (You can connect more sources to the destination later.)
```

2023-04-13 12:46 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-june/index.md
> +{% endcapture %}
@markzegarelli , what does this block do? i.e everything in the 'capture'? What will it render on the page?

2023-04-13 12:46 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-june/index.md
> +The June (Actions) destination does not offer a device-mode connection mode. If you're using one of Segment's new libraries ([Analytics.js 2.0](/docs/connections/sources/catalog/libraries/website/jav
I feel like this line is confusing. 

@markzegarelli Is this boiler plate? 

I'm wondering is something along the lines of: 
"The June (Actions) destination does not offer a device-mode connection mode, so all events generated on a browser or mobile app will be sent to June's servers via Segment's servers."

Or maybe I'm missing something?

2023-04-13 17:24 UTC, stayseesong requested changes

2023-04-13 17:24 UTC, stayseesong commented on src/connections/destinations/catalog/actions-june/index.md
> +5. Select the source you want to connect the destination to. (You can connect more sources to the destination later.)
```suggestion
5. Select the source you want to connect the destination to. 
```

2023-04-18 20:43 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-june/index.md
> +{% endcapture %}
@joe-ayoub-segment Sorry for the delay here.

This block is what I mentioned before, about trying to inject content into the rendered actions section. The idea here, is that everything being captured will render where it's referenced. However, this is pretty prone to error, so I think this will be a good use case for adding content to the `docs_description` object in the code.

2023-04-18 20:45 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-june/index.md
> +The June (Actions) destination does not offer a device-mode connection mode. If you're using one of Segment's new libraries ([Analytics.js 2.0](/docs/connections/sources/catalog/libraries/website/jav
@joe-ayoub-segment I believe this comes from the idea that Actions are cloud-mode only, but I could be mistaken. This is not boiler plate.

Your proposal does clean things up.

2023-04-18 20:46 UTC, markzegarelli commented
> @markzegarelli , the docs look to match what was designed. Can you take the PR from here please?

Yes, we'll take it from here!

2023-04-19 12:21 UTC, joe-ayoub-segment approved these changes
Looks good.

2023-04-19 21:01 UTC, tcgilbert commented
@markzegarelli - June is ready for their integration to go in Public Beta. Is there anything outstanding I can assist with? Or will we be able to get this live tomorrow?

2023-04-19 22:09 UTC, markzegarelli commented
I've opened #4610 to allow us to add content to the PR, as we can't push to this branch. Closing this, and will deploy #4610 tomorrow.

2023-04-19 22:09 UTC, closed without merging