Older browser support
segmentio/segment-docs pull request #4535
Opened 2023-04-05 13:42 UTC by jfoskin

### Proposed changes

 Added information regarding supporting older browsers

### Merge timing

### Related issues (optional)

2023-04-11 16:11 UTC, silesky commented
Content looks good, though a few grammar problems.

2023-04-11 16:15 UTC, rchinn-segment requested changes

2023-04-11 17:44 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/supported-browsers.md
> +If you need to support older versions of Internet Explorer or Opera, Segment encourages you to either load a polyfill script in the head (https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.7.0/p
@silesky does this make more sense?

2023-04-11 17:58 UTC, silesky commented on src/connections/sources/catalog/libraries/website/javascript/supported-browsers.md
> +If you need to support older versions of Internet Explorer or Opera, Segment encourages you to either load a polyfill script in the head (https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.7.0/p
That cdnjs link should not be clickable -- should be a code example. Developers will understand -- as they may be using a different link to a different version.

2023-04-12 16:35 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/supported-browsers.md
> +If you need to support older versions of Internet Explorer or Opera, Segment encourages you to either load a polyfill script in the head (https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.7.0/p
```suggestion
If you need to support older versions of Internet Explorer or Opera, Segment recommends you to either load a polyfill script in the head such as `https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.7.0/polyfill.min.js`, or use the analytics-next npm package and polyfill bundle as shown in [Babel](https://babeljs.io/docs/babel-preset-env){:target="_blank"}.
```

2023-04-12 16:36 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/supported-browsers.md
> +If you need to support older versions of Internet Explorer or Opera, Segment encourages you to either load a polyfill script in the head (https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.7.0/p
@silesky like this?

2023-04-18 16:42 UTC, stayseesong approved these changes

2023-04-18 16:42 UTC, merged