Adding section for new feature - useQueryString
segmentio/segment-docs pull request #4574
Opened 2023-04-13 09:07 UTC by joeynmq

### Proposed changes
The Engineering team has just released a new feature for Querystring API - useQueryString which allows customers to optionally add constraints to how parameters from query string are processed. Constraints include but not limited to, maximum and/or minimum length.

Currently, it is available on the NPM version but not on the CDN version.

### Merge timing
ASAP once approved

### Related issues (optional)
- https://github.com/segmentio/analytics-next/pull/774

2023-05-24 21:47 UTC, forstisabella requested changes

2023-05-24 21:47 UTC, forstisabella commented on src/connections/sources/catalog/libraries/website/javascript/querystring.md
> +```
Adding the `js` to the code snippet formatting helps the syntax highlighter mark up the code appropriately!
```suggestion
```js
```

2023-05-24 21:47 UTC, forstisabella commented on src/connections/sources/catalog/libraries/website/javascript/querystring.md
> +```
```suggestion
```js
```
```

2023-05-24 21:47 UTC, forstisabella commented on src/connections/sources/catalog/libraries/website/javascript/querystring.md
> +## How can I turn off the query string processing or add a condition to when it should be tracked?
```suggestion
## How can I control query string processing?
```

2023-05-24 21:47 UTC, forstisabella commented on src/connections/sources/catalog/libraries/website/javascript/querystring.md
> +Using `useQueryString` option enable you to control the query parameters behaviour. For example, you can entirely disable query string processing by setting `useQueryString` to `false`:
```suggestion
The `useQueryString` option allows you to control the behavior of the query parameters. For example, you can entirely disable query string processing by setting `useQueryString` to `false`:
```

2023-05-24 21:47 UTC, forstisabella commented on src/connections/sources/catalog/libraries/website/javascript/querystring.md
> +It is also possible to keep query string processing on, but enforce validation rules. For example:
```suggestion
You can also keep query string processing on, but enforce validation rules. For example:
```

2023-05-24 21:48 UTC, forstisabella commented on src/connections/sources/catalog/libraries/website/javascript/querystring.md
> +> Currently, the `useQueryString` option is **only** available when you load analytics.js through the [NPM package](https://www.npmjs.com/package/@segment/analytics-next){:target="_blank"}.
```suggestion
> Currently, the `useQueryString` option is **only** available when you load analytics.js through the [NPM package](https://www.npmjs.com/package/@segment/analytics-next){:target="_blank"}.
```
```suggestion
> The `useQueryString` option is **only** available when you load analytics.js through the [NPM package](https://www.npmjs.com/package/@segment/analytics-next){:target="_blank"}.
```

2023-05-31 20:59 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/website/javascript/querystring.md
> +You can also keep query string processing on, but enforce validation rules. For example:
```suggestion

You can also keep query string processing on, but enforce validation rules. For example:

```

2023-05-31 20:59 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/website/javascript/querystring.md
> +The `useQueryString` option allows you to control the behavior of the query parameters. For example, you can entirely disable query string processing by setting `useQueryString` to `false`:
```suggestion
The `useQueryString` option allows you to control the behavior of the query parameters. For example, you can entirely disable query string processing by setting `useQueryString` to `false`:

```

2023-05-31 21:00 UTC, markzegarelli approved these changes

2023-05-31 21:00 UTC, merged