final updates for onetrust before going public
segmentio/segment-docs pull request #4602
Opened 2023-04-18 17:16 UTC by tcgilbert

### Proposed changes

Updating event and event properties tables

### Merge timing
asap

2023-04-19 18:24 UTC, stayseesong requested changes

2023-04-19 18:24 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/onetrust/index.md
> +| Consent Updated | User has given or withdrawn consent for an express purpose |
```suggestion
| Consent Updated | The user gave or withdrew consent for an express purpose. |
```

2023-04-19 18:24 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/onetrust/index.md
> +| Purpose Name | string | Name given to the purpose in OneTrust for which the user is giving or withdrawing their consent |
```suggestion
| Purpose Name | string | The name given to the purpose in OneTrust for which the user is gives or withdraws their consent. |
```

2023-04-19 18:24 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/onetrust/index.md
> +| Purpose ID | string | GUID assigned to the purpose in OneTrust |
```suggestion
| Purpose ID | string | The GUID assigned to the purpose in OneTrust. |
```

2023-04-19 18:24 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/onetrust/index.md
> +| Purpose Name | string | Name given to the purpose in OneTrust for which the user is giving or withdrawing their consent |
```suggestion
| Purpose Name | string | The name given to the purpose in OneTrust for which the user gives or withdraws their consent. |
```

2023-04-19 18:24 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/onetrust/index.md
> +| Status | string | Current status of the users consent after the update. Options include ACTIVE, WITHDRAWN, PENDING, OPT_OUT, EXPIRED, NO_CONSENT, HARD_OPT_OUT, and NOT_OPTED_OUT |
```suggestion
| Status | string | The current status of the users consent after the update. Options include ACTIVE, WITHDRAWN, PENDING, OPT_OUT, EXPIRED, NO_CONSENT, HARD_OPT_OUT, and NOT_OPTED_OUT. |
```

2023-04-19 18:25 UTC, stayseesong commented
@tcgilbert when is this source going public so that I know when to merge

2023-04-20 16:28 UTC, stayseesong approved these changes

2023-04-20 16:37 UTC, tcgilbert commented
Hi @stayseesong, I'll make it live right now

2023-04-20 16:44 UTC, merged