Add navattic source doc
segmentio/segment-docs pull request #4674
Opened 2023-05-02 19:56 UTC by albert-yu

### Proposed changes

Adding documentation for Navattic to be a Segment Partner

### Merge timing

- ASAP once approved

2023-05-04 00:29 UTC, stayseesong commented
@joe-ayoub-segment do you happen to know when this source will be available in the Segment app?

2023-05-04 00:53 UTC, stayseesong requested changes

2023-05-04 00:53 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +> (delete after reading) Include clear, succinct steps including hyperlinks to where customers can locate the place in your app to enter their Segment writekey.
```suggestion
```

2023-05-04 00:53 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +1. From your workspace's [Sources catalog page](https://app.segment.com/goto-my-workspace/sources/catalog) click **Add Source**.
```suggestion
To get started with the Navattic source:
1. Navigate to **Connections > Sources** and click **Add Source** in the Segment App. 
```

2023-05-04 00:53 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +2. Search for "Navattic" in the Sources Catalog, select Navattic, and click **Add Source**.
```suggestion
2. Search for *Navattic* in the Sources Catalog, and select the Navattic tile, and click **Add Source**.
```

2023-05-04 00:53 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +3. On the next screen, give the Source a nickname configure any other settings.
```suggestion
3. Give the Source a nickname configure any other settings.
```

2023-05-04 00:53 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +   - The nickname is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The nickname can be anything, but we recommend using something that reflects the
```suggestion
   - The nickname is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The nickname can be anything, but Segment recommends using something that reflects the source itself and distinguishes amongst your environments (for example: SourceName_Prod, SourceName_Staging, SourceName_Dev).
```

2023-05-04 00:53 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +5. Copy the Write key from the Segment UI and log in to your Navattic account - navigate to Integrations > Segment and paste the key. Hit "Save" to connect.
```suggestion
5. Copy the Write key from the Segment UI and log in to your Navattic account. Navigate to **Integrations > Segment** and paste the key. Click **Save** to connect.
```

2023-05-04 00:53 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +Navattic uses our stream Source component to send Segment event data. It uses a server-side `track`, and `identify` methods to send data to Segment. These events are then available in any destination
```suggestion
Navattic uses the stream Source component to send Segment event data. It uses server-side `track`, and `identify` methods to send data to Segment. These events are then available in any destination that accepts server-side events, and is available in a schema in your data warehouse, so you can query using SQL.
```

2023-05-04 00:53 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +Navattic generates its own ID for each visitor to your product demo. This ID will be passed as both the `userId` and `anonymousId` when pushing Navattic events to Segment.
```suggestion
Navattic generates its own ID for each visitor to your product demo. This ID passes as both the `userId` and `anonymousId` when pushing Navattic events to Segment.
```

2023-05-04 00:53 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +The table below lists possible events that Navattic sends to Segment. With the exception of IDENTIFY_USER, all events are sent to the [Tracks table in Segment](https://segment.com/docs/connections/st
```suggestion
The table below lists possible events that Navattic sends to Segment. With the exception of IDENTIFY_USER, all events are send to the [Tracks table in Segment](/docs/connections/storage/warehouses/schema/#tracks-table). Additionally, every Navattic event includes the `userId` and `anonymousId` (which are the same), which are Navattic-generated for each user.
```

2023-05-04 00:53 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +<table>
```suggestion
Event Name | Description | 
------------ | ------------|
IDENTIFY_USER | A visitor submitted an email, usually through a form fill. This sends to the [Identifies table](/docs/connections/storage/warehouses/schema/#identifies-table) in Segment
VIEW_STEP | A visitor viewed a step in the demo.
START_FLOW | A visitor started a flow.
COMPLETE_FLOW | A visitor has completed a flow.
NAVIGATE | A visitor clicked on a link from within the demo.
OPEN_CHECKLIST | A visitor expanded a checklist.
CLOSE_CHECKLIST | A visitor collapsed a checklist.
COMPLETE_TASK | A visitor completed a checklist task.
CONVERTED | A visitor viewed a step tagged *Mark as converted*.
```

2023-05-04 00:53 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +</table>
```suggestion
```

2023-05-04 00:53 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +<table>
```suggestion
Property Name | Description
--------------- | ------------
project | An object containing the demo's (project's) ID and name.
checklist | An object containing the checklist's ID and name. Populated only if the demo contains a checklist.
flow | An object containing the current flow's ID and name.
step | An object containing the current flow step's ID, name, and index (`step.indx`)
session_id | A string that uniquely identifies this visitor's current session.
url | If the event is NAVIGATE, then this property contains the URL of the link that the visitor clicked on. Otherwise, it is empty.

```

2023-05-04 00:53 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +</table>
```suggestion
```

2023-05-04 00:53 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +Log into your downstream tools and check to see that your events appear as expected, and that they contain all of the properties you expect. If your events and properties don’t appear, check the [Eve
```suggestion
Log in to your downstream tools and check to see that your events appear as expected, and that they contain all of the properties you expect. If your events and properties don’t appear, check the [Event Delivery](/docs/connections/event-delivery/) tool, and refer to the Destination docs for each tool for troubleshooting.
```

2023-05-04 16:34 UTC, albert-yu commented on src/connections/sources/catalog/cloud-apps/navattic/index.md
> +The table below lists possible events that Navattic sends to Segment. With the exception of IDENTIFY_USER, all events are sent to the [Tracks table in Segment](https://segment.com/docs/connections/st
```suggestion
The table below lists possible events that Navattic sends to Segment. With the exception of IDENTIFY_USER, all events are sent to the [Tracks table in Segment](/docs/connections/storage/warehouses/schema/#tracks-table). Additionally, every Navattic event includes the `userId` and `anonymousId` (which are the same), which are Navattic-generated for each user.
```

I think "send" should be "sent", but this suggestion contains all other changes.

2023-05-04 16:41 UTC, stayseesong commented
@albert-yu thanks for applying all the suggestions! We'll merge the docs in once the Source is ready in the Segment app

2023-05-08 20:22 UTC, stayseesong commented
@albert-yu I'm closing this PR as I created an editable version for the docs team here: #4693

2023-05-08 20:22 UTC, closed without merging