feat: redesign react native documentation to match swift/kotlin [netlify-build]
segmentio/segment-docs pull request #4690
Opened 2023-05-08 18:19 UTC by alanjcharles

### Proposed changes
re-designed the react native documentation to match the swift/kotlin redesign 

### Merge timing
 (hopefully) May 15, 2023

2023-05-09 23:50 UTC, stayseesong requested changes

2023-05-09 23:50 UTC, stayseesong commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +> Analytics React Native versions 1.5.1 and older are no longer supported by Segment. You can reference the [migration guide](/docs/connections/sources/catalog/libraries/mobile/react-native/migration
```suggestion
> As of May 15, 2023, Segment ended support for [Analytics React Native Classic](/docs/connections/sources/catalog/libraries/mobile/react-native/classic), which includes versions 1.5.1 and older. [Upgrade to Analytics React Native 2.0](/docs/connections/sources/catalog/libraries/mobile/react-native/migration/) to use the latest version.
```

2023-05-09 23:50 UTC, stayseesong commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +> Analytics React Native versions 1.5.1 and older are no longer supported by Segment. You can reference the [migration guide](/docs/connections/sources/catalog/libraries/mobile/react-native/migration
@alanjcharles we need to include a link to the Classic docs as the classic version will still exist at the end of support date until all users upgrade to the new version. We also don't use the term "migration guide" as "upgrade" is a better term

2023-05-15 15:43 UTC, alanjcharles commented on src/connections/sources/catalog/libraries/mobile/react-native/index.md
> +> Analytics React Native versions 1.5.1 and older are no longer supported by Segment. You can reference the [migration guide](/docs/connections/sources/catalog/libraries/mobile/react-native/migration
Hi @stayseesong we've decided as a team to remove all reference to the classic library in the documentation so that we don't need to call the new one 2.0 and rather just refer to it as `Analytics React Native`. With that said, we can still provide a link to the old one somewhere in the docs so people can access it if you think that's the way to go

2023-05-23 16:07 UTC, markzegarelli approved these changes

2023-05-23 16:08 UTC, merged