feat: add new migration guides [netlify-build]
segmentio/segment-docs pull request #4783
Opened 2023-05-24 15:01 UTC by alanjcharles

### Proposed changes

added new mobile migration guides

### Merge timing
 as soon as we have team sign-off

2023-05-24 19:13 UTC, markzegarelli requested changes

2023-05-24 19:13 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/apple/migration.md
> -tags:
@alanjcharles Need to leave these in for searchability

2023-05-24 19:13 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/apple/migration.md
> +> NOTE: Analytics-Swift supports running multiple instances of the analytics object, so it does not assume a singleton. However, if you’re migrating from Analytics-iOS and all your track calls are ro
```suggestion
> Analytics-Swift supports running multiple instances of the analytics object, so it does not assume a singleton. However, if you’re migrating from Analytics-iOS and all your track calls are routed to the `Analytics.shared()` singleton, you can these calls to your new Analytics-swift object.
```

2023-05-24 19:13 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/apple/migration.md
> +With this simple extension, all of your existing Segment calls should work with Analytics-Swift.
```suggestion
With this extension, your existing Segment calls should work with Analytics-Swift. 
```

2023-05-24 19:13 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/apple/migration.md
> +If your app uses Segment to route data to Destinations via Segment-cloud (i.e. Cloud-mode destinations), you can skip this step. Analytics-Swift treats Device-mode Destinations as [plugins](/docs/con
```suggestion
If your app uses Segment to route data to Destinations through Segment-cloud (for example, Cloud-mode destinations), you can skip this step. Analytics-Swift treats Device-mode Destinations as [plugins](/docs/connections/sources/catalog/libraries/mobile/swift/plugin-architecture), and simplifies the process of integrating them into your app. Analytics-Swift supports these [Device-Mode Destinations](/docs/connections/sources/catalog/libraries/mobile/swift/destination-plugins). 
```

2023-05-24 19:13 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/apple/migration.md
> +Just under your Analytics-Swift library setup, call `analytics.add(plugin: ...)` to add an instance of the plugin to the Analytics timeline.
```suggestion
Under your Analytics-Swift library setup, call `analytics.add(plugin: ...)` to add an instance of the plugin to the Analytics timeline.
```

2023-05-24 19:13 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/apple/migration.md
> +Hopefully this simplifies your migration to Analytics-Swift. Once you’re up and running, you can take advantage of Analytics-Swift’s additional features, such as Destination Filters, Functions & Type
```suggestion
Once you’re up and running, you can take advantage of Analytics-Swift’s additional features, such as [Destination Filters](/docs/connections/sources/catalog/libraries/mobile/apple/swift-destination-plugins), [Functions](/docs/connections/functions/), and [Typewriter](/docs/connections/sources/catalog/libraries/mobile/apple/swift-typewriter) support. 
```

2023-05-24 19:13 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
> +If your app uses Segment to route data to Destinations via Segment-cloud (i.e. Cloud-mode destinations), you can skip this step. Analytics-Kotlin treats Device-mode Destinations as plugins, and simpl
```suggestion
If your app uses Segment to route data to Destinations through Segment-cloud (for example, Cloud-mode destinations), you can skip this step. Analytics-Kotlin treats Device-mode Destinations as plugins, and simplifies the process in integrating them into your app. Analytics-Kotlin supports these Device-Mode Destinations with more to come.
```

2023-05-24 19:13 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
> +Middlewares are a powerful mechanism that can augment events collected by the Analytics iOS (Classic) SDK. A middleware is a simple function that is invoked by the Segment SDK and can be used to moni
@alanjcharles Should this paragraph reference Kotlin?

2023-05-24 19:13 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
> +Hopefully this simplifies your migration to Analytics-Kotlin. Once you’re up and running, you can take advantage of Analytics-Kotlin’s additional features, such as Destination Filters, Functions & Ty
```suggestion
Once you’re up and running, you can take advantage of Analytics-Kotlin’s additional features, like [Destination Filters](/docs/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-destination-filters/), [Functions](https://segment.com/docs/connections/functions/), and [Typewriter](/docs/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-typewriter/) support.
```

2023-05-26 21:39 UTC, markzegarelli commented on src/connections/sources/catalog/libraries/mobile/apple/migration.md
>  strat: swift
```suggestion
strat: swift
tags:
  - apple
  - swift
  - ios
```

2023-05-31 16:27 UTC, alanjcharles commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
> +Middlewares are a powerful mechanism that can augment events collected by the Analytics iOS (Classic) SDK. A middleware is a simple function that is invoked by the Segment SDK and can be used to moni
@markzegarelli oh, yeah definitely

2023-06-29 18:38 UTC, merged