Update actions.md Added comprehensive migration strategy
segmentio/segment-docs pull request #4807
Opened 2023-05-27 00:58 UTC by lizkane222

Walkthrough provided for a comprehensive classic/actions migration strategy

### Proposed changes

Many customers have inquired about ensuring that their events are not dropped or duplicated when migrating from a Classic to Actions destination. The existing steps provided are useful and applicable to all non-BT customers, while the comprehensive guide I've shared is available to BT customers who want to ensure all events are successfully sent to the destination, none getting dropped or duplicated.

### Merge timing
- ASAP once approved?

### Related issues (optional)

Zendesk Tickets : 

**Mark Zegarelli:** here's one of the charts we discussed that might be useful to share at this point, after getting redesigned of course : 
[Migrate from Classic to Actions Destination.pdf](https://github.com/segmentio/segment-docs/files/11580642/Migrate.from.Classic.to.Actions.Destination.pdf)
![Migrate from Classic to Actions Destination](https://github.com/segmentio/segment-docs/assets/68755692/25fec2f7-8e11-41bc-bf4a-b19c0f35c199)

2024-01-26 18:43 UTC, forstisabella requested changes

2024-01-26 18:43 UTC, forstisabella commented on src/connections/destinations/actions.md
```suggestion

### Migrate to an actions-based destination using Destination Filters
```

2024-01-26 18:43 UTC, forstisabella commented on src/connections/destinations/actions.md
> +Classic Destination's Destination Filter : Public API - [Create Filter for Destination]([url](https://docs.segmentapis.com/tag/Destination-Filters#operation/createFilterForDestination))
```suggestion
#### Classic destination
```

2024-01-26 18:43 UTC, forstisabella commented on src/connections/destinations/actions.md
> +ENDPOINT : `POST` `https://api.segmentapis.com/destination/classic_destination_id_from_url/filters`
```suggestion
_Endpoint_: `POST` `https://api.segmentapis.com/destination/classic_destination_id_from_url/filters`
```

2024-01-26 18:43 UTC, forstisabella commented on src/connections/destinations/actions.md
> +Actions Destination's Destination Filter : Public API - [Create Filter for Destination]([url](https://docs.segmentapis.com/tag/Destination-Filters#operation/createFilterForDestination))
```suggestion
#### Actions destination
```

2024-01-26 18:43 UTC, forstisabella commented on src/connections/destinations/actions.md
> +ENDPOINT : `POST` `https://api.segmentapis.com/destination/actions_destination_id_from_url/filters`
```suggestion
_Endpoint_: `POST` `https://api.segmentapis.com/destination/actions_destination_id_from_url/filters`
```

2024-01-31 15:00 UTC, cmastr approved these changes

2024-01-31 16:17 UTC, forstisabella approved these changes

2024-01-31 16:17 UTC, merged