Stratconn 2671 optimizely public document
segmentio/segment-docs pull request #4811
Opened 2023-05-28 20:55 UTC by hvardhan-unth

### Proposed changes

This PR adds public document for Optimizely Feature Experimentation (Actions).
JIRA ticket link:- https://segment.atlassian.net/browse/STRATCONN-2671

### Merge timing

2023-05-30 13:59 UTC, varadarajan-tw commented on src/_data/catalog/destination_categories.yml
>  # AUTOGENERATED FROM PUBLIC API. DO NOT EDIT
Are the files under `_data/catalog` relevant to this change? If not, can we remove them?

2023-05-31 00:01 UTC, forstisabella commented on src/_data/catalog/destination_categories.yml
>  # AUTOGENERATED FROM PUBLIC API. DO NOT EDIT
Hi - we update our catalog before every deployment (Tuesdays & Thursdays) and so those files were out of sync with our current `develop` branch and were not in the scope of this PR.

2023-06-01 19:29 UTC, forstisabella requested changes

2023-06-01 19:29 UTC, forstisabella commented on src/connections/destinations/catalog/actions-optimizely-feature-experimentation-cloud/index.md
> +7. Under Select mappings, Select the event key from the dropdown or input the event manually as the  "event" and select the other mappings. Click **Save** and toggle to enable the mapping.
```suggestion
7. Under Select mappings, select the event key from the dropdown or input the event manually as the "event" and select the other mappings. Click **Save** and toggle to enable the mapping.
```

2023-06-01 19:29 UTC, forstisabella commented on src/connections/destinations/catalog/actions-optimizely-feature-experimentation-cloud/index.md
> +     * **Note:** The conversion event will only be sent if the event key configured should match exactly as the name of an active experiment metric set up in the Optimizely dashboard.
```suggestion
     * **Note:** The conversion event will only be sent if the configured event key configured exactly matches the name of an active experiment metric set up in the Optimizely dashboard.
```

2023-06-01 19:29 UTC, forstisabella commented on src/connections/destinations/catalog/actions-optimizely-feature-experimentation-cloud/index.md
> +     * **Note:** The current user should activated in a running experiment with the associated metric. (Activation is expected to be done at the event source before sending track events to Segment).
What does this say? The Segment user should activate a running experiment with the metric mentioned in the previous note?
```suggestion
     * **Note:** The current user should activate a running experiment with the associated metric before sending track events to Segment.
```

2023-06-01 19:29 UTC, forstisabella commented on src/connections/destinations/catalog/actions-optimizely-feature-experimentation-cloud/index.md
> +Segment supports deleting/suppressing users in Optimizely Feature Experimentation using the [Segment app](/docs/privacy/user-deletion-and-suppression/). In order to do this however, you will need to
```suggestion
Segment supports deleting/suppressing users in Optimizely Feature Experimentation (Actions) using the [Segment app](/docs/privacy/user-deletion-and-suppression/). Before deleting/suppressing a user, create a [Personal Access Token](https://developers.optimizely.com/x/authentication/personal-token/) in Optimizely and provide it as the value of the Personal Access Token setting.
```

2023-06-01 19:29 UTC, forstisabella commented on src/connections/destinations/catalog/actions-optimizely-feature-experimentation-cloud/index.md
> +{% include components/actions-fields.html settings="true"%}
There are no mappings that appear when the site is rendered - is that intentional?

2023-06-05 11:31 UTC, hvardhan-unth commented on src/connections/destinations/catalog/actions-optimizely-feature-experimentation-cloud/index.md
> +     * **Note:** The current user should activated in a running experiment with the associated metric. (Activation is expected to be done at the event source before sending track events to Segment).
Yes, The user should activate in running experiment with the metric mentioned in event.

2023-06-06 16:14 UTC, forstisabella approved these changes
A couple small notes, but looks good to me!

2023-06-06 16:14 UTC, forstisabella commented on src/connections/destinations/catalog/actions-optimizely-feature-experimentation-cloud/index.md
> +## Implementation Prerequisite
```suggestion
## Prerequisites
```

2023-06-06 16:14 UTC, forstisabella commented on src/connections/destinations/catalog/actions-optimizely-feature-experimentation-cloud/index.md
> +* Segment `track` event name to Optimizely `eventName`.
```suggestion
* Segment maps `track` events to Optimizely `eventName`.
```

2023-06-12 05:47 UTC, merged