VWO Cloud Update
segmentio/segment-docs pull request #4827
Opened 2023-05-31 15:59 UTC by prathamesh-88

### Proposed changes

Document changes to reflect the support added for VWO FullStack and additional steps to setup VWO.

### Merge timing

- ASAP once approved

### Related issues (optional)

2023-05-31 19:05 UTC, markzegarelli requested changes

2023-05-31 19:05 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-vwo-cloud/index.md
> +> The event name will be prepended with “**segment.**” before sending it to VWO. So if an event named "**ctaClick**" is triggered in Segment, it’ll appear as "**segment.ctaClick**" under **UNREGISTER
```suggestion
> Event names are prepended with `segment.` before they're sent to VWO. If an event named "**ctaClick**" is triggered in Segment, it appears as `segment.ctaClick` under **UNREGISTERED EVENTS** in VWO.
```

2023-05-31 19:05 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-vwo-cloud/index.md
> +The [Identify](https://segment.com/docs/connections/spec/identify/){:target="_blank"} call lets you associate a visitor with their actions and capture their traits.
```suggestion
The [Identify](/docs/connections/spec/identify/) call associates a visitor with their actions and captures their traits. 

```

2023-05-31 19:05 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-vwo-cloud/index.md
> +The destination forwards these traits to VWO Data360 where they can be seen under the **UNREGISTERED ATTRIBUTES** section in the **Data360 > Attributes** in VWO. These attributes can be registered an
```suggestion
The destination forwards these traits to VWO Data360 where they can be seen under the **UNREGISTERED ATTRIBUTES** section in the **Data360 > Attributes** in VWO. These attributes can be registered and used to create [segments in VWO](https://help.vwo.com/hc/en-us/articles/8976459309465-Working-with-Segments-in-VWO-Data360){:target="_blank"}. For more information about Attributes in VWO Data360, see [Working with Attributes in VWO](https://help.vwo.com/hc/en-us/articles/8681465703705-Working-with-Attributes-in-VWO){:target="_blank"}.
```

2023-05-31 19:05 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-vwo-cloud/index.md
> +> Each trait key will be prepended with “**segment.**” before sending to VWO. So if a trait named "**trait1**" is sent in Segment, it’ll appear as "**segment.trait1**" under UNREGISTERED ATTRIBUTES i
This is mentioned above. Recommend deleting here.

2023-05-31 19:05 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-vwo-cloud/index.md
> +The [Page](https://segment.com/docs/connections/spec/page/){:target="_blank"} call lets you record whenever a visitor arrives at a page of your website, along with any optional properties about the p
```suggestion
The [Page](/docs/connections/spec/page/){:target="_blank"} call records when a visitor arrives at a page of your website, along with any optional properties about the page. When received, the destination triggers VWO’s Page Visit event.
```

2023-05-31 19:05 UTC, markzegarelli commented on src/connections/destinations/catalog/actions-vwo-cloud/index.md
> +> It should only be used when working with web pages and not when using server-side sources as Page Visit event is not supported in VWO's FullStack Suite.
```suggestion
> Use Page calls with web pages only. Server-side sources in VWO's FullStack Suite do not support the Page Visit event.
```

2023-06-01 06:03 UTC, prathamesh-88 commented on src/connections/destinations/catalog/actions-vwo-cloud/index.md
> +2. Under the **Environments** section, click the **Copy** button corresponding to the environment that you want to link to Segment.
The copy button is for the SDK key which corresponds to the respective environments.

2023-06-01 06:08 UTC, prathamesh-88 commented on src/connections/destinations/catalog/actions-vwo-cloud/index.md
> +The destination forwards these events to VWO Data360 where they can be seen under the **UNREGISTERED EVENTS** section in **Data360 > Events** in VWO. These events can be registered and used as [Metri
The events are not registered by default. The user can register them if they want to use the events in VWO otherwise they can be left unregistered.

2023-06-01 06:10 UTC, prathamesh-88 commented on src/connections/destinations/catalog/actions-vwo-cloud/index.md
> +> Each trait key will be prepended with “**segment.**” before sending to VWO. So if a trait named "**trait1**" is sent in Segment, it’ll appear as "**segment.trait1**" under UNREGISTERED ATTRIBUTES i
The message shown above is specific to the event and event names. This is for the traits and how they'll be displayed in VWO's attributes.

2023-06-01 06:19 UTC, prathamesh-88 commented on src/connections/destinations/catalog/actions-vwo-cloud/index.md
> +4. Pass this cookie (*_vwo_uuid*) value with every call to Segment in the `vwo_uuid` key. The `vwo_uuid` key must be included in *properties* for Track and Page calls whereas it should be added in th
This is resolved in a separate commit as there was a minor typo in the suggestion.

2023-06-01 16:53 UTC, markzegarelli approved these changes

2023-06-01 16:53 UTC, merged