Add page for new direct destination
segmentio/segment-docs pull request #4831
Opened 2023-05-31 18:52 UTC by tcgilbert

### Proposed changes

Adds page for new direct destination, and removes blank 404 "Get Access" page

### Merge timing
asap

2023-05-31 22:25 UTC, rchinn-segment requested changes

2023-05-31 22:25 UTC, rchinn-segment commented on src/partners/direct-destination.md
> +Review the steps outlined in the [Developer Center Overview](/docs/partners). This document outlines specific details for Step four as it relates to building a Subscription Webhook.
```suggestion
Review the steps outlined in the [Developer Center Overview](/docs/partners). This document outlines specific details for [requesting access to the Development Center](/docs/partners/#development-process) as it relates to building a Subscription Webhook.
```

2023-05-31 22:25 UTC, rchinn-segment commented on src/partners/direct-destination.md
> +Review the steps outlined in the [Developer Center Overview](/docs/partners). This document outlines specific details for Step four as it relates to building a Subscription Webhook.
@tcgilbert wanted to update "step four" to an actual description and add a link. Is "request access to the Development Center" an accurate description for this step?

2023-06-01 13:53 UTC, tcgilbert commented on src/partners/direct-destination.md
> +Review the steps outlined in the [Developer Center Overview](/docs/partners). This document outlines specific details for Step four as it relates to building a Subscription Webhook.
@rchinn-segment I just removed that section entirely as it is somewhat redundant. I'll be making some bigger changes to the partner docs soon so everything flows better across all pages, but for now we just need this page so the link in dev center is not 404'ing

2023-06-01 16:20 UTC, rchinn-segment approved these changes

2023-06-01 16:20 UTC, merged