Update common.md
segmentio/segment-docs pull request #4841
Opened 2023-06-05 22:12 UTC by danieljackins

### Proposed changes

### Merge timing

### Related issues (optional)

2023-06-06 16:56 UTC, stayseesong requested changes

2023-06-06 16:56 UTC, stayseesong commented on src/connections/spec/common.md
> +- userAgentData is only collected if the [Client Hints API](https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API) is available on the browser.
```suggestion
- userAgentData is only collected if the [Client Hints API](https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API){:target="_blank"} is available on the browser.
```

2023-06-06 16:56 UTC, stayseesong commented on src/connections/spec/common.md
> +| `userAgentData` | Object | User agent data of the device making the request. Always contains `brands`, `mobile`, `platform`, and may contain `bitness`, `model`, `platformVersion`,`uaFullVersion`, `
```suggestion
| `userAgentData` | Object | The user agent data of the device making the request. This always contains `brands`, `mobile`, `platform`, and may contain `bitness`, `model`, `platformVersion`,`uaFullVersion`, `fullVersionList`, `wow64`, if [requested](docs/connections/sources/catalog/libraries/website/javascript/#client-hints) and available. <br><br> This populates if the [Client Hints API](https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API){:target="_blank"} is available on the browser. <br><br> This may contain more information than is available in the `userAgent` in some cases.                                                                                                                                |
```

2023-06-06 16:56 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +Some `userAgent` strings are being frozen and will contain less information. If you would like to request more information when it's available, you can pass an array of strings with whichever fields
```suggestion
Some `userAgent` strings are frozen and contain less information. If you would like to request more information when it's available, you can pass an array of strings with fields you would like to request to the `highEntropyValuesClientHints` option. The example array below contains all possible values.
```

2023-06-06 21:17 UTC, silesky approved these changes
LGTM

2023-06-06 21:19 UTC, silesky commented on src/connections/spec/common.md
> +      "platform": "macOS"
> This always contains `brands`, `mobile`, `platform`, and may contain `bitness`, `model`, `platformVersion`,`uaFullVersion`, `fullVersionList`, `wow64`, if [requested]

Shouldn't this contain everything?

2023-06-06 21:21 UTC, silesky requested changes
Thanks for putting this out there so quickly! Had some small questions!

2023-06-07 07:07 UTC, danieljackins commented on src/connections/spec/common.md
> +| `userAgentData` | Object | The user agent data of the device making the request. This always contains `brands`, `mobile`, `platform`, and may contain `bitness`, `model`, `platformVersion`,`uaFullVe
Brands, mobile, and platform are always available (if Client Hints are available), the rest are on request. That's what is specified here unless I'm misunderstanding your question

2023-06-07 07:08 UTC, danieljackins commented on src/connections/spec/common.md
> +      "platform": "macOS"
I could add them, I wasn't sure if it should contain the optional fields as well

2023-06-07 14:50 UTC, silesky commented on src/connections/spec/common.md
> +| `userAgentData` | Object | The user agent data of the device making the request. This always contains `brands`, `mobile`, `platform`, and may contain `bitness`, `model`, `platformVersion`,`uaFullVe
I misread!

2023-06-07 14:52 UTC, silesky approved these changes

2023-06-07 17:37 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +#### Client Hints
```suggestion
#### Client hints
```

2023-06-07 17:38 UTC, stayseesong approved these changes

2023-06-08 16:49 UTC, merged