Insider - Cloud Mode Actions Documentation
segmentio/segment-docs pull request #4862
Opened 2023-06-09 10:26 UTC by emreisik95

### Proposed changes

### Merge timing

### Related issues (optional)

2023-06-12 14:29 UTC, joe-ayoub-segment requested changes
Hi @emreisik95 , 
I'm not the main person who reviews the docs, but I had a couple of comments to think about. 
Best regards,
Joe

2023-06-12 14:29 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
> +(delete after reading) The line below renders a table of connection settings (if applicable), Pre-built Mappings, and available actions.
```suggestion
```

2023-06-12 14:29 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
> +Include additional information that you think will be useful to the user here. For information that is specific to an individual mapping, please add that as a comment so that the Segment docs team ca
You might consider adding a comment about the types of identifiers Insider accepts. 
You might also mention which Mappings are enabled by default when the Integration created - and which Mappings need to be enabled by the customer?

2023-06-14 12:34 UTC, parkaninsider commented on src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
> +(delete after reading) The line below renders a table of connection settings (if applicable), Pre-built Mappings, and available actions.
@emreisik95 Let's delete that, I forgot I believe :D

2023-06-14 12:36 UTC, parkaninsider commented on src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
> +Include additional information that you think will be useful to the user here. For information that is specific to an individual mapping, please add that as a comment so that the Segment docs team ca
I'm not sure, I though those would be added by default. No? @joe-ayoub-segment

2023-06-14 14:20 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
> +Include additional information that you think will be useful to the user here. For information that is specific to an individual mapping, please add that as a comment so that the Segment docs team ca
Hi @parkaninsider , @emreisik95 , 

There are multiple different 'identifiers' to consider with this Integration. 
uuid, segment_anonymous_id, and then there's also potentially email, which is controlled by the email_as_identifier field. 

I think it would be a good idea to explain the above in a little more detail to the user in a dedicated paragraph. Would that be possible?

2023-06-15 14:57 UTC, parkaninsider commented on src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
> +Include additional information that you think will be useful to the user here. For information that is specific to an individual mapping, please add that as a comment so that the Segment docs team ca
Yes let me do that, thanks @joe-ayoub-segment 

@emreisik95 can you add the following line and replace the place Joe highlighted please.


**IDENTITY**

The default behavior is for Segment to pass the userID associated with the user as the uuid (unique user ID). You can easily change the identity attribute to email or phone number by utilizing the Treat Email/Phone Number as Identifier so that users can be matched by using UUID, email and phone number. Insider also receives segment_anonymous_id for every request to match user data between platforms which enables sending anonymous users as well.

2023-06-15 22:41 UTC, forstisabella requested changes

2023-06-15 22:41 UTC, forstisabella commented on src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
> +Include additional information that you think will be useful to the user here. For information that is specific to an individual mapping, please add that as a comment so that the Segment docs team ca
There is one component that's autogenerated. It's the destination box at the top of the page, like in the following screenshot:
![destination info box for the Insider Cloud Mode (Actions) destination](https://github.com/segmentio/segment-docs/assets/92472883/c4d726de-e733-44b2-9aa4-5de04f18a00b)

2023-06-15 22:41 UTC, forstisabella commented on src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
> +   2. **API Key: Your Unified Customer Database API Key, see how you can generate API key from [here](https://academy.useinsider.com/docs/api-authentication-tokens#generate-api-key).**
```suggestion
   - **API Key**: Your Unified Customer Database API Key, see how you can generate API key in the [Insider Academy API Authentication Tokens](https://academy.useinsider.com/docs/api-authentication-tokens#generate-api-key){:target="_blank”} documentation.**
 6. Enable your destination and click **Save**.
```

2023-06-15 22:41 UTC, forstisabella commented on src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
> +   1. **Account Name:** Your Insider Account (Partner) Name.
```suggestion
   - **Account Name**: Your Insider Account (Partner) Name.
```

2023-06-15 22:41 UTC, forstisabella commented on src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
> +[Insider](https://useinsider.com/integration/segment/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners) Growth Management Platform (GMP) helps digital marketers drive growth across the funn
This looks like the same intro as the non-Actions Insider Destination: is that intentional?

2023-06-15 22:41 UTC, forstisabella commented on src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
> +success "" Good to know: This page is about the [Actions-framework](https://segment.com/docs/connections/destinations/actions/) Insider Segment destination. There's also a page about the [non-Actions
I added some frontmatter to the page that will auto-populate this information in a box at the top of the page, so you can go ahead and remove it in this part of the page!
```suggestion
```

2023-06-15 22:41 UTC, forstisabella commented on src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
> +4. Select an existing Source to connect to Insider(Actions).
```suggestion
4. Select an existing Source to connect to Insider Cloud Mode (Actions) and click **Next**.

5. Give your destination a name and click **Create destination*.
```

2023-06-15 22:41 UTC, forstisabella commented on src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
> +5. Add the following settings to your Insider Destinations
```suggestion
5. On the settings page for your destination, add the following settings:
```

2023-06-16 00:30 UTC, forstisabella commented
Hey all - I'm unable to edit this PR because of restrictions on the original branch. I've created a new PR, #4893, to add changes to, and I'll make sure all changes from this branch make it onto the new branch. The new branch does have some of the autogenerated elements, if y'all wanted to build those locally and explore!

2023-07-04 06:29 UTC, parkaninsider commented on src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
> +[Insider](https://useinsider.com/integration/segment/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners) Growth Management Platform (GMP) helps digital marketers drive growth across the funn
Intro refers to the what insider does, as we are the same company for both of the destinations, that shouldn't be a problem I believe @forstisabella

2023-07-13 23:07 UTC, forstisabella commented
I'll close this - looks like the changes were merged with #4893.

2023-07-13 23:07 UTC, closed without merging