Add blurb when source isn't available in catalog
segmentio/segment-docs pull request #4888
Opened 2023-06-15 16:52 UTC by sarahrudy

### Proposed changes
- Remove extra "Create a source block" (redundant)
- Add paragraph about alternatives when source isn't available in our catalog

### Merge timing
- ASAP once approved

2023-09-05 16:19 UTC, forstisabella requested changes

2023-09-05 16:19 UTC, forstisabella commented on src/connections/sources/index.md
> +> If a tool is not listed as a supported source in our [catalog](https://segment.com/catalog/){:target='_blank’}, then it is not possible to incorporate the integration within a Segment workspace out
I moved around "out-of-the-box" to describe the integration rather than the workspace. 

Also, links that point to pages in the docs should be relative links (which I do by copying the entire URL, like `https://segment.com/docs/connections/functions/`, and then just deleting the `https://segment.com` part). Relative links like that also don't need the `{:target='_blank’}` attribute!

```suggestion
> If a tool is not listed as a supported source in our [catalog](https://segment.com/catalog/){:target='_blank’}, then it is not possible to incorporate the integration out-of-the-box within a Segment workspace. However, as an alternative, you can use the [HTTP API](/docs/connections/sources/catalog/libraries/server/http-api/) source to collect data from the tool's API. You can also use [Functions](/docs/connections/functions/) to send or receive data from other tools.
```

2023-09-05 17:03 UTC, sarahrudy commented on src/connections/sources/index.md
> -## Create a source
Hi @forstisabella, yes, this is an older PR where I made multiple changes, but you're correct! The duplicate "create a source" block has been removed already!

2023-09-05 17:04 UTC, sarahrudy commented on src/connections/sources/index.md
> +> If a tool is not listed as a supported source in our [catalog](https://segment.com/catalog/){:target='_blank’}, then it is not possible to incorporate the integration within a Segment workspace out
Ok, great! Thank you for letting me know! I'll keep this in mind moving forward.

2023-09-07 23:12 UTC, forstisabella approved these changes

2023-09-07 23:13 UTC, merged