Add docs for Canny (Actions) Destination
segmentio/segment-docs pull request #4948
Opened 2023-06-27 07:47 UTC by BR4VE

### Proposed changes

- Added documentation for Canny (Actions) Destination as it is required to get the destination in public beta.

### Merge timing
- ASAP once approved, we'd like to make our destination public.

2023-06-27 07:48 UTC, BR4VE commented on src/connections/destinations/catalog/canny-functions/index.md
> +id: <integration_id>
I'm not sure what to write for id. I was not able to find the id of our destination in private beta.

2023-06-28 09:02 UTC, BR4VE commented
@stayseesong Any updates on this?

2023-06-29 00:40 UTC, stayseesong requested changes

2023-06-29 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/canny-functions/index.md
> +id: <integration_id>
```suggestion
id: 6489bbade6fe3eb57c13bd6a
beta: true
hidden: true
private: true
```

2023-06-29 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/canny-functions/index.md
> +[Canny](https://canny.io?utm_source=segmentio&utm_medium=docs&utm_campaign=partners) is a single place for all customer feedback. It saves you time managing all the feedback while keeping your custom
```suggestion
[Canny](https://canny.io?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} is a single place for all customer feedback. It saves you time managing all the feedback while keeping your customers in the loop. Let your customers post and vote on feedback from within your website or mobile app. You'll get an organized list of feedback that you can use to inform your roadmap.
```

2023-06-29 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/canny-functions/index.md
> +This destination is maintained by Canny. For any issues with the destination, [contact the Canny Support team](mailto:segment-help@canny.io).
```suggestion
Canny maintains this destination. For any issues with the destination, [contact the Canny Support team](mailto:segment-help@canny.io).
```

2023-06-29 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/canny-functions/index.md
> +1. Go to your [Canny Admin Segment Settings](https://canny.io/redirect?to=%2Fadmin%2Fsettings%2Fsegment).
```suggestion
1. Go to your [Canny Admin Segment Settings](https://canny.io/redirect?to=%2Fadmin%2Fsettings%2Fsegment){:target="_blank"}.
```

2023-06-29 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/canny-functions/index.md
> +3. From the Segment web app, click **Catalog**, then click **Destinations**.
```suggestion
3. From the Segment web app, navigate to **Connections > Catalog**, then select the **Destinations** tab in the catalog.
```

2023-06-29 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/canny-functions/index.md
> +4. Find the Destinations Actions item in the left navigation, and click it.
```suggestion
4. Search for *Canny (Actions)* and select it.
```

2023-06-29 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/canny-functions/index.md
> +7. After you finished configuring the destination, update the API key in the Canny (Actions) destination settings, enable destination and save changes.
```suggestion
7. Enter your configuration settings. 
8. Update the API key in the Canny (Actions) destination settings.
9. Enable the destination and save changes.
```

2023-06-29 00:40 UTC, stayseesong commented on src/connections/destinations/catalog/canny-functions/index.md
> +Custom Fields is a list of [traits](/docs/connections/spec/identify/#traits) to be imported as custom fields for Identify events.
@BR4VE are you sure you want to include these sections? These sections aren't needed for actions destinations and are usually only needed for the classic docs.

2023-06-29 00:50 UTC, stayseesong commented
Also, not sure if you wanted to add this, but normally our Actions docs has a benefits section. Here's the template: 

## Benefits of <destination_name> (Actions) vs <destination_name> Classic

<destination_name> (Actions) provides the following benefits over the classic <destination_name> destination:

- **Main point 1**. One or two sentences that back up the main point.
- **Main point 2**. One or two sentences that back up the main point.

2023-06-29 00:55 UTC, stayseesong requested changes

2023-06-29 00:55 UTC, stayseesong commented on src/connections/destinations/catalog/canny-functions/index.md
> +
```suggestion

> success ""
> **Good to know**: This page is about the [Actions-framework](/docs/connections/destinations/actions/) Canny Segment destination. There's also a page about the [non-Actions Canny destination](/docs/connections/destinations/catalog/canny/). Both of these destinations receive data from Segment.
```

2023-06-29 07:27 UTC, BR4VE commented on src/connections/destinations/catalog/canny-functions/index.md
> +Custom Fields is a list of [traits](/docs/connections/spec/identify/#traits) to be imported as custom fields for Identify events.
@stayseesong Thanks for mentioning this. I was not sure it it's required or not. Now I removed it 👍

2023-06-29 07:28 UTC, BR4VE commented
@stayseesong Updated the PR based on your suggestions. Waiting for your review 👍

2023-06-29 16:42 UTC, stayseesong requested changes

2023-06-29 16:45 UTC, stayseesong commented
@joe-ayoub-segment Is this one going straight to public beta or will it be in private beta first?

2023-06-29 17:22 UTC, joe-ayoub-segment commented
Hi @BR4VE , @stayseesong , 

The docs just go live once they've been approved - @tcgilbert can you confirm please?

2023-06-30 07:58 UTC, BR4VE commented
@stayseesong Updated 👍. Waiting for you to review.

2023-06-30 19:08 UTC, stayseesong commented
Looks good @BR4VE, I'm going to close this PR out as I created an editable version for the docs team to work on here #4965

2023-06-30 19:08 UTC, closed without merging