Canny Actions Destination
segmentio/segment-docs pull request #4965
Opened 2023-06-30 18:59 UTC by stayseesong

### Proposed changes

### Merge timing

### Related issues (optional)

2023-06-30 20:31 UTC, markzegarelli requested changes

2023-06-30 20:31 UTC, markzegarelli commented on src/connections/destinations/catalog/canny-functions/index.md
>  ---
```suggestion

```

2023-06-30 20:31 UTC, markzegarelli commented on src/connections/destinations/catalog/canny-functions/index.md
> +2. Obtain your API key by installing the integration.
```suggestion
2. Install the integration to get your API key.
```

2023-06-30 20:31 UTC, markzegarelli commented on src/connections/destinations/catalog/canny-functions/index.md
> +4. Search fpr _Canny (Actions)_ and select it.
```suggestion
4. Search for **Canny (Actions)** and select it.
```

2023-06-30 20:31 UTC, markzegarelli commented on src/connections/destinations/catalog/canny-functions/index.md
> +8. Update the API key in the Canny (Actions) destination settings.
```suggestion
8. Enter the Canny API key in the Canny (Actions) destination settings.
```

2023-07-03 15:41 UTC, tcgilbert approved these changes

2023-07-04 07:02 UTC, BR4VE commented
@tcgilbert @stayseesong What is the ETA for this? We'd like to ship our integration soon.

2023-07-05 16:45 UTC, merged