Add Userpilot (Actions) Destination Docs
segmentio/segment-docs pull request #5005
Opened 2023-07-10 22:58 UTC by pwseg

- userpilot new integration docs
- update description
- Add ID to Userpilot Docs

### Proposed changes

### Merge timing

### Related issues (optional)

2023-07-11 17:37 UTC, rchinn-segment requested changes

2023-07-11 17:37 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-userpilot-cloud/index.md
> +This destination is maintained by Userpilot. For any issues with the destination, [contact their Support team](mailto:support@userpilot.co).
```suggestion
This destination is maintained by Userpilot. For any issues with the destination, [contact Userpilot's Support team](mailto:support@userpilot.co){:target="_blank"}.
```

2023-07-11 17:37 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-userpilot-cloud/index.md
> +- If you're still having trouble, contact Segment's support team for further assistance.
```suggestion
- If you're still having trouble, [contact Segment's support team](https://segment.com/help/contact/){:target="_blank"} for further assistance.
```

2023-07-11 17:37 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-userpilot-web/index.md
> +## Getting Started
```suggestion
## Getting started
```

2023-07-11 17:37 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-userpilot-web/index.md
> +This destination is maintained by Userpilot. For any issues with the destination, [contact their Support team](mailto:support@userpilot.co).
```suggestion
This destination is maintained by Userpilot. For any issues with the destination, [contact Userpilot's Support team](mailto:support@userpilot.co){:target="_blank"}.
```

2023-07-11 17:56 UTC, rchinn-segment approved these changes

2023-08-09 16:39 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-userpilot-cloud/index.md
> +{% include content/ajs-upgrade.md %}
You can remove this snippet as it is only relevant for the web destination
```suggestion
```

2023-08-09 16:43 UTC, tcgilbert commented
@rchinn-segment can we get this one merged before site rebuild tomorrow?

2023-08-09 17:22 UTC, rchinn-segment approved these changes

2023-08-09 17:22 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-userpilot-cloud/index.md
> +- **User Identification** Send [Identify](/docs/connections/spec/identify/) calls from Segment to Userpilot for identifying or updating user and company properties. This data is dispatched directly f
```suggestion
- **User Identification** Send [Identify](/docs/connections/spec/identify/) calls from Segment to Userpilot for identifying or updating user and company properties. This data is dispatched directly from your backend servers and can be used for segmenting users and triggering personalized content in real-time.
```

2023-08-09 17:22 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-userpilot-web/index.md
> +Calling `identify` from `analytics.js` will trigger the `userpilot.identify`. We recommend passing as much data as possible to get the most out of Userpilot.
```suggestion
Calling `identify` from `analytics.js` will trigger the `userpilot.identify`. Segment recommends passing as much data as possible to get the most out of Userpilot.
```

2023-08-09 17:24 UTC, rchinn-segment commented
@tcgilbert - absolutely, we'll merge and include this in our deploy tomorrow

2023-08-10 15:40 UTC, merged