Consent management private beta
segmentio/segment-docs pull request #5013
Opened 2023-07-11 21:52 UTC by forstisabella

### Proposed changes
Tes

### Merge timing
After eng is complete

### Related issues (optional)

2023-07-21 21:03 UTC, rchinn-segment requested changes
Great job on this, @forstisabella! Had a few suggestions, but looks good overall!

2023-07-21 21:03 UTC, rchinn-segment commented on src/privacy/reconcile-consent.md
> +| `{ad: true,` <br>`analytics: false}`<br> <br>//ad = facebook, google ads                                        | `{facebook: true,`<br>`amplitude: false}`   | Message delivered to all ad destinati
```suggestion
| `{ad: true,` <br>`analytics: false}`<br> <br>//ad = facebook, google ads                                        | `{facebook: true,`<br>`amplitude: false}`   | Message delivered to all ad destinations even though google ads is not provided in the integrations object. Use metadata if provided for Facebook (the current behavior). No data is delivered to analytics destinations. |
```

2023-07-21 21:03 UTC, rchinn-segment commented on src/privacy/reconcile-consent.md
> +| `{ad: true,` <br>`analytics: false}`<br> <br>//ad = facebook, google ads                                        | `{facebook: true,`<br>`amplitude: false}`   | Message delivered to all ad destinati
Not necessarily a suggested change. Just curious if the different formatting/casing of Google Ads and Facebook was intentional in this table.

2023-07-24 17:47 UTC, forstisabella commented on src/privacy/configure-consent-management.md
> +- **A way to update your web libraries with the consent object**. After you set up consent categories in the Segment app, you need to add a wrapper to your Analytics.js snippet so that Segment can re
This list item was intended to call out that a user would need access to their web libraries (in the Segment app but also API access afaik) so that they can install a wrapper on top of the a.js SDK.

Would "The ability to update your web libraries with the consent object" or "Access to your web libraries" fit better here?

2023-07-24 17:50 UTC, forstisabella commented on src/privacy/reconcile-consent.md
> +| `{ad: true,` <br>`analytics: false}`<br> <br>//ad = facebook, google ads                                        | `{facebook: true,`<br>`amplitude: false}`   | Message delivered to all ad destinati
@rchinn-segment Nope, not intentional! I waffled between the formatting/casing options and never ended up picking one (plus, a different version of the table exists on the overview page anyway 😬). Good catch!

2023-07-24 18:04 UTC, rchinn-segment commented on src/privacy/configure-consent-management.md
> +- **A way to update your web libraries with the consent object**. After you set up consent categories in the Segment app, you need to add a wrapper to your Analytics.js snippet so that Segment can re
@forstisabella - Got it! I think "Access to your web libraries" works well here - as long as you feel that it gives customers enough context.

2023-07-24 18:13 UTC, forstisabella commented on src/privacy/reconcile-consent.md
> +| `{ad: true,` <br>`analytics: false}`<br> <br>//ad = facebook, google ads                                        | `{facebook: true,`<br>`amplitude: false}`   | Message delivered to all ad destinati
Addressed in [b62b255](https://github.com/segmentio/segment-docs/pull/5013/commits/b62b255dccacfc4b782c9d4d3b737e652082ba02) - marking as resolved.

2023-07-25 15:58 UTC, rchinn-segment commented on src/privacy/configure-consent-management.md
> +> This means that the Consent Management features are in active development, and some functionality may change before it becomes generally available. [Contact Segment](https://segment.com/help/contac
```suggestion
> This means that Consent Management features are in active development, and some functionality may change before it becomes generally available. [Contact Segment](https://segment.com/help/contact/){:target="_blank"} with any feedback or questions.
```

2023-07-25 15:58 UTC, rchinn-segment commented on src/privacy/consent-management.md
> +If an end user changes the categories they consent to (or if they consent using a different device or identifier,) any events they generate after updating their consent preferences will contain the u
```suggestion
If an end user changes the categories they consent to (or if they consent using a different device or identifier,) any events they generate after updating their consent preferences will contain the updated consent information. Segment only sends events to the destinations in the categories that are currently consented to.
```

2023-07-25 15:58 UTC, rchinn-segment commented on src/privacy/reconcile-consent.md
> +> This means that the Consent Management features are in active development, and some functionality may change before it becomes generally available. [Contact Segment](https://segment.com/help/contac
```suggestion
> This means that Consent Management features are in active development, and some functionality may change before it becomes generally available. [Contact Segment](https://segment.com/help/contact/){:target="_blank"} with any feedback or questions.
```

2023-07-25 15:58 UTC, rchinn-segment commented on src/privacy/reconcile-consent.md
> +Segment detects when there are conflicting consent categories for a user and
Flagging this for review.

2023-07-25 16:51 UTC, rchinn-segment approved these changes

2023-07-26 22:01 UTC, merged