Tracking Plan Ids
segmentio/segment-docs pull request #5059
Opened 2023-07-21 22:05 UTC by jfoskin

### Proposed changes

Provide customers with information about the two tracking plan ids they might encounter

### Merge timing

### Related issues (optional)

2023-09-07 19:06 UTC, forstisabella requested changes

2023-09-07 19:06 UTC, forstisabella commented on src/protocols/faq.md
> +*Please be aware that depending on how you access your tracking plan will depend on the slug that is presented in the URL.*
What does the difference look like? If you access it in the app it has one URL, and if you access it using the API it has a different URL?

2023-10-25 23:21 UTC, forstisabella approved these changes

2023-10-25 23:23 UTC, forstisabella commented on src/protocols/faq.md
> +### Why do I have to different Tracking Plan IDs?
```suggestion
### Why do I have two different Tracking Plan IDs?
```

2023-10-25 23:23 UTC, forstisabella commented on src/protocols/faq.md
> +*Please be aware that the way you access your Tracking Plan determines the slug that is present in the URL.*
@jfoskin - when you say "slug", are you referring to the prefix (`tp_` or `rs_`) of your tracking plan ID?

2024-04-22 15:34 UTC, cmastr commented
requested answers via Slack

2024-05-28 19:35 UTC, forstisabella approved these changes

2024-05-28 19:35 UTC, forstisabella commented on src/protocols/faq.md
> +*Please be aware that the way you access your Tracking Plan determines the slug that is present in the URL.*
```suggestion
```

2024-05-28 19:35 UTC, forstisabella commented on src/protocols/faq.md
> +If you are using Config API, copy the ID that starts with "rs".
```suggestion
If you're using the Config API, you'll need the ID that starts with `rs`. 
```

2024-05-28 19:35 UTC, forstisabella commented on src/protocols/faq.md
> +When you access a Tracking Plan, you'll come across two IDs: `tp_` and `rs_`.
```suggestion
When you access a Tracking Plan, you'll come across two IDs: `tp_` and `rs_`. Segment uses the two IDs to identify your Tracking Plan in the two APIs you can use to manage your workspace: the [Public API](/docs/api/public-api/) and the [Config API](/docs/api/config-api/). 

To view the two IDs for your Tracking Plan, navigate to the Tracking Plan you'd like to view the ID for and select the dropdown next to **Tracking Plan ID**. 
```

2024-05-28 19:35 UTC, forstisabella commented on src/protocols/faq.md
> +If you are using Public API, copy the ID that starts with "tp".
```suggestion
If you're using the Public API, you'll need the ID that starts with `tp_`. 
```

2024-05-28 19:36 UTC, merged