Update doc: iOS does not support destination middleware
segmentio/segment-docs pull request #5078
Opened 2023-07-27 05:00 UTC by joeynmq

### Proposed changes

There is a known issue where destination middlewares are not functioning well for the iOS library. The Engineering team will now be focusing on the new libraries (Swift & Kotlin) so the issue won't be fixed. 

JIRA: https://segment.atlassian.net/browse/LIBMOBILE-635

### Merge timing
ASAP once approved

2023-07-27 11:09 UTC, niallzato commented on src/connections/sources/catalog/libraries/mobile/ios/middleware.md
> +> **Note**: Destination middleware is **not** available for iOS.
```suggestion
> **Note**: Destination Middlewares are **not** available for iOS.
```

2023-07-27 11:14 UTC, niallzato requested changes
Looks great! Some small changes requested.

2023-07-27 11:14 UTC, niallzato commented on src/connections/sources/catalog/libraries/mobile/ios/middleware.md
> +> **Note**: Destination middleware is **not** available for iOS.
```suggestion
> **Note**: Destination Middlewares are **not** available for iOS.
```

2023-07-27 11:14 UTC, niallzato commented on src/connections/sources/catalog/libraries/mobile/ios/middleware.md
> +    blockScreenCallsToAmplitude
```suggestion
    blockScreenCallsToAmplitude,
```

2023-07-27 11:14 UTC, niallzato commented on src/connections/sources/catalog/libraries/mobile/ios/middleware.md
> +    blockScreenCallsToAmplitude
```suggestion
    blockScreenCallsToAmplitude,
```

2023-07-27 11:14 UTC, niallzato commented on src/connections/sources/catalog/libraries/mobile/ios/middleware.md
> +The following example blocks only screen calls from reaching the Amplitude destination.
```suggestion
The following example blocks only screen calls from reaching the Amplitude destination.
```

2023-08-22 00:10 UTC, forstisabella approved these changes

2023-08-22 00:11 UTC, forstisabella commented
@joeynmq does Niall need to re-review this or can I go ahead and merge?

2023-08-28 08:30 UTC, joeynmq commented
hey @forstisabella the [KCS ticket](https://segment.atlassian.net/browse/KCS-506) has been approved, thank you!!

2023-08-28 16:32 UTC, merged