Update zendesk full sync collections
segmentio/segment-docs pull request #5085
Opened 2023-07-28 05:08 UTC by terence1988

### Proposed changes

Customer would like to have some more information regarding the synced objects from Zendesk as the fully synced collections could cause overage in their workspace.

### Merge timing

### Related issues (optional)

2023-07-31 20:13 UTC, forstisabella requested changes

2023-08-01 22:32 UTC, terence1988 commented on src/connections/sources/catalog/cloud-apps/zendesk/index.md
> +|  [ticket_forms](#ticket_forms) | object | Ticket forms allow an admin to define a subset of ticket fields for display to both agents and end users. **Note**: This feature requires a Zendesk Enterpr
With an example of 1 million records in a table, when we fully sync it, we pull the same data 4 time a day by default, and we charge customers for it. So it's 120 million objects per month, customers have been surprised with it.  Sync is an umbrella term to cover incremental sync, selective sync and full sync.

2023-08-01 22:36 UTC, terence1988 commented on src/connections/sources/catalog/cloud-apps/zendesk/index.md
> +|  [tickets](#tickets) | object | Tickets are the means through which your End-users (customers) communicate with Agents in Zendesk. **Note**: Segment pulls all tickets updated (or created) in the la
Each time we start/stop pulling data from a third-party API is defined as a 'run', and we assign the 'run' with an internal id for troubleshooting purposes. Do we have a better phrase for it?

2023-08-01 23:25 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/zendesk/index.md
> +|  [tickets](#tickets) | object | Tickets are the means through which your End-users (customers) communicate with Agents in Zendesk. **Note**: Segment pulls all tickets updated (or created) in the la
Thanks for clarifying! After reading some of the docs I don't think there's another term for it

2023-08-01 23:27 UTC, forstisabella approved these changes

2023-08-01 23:27 UTC, merged