Add link to Kotlin plugin page
segmentio/segment-docs pull request #5095
Opened 2023-07-31 09:33 UTC by niallzato

### Proposed changes
Add link to Kotlin plugin page:
- Fix broken link
- Add to side menu

2023-07-31 17:18 UTC, rchinn-segment requested changes

2023-07-31 17:18 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
> +Analytics Kotlin adds several improvements to the overall experience of using the core SDK, as well as improvements to the overall [Plugin Architecture](/docs/connections/sources/catalog/libraries/mo
```suggestion
Analytics Kotlin adds several improvements to the overall experience of using the core SDK, as well as improvements to the overall [Plugin Architecture](/docs/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-plugin-architecture):
```

2023-07-31 17:18 UTC, rchinn-segment commented on src/_data/sidenav/strat.yml
> +  - path: /connections/sources/catalog/libraries/mobile/kotlin-android/kortlin-android-plugin-architecture
```suggestion
  - path: /connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-plugin-architecture
```

2023-08-01 12:51 UTC, niallzato commented
@rchinn-segment no idea how I typed kortlin 😅 Thanks for the review

2023-08-01 16:36 UTC, rchinn-segment approved these changes

2023-08-01 16:36 UTC, merged