update the BQ permission requirement section
segmentio/segment-docs pull request #5098
Opened 2023-07-31 19:27 UTC by reneewang21

### Proposed changes

Updating the permissions required if a rETL BigQuery customer creates the `__segment_reverse_etl` dataset.

### Merge timing
ASAP once approved

### Related issues (optional)

2023-07-31 21:31 UTC, stayseesong requested changes

2023-07-31 21:31 UTC, stayseesong commented on src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
> +If you don't wish to grant `bigquery.datasets.create` access, you may create this dataset yourself, and Segment needs the following permissions:
```suggestion
If you don't want to grant Segment `bigquery.datasets.create` access, you can create your own `__segment_reverse_etl` dataset and give Segment the following permissions: 
```

2023-07-31 21:31 UTC, stayseesong commented on src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
>  `bigquery.datasets.get` | This allows Segment to determine if the aforementioned dataset exists
```suggestion
`bigquery.datasets.get` | This allows Segment to determine if the aforementioned dataset exists.
```

2023-07-31 21:31 UTC, stayseesong commented on src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
>  `bigquery.jobs.create` | This allows Segment to execute queries on any datasets/tables your model query references and manage tables that Segment uses for tracking
```suggestion
`bigquery.jobs.create` | This allows Segment to execute queries on any datasets/tables your model query references and manage tables that Segment uses for tracking.
```

2023-07-31 21:31 UTC, stayseesong commented on src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
> +`bigquery.jobs.create` | This allows Segment to execute queries on any datasets/tables your model query references and manage tables that Segment uses for tracking
```suggestion
`bigquery.datasets.get` | This allows Segment to determine if the `__segment_reverse_etl` dataset exists.
`bigquery.tables.create` | This allows Segment to determine if the tables Segment uses to track state in the `__segment_reverse_etl` dataset exists.
`bigquery.jobs.create` | This allows Segment to execute queries on any datasets or tables your model query references, and also allows Segment to manage tables used for tracking.
```

2023-07-31 21:31 UTC, stayseesong commented on src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
> +The `bigquery.datasets.*` permissions can be scoped only to the `__segment_reverse_etl` dataset.
@reneewang21 just want to make sure, should there be a `*` for bigquery.datasets.

2023-07-31 22:01 UTC, reneewang21 commented on src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
> +The `bigquery.datasets.*` permissions can be scoped only to the `__segment_reverse_etl` dataset.
yes, there are two `bigquery.datasets` permissions we mentioned, one is for `create` and the other is for `get`.

2023-07-31 22:04 UTC, reneewang21 commented on src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
> +`bigquery.jobs.create` | This allows Segment to execute queries on any datasets/tables your model query references and manage tables that Segment uses for tracking
Hey @stayseesong, I assume the above suggested change for line 47 applies to line 40 as well?

2023-08-01 16:15 UTC, stayseesong approved these changes

2023-08-01 16:16 UTC, merged