Tiktok/tiktok pixel
segmentio/segment-docs pull request #5128
Opened 2023-08-03 21:12 UTC by jae-rhee-tiktok

### Proposed changes

Added documentation for TikTok Pixel

### Merge timing
ASAP

2023-08-04 09:49 UTC, joe-ayoub-segment requested changes
Hi @jae-rhee-tiktok , 

I did a quick review of the doc. 
Our docs team will do a more thorough review once you've updated based on my feedback. 

Cheers,
Joe

2023-08-04 09:49 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +3. Click **Configure TikTok Pixel**.
These steps are slightly incorrect.

2023-08-04 09:49 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +4. Select an existing Source to connect to TikTok Pixel.
Maybe explain that the Source should be a Javascript Source?

2023-08-04 09:49 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +6. On the Settings screen, provide Pixel Code and toggle "Use Existin Pixel" to use existing Pixel that is already installed on your website.
I'm thinking we could explain this a little more clearly. Maybe explain that the customer has the option having Segment load the TikTok pixel JS or the customer can tell Segment to use an existing TikTok Pixel JS which is already on the website...? Maybe this could use its own section with its own heading? Perhaps we'd also want to explain if there are any benefits or drawbacks of both approaches?

Also I think we might need to change the code slightly - for example should the Pixel Code setting field be required if the customer decides to use their own Pixel?

2023-08-04 09:49 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +The email addresses and phone numbers need to be hashed using SHA-256 before they are sent to TikTok. Please normalize and hash the PIIs before sending them to Segment. In addition, TikTok Pixel Dest
I'm wondering if this paragraph will be confusing for customers? 
I don't believe the customer needs to hash email or phone numbers before sending them to Segment? Instead, Segment will hash those values before sending them on to TikTok Pixel, isn't that correct?

2023-08-04 09:49 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +**Important notes for passing PIIs**
```suggestion
**Important notes for passing PII**
```

2023-08-04 09:49 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +- Only sha-256 is accepted. Here is the [recommended package](https://github.com/emn178/js-sha256).
This this paragraph provide instructions for the customer? Or does it explain what the TikTok Pixel Destination will do with an email address before it forwards it to TikTok?

2023-08-04 09:49 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +- Only sha-256 is accepted. Here is the [recommended package](https://github.com/emn178/js-sha256).
I think this paragraph should explain that only phone numbers matching a certain format will be forwarded on to TikTok. We could also explain the format a little better?

2023-08-04 09:49 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +- Leading/Trailing spaces need to be trimmed before hashing.
Maybe we should explain that Segment will trim spaces for identifiers before forwarding on to TikTok?

2023-08-11 18:58 UTC, rchinn-segment requested changes

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +title: [integration_name] Destination
```suggestion
title: TikTok Pixel Destination
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +[TikTok Pixel](https://ads.tiktok.com/marketing_api/docs?id=1739583652957185) is a piece of code that you can place on your website that allows you to share website events with TikTok. With any of ou
```suggestion
[TikTok Pixel](https://ads.tiktok.com/marketing_api/docs?id=1739583652957185){:target="_blank"} is a piece of code that you can place on your website that allows you to share website events with TikTok. With TikTok for Business Tools, the Pixel can help you measure traffic on your website, measure ad campaign performance, optimize your campaigns, and find new customers.
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +- **Build marketing audiences**: Create Custom Audiences based on website visitor events, like viewing a product page or making a purchase. Audiences can be used to re-engage previous site visitors o
```suggestion
- **Build marketing audiences**: Create custom Audiences based on website visitor events, like viewing a product page or making a purchase. Audiences can be used to re-engage previous site visitors or model lookalikes to find new customers. 
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +- **Optimize ad delivery**: Target audiences that are more likely to initiate a website event by setting an optimization goal on visitor events like add to cart, view page or purchase.
```suggestion
- **Optimize ad delivery**: Target Audiences that are more likely to initiate a website event by setting an optimization goal on visitor events like add to cart, view page, or purchase. 
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +This destination is maintained by Tiktok. For any issues with the destination, [contact their Support team](mailto:segmenteng@bytedance.com).
```suggestion
This destination is maintained by TikTok. For any issues with the destination, [contact TikTok's Support team](mailto:segmenteng@bytedance.com).
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +2. Search for the 'TikTok Pixel' in the search bar, and then click on the Destination named 'TikTok Pixel'.
```suggestion
2. Search for "TikTok Pixel" in the search bar, then click on the Destination "TikTok Pixel".
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +    - Ensure that the "Use Existing Pixel" field is 'off' if you want Segment to load the TikTok Pixel JavaScript code onto your website.
```suggestion
    - Ensure that the Use Existing Pixel field is **off** if you want Segment to load the TikTok Pixel JavaScript code onto your website.
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +    - Ensure that the "Use Existing Pixel" field is 'on' if you want Segment to detect and keep using the exsiting TikTok Pixel JavaScript snippet which has already been loaded on your website.
```suggestion
    - Ensure that the Use Existing Pixel field is **on** if you want Segment to detect and keep using the existing TikTok Pixel JavaScript snippet which has already been loaded on your website.
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +7. Toggle on the Destination using the 'Enable Destination' toggle.
```suggestion
7. Toggle on the Destination using the **Enable Destination** toggle.
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +8. Hit the Save Change button.
```suggestion
8. Click **Save Change**.
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +**Mappings Enabled by Default**
```suggestion
### Mappings enabled by default
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +After setting up the Destination, seven mappings will be enabled by default. You can click on the mappings tab to view and edit these mappings.
```suggestion
After setting up the Destination, Segment enables seven mappings by default. You can click on the mappings tab to view and edit these mappings.
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +## Getting Started with Pixel & Obtaining Pixel Code
```suggestion
## Getting started with Pixel and obtaining Pixel code
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +Please refer to the [TikTok Help Center documentation](https://ads.tiktok.com/help/article/get-started-pixel?redirected=2) to learn more about how to get started with TikTok Pixel. Once the Pixel is
```suggestion
Please refer to the [TikTok Help Center documentation](https://ads.tiktok.com/help/article/get-started-pixel?redirected=2){:target="_blank"} to learn more about how to get started with TikTok Pixel. Once the Pixel is created, please retrieve the Pixel Code from TikTok Events Manager (TTEM).
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +Advanced Matching helps you optimize your TikTok ads and drive performance by matching customer information with TikTok users. Hashed customer information can be shared with any TikTok event to attri
```suggestion
Advanced Matching helps you optimize your TikTok ads and drive performance by matching customer information with TikTok users. Hashed customer information can be shared with any TikTok event to attribute more conversions, build bigger audiences, and improve campaign optimization.
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +**Benefits**
```suggestion
### Benefits of TikTok Pixel
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +**Automatic Advanced Matching** is when advertisers instruct TikTok to automatically identify form fields on pages where Pixel is installed and to hash and collect email and phone numbers entered on
```suggestion
**Automatic Advanced Matching** is when advertisers instruct TikTok to automatically identify form fields on pages where Pixel is installed and to hash and collect email and phone numbers entered on those pages for ad measurement and attribution purposes. Learn more about Automatic Advanced Matching and how to turn it on in [TikTok help center](https://ads.tiktok.com/help/article/advanced-matching-web?lang=en){:target="_blank"}.
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +When email and/or phone number values are sent to TikTok, TikTok will try to match TikTok users using the PIIs that were sent to TikTok. If both email and phone number values are not sent to TikTok,
```suggestion
When email and/or phone number values are sent to TikTok, TikTok will try to match users with the PII you send to TikTok. If you don't send email or phone number values, TikTok will try to match users with IP and user-agent values that are included in the Pixel event payload.
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +TikTok recommends advertisers use both Manual and Automatic Advanced Matching at the same time, as this setting maximizes Advanced Matching's full performance.
```suggestion
To maximize Advanced Matching's performance, TikTok recommends using both Manual and Automatic Advanced Matching at the same time. 
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +TikTok will automatically hash value with sha256 before value enters TikTok's system.
```suggestion
- TikTok hashes all values with `sha256` before processing.
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +- Phone number sent to TikTok should be normalized to the E.164 format. This format is a combination of +［country code]［phone number]. An example of a US number in the E.164 format: +12133734253
```suggestion
- Normalize phone numbers you send to TikTok with in the `E.164` format. This format is a combination of `+［country code]［phone number]`. For example: `+12133734253`.
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +## PII Hashing
```suggestion
## PII hashing
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +## Data and Privacy Considerations
```suggestion
## Data and privacy 
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +Please refer [here](https://ads.tiktok.com/i18n/official/policy/business-products-terms) for TikTok Business Products (Data) Terms.
```suggestion
Visit TikTok's [docs](https://ads.tiktok.com/i18n/official/policy/business-products-terms){:target="_blank"} to learn more about TikTok's privacy and data terms.
```

2023-08-11 18:58 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +---
```suggestion

```

2023-08-11 19:01 UTC, rchinn-segment commented
Thanks for submitting and reviewing @jae-rhee-tiktok and @joe-ayoub-segment A few follow up Qs:
- Do either of you know the id for this destination? I'm having trouble locating one. 
- Also is this in private beta or public?

2023-08-15 14:49 UTC, jae-rhee-tiktok commented
@rchinn-segment Thank you so much for the feedback! I have added the changes to the PR.

I believe the slug name is "actions-tiktok-pixel".

This is currently in private beta.

2023-08-15 18:31 UTC, rchinn-segment approved these changes

2023-08-15 19:27 UTC, merged