Unlocking attribution Initial Documentation for source
segmentio/segment-docs pull request #5187
Opened 2023-08-14 00:40 UTC by ugpeter

### Proposed changes

This is the first version of documentation submitted as part of the new Segment source, Unlocking Attribution.

### Merge timing
ASAP once approved please.

### Related issues (optional)

2023-08-14 23:47 UTC, stayseesong requested changes

2023-08-14 23:47 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +| `search_narrative`            | The plain-English description of how this particular touch was mapped to campaign cost data           |
```suggestion
Property Name | Description
--------------- | -------------   
`timestamp` | The time that the touch occurred.                                                                 
`id` | The unique ID of the touch.                                                                           
`context_page_url` | The full URL of the page viewed.                                                                       
`context_page_path` | The path of the page viewed.                                                                           
`context_page_title` | The title of the page viewed.                                                                          
`context_page_referrer` | The referrer from where the user clicked from to get to the page.                                     
`context_campaign_source` | The contents of the utm_source query parameter in the URL.                                             
`context_campaign_medium` | The contents of the utm_medium query parameter in the URL.                                             
`context_campaign_name` | The contents of the utm_campaign query parameter in the URL.                                           
`context_campaign_content` | The contents of the utm_content query parameter in the URL.                                            
`context_campaign_terms` | The contents of the utm_terms query parameter in the URL.                                              
`campaign` | The unique ID of the “Media Spend Item” object which the touch was mapped to.                         
`search_narrative` | The description of how the touch was mapped to campaign cost data.           
```

2023-08-14 23:47 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +| `search_narrative`            | The plain-English description of how this particular touch was mapped to campaign cost data           |
@ugpeter are `context_campaign_source`, `context_campaign_medium`, `context_campaign_name`, and `context_campaign_terms` supposed to all have the same description?

2023-08-14 23:47 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +| `spend`                       | The amount of spend on that day                                                                       |
```suggestion
Property Name | Description 
--------------- | -------------
`campaign` | The unique ID of the media_spend_items item, which the spend row corresponds to.   
`date_start` | The date of the spending item.                                                               
`spend` | The amount spent on that day.                                        
```

2023-08-14 23:47 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +| `type`                        | The type of this media item (Paid, Organic)                                                           |
```suggestion
Property Name | Description  
--------------- | --------------                                                                                         
`campaign_name` | The name of the campaign.                                                                              
`campaign_id` | The unique ID of the campaign. This is set by the paid media platform.                                     
`id` | The unique ID of the item.                                                                            
`ad_collective_name` | The name of the Ad Collective.                                                                         
`ad_collective_id` | The unique ID of the Ad Collective. This is set by the paid media platform.                                 
`media_source` | The platform of the media item.                                                                       
`type` | The type of the media item (Paid, Organic).                                                      
```

2023-08-14 23:47 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +Each row in the Media Spend Items collection represent a unique combination of the above 4 attributes. After matching a touch against a campaign, the `campaign` identifier in the `touches` collection
@ugpeter is there a reason why the information here is repeated in the table? Can we just consolidate and put it in the table?

2023-08-14 23:47 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +| `media_spend_daily_spend`         | object | This collection captures the daily spend for each campaign (and sometimes broken down by Ad Collective or Ad Id).
```suggestion
Collection | Type | Description
---------- | ----- | -------------                                                                                                                                                                                                                                                                                                                                                                                                       
`conversions` | object | This collection contains each identified conversion event, as configured in Unlocking Attribution and detected by the modeling.                                                                                         |
`conversion_touch_lookup` | object | This collection contains a cross-reference between each conversion and all the pre-conversion touches the end-user had.                                                                                                    |
`touches` | object | A touch is defined as any interaction that a user had leading up to the conversion event. This generally means website visits, but can sometimes have broader definitions, based on the exact implementation.
`media_spend_items` | object | All cost data from the various media platforms is downloaded and stored in the the Media Spend Items and Media Spend Daily Spend collections.
`media_spend_daily_spend` | object | This collection captures the daily spend for each campaign (and is sometimes broken down by Ad Collective or Ad Id).
```

2023-08-14 23:47 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +1. From your workspace's [Sources catalog page](https://app.segment.com/goto-my-workspace/sources/catalog) click **Add Source**.
```suggestion
1. Navigate to **Connections > Catalog** and select the **Sources** tab of the catalog. 
```

2023-08-14 23:47 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +2. Search for "Unlocking Attribution" in the Sources Catalog, select Unlocking Attribution, and click **Add Source**.
```suggestion
2. Search for *Unlocking Attribution* in the Sources Catalog.
3. Select **Unlocking Attribution** and click **Add Source**.
```

2023-08-14 23:47 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +12. Click "Connect" and then follow the remaining steps within the onboarding wizard.
```suggestion
4. Give the Source a nickname.
     - The nickname is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The nickname can be anything, but we recommend using something that reflects the source itself and distinguishes amongst your environments (eg. SourceName_Prod, SourceName_Staging, SourceName_Dev).

5. Enter the configuration setting.  
6. Click **Add Source** to save your settings.
7. Navigate to **Settings > Workspace Settings**
8. Select the **Access Management** tab.
7. Select the **Tokens** tab. 
8. Click the **+ Create Token**.
9. Enter a description such as *Unlocking Attribution*, select **Workspace Owner** and click **Create**.
10. Copy the token that is presented on the screen.
11. Switch to your account in Unlocking Attribution and within the Onboarding Wizard, paste the token you copied.
12. Click **Connect** and follow the remaining steps within the onboarding wizard.
```

2023-08-14 23:47 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +The Unlocking Attribution source is built with a sync component, which means that Unlocking Attribution writes to Segment on a regular basis, when modelling is re-performed on your customer data (typ
```suggestion
The Unlocking Attribution source is built with a sync component, which means that Unlocking Attribution writes to Segment on a regular basis when modeling is re-performed on your customer data (typically on a daily basis).  In the initial sync, all historical modeling is performed and written according to the Collections structure below. The objects are written into a separate schema, corresponding to the source instance's schema name you designated upon creation (for example, `ug_attribution.media_spend_items`).
```

2023-08-14 23:47 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +Segment's sync component uses an upsert API, so the data in your warehouse loaded using sync reflects the latest state of the corresponding resource in Unlocking Attribution. For example, if `convers
```suggestion
Segment's sync component uses an upsert API, so the data in your warehouse loaded using sync reflects the latest state of the corresponding resource in Unlocking Attribution. For example, if `conversions.value` goes from `0` to `212` between syncs, on its next sync, that conversion's value will be `212`.
```

2023-08-14 23:47 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +The source syncs and warehouse syncs are independent processes. Source runs pull your data into the Segment Hub, and warehouse runs flush that data to your warehouse. Sources will sync with Segment d
```suggestion
The source syncs and warehouse syncs are independent processes. Source runs pull your data into the Segment Hub, and warehouse runs flush that data to your warehouse. Sources sync with Segment daily. Depending on your Warehouses plan, Segment pushes the Source data to your warehouse on the interval associated with your billing plan.
```

2023-08-15 15:46 UTC, stayseesong commented
@ugpeter would you be able to address these change suggestions?

2023-08-23 21:08 UTC, stayseesong commented
@ugpeter @peterikladious any updates?

2023-08-29 04:02 UTC, ugpeter commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +The [Unlocking Attribution](https://yourintegration.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners) source is a powerful solution designed to model attribution data, aiding marketers
Yes - will do.  I'm going to issue a new PR to factor this in.

2023-08-29 04:13 UTC, ugpeter commented
Hi @stayseesong - Thanks for your feedback.  I've accepted most of your changes and for the larger ones, I'm working on a subsequent PR that incorporates those.

2023-08-31 15:51 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +Each row in the Media Spend Items collection represent a unique combination of the above 4 attributes. After matching a touch against a campaign, the `campaign` identifier in the `touches` collection
@ugpeter would you be able to address this comment please?

2023-09-01 00:31 UTC, ugpeter commented on src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
> +Each row in the Media Spend Items collection represent a unique combination of the above 4 attributes. After matching a touch against a campaign, the `campaign` identifier in the `touches` collection
I've removed this and then edited the text to be consisted with all data being in the table.

2023-09-05 18:36 UTC, stayseesong commented
@ugpeter I'm going to close this PR out as I created an editable version of the PR at #5302. I'll have this merged in our deploy on Thursday

2023-09-05 18:36 UTC, closed without merging