Added rehook-segment documentation
segmentio/segment-docs pull request #5219
Opened 2023-08-18 08:33 UTC by tushardhara

### Proposed changes

- Added integration document for Rehook as Destination in Segment

### Merge timing

- ASAP once approved

2023-08-18 14:43 UTC, tcgilbert requested changes
@tushardhara looks like you used the template for the [direct destination](https://github.com/segmentio/segment-docs/blob/develop/templates/partners/direct-destination.md?plain=1)

Because your destination is an Actions destination, I added some comments to reflect what is needed for the [Actions docs](https://github.com/segmentio/segment-docs/blob/develop/templates/partners/destination-new.md?plain=1).

2023-08-18 14:43 UTC, tcgilbert commented on src/connections/destinations/catalog/rehook/index.md
> +
```suggestion
{% include content/plan-grid.md name="actions" %}
```

2023-08-18 14:43 UTC, tcgilbert commented on src/connections/destinations/catalog/rehook/index.md
> +> * The referral_code field is required, if event name is set as a conversion event on Rehook.
```suggestion
> * The referral_code field is required, if event name is set as a conversion event on Rehook. 

{% include components/actions-fields.html %}
```

2023-08-18 14:43 UTC, tcgilbert commented on src/connections/destinations/catalog/rehook/index.md
> +Rehook supports the following methods, as specified in the [Segment Spec](/docs/connections/spec).
```suggestion
Rehook's destination is designed to support the following methods, as specified in the [Segment Spec](/docs/connections/spec). Note that because this is an Actions Destination, you will also have the capability to map other Segment methods if neccessary.
```

2023-08-18 15:17 UTC, tushardhara commented on src/connections/destinations/catalog/rehook/index.md
> +
done

2023-08-18 15:17 UTC, tushardhara commented on src/connections/destinations/catalog/rehook/index.md
> +> * The referral_code field is required, if event name is set as a conversion event on Rehook.
done

2023-08-18 15:18 UTC, tushardhara commented on src/connections/destinations/catalog/rehook/index.md
> +Rehook supports the following methods, as specified in the [Segment Spec](/docs/connections/spec).
done

2023-08-18 15:41 UTC, tcgilbert commented
@tushardhara thanks, looks good! Just need one more review from someone on our docs team, and we can get this merged.

2023-08-21 20:42 UTC, pwseg commented
@tushardhara @tcgilbert I created #5228 to deploy these docs.

2023-08-21 20:42 UTC, closed without merging