Elastic path/source
segmentio/segment-docs pull request #5251
Opened 2023-08-25 14:31 UTC by psin32

### Proposed changes

New integration is built for Elastic Path Commerce Cloud and Segment. This PR is covering documentation for the new integration. Details of events are provided which is covered by this integration and event pay load details are also covered.

### Merge timing
- ASAP

### Related issues (optional)

2023-08-28 21:58 UTC, stayseesong requested changes

2023-08-28 21:58 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/elastic-path/index.md
> +| `properties.products.$.quantity`        | Quantity of a product                                                  |
```suggestion
| `userId`                                | If the registered user places an order, then the value of the userId is the Customer ID. Otherwise, it will be the order ID. You can change this as per your requirement.                                                                                                       |
| `event`                                 | The event name, for example,  `Checkout Started`, `Order Completed`.             |
| `properties`                            | This holds information about the order.                             |
| `properties.order_id`                   | The Elastic Path Order ID.                                                  |
| `properties.value`                      | The revenue ($) with discounts and coupons added in. For better flexibility and total control over tracking, Elastic Path lets you decide how to calculate how coupons and discounts are applied. This is usually required for the `Checkout Started` event.                                                                              |
| `properties.total`                      | The revenue ($) with discounts and coupons added in. For better flexibility and total control over tracking, Elastic Path lets you decide how to calculate how coupons and discounts are applied. This is usually required for all the events apart from the `Checkout Started` event.                                                    |
| `properties.revenue`                    | The revenue ($) associated with the transaction (excluding shipping and tax). This is usually required for all the events apart from the `Checkout Started` event.                                    |
| `properties.tax`                        | The total tax associated with the transaction.                              |
| `properties.discount`                   | The total discount associated with the transaction.                         |
| `properties.shipping`                   | The shipping cost associated with the transaction.                          |
| `properties.currency`                   | The currency code associated with the transaction. For example, GBP, USD.       |
| `properties.products`                   | The list of products in order.                                          |
| `properties.products.$.product_id`      | The product ID.                                                             |
| `properties.products.$.name`            | The product name.                                                           |
| `properties.products.$.sku`             | The product SKU.                                                            |
| `properties.products.$.price`           | The product unit price.                                                     |
| `properties.products.$.quantity`        | The quantity of a product.                                                  |
```

2023-08-28 21:58 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/elastic-path/index.md
> +Note: We are using properties of these events from [eCommerce Spec](https://segment-docs.netlify.app/docs/connections/spec/ecommerce/v2){:target="_blank"} defined by Segment doc. Add more properties
```suggestion
Note: Elastic path is using properties of these events from the [eCommerce Spec](https://segment-docs.netlify.app/docs/connections/spec/ecommerce/v2){:target="_blank"} defined by the Segment doc. Add more properties as per this documentation based on your business requirement.
```

2023-08-28 21:58 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/elastic-path/index.md
> +Now that your Source is configured, you can connect it with Destinations. Log into your downstream tools and check to see that your events appear as expected, and that they contain all of the propert
```suggestion
Now that you've configured your source, you can connect it with destinations. Log in to your downstream tools and check to see that your events appear as expected, and that they contain all of the properties you expect. If your events and properties don’t appear, check the Event Delivery tool, and refer to the Destination docs for each tool for troubleshooting. If there are any issues with how the events arrive to Segment, contact the [Elastic Path Support team](https://support.elasticpath.com/hc/en-us){:target="_blank"}.
```

2023-08-30 11:52 UTC, psin32 reviewed
Changes are updated as requested

2023-08-30 11:53 UTC, psin32 reviewed
Updated as requested

2023-08-30 21:44 UTC, stayseesong approved these changes

2023-08-30 21:48 UTC, merged