Linked Events
segmentio/segment-docs pull request #5267
Opened 2023-08-30 04:04 UTC by rchinn-segment

### Proposed changes

### Merge timing

### Related issues (optional)

2023-09-15 20:57 UTC, stayseesong requested changes

2023-09-15 20:57 UTC, stayseesong commented on src/connections/destinations/actions.md
> +4. Next, set up the data mapping from the Segment format to the destination tool format.
```suggestion
4. Set up the data mapping from the Segment format to the destination tool format.
```

2023-09-15 20:57 UTC, stayseesong commented on src/unify/linked-profiles/setup-guides/redshift-setup.md
> +If you've used RETL in your database, you'll need to add the following [table permissions](https://docs.aws.amazon.com/redshift/latest/dg/r_GRANT.html){:target="_blank"}:
```suggestion
If you used RETL in your database, you'll need to add the following [table permissions](https://docs.aws.amazon.com/redshift/latest/dg/r_GRANT.html){:target="_blank"}:
```

2023-09-15 20:57 UTC, stayseesong commented on src/unify/linked-profiles/linked-events.md
> +{% faqitem What data warehouse permissions does Segment require? %}
how come it's being formatted like this? I think we stopped using these faq tags and just moved on to putting questions as h4 headers

2023-09-15 20:57 UTC, stayseesong commented on src/unify/linked-profiles/linked-events.md
> +| **Table**              |      **Steps**          |
```suggestion
|  Table              |      Steps          |
```

2023-09-15 20:57 UTC, stayseesong commented on src/unify/linked-profiles/linked-events.md
> +| **Table**              |      **Steps**          |
Instead of Table, shouldn't it say Data Warehouse?

2023-09-18 19:17 UTC, rchinn-segment commented on src/unify/linked-profiles/linked-events.md
> +{% faqitem What data warehouse permissions does Segment require? %}
Oh, good callout. If we've moved away from these tags, I'll update the formatting here to remain consistent.

2023-09-20 16:54 UTC, merged