First draft of the ABsmartly (Actions) docs
segmentio/segment-docs pull request #5268
Opened 2023-08-30 15:11 UTC by marcio-absmartly

### Proposed changes
Adding ABsmartly (Actions) documentation.
See: https://github.com/segmentio/action-destinations/pull/1533

### Merge timing
As close as possible to when the ABsmartly (Actions) is deployed in production.

2023-08-30 16:03 UTC, calthejuggler requested changes

2023-08-30 16:03 UTC, calthejuggler commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +- **Easier Setup**. Actions-based destinations are easier to configure with clear default settings enabling you to get started quickly.
```suggestion
- **Easier Setup**. Actions-based destinations are easier to configure with clear default settings; Enabling you to get started quickly.
```

2023-08-30 16:03 UTC, calthejuggler commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +- **Control and clearer mapping**. Actions-based destinations enable you to define the mapping between the data Segment receives from your source, and the data Segment sends to the ABsmartly.
```suggestion
- **Control and clearer mapping**. Actions-based destinations enable you to define the mapping between the data Segment receives from your source, and the data Segment sends to ABsmartly.
```

2023-08-30 16:03 UTC, calthejuggler commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +> By default, the _Track Calls_ mapping will filter and not send to ABsmartly events with name `Experiment Viewed`.
```suggestion
> By default, the _Track Calls_ mapping will filter and not send any events with the name `Experiment Viewed` to ABsmartly.
```

2023-08-30 16:03 UTC, calthejuggler commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +To migrate from the classic A/B Smartly destination to ABsmartly (Actions) be sure to disconnect the classic A/B Smartly destination before enabling the ABsmartly (Actions) destination to avoid dupli
```suggestion
To migrate from the classic A/B Smartly destination to ABsmartly (Actions) be sure to disconnect the classic A/B Smartly destination before enabling the ABsmartly (Actions) destination to avoid duplicate experimentation events.
```

2023-08-31 21:43 UTC, forstisabella requested changes

2023-08-31 21:43 UTC, forstisabella commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +- **Easier Setup**. Actions-based destinations are easier to configure with clear default settings; Enabling you to get started quickly.
```suggestion
- **Easier Setup**: Actions-based destinations are easier to configure with clear default settings, letting you quickly get started.
```

2023-08-31 21:43 UTC, forstisabella commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +- **Control and clearer mapping**. Actions-based destinations enable you to define the mapping between the data Segment receives from your source, and the data Segment sends to ABsmartly.
```suggestion
- **Control and clearer mapping**: Actions-based destinations enable you to define the mapping between the data Segment receives from your source and the data Segment sends to ABsmartly.
```

2023-08-31 21:43 UTC, forstisabella commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +   - **API Key**: An existing API Key. Created under Settings->API Keys in the ABsmartly Web Console.
```suggestion
   - **API Key**: An existing API Key. Created under Settings > API Keys in the ABsmartly Web Console.
```

2023-08-31 21:43 UTC, forstisabella commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +> If you need support setting things up, you can contact the ABsmartly support team on Slack or via email at [ABsmartly's Support](mailto:support@absmartly.com).
```suggestion
> If you need support setting things up, you can contact the ABsmartly support team on Slack or [via email](mailto:support@absmartly.com).
```

2023-08-31 21:43 UTC, forstisabella commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +other destinations. The Segment spec includes the [Experiment Viewed semantic event](https://segment.com/docs/connections/spec/ab-testing/)
```suggestion
other destinations. The Segment Spec includes the [Experiment Viewed semantic event](/docs/connections/spec/ab-testing/)
```

2023-08-31 21:43 UTC, forstisabella commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +In the ABsmartly context, we can [install a custom event logger](https://docs.absmartly.com/docs/sdk%20documentation/getting-started/#using-a-custom-event-logger) and send exposures directly to Segme
```suggestion
You can [install a custom event logger](https://docs.absmartly.com/docs/sdk%20documentation/getting-started/#using-a-custom-event-logger){:target="_blank"} in ABsmartly and send exposures directly to Segment.
```

2023-08-31 21:43 UTC, forstisabella commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +and enable the _Exposures (Verbatim)_ mapping on your ABsmartly (Actions) destination.
```suggestion
and enable the _Exposures (Verbatim)_ mapping in your ABsmartly (Actions) destination.
```

2023-08-31 21:43 UTC, forstisabella commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +We want to replace the direct flow of exposure events from the ABsmartly SDK to the ABsmartly collector, by instead sending them to Segment
```suggestion
By enabling the _Exposures (Verbatim)_ mapping in Segment, you replace the direct flow of exposure events from the ABsmartly SDK to the ABsmartly collector and instead send them to Segment
```

2023-08-31 21:43 UTC, forstisabella commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +## Migration from the classic A/B Smartly destination
```suggestion
## Migration from the classic ABsmartly destination
```

2023-08-31 21:43 UTC, forstisabella commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +To migrate from the classic A/B Smartly destination to ABsmartly (Actions) be sure to disconnect the classic A/B Smartly destination before enabling the ABsmartly (Actions) destination to avoid dupli
```suggestion
To migrate from the classic ABsmartly destination to ABsmartly (Actions), disconnect the classic ABsmartly destination before enabling the ABsmartly (Actions) destination to avoid duplicate experimentation events.
```

2023-08-31 21:43 UTC, forstisabella commented on src/connections/destinations/catalog/actions-absmartly/index.md
> +## Benefits of ABsmartly (Actions) vs A/B Smartly Classic
Does the classic destination have the same marketing/casing for the name as the Actions destination does?

```suggestion
## Benefits of ABsmartly (Actions) vs ABsmartly Classic
```

2023-09-06 20:44 UTC, forstisabella approved these changes

2023-09-06 20:44 UTC, merged