rokt action destination doc
segmentio/segment-docs pull request #5303
Opened 2023-09-06 05:01 UTC by aval-rokt

### Proposed changes

Adding documentation for rokt action destination ( currently in private beta mode ), so it can be moved to public beta and more customers can start sending custom audiences to ROKT.

### Merge timing
- ASAP once approved

2023-09-06 19:20 UTC, stayseesong requested changes

2023-09-06 19:20 UTC, stayseesong commented on src/connections/destinations/catalog/action-rokt-audiences/index.md
> +5. On the **Settings** tab, name your destination. For example, `Rokt audiences – <audience name>`.
```suggestion
5. On the **Settings** tab, enter the name of your destination. For example, `Rokt audiences – <audience name>`.
```

2023-09-06 19:20 UTC, stayseesong commented on src/connections/destinations/catalog/action-rokt-audiences/index.md
> +8. In the **Mappings** tab, click **New Mapping** and select **Add Users to Audience**. Don't change any defaults.
```suggestion
8. In the **Mappings** tab, select **+ New Mapping** and select **Add Users to Audience**. Don't change any defaults.
```

2023-09-06 19:20 UTC, stayseesong commented on src/connections/destinations/catalog/action-rokt-audiences/index.md
> +9. Go to the **Settings** tab and **Enable** the destination.
```suggestion
9. Go to the **Settings** tab and select the toggle to **Enable** the destination.
```

2023-09-06 19:20 UTC, stayseesong commented on src/connections/destinations/catalog/action-rokt-audiences/index.md
> +10. Select your space, and navigate to **Engage > Audiences**. Select the source audience that you want to send to your Rokt Audiences destination.
```suggestion
10. Select your space, and navigate to **Engage > Audiences**. Select the source audience that you want to send to your Rokt Audiences (Actions) destination.
```

2023-09-06 19:20 UTC, stayseesong commented on src/connections/destinations/catalog/action-rokt-audiences/index.md
> +> You can connect **ONE** Engage audience to a single instance of Rokt Audience destination. If you have multiple audiences, repeat the above process to create a new Rokt audience destination and con
```suggestion
> You can only connect **one** Engage audience to a single instance of the Rokt Audience (Actions) destination. If you have multiple audiences, repeat the above process to create a new Rokt Audience (Actions) destination and connect the audience to a new destination each time.
```

2023-09-06 19:20 UTC, stayseesong commented on src/connections/destinations/catalog/action-rokt-audiences/index.md
> +id:
```suggestion
id: 643697130067c2f408ff28ca
```

2023-09-06 19:20 UTC, stayseesong commented on src/connections/destinations/catalog/action-rokt-audiences/index.md
> +hide-dossier: false
```suggestion
hide-dossier: false
private: true
hidden: true
beta: true
```

2023-09-06 19:20 UTC, stayseesong commented on src/connections/destinations/catalog/action-rokt-audiences/index.md
> +Your Rokt destination is now ready to receive audiences, and your Persona audiences are now accessible in your Rokt Advertiser dashboard. Be aware, it can take 12-24 hours for the first sync when the
```suggestion
Your Rokt destination is now ready to receive audiences, and your Persona audiences are now accessible in your Rokt Advertiser dashboard. Keep in mind that it can take 12-24 hours for the first sync when the number of email identifies are in the millions. 
```

2023-09-06 20:18 UTC, stayseesong commented
@aval-rokt if you could address these changes and then I can add the final adjustments needed

2023-09-06 23:13 UTC, aval-rokt commented
> @aval-rokt if you could address these changes and then I can add the final adjustments needed

Thanks for quick review @stayseesong, I have committed your suggestions. 
One quick question, since I haven't specified any logos or images, where will it get those or how this destination will look like when shown to customers

2023-09-07 16:55 UTC, stayseesong commented
@aval-rokt the logo will pull into the docs site from the Segment app. Once the engineers get the logo into the Segment app, and once the docs go live, the logo from the Segment app gets pulled into the docs site

2023-09-08 01:02 UTC, stayseesong commented
@aval-rokt I'm going to close this PR out as I created an editable version of the PR for the docs team here #5316. We'll get this published in our next deploy on Tuesday

2023-09-08 01:02 UTC, closed without merging