add destinations from npm
segmentio/segment-docs pull request #5315
Opened 2023-09-07 21:34 UTC by stayseesong

### Proposed changes

### Merge timing

### Related issues (optional)

2023-09-11 18:44 UTC, silesky commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +  AnalyticsBrowser.load({
const analytics =

2023-09-11 18:46 UTC, silesky commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +  // the following rig assumes configuration for Google Analytics will be available in the fetched settings
The following rig? Maybe "The following example"?

2023-09-11 18:47 UTC, silesky commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +Bundle the destinations you want loaded from [npm](https://www.npmjs.com/package/@segment/analytics-next){:target="_blank"} instead of having them loaded from CDN. This enables you to have fewer netw
instead of having them loaded from *a remote* CDN

2023-09-11 18:48 UTC, silesky requested changes
LGTM! Just a couple comments ;-)

2023-09-13 22:18 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +Bundle the destinations you want loaded from [npm](https://www.npmjs.com/package/@segment/analytics-next){:target="_blank"} instead of having them loaded from CDN. This enables you to have fewer netw
```suggestion
Bundle the destinations you want loaded from [npm](https://www.npmjs.com/package/@segment/analytics-next){:target="_blank"} instead of having them loaded from a remote CDN. This enables you to have fewer network requests when adding destinations.
```

2023-09-13 22:18 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +    writeKey,
```suggestion
  const analytics = AnalyticsBrowser.load({
    writeKey: '<WRITE_KEY>',
```

2023-09-13 22:18 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +  // the following rig assumes configuration for Google Analytics will be available in the fetched settings
```suggestion
  // The following example assumes configuration for Google Analytics will be available in the fetched settings
```

2023-09-14 04:44 UTC, silesky commented
@zikaari can post a list of the npm name of every action destination we support (or link to one?)

2023-09-14 16:17 UTC, forstisabella approved these changes

2023-09-14 20:20 UTC, silesky approved these changes

2023-09-14 21:12 UTC, merged