1Flow iOS doc update
segmentio/segment-docs pull request #5322
Opened 2023-09-11 11:01 UTC by rohantryskybox

### Proposed changes

### Merge timing

### Related issues (optional)

2023-09-11 19:58 UTC, forstisabella commented on src/connections/destinations/catalog/test-flow/index.md
> +5. Copy 1Flow project key and paste it into the Connection Settings in Segment.
Hi @rohantryskybox - where could a user find the 1Flow project key? Could we add a step or two here explaining how you could find the key in 1Flow?

2023-09-12 04:37 UTC, rohantryskybox commented on src/connections/destinations/catalog/test-flow/index.md
> +5. Copy 1Flow project key and paste it into the Connection Settings in Segment.
Done

2023-09-13 12:51 UTC, tcgilbert requested changes

2023-09-13 12:51 UTC, tcgilbert commented on src/connections/destinations/catalog/test-flow/index.md
> +title: 1Flow (Actions) Destination
```suggestion
title: 1Flow Mobile Plugin Destination
id: 64dd07c1fed86b6866cd93f5
```

2023-09-13 12:51 UTC, tcgilbert commented on src/connections/destinations/catalog/test-flow/index.md
> +5. Go to 1flow.ai -> Settings -> Project Settings -> Copy 1Flow project key and paste it into the Connection Settings in Segment.
```suggestion
1. From the Segment web app, click **Catalog**, then search for **1Flow Mobile Plugin**.
2. Click **Add Destination**.
4. Select an existing Source to connect to 1Flow Mobile Plugin.
5. Go to 1flow.ai -> Settings -> Project Settings, copy the 1Flow project key, and paste it into the Destination Settings in Segment.
6. Depending on the mobile source you’ve selected, include 1Flow's library by adding the following lines to your dependency configuration.
```

2023-09-13 12:51 UTC, tcgilbert commented on src/connections/destinations/catalog/test-flow/index.md
> +
Add installation instructions for each library, see example documentation here: 

- Braze iOS installation: https://segment.com/docs/connections/destinations/catalog/braze/#ios
- Braze Android installation: https://segment.com/docs/connections/destinations/catalog/braze/#android

```suggestion
### iOS

1. Add the 1Flow Segment Pod to your `Podfile`:

    ```
    pod '1Flow-Segment'
    ```

(add other relevant instructions)

### Android


1. In the top-level project `build.gradle` add the following as a repository in *all projects > repositories*.

    ```js
    maven { url "http://appboy.github.io/1flow-android-sdk/sdk" }
    maven { url "http://appboy.github.io/1flow-segment-android/sdk" }
    ```

(add other relevant instructions)
```

2023-09-13 12:51 UTC, tcgilbert commented on src/connections/destinations/catalog/test-flow/index.md
> +
```suggestion
The 1Flow Mobile Plugin Destination is open-source and available on GitHub. You can view these repositories here: 

- [iOS](github url){:target="_blank"} 
- [Android](github url){:target="_blank"}
```

2023-09-14 13:41 UTC, rohan1flow commented on src/connections/destinations/catalog/test-flow/index.md
> +title: 1Flow (Actions) Destination
Done. Thanks for suggestion

2023-09-14 13:41 UTC, rohan1flow commented on src/connections/destinations/catalog/test-flow/index.md
> +5. Go to 1flow.ai -> Settings -> Project Settings -> Copy 1Flow project key and paste it into the Connection Settings in Segment.
Done

2023-09-14 13:41 UTC, rohan1flow commented on src/connections/destinations/catalog/test-flow/index.md
> +
Done. Also added setup instructions

2023-09-14 13:41 UTC, rohan1flow commented on src/connections/destinations/catalog/test-flow/index.md
> +
Done

2023-09-14 14:53 UTC, forstisabella commented on src/connections/destinations/catalog/test-flow/index.md
> +[1Flow](https://1flow.ai/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners) is a leading in-app user survey and messaging platform for Mobile app and SaaS businesses.
```suggestion
[1Flow](https://1flow.ai/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} is a leading in-app user survey and messaging platform for Mobile app and SaaS businesses.
```

2023-09-14 14:55 UTC, forstisabella commented on src/connections/destinations/catalog/test-flow/index.md
> +title: 1Flow Mobile Plugin Destination
```suggestion
title: 1Flow Mobile Plugin Destination
id: 64dd07c1fed86b6866cd93f5
beta: true
hidden: true
```

2023-09-14 14:57 UTC, forstisabella approved these changes
Approved and g2g pending two comments!

2023-09-14 18:33 UTC, rohan1flow commented
> Approved and g2g pending two comments!

Addressed both. Ready if you want to take a look

2023-09-14 18:39 UTC, forstisabella commented
lgtm! I'll wait for one more review from @tcgilbert before we merge

2023-09-14 18:52 UTC, tcgilbert approved these changes

2023-09-14 19:13 UTC, merged