[STRATCONN-3100] TikTok Docs Update
segmentio/segment-docs pull request #5326
Opened 2023-09-11 19:48 UTC by marinhero

### Proposed changes

We've updated the TikTok destinations. This PR reflects the new state of the destination.

### Merge timing

- Depending on the rollout of the destination. Targeting September 18th.

2023-09-12 18:01 UTC, rvadera12 reviewed
Great Job! I left a few comments and @maryamsharif could you just fact check me for a couple of comments.

2023-09-12 20:53 UTC, rvadera12 commented on src/connections/destinations/catalog/actions-tiktok-audiences/index.md
> +    In the settings that appear in the side panel, toggle the **Send Track** option on and do **not** change the Audience Entered/Audience Exited event names.
Confirmed with Maryam that technically you can change the event name - so lets add 

_If you update the event names, please make sure to also update it in the Add Users and Remove Users mappings under step 1 **(Select events to map and Send)**._

2023-09-12 21:32 UTC, forstisabella requested changes

2023-09-12 21:32 UTC, forstisabella commented on src/connections/destinations/catalog/actions-tiktok-audiences/index.md
> +- If you created a TikTok Audiences destination instance before September 18th your instance and all subsequent new instances are considered _legacy_. Therefore, follow the documentation labeled as s
```suggestion
- If you created a TikTok Audiences destination instance before September 18th, 2023, your instance(s) and all subsequent instances are considered _legacy_ instances. To create new _legacy_ instances, see the [Create a TikTok audience (Legacy)](#create-a-tiktok-audience-legacy) documentation. Users who created their first instance after September 18, 2023 are considered to have _native_ instances. To create new _native_ instances, see the [Configure the TikTok Audiences destination (Native)](#configure-the-tiktok-audiences-destination-native) documentation.
```

2023-09-12 21:32 UTC, forstisabella commented on src/connections/destinations/catalog/actions-tiktok-audiences/index.md
> +- For more information about how to update from _legacy_ to _native_ reach out to [friends@segment.com](mailto:friends@segment.com).
```suggestion
- For more information about how to update from _legacy_ to _native_, reach out to [friends@segment.com](mailto:friends@segment.com).
```

2023-09-12 21:32 UTC, forstisabella commented on src/connections/destinations/catalog/actions-tiktok-audiences/index.md
> +- Both versions offer the same set of features, the difference sits in the way to configure them. For legacy, you are required to create an audience manually whereas native will do that automatically
```suggestion
- Both _legacy_ and _native_ instances have the same set of features, but are configured differently. Legacy instances require you to create an audience or action manually, but native instances automatically create audiences and actions.
```

2023-09-12 21:32 UTC, forstisabella commented on src/connections/destinations/catalog/actions-tiktok-audiences/index.md
> +**add user and remove user are considered legacy actions**
Why are they considered legacy actions? Does that mean they're restricted to the legacy instances of this destination?

```suggestion
> info ""
> Add User and Remove User are considered legacy actions.
```

2023-09-12 21:32 UTC, forstisabella commented on src/connections/destinations/catalog/actions-tiktok-audiences/index.md
> +1. From the Segment web app, navigate to **Engage > Audiences**. Ensure you are in the Engage space you plan to use with the TikTok Audiences destination. Either choose an existing Engage audience or
```suggestion
1. From the Segment web app, navigate to **Engage > Audiences**. Ensure you are in the Engage space you plan to use with the TikTok Audiences destination. Either choose an existing Engage audience or create a new one.
```

2023-09-12 21:32 UTC, forstisabella commented on src/connections/destinations/catalog/actions-tiktok-audiences/index.md
> +2. Navigate to **Engage > Engage Settings** and click **Destinations**. Please ensure you are still in the correct Engage space.
```suggestion
2. Navigate to **Engage > Engage Settings** and click **Destinations**. 
```

2023-09-12 21:32 UTC, forstisabella commented on src/connections/destinations/catalog/actions-tiktok-audiences/index.md
> +5. On the Destination **Settings** tab, name your destination and authenticate with TikTok Audiences using OAuth.
```suggestion
5. On the **Settings** tab for the TikTok Audiences destination, name your destination and authenticate with TikTok Audiences using OAuth.
```

2023-09-12 21:32 UTC, forstisabella commented on src/connections/destinations/catalog/actions-tiktok-audiences/index.md
> +6. Once authenticated, toggle “Enable Destination” on and click  **Save Changes**.
```suggestion
6. Once authenticated, toggle “Enable Destination” on and click **Save Changes**.
```

2023-09-12 21:32 UTC, forstisabella commented on src/connections/destinations/catalog/actions-tiktok-audiences/index.md
> +    Provide the [**Advertiser ID**](https://ads.tiktok.com/help/article/ad-account-information-faq?lang=en) linked to the TikTok account that will receive the audience data, as well as the **ID Type*
```suggestion
    Provide the [**Advertiser ID**](https://ads.tiktok.com/help/article/ad-account-information-faq?lang=en) linked to the TikTok account that will receive the audience data, as well as the **ID Type** of data you'll be sending. Click **Save Settings**.
```
```suggestion
    Provide the [**Advertiser ID**](https://ads.tiktok.com/help/article/ad-account-information-faq?lang=en){:target="_blank”} linked to the TikTok account that will receive the audience data, as well as the **ID Type** of data you'll be sending. Click **Save Settings**.
```

2023-09-19 17:47 UTC, forstisabella commented
@marinhero - just want to confirm new deploy date is looking like 9/25?

2023-09-21 21:47 UTC, rvadera12 commented on src/connections/destinations/catalog/actions-tiktok-audiences/index.md
> +you can use the same mapping to create as many audiences as you would like. you just need to change the audience name and click **test mapping** again.
This is going to be a field on a mapping and we already listed above the user can use the same mapping, so there technically isn't a screen name besides mapping and the customer shouldn't have any confusion.

2023-09-21 21:51 UTC, rvadera12 commented on src/connections/destinations/catalog/actions-tiktok-audiences/index.md
> +    In the settings that appear in the side panel, toggle the **Send Track** option on and do **not** change the Audience Entered/Audience Exited event names.
```suggestion
    In the settings that appear in the side panel, toggle the **Send Track** option on and do **not** change the Audience Entered/Audience Exited event names. 
    
    *If you update the events names, please make sure to also update it in the "Add to Audience" and "Remove from Audience" mappings under step 1 (Select events to map and Send).*

    
```

2023-09-22 22:05 UTC, marinhero commented
Hi @forstisabella! Yes, 9/25 is the accurate date. Thank you and @rvadera12 for addressing the suggestions 🙇🏽

2023-09-25 18:51 UTC, forstisabella reviewed
A few changes and we'll be good to go for tomorrow 🚀

2023-09-25 18:51 UTC, forstisabella commented on src/connections/destinations/catalog/actions-tiktok-audiences/index.md
> +    Provide the [**Advertiser ID**](https://ads.tiktok.com/help/article/ad-account-information-faq?lang=en){:target="_blank”} linked to the TikTok account that will receive the audience data, as well
```suggestion
    In the settings that appear in the side panel, toggle the **Send Track** option on and **Send Identify** option off. Provide the [**Advertiser ID**](https://ads.tiktok.com/help/article/ad-account-information-faq?lang=en){:target="_blank”} linked to the TikTok account that will receive the audience data, as well as the **ID Type** of data you'll be sending. Click **Save Settings**.
    
> info " "
> If you update the events names from the default Audience Entered/Audience Exited, please make sure to also update it in the "Add to Audience" and "Remove from Audience" mappings under step 1 (Select events to map and Send)
```

2023-09-28 16:37 UTC, forstisabella approved these changes

2023-09-28 16:39 UTC, merged