Update user-deletion-and-suppression guide.md
segmentio/segment-docs pull request #5340
Opened 2023-09-13 04:19 UTC by muhammadatifjav

Update User Deletion and Suppression guide

### Proposed changes

There were some inconsistencies and missing details in the deletion and suppression guide, so I'm made some changes to mention Public API upfront, and then also add more details on what the UI shows and what Public API will show. 

### Merge timing
- ASAP once approved

### Related issues (optional)

https://segment.atlassian.net/browse/KCS-620

2023-09-18 18:56 UTC, rchinn-segment requested changes
Thanks for submitting @muhammadatifjav! A few minor suggestions to address, then I'll include this in our next deploy.

2023-09-18 18:56 UTC, rchinn-segment commented on src/privacy/user-deletion-and-suppression.md
> +1. "FAILED"
```suggestion
1. `FAILED`
```

2023-09-18 18:56 UTC, rchinn-segment commented on src/privacy/user-deletion-and-suppression.md
> +2. "FINISHED"
```suggestion
2. `FINISHED`
```

2023-09-18 18:56 UTC, rchinn-segment commented on src/privacy/user-deletion-and-suppression.md
> +3. "INITIALIZED"
```suggestion
3. `INITIALIZED`
```

2023-09-18 18:56 UTC, rchinn-segment commented on src/privacy/user-deletion-and-suppression.md
> +4. "INVALID"
```suggestion
4. `INVALID`
```

2023-09-18 18:56 UTC, rchinn-segment commented on src/privacy/user-deletion-and-suppression.md
> +5. "NOT_SUPPORTED"
```suggestion
5. `NOT_SUPPORTED`
```

2023-09-18 18:56 UTC, rchinn-segment commented on src/privacy/user-deletion-and-suppression.md
> +6. "PARTIAL_SUCCESS"
```suggestion
6. `PARTIAL_SUCCESS`
```

2023-09-18 18:56 UTC, rchinn-segment commented on src/privacy/user-deletion-and-suppression.md
> +7. "RUNNING"
```suggestion
7. `RUNNING`
```

2023-09-19 00:04 UTC, muhammadatifjav reviewed
Accepted all suggestions ! Thanks for all corrections Ryan!

2023-09-19 00:31 UTC, rchinn-segment approved these changes

2023-09-19 00:31 UTC, merged