Feature/upollo source
segmentio/segment-docs pull request #5346
Opened 2023-09-14 02:01 UTC by stephen-up

### Proposed changes

Add documentation for the Upollo Source.

Note, we have a source that we are submitting for review.
https://app.segment.com/dev-portal/integrations/source/upollo-source/status

### Merge timing
- ASAP once approved?

Thanks.

2023-09-14 19:39 UTC, rchinn-segment requested changes
Thanks for submitting - I left a few initial changes to align this a bit more with the Segment docs style guide.

2023-09-14 19:39 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +[Upollo](https://upollo.ai?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} gives unique and actionable insights that lead to conversion, retention and expansion.
```suggestion
[Upollo](https://upollo.ai?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} gives unique and actionable insights that lead to conversion, retention, and expansion.
```

2023-09-14 19:39 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +This source is maintained by Upollo. For any issues with the source, [contact their Support team](mailto:support@upollo.ai).
```suggestion
This source is maintained by Upollo. For any issues with the source, [contact Upollo's Support team](mailto:support@upollo.ai).
```

2023-09-14 19:39 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +_**NOTE:** The Upollo Source is currently in beta, which means that they are still actively developing the source. If you are interested in joining their beta program or have any feedback to help imp
```suggestion
> info ""
> The Upollo Source is currently in beta, which means that Upollo still actively developing the source. If you are interested in joining the beta program or have any feedback to help improve the Upollo Source and its documentation, [let the Upollo team know](mailto:support@upollo.ai).
```

2023-09-14 19:39 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +3. On the next screen, give the Source a nickname configure any other settings.
```suggestion
3. On the next screen, give the Source a nickname and configure any other settings.
```

2023-09-14 19:39 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +   - The nickname is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The nickname can be anything, but we recommend using something that reflects the
```suggestion
   - The nickname is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The nickname can be anything, but Segment recommends using something that reflects the source itself and distinguishes amongst your environments (for example, SourceName_Prod, SourceName_Staging, SourceName_Dev).
```

2023-09-14 19:39 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +6. Log in to your Upollo account - navigate to [Connections](https://upollo.ai/app/settings/connections) > Connect Segment Source and paste the key to connect.
```suggestion
6. Log in to your Upollo account and navigate to [Connections](https://upollo.ai/app/settings/connections). Connect the Segment Source and paste the Write key to connect.
```

2023-09-14 23:00 UTC, stephen-up commented
Hi @rchinn-segment, thank you so much for the great feedback. I've accepted it all.

Some of that come from the [documentation template](https://github.com/segmentio/segment-docs/blob/develop/templates/partners/source.md) though. So it might be good to update that too.

Thanks.

2023-09-15 16:21 UTC, tcgilbert requested changes

2023-09-15 16:21 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +| `traits.preductions`                    | An array of predictions about the user                    |
should this be "predictions" instead of "preductions"?

2023-09-15 16:21 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +title: Upollo Source
```suggestion
title: Upollo Source
id: 9TYqEh3nMe
beta: true
```

2023-09-15 16:28 UTC, tcgilbert requested changes

2023-09-15 16:28 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +   - The nickname is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The nickname can be anything, but Segment recommends using something that reflect
```suggestion
   - The nickname is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The nickname can be anything, but Segment recommends using something that reflects the source itself and distinguishes amongst your environments (for example, Upollo_Prod, Upollo_Staging, Upollo_Dev).
```

2023-09-15 16:28 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +Upollo uses a stream Source component to send Segment event data. It uses a server-side `identify` method to send data to Segment. These events are then available in any destination that accepts serv
Could you clarify in this line how Upollo is setting the `userId` value when sending to Segment? Here is an example from Klaviyo's source: 

> The default behavior is for Klaviyo to pass the userId associated with the email recipient as the userId. There are cases in which Klaviyo does not have an associated userId, in which case the email address will be passed in as the anonymousId.

2023-09-17 23:14 UTC, stephen-up commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +| `traits.preductions`                    | An array of predictions about the user                    |
Sorry, yes it is.
Thank you.

2023-09-17 23:17 UTC, stephen-up commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +Upollo uses a stream Source component to send Segment event data. It uses a server-side `identify` method to send data to Segment. These events are then available in any destination that accepts serv
Thanks @tcgilbert, falling back to using the email as the anonymous id a great way of handling that issue. I've updated our source to do that too. And I've updated this documentation to reflect that.

Thanks.

2023-09-18 16:25 UTC, rchinn-segment reviewed
Hey @stephen-up Found a few more small edits, then this looks good to me.

2023-09-18 16:25 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +6. Log in to your Upollo account and navigate to [Connections](https://upollo.ai/app/settings/connections). Connect the Segment Source and paste the Write key to connect.
```suggestion
6. Log in to your Upollo account and navigate to [Connections](https://upollo.ai/app/settings/connections){:target="_blank”}. Connect the Segment Source and paste the Write key to connect.
```

2023-09-18 16:25 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +The default behavior is for Upollo to pass the userId associated with the email recipient as the userId. There are cases in which Upollo does not have an associated userId, in which case the email ad
```suggestion
The default behavior is for Upollo to pass the `userId` associated with the email recipient as the `userId`. There are cases in which Upollo does not have an associated userId, in which case the email address is passed in as the `anonymousId`.
```

2023-09-18 16:25 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/upollo/index.md
> +The table below list the properties included in the events. Learn more about different properties in the Upollo [documentation](https://upollo.ai/docs/reference?utm_source=segmentio&utm_medium=docs&u
```suggestion
The table below lists the properties included in the events. Learn more about different properties in the Upollo [documentation](https://upollo.ai/docs/reference?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank”}
```

2023-09-18 22:57 UTC, stephen-up commented
Thanks @rchinn-segment. All applied.

2023-09-18 22:59 UTC, rchinn-segment approved these changes

2023-09-18 23:04 UTC, rchinn-segment commented
Great, LGTM. I'll let @tcgilbert sign off on this before merging

2023-09-19 12:37 UTC, tcgilbert commented
@rchinn-segment @stephen-up everything checks out! good to merge.

2023-09-19 16:00 UTC, merged