adding livelike source docs to correct integration folder
segmentio/segment-docs pull request #5474
Opened 2023-10-03 16:00 UTC by tcgilbert

### Proposed changes

Moved docs from [5448](https://github.com/segmentio/segment-docs/pull/5448) so I could change directory folder to be the same as integration slug. 

### Merge timing
asap

2023-10-03 16:15 UTC, stayseesong requested changes

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +This source is maintained by LiveLike. For any issues with the source, [contact their Support team](mailto:support@livelike.com).
```suggestion
This source is maintained by LiveLike. For any issues with the source, [contact the LiveLike Support team](mailto:support@livelike.com).
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +2. Search for "LiveLike" in the Sources Catalog, select LiveLike, and click **Add Source**.
```suggestion
2. Search for *LiveLike* in the Sources Catalog. Select **LiveLike**, and click **Add Source**.
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +3. On the next screen, give the Source a nickname configure any other settings.
```suggestion
3. Give the Source a name and configure any other settings.
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +   - The nickname is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The nickname can be anything, but we recommend using something that reflects the
```suggestion
   - The name is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The name can be anything, but Segment recommends using something that reflects the source itself and distinguishes amongst your environments (for example, LiveLike_Prod, LiveLike_Staging, LiveLike_Dev).
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +5. Copy the Write key from the Segment UI.
```suggestion
5. Copy the **Write Key** from the Segment UI.
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +6. In order to enable the integration, provide thhis Write Key to your LiveLike Account Manager so that LiveLike staff can input that Write Key into the platform to complete the process.
```suggestion
6. Provide the write Key to your LiveLike Account Manager so that LiveLike staff can input that write key into the platform to complete the process and enable the integration.
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +LiveLike uses our stream Source component to send Segment event data. It uses a server-side `track` method(s) to send data to Segment. These events are then available in any destination that accepts
```suggestion
LiveLike uses Segment's stream Source component to send Segment event data. It uses a server-side `track` method(s) to send data to Segment. These events are then available in any destination that accepts server-side events, and available in a schema in your data warehouse, so you can query using SQL.
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +| User Quest Completed       | When a user completes a Quest                             |
```suggestion
| Badge Rewarded             | When a user receives a badge.                              |
| Quest Task Completed       | When a user completes a Quest Task.                        | 
| Quest Reward Awarded       | When a user receives a Reward Item via a Quest Completion. |
| Reward Item Rewarded       | When a user is rewarded via a Reward Table.                |
| User Quest Task Progressed | When a user progresses a Quest Task.                       | 
| User Quest Completed       | When a user completes a Quest.                             | 
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +| `reward_item_threshold`  | Threshold amount of the Reward Item that's associated to earning the Badge   |
```suggestion
| `livelike_profile_id`    | The profile ID of the LiveLike user.                                              |
| `badge_id`               | The ID of the specific Badge the user earned.                                     |
| `badge_title`            | The title of the specific Badge the user earned.                                  |
| `description`            | The description of the specific Badge the user earned.                            |
| `earned_badge_id`        | The ID of the specific transaction of the user earning the Badge.                 |
| `image_url`              | The URL of the Badge image.                                                       |
| `reward_item_id`         | The ID of the Reward Item that's associated to the threshold to earn the Badge.   |
| `reward_item_name`       | The name of the Reward Item that's associated to the threshold to earn the Badge. |
| `reward_item_threshold`  | The threshold amount of the Reward Item that's associated to earning the Badge.   |
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +| `user_quest_task_id`     | ID of the specific relationship between the User and that Quest Task         |
```suggestion
| `livelike_profile_id`    | The profile ID of the LiveLike user.                                              |
| `quest_id`               | The ID of the Quest.                                                              |
| `quest_name`             | The name of the Quest.                                                            |
| `quest_task_id`          | The ID of the specific Task within the Quest that was completed.                  |
| `quest_task_name`        | The name of the specific Task within the Quest that was completed.                |
| `user_quest_id`          | The ID of the specific relationship between the User and that Quest.              |
| `user_quest_task_id`     | The ID of the specific relationship between the User and that Quest Task.         |
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +| `reward_item_transaction_id`  | ID of the transaction of the User being rewarded                             |
```suggestion
| `livelike_profile_id`         | The profile ID of the LiveLike user.                                              |
| `quest_id`                    | The ID of the Quest the user completed to earn Rewards (if applicable).           |
| `quest_name`                  | The name of the Quest the user completed to earn Rewards (if applicable).         |
| `reward_item_name`            | The name of the Reward Item that was rewarded.                                    |
| `reward_item_amount`          | The amount of the Reward Item that was rewarded.                                  |
| `reward_item_balance`         | The new balance of the Reward Item for the user.                              |
| `reward_item_id`              | The ID of the Reward Item that was rewarded.                                      |
| `reward_item_transaction_id`  | The ID of the transaction of the User being rewarded.                             |
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +| `reward_item_transaction_id`  | ID of the transaction of the User being rewarded                             |
```suggestion
| `livelike_profile_id`         | The profile ID of the LiveLike user.                                              |
| `reward_item_name`            | The name of the Reward Item that was rewarded.                                    |
| `reward_item_amount`          | The amount of the Reward Item that was rewarded.                                  |
| `reward_item_balance`         | The new balance of the Reward Item for the user.                              |
| `reward_item_id`              | The ID of the Reward Item that was rewarded.                                      |
| `reward_item_transaction_id`  | The ID of the transaction of the User being rewarded.                             |
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +| `user_quest_task_progress` | Number of times this Task has been done so far                               |
```suggestion
| `livelike_profile_id`      | The profile ID of the LiveLike user.                                              |
| `quest_id`                 | The ID of the Quest.                                                              |
| `quest_name`               | The name of the Quest.                                                            |
| `quest_task_id`            | The ID of the specific Task within the Quest that was completed.                  |
| `quest_task_name`          | The name of the specific Task within the Quest that was completed.                |
| `quest_task_target_value`  | The target number of times this Task needs to be done to complete the Task.       |
| `user_quest_id`            | The ID of the specific relationship between the User and that Quest.              |
| `user_quest_task_id`       | The ID of the specific relationship between the User and that Quest Task.         |
| `user_quest_task_progress` | The number of times this Task has been done so far.                               |
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +| `user_quest_id`          | ID of the specific relationship between the User and that Quest              |
```suggestion
| `livelike_profile_id`    | The profile ID of the LiveLike user.                                              |
| `quest_id`               | The ID of the Quest.                                                              |
| `quest_name`             | The name of the Quest.                                                            |
| `user_quest_id`          | The ID of the specific relationship between the User and that Quest.              |
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +Now that your Source is set up, you can connect it with Destinations.
```suggestion
Once your Source is set up, you can connect it with Destinations.
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +Log into your downstream tools and check to see that your events appear as expected, and that they contain all of the properties you expect. If your events and properties don’t appear, check the [Eve
```suggestion
Log in to your downstream tools and check to see that your events appear as expected, and that they contain all of the properties you expect. If your events and properties don’t appear, check the [Event Delivery](/docs/connections/event-delivery/) tool, and refer to the Destination docs for each tool for troubleshooting.
```

2023-10-03 16:15 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +If there are any issues with how the events are arriving to Segment, [contact the LiveLike support team](mailto:support@livelike.com).
```suggestion
If there are any issues with how the events arrive to Segment, [contact the LiveLike support team](mailto:support@livelike.com).
```

2023-10-03 16:20 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +1. From your workspace's [Sources catalog page](https://app.segment.com/goto-my-workspace/sources/catalog) click **Add Source**.
```suggestion
1. From your workspace's [Sources catalog page](https://app.segment.com/goto-my-workspace/sources/catalog){:target="_blank"} click **Add Source**.
```

2023-10-03 16:20 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +The table below list the properties included in the events listed above.
```suggestion
The table below lists the properties included in the events listed above.
```

2023-10-03 16:20 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +The table below list the properties included in the events listed above.
```suggestion
The table below lists the properties included in the events listed above.
```

2023-10-03 16:20 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +The table below list the properties included in the events listed above.
```suggestion
The table below lists the properties included in the events listed above.
```

2023-10-03 16:20 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +The table below list the properties included in the events listed above.
```suggestion
The table below lists the properties included in the events listed above.
```

2023-10-03 16:20 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +The table below list the properties included in the events listed above.
```suggestion
The table below lists the properties included in the events listed above.
```

2023-10-03 16:20 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/livelike-source/index.md
> +The table below list the properties included in the events listed above.
```suggestion
The table below lists the properties included in the events listed above.
```

2023-10-03 16:24 UTC, stayseesong approved these changes

2023-10-03 16:24 UTC, merged

2023-10-09 07:56 UTC, gautamLL commented
@tcgilbert We can see the pr is merged and the code in master also but we can't see the changes of documentation in catalog, https://github.com/segmentio/segment-docs/blob/master/src/connections/sources/catalog/cloud-apps/livelike-source/index.md
@tcgilbert can you help us here.

2023-10-09 19:05 UTC, tcgilbert commented
@gautamLL is there are particular section you are not seeing updated? If you are referring to adding [the beta tag](https://github.com/segmentio/segment-docs/commit/458e1b0f5009cd0b9eda6d263e8c4e9e7e9bcabd), this should be accounted for tomorrow after the docs deployment