LIBWEB-1531 - TikTok Pixel - updating docs to explain 'Use Existing Pixel' setting
segmentio/segment-docs pull request #5481
Opened 2023-10-04 14:21 UTC by joe-ayoub-segment

Related to SEV - inc-sev2-6364-tiktok-pixel-is-preventing-ajs-from-tracking-events-2023-10-02

Slack: https://twilio.slack.com/archives/C05USP6KDC3/p1696264024954719

JIRA ticket to fix Actions code: https://segment.atlassian.net/browse/LIBWEB-1531

This PR updates the TikTok Pixel docs to provide a clearer explanation of how to use the 'Use Existing Pixel', and the risks involved with disabling it.

2023-10-04 14:21 UTC, joe-ayoub-segment commented
Hi Docs Team, this PR can go out without being dependent on the associated JIRA ticket mentioned in the description above.

2023-10-04 15:21 UTC, chrisradek requested changes
I think you flipped "off" vs "on"

2023-10-04 15:21 UTC, chrisradek commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +Toggling "off" the "Use Existing Pixel" will prevent Segment from loading a TikTok Pixel library onto the web page. Instead, Segment will attempt to detect your pre-loaded TikTok Pixel library and wi
```suggestion
Toggling "on" the "Use Existing Pixel" will prevent Segment from loading a TikTok Pixel library onto the web page. Instead, Segment will attempt to detect your pre-loaded TikTok Pixel library and will use it when forwarding events to TikTok. 
```

2023-10-04 15:21 UTC, chrisradek commented on src/connections/destinations/catalog/actions-tiktok-pixel/index.md
> +Care should be taken when toggling the "Use Existing Pixel" setting to "off" as doing so could result in disruption to data collection if Segment doesn't detect TikTok Pixel on the website.
```suggestion
Care should be taken when toggling the "Use Existing Pixel" setting to "on" as doing so could result in disruption to data collection if Segment doesn't detect TikTok Pixel on the website. 
```

2023-10-04 20:35 UTC, chrisradek approved these changes

2023-10-05 16:17 UTC, pwseg approved these changes

2023-10-05 16:18 UTC, merged