Cdpresolution/sync
segmentio/segment-docs pull request #5495
Opened 2023-10-06 14:34 UTC by ajaysikri

### Proposed changes

### Merge timing

### Related issues (optional)

2023-10-09 13:12 UTC, joe-ayoub-segment requested changes

2023-10-09 13:12 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/cdpresolution/index.md
> +To verify that the destination has been set up correctly, check the Debugger section of your Segment Source. Assuming everything is as it should be, you should start seeing resolution data populate i
Hi @ajaysikri , 

I don't believe that this is what the expected behavior of the Integration is. 

Please correct me if I'm wrong, but based on the code the following is what happens: 
When a event (such as a track() event) is triggered on the browser, CDP Resolution will set a cookie on the browser, and will send an API call to its servers containing the Segment anonymousId. 

Can you please clarify if this is the correct behavior?
Best regards,
Joe

2023-10-09 15:31 UTC, ajaysikri commented on src/connections/destinations/catalog/cdpresolution/index.md
> +To verify that the destination has been set up correctly, check the Debugger section of your Segment Source. Assuming everything is as it should be, you should start seeing resolution data populate i
Hi Joe,

You are correct from the description above.  However, we do have processing that takes place on the server side, in terms of what happens after we receive the anonymous Id.  And that is what we are stating in the above.  Our goal with this documentation was to provide a review of the complete offering that CDP Resolution is providing.

Please let me know if we need a call.

Thanks, Ajay

2023-10-09 23:31 UTC, stayseesong requested changes

2023-10-09 23:31 UTC, stayseesong commented on src/connections/destinations/catalog/cdpresolution/index.md
> +3.	In your Segment Settings UI, enter your CDP Resolution API key. You can find this in the CDP Connector Setting section of your [CDP Resolution Dashboard Connection Settings](https://app.cdpresolut
```suggestion
1.	Navigate to **Connections > Catalog** in the Segment app and select the **Destinations** tab of the catalog. 
2.	Search for *CDP Resolution* and select it.
3. Choose which of your sources to connect the destination to.
4.	In the Settings, enter your CDP Resolution API key. You can find this in the CDP Connector Setting section of your [CDP Resolution Dashboard Connection Settings](https://app.cdpresolution.com/administration/cdp-connections/segment-io-f4241?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"}.
5. Go to the CDP Resolution UI. 
5. Go to the [CDP Resolution Connectors](https://app.cdpresolution.com/administration/cdp-connections?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} page and select the Segment IO connector.
2.	Paste your CDP Resolution API key in Segment to generate your Write Key.
3.	Paste your Write Key into CDP Resolution's connection configuration.
4.	Click **Upload Key**.

```

2023-10-09 23:31 UTC, stayseesong commented on src/connections/destinations/catalog/cdpresolution/index.md
> +4.	Click ‘Upload Key’.
```suggestion
```

2023-10-12 17:38 UTC, ajaysikri commented on src/connections/destinations/catalog/cdpresolution/index.md
> +To verify that the destination has been set up correctly, check the Debugger section of your Segment Source. Assuming everything is as it should be, you should start seeing resolution data populate i
Updated documentation based on discussion.

2023-10-16 11:05 UTC, joe-ayoub-segment requested changes

2023-10-16 11:05 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/cdpresolution/index.md
> +To verify that the destination has been set up correctly, check the Debugger section of your Segment Source. Assuming everything is as it should be, you should start seeing resolution data populate i
Hi @ajaysikri , 
I think we should clarify this text a little more. 

For example: 

If you have configured your CDP Resolution Destination correctly, and if you've also configured CDP Resolution to send user profile data to a Segment Source, you should start to see user profile data show in the Segment Source debugger as identify() and group() calls. 

etc...

2023-10-16 11:05 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/cdpresolution/index.md
> +When you make requests to CDP Resolution, CDP Resolution sends events with its own data back to your Segment source server-side using Segment's Node JS Library. If you see unexpected traffic from cur
Let's remove the second sentence as I think customers will find it confusing.

2023-10-16 17:30 UTC, stayseesong requested changes

2023-10-16 17:30 UTC, stayseesong commented on src/connections/destinations/catalog/cdpresolution/index.md
> +Further documentation can be found on our [documentation site](https://docs.cdpresolution.com?utm_source=segmentio&utm_medium=docs&utm_campaign=partners).
```suggestion
Further documentation can be found on our [documentation site](https://docs.cdpresolution.com?utm_source=segmentio&utm_medium=docs&utm_campaign=partners).
```
```suggestion
Further documentation can be found on the [CDP documentation site](https://docs.cdpresolution.com?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"}.
```

2023-10-16 17:30 UTC, stayseesong commented on src/connections/destinations/catalog/cdpresolution/index.md
> +When you make requests to CDP Resolution, CDP Resolution sends events with its own data back to your Segment source server-side using Segment's Node JS Library. If you see unexpected traffic from cur
```suggestion
When you make requests to CDP Resolution, CDP Resolution sends events with its own data back to your Segment source server-side using Segment's Node.js library. If you see unexpected traffic from curl in your Debugger, that traffic represents the events that CDP Resolution sends back.
```

2023-10-17 02:07 UTC, ajaysikri commented on src/connections/destinations/catalog/cdpresolution/index.md
> +To verify that the destination has been set up correctly, check the Debugger section of your Segment Source. Assuming everything is as it should be, you should start seeing resolution data populate i
Updated based on this feedback.

2023-10-17 02:07 UTC, ajaysikri commented on src/connections/destinations/catalog/cdpresolution/index.md
> +When you make requests to CDP Resolution, CDP Resolution sends events with its own data back to your Segment source server-side using Segment's Node JS Library. If you see unexpected traffic from cur
Updated based on this feedback.

2023-10-17 02:08 UTC, ajaysikri commented on src/connections/destinations/catalog/cdpresolution/index.md
> +When you make requests to CDP Resolution, CDP Resolution sends events with its own data back to your Segment source server-side using Segment's Node JS Library. If you see unexpected traffic from cur
Removed this sentence based on feedback from Joe

2023-10-17 17:00 UTC, stayseesong approved these changes

2023-10-17 17:09 UTC, merged