Optimizely Audience Doc
segmentio/segment-docs pull request #5500
Opened 2023-10-09 12:59 UTC by Romani-Ramzi

### Proposed changes

Create documentation for Optimizely Audience sync

### Merge timing
 -> ASAP once approved

2023-10-09 15:33 UTC, joe-ayoub-segment requested changes

2023-10-09 15:33 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +2. Find the Destinations Actions item in the left navigation, and click it.
```suggestion
2. Click on the Destinations Tab and search for **Optimizely Advanced Audience Targeting**.
```

2023-10-09 15:33 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +3. Click **Configure Optimizely Advanced Audience Targeting**.
```suggestion
3. Click on the **Configure Optimizely Advanced Audience Targeting** tile.
```

2023-10-09 15:33 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +4. Select your **Personas** source as the source (The app will not work with any other source)
```suggestion
4. Select your **Engage Space** as a Source. Note that this Destination will only work when an Engage Space is configured as a Source.
```

2023-10-09 15:33 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +7. Click into the **Mappings** section and click **New Mapping**
```suggestion
7. Click into the **Mappings** section, then click **New Mapping**, then click on the **Sync Audience** tile. 
```

2023-10-09 15:33 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +8. In section 3 **Select Mappings** ensure the user identifier you are targeting with your Advanced Audience Targeting integration is mapped to the Optimizely User ID field.
```suggestion
8. In section 3 **Select Mappings** ensure the user identifier you are targeting with your Advanced Audience Targeting integration is mapped to the Optimizely User ID field.
9. Click the Save button to save the Action. 
10. Enable the Action by toggling the Status to **Enabled**.
11. Click back to the **Settings** tab and enable the Destination by toggling the **Enable Destination** toggle to "On", then click "Save Changes". 
```

2023-10-09 15:33 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +6. Within the **Settings** tab paste your ODP token into the **API Key** field, select your region, enable the integration and click **Save**
```suggestion
6. Within the **Settings** tab paste your ODP token into the **API Key** field, select your region, enable the integration and click **Save Changes**
```

2023-10-09 15:33 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +- Ensure the Advanced Audience Targeting integration is configured in your Optimizely Products so that you can access your connected audiences from Twilio Segment in your Optimizely Product (Web Expe
Can this be reworded slightly? Maybe break up the sentence?

2023-10-09 15:33 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +[Web Experimentation Advanced Audience Targeting](https://docs.developers.optimizely.com/web-experimentation/docs/configure-odp-audience-targeting#integrate-with-other-cdps)
Can we explain why we are linking to this location please?

2023-10-09 15:33 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +[Feature Experimentation Advanced Audience Targeting](https://docs.developers.optimizely.com/feature-experimentation/docs/optimizely-data-platform-advanced-audience-targeting)
Can we explain why we are linking to this location please?

2023-10-09 15:33 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +[CMS Visitor Groups Advanced Audience Targeting](https://github.com/unrvld/ODP.VisitorGroups)
Can we explain why we are linking to this location please?

2023-10-09 15:33 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +- If connecting audiences to **Optimizely Web Experimentation** ensure the user id you map to the Optimizely User ID in the destination mappings area is an identifier available on the browser (client
Can we make this sentence a little clearer to understand please

2023-10-10 13:51 UTC, tcgilbert commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +[Optimizely Advanced Audience Targeting](https://optimizely.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners) allows you to sync your Segment Engage audiences to Optimizely for targeti
```suggestion
[Optimizely Advanced Audience Targeting](https://optimizely.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} allows you to sync your Segment Engage audiences to Optimizely for targeting with Web Experimentation audiences, Feature Experimentation audiences, and CMS Visitor Groups.
```

2023-10-10 13:51 UTC, tcgilbert commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +[Web Experimentation Advanced Audience Targeting](https://docs.developers.optimizely.com/web-experimentation/docs/configure-odp-audience-targeting#integrate-with-other-cdps)
```suggestion
[Web Experimentation Advanced Audience Targeting](https://docs.developers.optimizely.com/web-experimentation/docs/configure-odp-audience-targeting#integrate-with-other-cdps){:target="_blank"}
```

2023-10-10 13:52 UTC, tcgilbert commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +[CMS Visitor Groups Advanced Audience Targeting](https://github.com/unrvld/ODP.VisitorGroups)
```suggestion
[CMS Visitor Groups Advanced Audience Targeting](https://github.com/unrvld/ODP.VisitorGroups){:target="_blank"}
```

2023-10-10 14:36 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +2. Find the Destinations Actions item in the left navigation, and click it.
Fixed

2023-10-10 14:36 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +3. Click **Configure Optimizely Advanced Audience Targeting**.
fixed

2023-10-10 14:36 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +4. Select your **Personas** source as the source (The app will not work with any other source)
Fixed

2023-10-10 14:36 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +7. Click into the **Mappings** section and click **New Mapping**
Fixed

2023-10-10 14:51 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +- If connecting audiences to **Optimizely Web Experimentation** ensure the user id you map to the Optimizely User ID in the destination mappings area is an identifier available on the browser (client
Fixed

2023-10-10 14:51 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +[CMS Visitor Groups Advanced Audience Targeting](https://github.com/unrvld/ODP.VisitorGroups)
Fixed

2023-10-10 14:51 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +---
Fixed

2023-10-10 14:51 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +[Web Experimentation Advanced Audience Targeting](https://docs.developers.optimizely.com/web-experimentation/docs/configure-odp-audience-targeting#integrate-with-other-cdps)
Fixed

2023-10-10 14:51 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +[CMS Visitor Groups Advanced Audience Targeting](https://github.com/unrvld/ODP.VisitorGroups)
Fixed

2023-10-10 14:51 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +[Feature Experimentation Advanced Audience Targeting](https://docs.developers.optimizely.com/feature-experimentation/docs/optimizely-data-platform-advanced-audience-targeting)
Fixed

2023-10-10 14:51 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +[Web Experimentation Advanced Audience Targeting](https://docs.developers.optimizely.com/web-experimentation/docs/configure-odp-audience-targeting#integrate-with-other-cdps)
Fixed

2023-10-10 14:51 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +- Ensure the Advanced Audience Targeting integration is configured in your Optimizely Products so that you can access your connected audiences from Twilio Segment in your Optimizely Product (Web Expe
Fixed

2023-10-10 14:52 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
> +6. Within the **Settings** tab paste your ODP token into the **API Key** field, select your region, enable the integration and click **Save**
Fixed

2023-10-10 16:30 UTC, stayseesong commented
I'm closing this PR out as I created an editable version for the docs team here: #5512

2023-10-10 16:30 UTC, closed without merging