init commit
segmentio/segment-docs pull request #5510
Opened 2023-10-10 05:38 UTC by terence1988

### Proposed changes
We have updated the product but docs is outdated

### Merge timing
ASAP once approved

2023-10-24 16:57 UTC, stayseesong requested changes

2023-10-24 16:57 UTC, stayseesong commented on src/connections/reverse-etl/index.md
> +        * Scheduling multiple **Extractions** to start at the same time inside the same data warehouse can cause extraction errors
```suggestion
        * Scheduling multiple extractions to start at the same time inside the same data warehouse causes extraction errors.
```

2023-10-24 16:57 UTC, stayseesong commented on src/connections/reverse-etl/index.md
> +        * You can only choose to start the **Extraction** at the top of the hour.
```suggestion
        * You can only choose to start the extraction at the top of the hour.
```

2023-10-24 16:57 UTC, stayseesong commented on src/connections/reverse-etl/index.md
> +12. Select the destination you’d like to enable on the **My Destinations** page under **Reverse ETL > Destinations**.
```suggestion
13. Select the destination you’d like to enable on the **My Destinations** page under **Connections > Destinations> Reverse ETL**.
```

2023-10-24 16:57 UTC, stayseesong commented on src/connections/reverse-etl/index.md
> +11. Click **Create Mapping**.
```suggestion
11. *(Optional)* Send a test record to verify the mappings correctly send to your destination.
12. Click **Create Mapping**.
```

2023-10-24 16:57 UTC, stayseesong commented on src/connections/reverse-etl/index.md
> +13. Turn the toggle on for the **Mapping Status**. Events that match the trigger condition in the mapping will be sent to the destination.
```suggestion
14. Turn the toggle on for the **Mapping Status**. Events that match the trigger condition in the mapping will be sent to the destination.
```

2023-10-26 02:53 UTC, terence1988 commented
Thanks, I have updated the content

2023-10-26 15:54 UTC, stayseesong approved these changes

2023-10-26 15:55 UTC, merged