Update index.md
segmentio/segment-docs pull request #5515
Opened 2023-10-10 17:49 UTC by lookerb10

Add source doc

### Proposed changes

### Merge timing

### Related issues (optional)

2023-10-12 21:36 UTC, tcgilbert requested changes

2023-10-12 21:36 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/alloy-automation/index.md
> +---
```suggestion
id: tisa2A0jAs
beta: true
---
```

2023-10-12 21:36 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/alloy-automation/index.md
> +[Alloy](https://runalloy.com/flow/) is a specialized no-code automation platform, built with e-commerce businesses in mind. It seamlessly integrates various applications, paving the way for a streaml
```suggestion
[Alloy](https://runalloy.com/flow/){:target="_blank"} is a specialized no-code automation platform, built with e-commerce businesses in mind. It seamlessly integrates various applications, paving the way for a streamlined shopping experience and efficient operational workflows.
```

2023-10-12 21:36 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/alloy-automation/index.md
> +1. **Set Up the Segment Block**: Begin by setting up the Segment block within Alloy. This will enable Alloy to forward data to Segment efficiently. If you're unfamiliar with how to do this, the Alloy
Can you provide a link for "the Alloy documentation"?

2023-10-12 21:36 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/alloy-automation/index.md
> +2. **Contact the Alloy Team**: If you prefer a hands-off approach, you can request the Alloy team to set up the Segment integration on your behalf. They possess the expertise to ensure a smooth data
```suggestion
1. From your workspace's [Sources catalog page](https://app.segment.com/goto-my-workspace/sources/catalog){:target="_blank”} click **Add Source**.
2. Search for "Ally Automation" in the Sources Catalog, select it, and click **Add Source**.
3. Give the source a name, for example Alloy_Prod. The name is used in the Segment interface. Click add source to save your settings.
4. Copy the Write key from the Segment UI.
5. In Alloy, **Set Up the Segment Block**: This will enable Alloy to forward data to Segment efficiently. If you're unfamiliar with how to do this, the Alloy documentation or support team can guide you through the process.
6. **Contact the Alloy Team**: If you prefer a hands-off approach, you can request the Alloy team to set up the Segment integration on your behalf. They possess the expertise to ensure a smooth data flow from Alloy to Segment.
```

2023-10-12 21:36 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/alloy-automation/index.md
> +## Types of Calls to Segment
Are the events you send to Segment configured by the user? In other words, are there no events that alloy sends to segment b default? 

If there are default events, you will need to create a table like so listing out the events that are sent. 

- https://github.com/segmentio/segment-docs/blob/develop/templates/partners/source.md#events

2023-10-12 21:36 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/alloy-automation/index.md
> +
```suggestion

This source is maintained by Alloy. For any issues with the source, [Contact the Alloy Support team](mailto:<add support email>)
```

Please provide a mailing address or link to support page^

2023-10-12 21:36 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/alloy-automation/index.md
> +This source is maintained by Alloy. For any inquiries or challenges related to the source, the Alloy support team is readily available.
```suggestion
```

Moved to top of page to be inline with our doc spec

2023-10-12 21:41 UTC, lookerb10 commented on src/connections/sources/catalog/cloud-apps/alloy-automation/index.md
> +
contact@runalloy.com

2023-10-12 21:42 UTC, lookerb10 commented on src/connections/sources/catalog/cloud-apps/alloy-automation/index.md
> +## Types of Calls to Segment
There are no default events, the user must select which ones.

2023-10-12 21:42 UTC, lookerb10 commented on src/connections/sources/catalog/cloud-apps/alloy-automation/index.md
> +2. **Contact the Alloy Team**: If you prefer a hands-off approach, you can request the Alloy team to set up the Segment integration on your behalf. They possess the expertise to ensure a smooth data
looks to be a typo in Alloy missing the o

2023-10-12 21:42 UTC, lookerb10 commented on src/connections/sources/catalog/cloud-apps/alloy-automation/index.md
> +1. **Set Up the Segment Block**: Begin by setting up the Segment block within Alloy. This will enable Alloy to forward data to Segment efficiently. If you're unfamiliar with how to do this, the Alloy
https://docs.runalloy.com/docs

2023-10-18 18:14 UTC, tcgilbert commented
Created new PR for edits: https://github.com/segmentio/segment-docs/pull/5555

2023-10-18 18:14 UTC, closed without merging