Add info about CleverTap repo ownership
segmentio/segment-docs pull request #5519
Opened 2023-10-11 01:06 UTC by joeynmq

### Proposed changes
Our Mobile-CleverTap integrations are actually maintained by the CleverTap team:
- https://github.com/CleverTap/clevertap-segment-android
- https://github.com/CleverTap/clevertap-segment-ios

Add this information to our public documentation so that our customers can contact the appropriate team for assistance.

### Merge timing
ASAP once approved

2023-10-11 14:29 UTC, niallzato requested changes

2023-10-11 14:29 UTC, niallzato commented on src/connections/destinations/catalog/clevertap/index.md
> +
Can you delete this empty line? LGTM after that is done!

2023-10-16 16:13 UTC, rchinn-segment requested changes
Looks good - just a few additional edits to align this with our [style guide](https://github.com/segmentio/segment-docs/blob/develop/styleguide.md#styling-the-segment-methods).

2023-10-16 16:13 UTC, rchinn-segment commented on src/connections/destinations/catalog/clevertap/index.md
> +CleverTap supports the `identify`, `track`, `page` (server-side only), and `screen` (iOS and server-side only) methods.
```suggestion
CleverTap supports the Identify, Track, Page (server-side only), and Screen (iOS and server-side only) methods.
```

2023-10-16 16:13 UTC, rchinn-segment commented on src/connections/destinations/catalog/clevertap/index.md
> +All server-side destination requests require both the Segment `anonymousId` and `userId` in the payload. This is a requirement from CleverTap.
```suggestion
For server-side destination requests, CleverTap requires both the Segment `anonymousId` and `userId` in the payload.  
```

2023-10-16 16:13 UTC, rchinn-segment commented on src/connections/destinations/catalog/clevertap/index.md
> +- [Android](https://github.com/CleverTap/clevertap-segment-android)
```suggestion
- [Android](https://github.com/CleverTap/clevertap-segment-android){:target="_blank"}
```

2023-10-16 16:13 UTC, rchinn-segment commented on src/connections/destinations/catalog/clevertap/index.md
> +- [iOS](https://github.com/CleverTap/clevertap-segment-ios)
```suggestion
- [iOS](https://github.com/CleverTap/clevertap-segment-ios){:target="_blank"}
```

2023-10-17 17:04 UTC, rchinn-segment approved these changes

2023-10-17 17:04 UTC, merged