[Hyperengage Actions] - Added Documentation for New Destination
segmentio/segment-docs pull request #5539
Opened 2023-10-16 12:27 UTC by zhadier39

### Proposed changes

Added documentation for the [Hyperengage Actions Destination.](https://github.com/segmentio/action-destinations/pull/1621)

### Merge timing
- ASAP

2023-10-16 12:41 UTC, joe-ayoub-segment requested changes
Note for docs team reviewer: 

This Integration has 3 Actions, one to handle each of track(), identify() and group calls.

2023-10-16 12:50 UTC, zhadier39 commented on src/connections/destinations/catalog/hyperengage/index.md
> +- **Seamless Data Mapping.** Hyperengage streamlines the process of syncing your user and account data. By linking your account, identify, track, and group calls with user or account data will be pro
Hey @joe-ayoub-segment ,
Thank you for your feedback, I've rephrased the sentence to sound less ambigious.

2023-10-16 21:04 UTC, forstisabella requested changes
a couple of changes and we'll be good to go 🚀

2023-10-16 21:04 UTC, forstisabella commented on src/connections/destinations/catalog/hyperengage/index.md
> +## Benefits of Hyperengage (Actions)
hi @tcgilbert - do we typically include this section if there is not a classic destination already available to folks?

2023-10-16 21:04 UTC, forstisabella commented on src/connections/destinations/catalog/hyperengage/index.md
> +---
This destination is in the catalog as Hyperengage (Actions), so I've updated the destination's name accordingly. I also added the private and beta tags to denote the current status of the destination. The destination ID is pulled from Segment's Public API - including it in the frontmatter like this allows us to programmatically build content on the site (for example, this destination will appear on the [list of Actions destinations](https://segment.com/docs/connections/destinations/actions/#destination-actions-compatibility)).

```suggestion
---
title: Hyperengage (Actions) Destination
hide-boilerplate: true
hide-dossier: true
private: true
beta: true
id: 651c1db19de92d8e595ff55d
---
```

2023-10-16 21:04 UTC, forstisabella commented on src/connections/destinations/catalog/hyperengage/index.md
> +- **Seamless Data Mapping.** Hyperengage streamlines the process of syncing your user and account data. When you link your data, Hyperengage will automatically process Segment's identify, track, and
```suggestion
- **Seamless Data Mapping**: Hyperengage streamlines the process of syncing your user and account data. When you link your data with Segment, Hyperengage automatically processes Segment's Identify, Track, and Group calls, eliminating the need for manual API integrations.
```

2023-10-16 21:04 UTC, forstisabella commented on src/connections/destinations/catalog/hyperengage/index.md
> +- **Pre-configured Mapping.** We have prebuilt mappings tailored for Hyperengage with all the necessary parameters, reducing the need for manual customization.
```suggestion
- **Pre-configured Mappings**: The Hyperengage (Actions) Destination has prebuilt mappings tailored for Hyperengage with all the necessary parameters, reducing the need for manual customization.
```

2023-10-16 21:04 UTC, forstisabella commented on src/connections/destinations/catalog/hyperengage/index.md
> +- **Direct Data Transfer.** Data moves straight from Segment to Hyperengage, eliminating the need for third-party intermediaries.
```suggestion
- **Direct Data Transfer**: Data moves straight from Segment to Hyperengage, eliminating the need for third-party intermediaries.
```

2023-10-16 21:04 UTC, forstisabella commented on src/connections/destinations/catalog/hyperengage/index.md
> +- **Event Tracking and User Identification.** With Actions-based destinations, you can keep track of events and identify users and organizations in Hyperengage.
```suggestion
- **Event Tracking and User Identification**: With Segment's Actions-based destination, you can keep track of events and identify users and organizations in Hyperengage.
```

2023-10-16 21:04 UTC, forstisabella commented on src/connections/destinations/catalog/hyperengage/index.md
> +2. In the Destinations Catalog, search for "hyperengage" and choose the destination.
```suggestion
2. In the Destinations Catalog, search for "Hyperengage" and select the Hyperengage (Actions) destination.
```

2023-10-16 21:04 UTC, forstisabella commented on src/connections/destinations/catalog/hyperengage/index.md
> +3. Opt for **Configure Hyperengage**.
```suggestion
3. Click **Add destination**.
```

2023-10-16 21:04 UTC, forstisabella commented on src/connections/destinations/catalog/hyperengage/index.md
> +4. Choose an existing Source to connect to Hyperengage (Actions).
```suggestion
4. Choose an existing Source to connect to Hyperengage (Actions) and click **Next**.
5. Enter a name for your destination and click **Create destination**.
```

2023-10-16 21:04 UTC, forstisabella commented on src/connections/destinations/catalog/hyperengage/index.md
> +5. Access the [Hyperengage App](https://hyperengage.io/){:target="_blank"}, proceed to **Integration Settings**, and copy the **API Key** & **Workspace Identifier**.
```suggestion
6. Open the [Hyperengage App](https://hyperengage.io/){:target="_blank"}, proceed to **Integration Settings**, and copy the API Key and Workspace Identifier.
```

2023-10-16 21:04 UTC, forstisabella commented on src/connections/destinations/catalog/hyperengage/index.md
> +6. Paste the "API Key" & "Workspace Identifier" into the "Hyperengage (Actions)" destination settings within Segment.
```suggestion
7. Open the Segment app, navigate to your Hyperengage (Actions) destination, and paste the API Key and Workspace Identifier into the destination's settings page.
```

2023-10-17 16:22 UTC, forstisabella approved these changes

2023-10-17 16:22 UTC, forstisabella commented on src/connections/destinations/catalog/hyperengage/index.md
> +title: Hyperengage Destination
```suggestion
title: Hyperengage (Actions) Destination
```

2023-10-17 16:22 UTC, forstisabella commented on src/connections/destinations/catalog/hyperengage/index.md
> +hide-dossier: true
```suggestion
hide-dossier: true
beta: true
private: true
id: 651c1db19de92d8e595ff55d
```

2023-10-18 22:41 UTC, forstisabella commented
hey @tcgilbert - can you take a look at this PR when you get a chance?

2023-10-19 16:46 UTC, tcgilbert requested changes
please remove template comments

2023-10-19 16:46 UTC, tcgilbert commented on src/connections/destinations/catalog/hyperengage/index.md
> +<!-- This template is meant for Actions-based destinations that do not have an existing Classic or non-Actions-based version. For Actions Destinations that are a new version of a classic destination,
```suggestion
```

2023-10-19 16:46 UTC, tcgilbert commented on src/connections/destinations/catalog/hyperengage/index.md
> +<!-- Include a brief description of the destination here, along with a link to your website. -->
```suggestion
```

2023-10-19 16:46 UTC, tcgilbert commented on src/connections/destinations/catalog/hyperengage/index.md
> +<!-- In the section below, explain the value of this actions-based destination. If you don't have a classic version of the destination, remove this section. -->
```suggestion
```

2023-10-19 16:46 UTC, tcgilbert commented on src/connections/destinations/catalog/hyperengage/index.md
> +<!-- The section below describes how to activate and set up the destination. Include any additional configuration steps not mentioned. For example, acquiring an API key from your system and any setup
```suggestion
```

2023-10-19 16:46 UTC, tcgilbert commented on src/connections/destinations/catalog/hyperengage/index.md
> +<!-- The line below will render a table of connection settings (if they exist), Pre-built Mappings, and potential actions. -->
```suggestion
```

2023-10-19 16:46 UTC, tcgilbert commented on src/connections/destinations/catalog/hyperengage/index.md
> +-->
```suggestion
```

2023-10-31 16:16 UTC, forstisabella commented
hi @zhadier39 - I'm not able to directly edit this branch due to protections on your branch. I've duplicated the contents of this PR in #5606 and we'll use that one to merge the docs into the site!

2023-10-31 16:16 UTC, closed without merging