OAuth 2.0 new SDK feature documentation
segmentio/segment-docs pull request #5569
Opened 2023-10-20 21:10 UTC by MichaelGHSeg

### Proposed changes

Adding OAuth information to Node and Python

### Merge timing

Depending on OAuth release

2023-10-23 18:46 UTC, rchinn-segment requested changes
Thanks for submitting this, @MichaelGHSeg. Just a few formatting suggestions, but other than that looks good!

2023-10-23 18:46 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/server/node/index.md
> +In order to guarantee authorized communication between your server environment and Segment's Tracking API, you can enable OAuth 2 in your Segment workspace.  To support the non-interactive server env
```suggestion
Enable OAuth 2 in your Segment workspace to guarantee authorized communication between your server environment and Segment's Tracking API. To support the non-interactive server environment, the OAuth workflow used is a signed client assertion JWT.  

 You will need a public and private key pair where:
 - The public key is uploaded to the Segment dashboard.
 - The private key is kept in your server environment to be used by this SDK.
 Your server will verify its identity by signing a token request, and will receive a token that is used to authorize all communication with the Segment Tracking API.
```

2023-10-23 18:46 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/server/node/index.md
> +You will also need to provide the OAuth Application ID and the public key's ID, both of which are provided in the Segment dashboard.  There are also options available to specify the authorization ser
```suggestion
You'll need to provide the OAuth Application ID and the public key's ID, both of which are provided in the Segment dashboard.  There are also options available to specify the authorization server, custom scope, maximum number of retries, or a custom HTTP client if your environment has special rules for separate segment endpoints.
```

2023-10-23 18:46 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/server/node/index.md
> +You should ensure that you are implementing handling for Analytics SDK errors.  Good logging will help distinguish any configuration issues.
```suggestion
Be sure to implement handling for Analytics SDK errors. Good logging will help distinguish any configuration issues.
```

2023-10-23 18:46 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/server/node/index.md
> +For more information, see the [Segment OAuth 2.0 documentation](/docs/connections/oauth/)
```suggestion
For more information, see the [Segment OAuth 2.0 documentation](/docs/connections/oauth/).
```

2023-10-23 18:46 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/server/python/index.md
> +In order to guarantee authorized communication between your server environment and Segment's Tracking API, you can enable OAuth 2 in your Segment workspace.  To support the non-interactive server env
```suggestion
Enable OAuth 2 in your Segment workspace to guarantee authorized communication between your server environment and Segment's Tracking API. To support the non-interactive server environment, the OAuth workflow used is a signed client assertion JWT.  

You will need a public and private key pair where:
- The public key is uploaded to the Segment dashboard. 
- The private key is kept in your server environment to be used by this SDK. 
Your server will verify its identity by signing a token request and will receive a token that is used to authorize all communication with the Segment Tracking API.
```

2023-10-23 18:46 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/server/python/index.md
> +You will also need to provide the OAuth Application ID and the public key's ID, both of which are provided in the Segment dashboard.  There are also options available to specify the authorization ser
```suggestion
You'll need to provide the OAuth Application ID and the public key's ID, both of which are provided in the Segment dashboard.  There are also options available to specify the authorization server, custom scope, maximum number of retries, or a custom HTTP client if your environment has special rules for separate segment endpoints.
```

2023-10-23 18:46 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/server/python/index.md
> +You should ensure that you are implementing handling for Analytics SDK errors.  Good logging will help distinguish any configuration issues.
```suggestion
Be sure to implement handling for Analytics SDK errors. Good logging will help distinguish any configuration issues.
```

2023-10-23 18:46 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/server/python/index.md
> +For more information, see the [Segment OAuth 2.0 documentation](/docs/connections/oauth/)
```suggestion
For more information, see the [Segment OAuth 2.0 documentation](/docs/connections/oauth/).
```

2023-10-23 21:20 UTC, stayseesong commented on src/connections/sources/catalog/libraries/server/node/index.md
> +### OAuth 2
```suggestion
### OAuth 2.0
```

2023-10-23 21:22 UTC, stayseesong commented on src/connections/sources/catalog/libraries/server/node/index.md
> +### OAuth 2
@rchinn-segment all mentions of OAuth 2 should be OAuth 2.0 as that's what we call it in other parts of the docs site. Think it'd be good if you add a hyperlink somewhere to the OAuth 2.0 page https://segment.com/docs/connections/oauth/

2023-10-24 00:05 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/server/node/index.md
> +In order to guarantee authorized communication between your server environment and Segment's Tracking API, you can enable [OAuth 2.0](/docs/connections/oauth/) in your Segment workspace.  To support
```suggestion
Enable [OAuth 2](/docs/connections/oauth/) in your Segment workspace to guarantee authorized communication between your server environment and Segment's Tracking API. To support the non-interactive server environment, the OAuth workflow used is a signed client assertion JWT.  

You will need a public and private key pair where:
- The public key is uploaded to the Segment dashboard. 
- The private key is kept in your server environment to be used by this SDK. 
Your server will verify its identity by signing a token request and will receive a token that is used to to authorize all communication with the Segment Tracking API.
```

2023-10-24 00:06 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/server/python/index.md
> +In order to guarantee authorized communication between your server environment and Segment's Tracking API, you can enable [OAuth 2.0](/docs/connections/oauth/) in your Segment workspace.  To support
```suggestion
Enable [OAuth 2](/docs/connections/oauth/) in your Segment workspace to guarantee authorized communication between your server environment and Segment's Tracking API. To support the non-interactive server environment, the OAuth workflow used is a signed client assertion JWT.  

You will need a public and private key pair where:
- The public key is uploaded to the Segment dashboard. 
- The private key is kept in your server environment to be used by this SDK. 
Your server will verify its identity by signing a token request and will receive a token that is used to to authorize all communication with the Segment Tracking API.
```

2023-10-25 20:25 UTC, rchinn-segment approved these changes

2023-12-04 19:46 UTC, stayseesong requested changes
I just realized that OAuth 2.0 should be in its own section and not nested under "Troubleshooting" or "Multiple Clients"

2023-12-04 19:46 UTC, stayseesong commented on src/connections/sources/catalog/libraries/server/python/index.md
> +### OAuth 2
```suggestion
## OAuth 2
```

2023-12-04 19:46 UTC, stayseesong commented on src/connections/sources/catalog/libraries/server/node/index.md
> +### OAuth 2
```suggestion
## OAuth 2
```

2024-01-29 18:42 UTC, stayseesong commented
@rchinn-segment I'll take care of merging this PR in as it'll go out with the OAuth docs that I'm releasing later this week

2024-01-31 19:24 UTC, stayseesong approved these changes

2024-01-31 19:26 UTC, merged