1Flow-web doc
segmentio/segment-docs pull request #5623
Opened 2023-11-01 10:27 UTC by namit1Flow

1Flow web  bowser-destinations segment docs.

2023-11-01 11:16 UTC, namit1Flow commented
1Flow-web doc s for browser-destinations  .We are targeting trackEvent(track) and identifyUser(identify).

2023-11-02 02:56 UTC, tcgilbert requested changes

2023-11-02 02:56 UTC, tcgilbert commented on src/connections/destinations/catalog/1flow-web/index.md
> +
```suggestion
```suggestion
{% include components/actions-fields.html %}
```

For actions destinations, this snippet will autopopulate information related to the available actions

2023-11-02 02:56 UTC, tcgilbert commented on src/connections/destinations/catalog/1flow-web/index.md
> +id: 64dd07c1fed86b6866cd93f5
```suggestion
hidden: true
```

The destination has not been deployed yet, so there is no existing id. We will keep this hidden until the integration is in Public Beta

2023-11-02 02:56 UTC, tcgilbert commented on src/connections/destinations/catalog/1flow-web/index.md
> +
```suggestion
{% include content/ajs-upgrade.md %}
```

Add this snippet, which will include content on ensuring they are using a.js 2.0

2023-11-02 02:56 UTC, tcgilbert commented on src/connections/destinations/catalog/1flow-web/index.md
> +If you're not familiar with the Segment Specs, take a look to understand what the [Identify method](/docs/connections/spec/identify/) does. An example call would look like:
```suggestion
If you're not familiar with the Segment Specs, take a look to understand what the [Identify method](/docs/connections/spec/identify/) does. Below is an example of how a Segment Identify event maps to an invocation of the 1flow SDK:
```

Clarify this, because this mapping is done automatically. Don't want to cause confusion and have them think they need to add the 1flow invocations in their codebase.

2023-11-02 02:56 UTC, tcgilbert commented on src/connections/destinations/catalog/1flow-web/index.md
> +If you're not familiar with the Segment Specs, take a look to understand what the [Track method](/docs/connections/spec/track/) does. An example call would look like:
```suggestion
If you're not familiar with the Segment Specs, take a look to understand what the [Track method](/docs/connections/spec/track/) does. Below is an example of how a Segment Track event maps to an invocation of the 1flow SDK:
```

same here

2023-11-15 16:04 UTC, rchinn-segment approved these changes

2023-11-16 17:59 UTC, merged