Added information on timestamp format for time comparison operators
segmentio/segment-docs pull request #5657
Opened 2023-11-09 17:14 UTC by olesia-ag

### Proposed changes

Added a section on time comparison operators, with a note that they will only work with valid ISO timestamps

### Merge timing

ASAP once approved

2023-11-13 23:57 UTC, rchinn-segment requested changes

2023-11-13 23:57 UTC, rchinn-segment commented on src/engage/audiences/index.md
> +### Time Comparision
```suggestion
### Time comparison
```

2023-11-13 23:57 UTC, rchinn-segment commented on src/engage/audiences/index.md
> +You can use various time comparison operators in your Audience definition. Such operators are: before date, after date, within last, within next, before last, after next. Only ISO timestamps can be u
```suggestion
You can use the following time comparison operators in your audience definition: 
- before date
- after date 
- within last
- within next 
- before last
- after next 

Only ISO timestamps can be used with these operators.
```

2023-11-13 23:57 UTC, rchinn-segment commented on src/engage/audiences/index.md
> +If the timestamp is not a valid ISO timestamp (for example, a trailing 'Z' is missing), it will not be processed by Real-time compute. See [Real-time compute compared to batch](docs/engage/audiences/
```suggestion
If the timestamp is not a valid ISO timestamp (for example, a trailing `Z` is missing), Segment won't process the audience in real-time. Learn more about [real-time compute compared to batch](docs/engage/audiences/#real-time-compute-compared-to-batch)
```

2023-11-30 17:54 UTC, pwseg approved these changes

2023-11-30 17:55 UTC, merged