update plugins section
segmentio/segment-docs pull request #5669
Opened 2023-11-13 20:27 UTC by silesky

### Proposed changes

- explain difference between addSourceMiddleware and Plugins, and prefer addSourceMiddleware.
- correct description of plugins that suggest parallel vs synchronous loading -- we wait for all plugin types to io initialize.

2023-11-13 22:02 UTC, stayseesong commented
@silesky should this be converted to draft mode since it's still wip?

2023-11-13 22:03 UTC, silesky commented
> @silesky should this be converted to draft mode since it's still wip?

What makes you think it's still wip? The commit messages?

2023-11-13 22:04 UTC, stayseesong commented
yeah

2023-11-13 22:04 UTC, silesky commented
@stayseesong OK! those messages get squashed on merge, but I can squash them in advance.

2023-11-13 22:46 UTC, stayseesong requested changes

2023-11-13 22:46 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> + d
```suggestion
```

2023-11-13 22:46 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +## Plugins and Source Middleware
```suggestion
## Plugins and source middleware
```

2023-11-13 22:46 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +For basic use cases like adding event fields or dropping specific events, use [Source Middleware](#source-middleware). If you need more granular control of the lifecycle, or want to be able to abort
```suggestion
Plugins and source middleware accomplish the same thing, but plugins are significantly more powerful (but more verbose to implement).

For basic use cases like adding event fields or dropping specific events, use [source middleware](#source-middleware). If you need more granular control of the lifecycle, or want to be able to abort the Segment initialization, you should use [plugins](#plugins-for-advanced-use-cases).
```

2023-11-13 22:46 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +[Source middleware](docs/connections/sources/catalog/libraries/website/javascript/middleware/) runs before any other plugins. You can use this to enrich or drop an event.
```suggestion
[Source middleware](/docs/connections/sources/catalog/libraries/website/javascript/middleware/) runs before any other plugins. You can use this to enrich or drop an event.
```

2023-11-13 22:46 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> + d
should there be something here?

2023-11-13 22:46 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +#### Enrichment
does this section just contain an example of enrichment?

2023-11-13 22:46 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +#### Validation
does this section contain an example of validation?

2023-11-13 22:46 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +### Plugins (For advanced use-cases)
Is there supposed to be something here?

2023-11-15 20:23 UTC, silesky commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> + d
Oh no, I meant that `addSourceMiddleware` has two examples nested: "enrichment" and "validation"

2023-11-15 20:23 UTC, silesky commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +#### Enrichment
Yes

2023-11-15 20:23 UTC, silesky commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +#### Validation
Yes

2023-11-15 20:26 UTC, silesky commented on src/connections/sources/catalog/libraries/website/javascript/index.md
> +### Plugins (For advanced use-cases)
No -- I wanted to nest stuff underneath it =S But maybe H4

### Plugins  (for advanced use cases)
#### Plugin Categories, etc

2023-11-20 22:58 UTC, stayseesong commented
@silesky sorry, I'm going to close this PR out. I accidentally did something funky with git but I remade the PR: #5705

2023-11-20 23:01 UTC, closed without merging