Fueled/shopify fueled
segmentio/segment-docs pull request #5677
Opened 2023-11-14 21:35 UTC by seanberto

### Proposed changes

Documenting Fueled's Shopify Source integration for Segment.

### Merge timing

- ASAP once approved

2023-11-15 01:00 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +Fueled's Shopify Source also supports *custom events* captured client-side by our javascript library and sent to Segment. To learn more about sending custom events to Segment, visit this [Learning Ce
who does "our" refer to?

2023-11-15 01:00 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +Fueled's Shopify Source integration follows Segment's [eCommerce event specification](https://segment.com/docs/connections/spec/ecommerce/v2/){:target="_blank”}.
```suggestion
Fueled's Shopify Source integration follows Segment's [eCommerce event specification](/docs/connections/spec/ecommerce/v2/).
```

2023-11-15 01:01 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +### Fueled Standard Events
```suggestion
### Fueled standard events
```

2023-11-15 01:02 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +## Event Properties
```suggestion
## Event properties
```

2023-11-15 01:02 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +## Headless Shopify Integrations
```suggestion
## Headless Shopify integrations
```

2023-11-15 01:02 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +Fueled can be implemented on "headless" or "composable" Shopify sites. Fueled provides out-of-the-box integrations for:
```suggestion
Fueled can be implemented on *headless* or *composable* Shopify sites. Fueled provides out-of-the-box integrations for:
```

2023-11-15 01:03 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +## Additional Shopify App Source Integrations for Segment
```suggestion
## Additional Shopify App source integrations for Segment
```

2023-11-15 01:03 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +Fueled offers Segment Source integrations for a number of Shopify Marketplace apps. These integrations are available by contacting Fueled's customer support team at: [support@fueled.io](mailto:suppor
```suggestion
Fueled offers Segment source integrations for a number of Shopify Marketplace apps. These integrations are available by contacting Fueled's customer support team at: [support@fueled.io](mailto:support@fueled.io).
```

2023-11-15 01:03 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +## Adding Destinations
```suggestion
## Add destinations
```

2023-11-15 01:04 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +Now that your Shopify Source is set up, you can connect it with Destinations.
```suggestion
Now that your Shopify Source is set up, you can connect it with destinations.
```

2023-11-15 01:04 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +Log into your downstream tools and check to see that your events appear as expected, and that they contain all of the properties you expect. If your events and properties don’t appear, check the [Eve
```suggestion
Log in to your downstream tools and check to see that your events appear as expected, and that they contain all of the properties you expect. If your events and properties don’t appear, check the [Event Delivery](/docs/connections/event-delivery/) tool, and refer to the destination docs for each tool for troubleshooting.
```

2023-11-15 01:04 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +If there are any issues with how the events are arriving to Segment, [contact the Fueled support team](mailto:support@fueled.io).
```suggestion
If there are any issues with how the events arrive to Segment, [contact the Fueled support team](mailto:support@fueled.io).
```

2023-11-15 02:03 UTC, seanberto commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +**Shopify merchants can try our Segment integration for free for 15 days.**
@stayseesong - I understand that you want to remove the word "our", but your suggestion is missing an article and isn't grammatically correct. Could we say:

**Shopify merchants can try Fueled's Segment integration for free for 15 days.**

2023-11-15 02:07 UTC, seanberto commented
@stayseesong - Thank you for the review. There's one open issue, but I've committed all of the other suggestions. Let me know next steps. Really appreciate how prompt this process has been!! This is great!!!

2023-11-15 19:33 UTC, tcgilbert requested changes
Just add the frontmatter, and address stacy's comments, and we should be all set!

2023-11-15 19:33 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +---
```suggestion
---
title: Shopify - Powered by Fueled
id: 57hcOLuW6Q
beta: true
---
```

Can you add this frontmatter please?

2023-11-15 19:38 UTC, seanberto commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +**Shopify merchants can try our Segment integration for free for 15 days.**
@tcgilbert - How do we resolve @stayseesong's suggestion above? I understand the request, but the grammar in the suggestion isn't correct.

2023-11-15 19:41 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +**Shopify merchants can try our Segment integration for free for 15 days.**
@seanberto your copy looks good to me! Removing one "for"

> Shopify merchants can try Fueled's Segment integration free for 15 days.

2023-11-15 19:42 UTC, seanberto commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +**Shopify merchants can try our Segment integration for free for 15 days.**
@tcgilbert there's still a missing "this" or "Fueled's" in front of the word Segment.

2023-11-15 19:43 UTC, seanberto commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +**Shopify merchants can try our Segment integration for free for 15 days.**
in @stayseesong's commit suggestion that is, @tcgilbert.

2023-11-15 19:50 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +**Shopify merchants can try our Segment integration for free for 15 days.**
Ah, I see. I just edited the suggestion. Lmk if there is anything else!

2023-11-15 19:54 UTC, seanberto commented
Updated. Hopfully ready to go!! Thanks, team!!

2023-11-15 19:55 UTC, seanberto commented
Actually, @tcgilbert - Not sure why the PR is listed as still blocked b/c of pending change requests. Mind taking a look?

2023-11-15 20:24 UTC, seanberto reviewed
Looks good!

2023-11-15 20:27 UTC, seanberto commented
@tcgilbert - I think I've not resolved those issues, but the merge is still blocked.

2023-11-15 20:27 UTC, seanberto commented
I'm happy with all of your edits, @tcgilbert .

2023-11-15 20:32 UTC, tcgilbert requested changes

2023-11-15 20:32 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +Fueled's Shopify Source also supports *custom events* captured client-side by our javascript library and sent to Segment. To learn more about sending custom events to Segment, visit this [Learning Ce
Echoing what @stayseesong put: 

By "our" javascript library, are you referring to Fueled or Segment's?

2023-11-15 21:01 UTC, seanberto commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +Fueled's Shopify Source also supports *custom events* captured client-side by our javascript library and sent to Segment. To learn more about sending custom events to Segment, visit this [Learning Ce
Oh! Fueled's. Let's change that, @tcgilbert.

2023-11-15 21:19 UTC, seanberto commented
@tcgilbert - I accidentally asked @stayseesong for an additional review. Sorry. Also, not sure how to address the question about "our" above. I was referring to Fueled's library. Can you suggest a commit?

2023-11-15 23:25 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +Fueled's Shopify Source also supports *custom events* captured client-side by our javascript library and sent to Segment. To learn more about sending custom events to Segment, visit this [Learning Ce
```suggestion
Fueled's Shopify Source also supports *custom events* captured client-side by Fueled's javascript library and sent to Segment. To learn more about sending custom events to Segment, visit this [Learning Center article](https://learn.fueled.io/apps/shopify/shopify-event-tracking/customizing-client-side-shopify-events){:target="_blank”}.
```

2023-11-15 23:25 UTC, stayseesong commented on src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
> +Fueled's Shopify Source also supports *custom events* captured client-side by our javascript library and sent to Segment. To learn more about sending custom events to Segment, visit this [Learning Ce
@seanberto can you just commit this one change, and then it should be ready to go

2023-11-15 23:59 UTC, seanberto commented
@tcgilbert and @stayseesong - I believe I have reviewed all change reqeusts, but the merging is still blocked. Not sure what I need to do.

2023-11-16 00:00 UTC, seanberto reviewed
Looks good.

2023-11-16 00:20 UTC, stayseesong commented
I will be able to merge it after I approve. All of our PRs need approval from the docs team in order to merge, and the docs team is in charge of merging all requests

2023-11-16 00:21 UTC, stayseesong approved these changes

2023-11-16 00:23 UTC, merged