Feature/upollo sdm 1
segmentio/segment-docs pull request #5697
Opened 2023-11-20 00:44 UTC by stephen-up

### Proposed changes

Hi, I would like to add documentation for the Upollo destination for single destination mode.

Thanks

### Merge timing
- ASAP once approved?

### Related issues (optional)
Note we also have a source and a web destination.

https://segment.com/docs/connections/destinations/catalog/actions-upollo/
https://segment.com/docs/connections/sources/catalog/cloud-apps/upollo/

2023-11-22 14:54 UTC, tcgilbert requested changes
Just a couple of changes and we should be all set

2023-11-22 14:54 UTC, tcgilbert commented on src/connections/destinations/catalog/upollo/index.md
> +---
```suggestion
---
title: Upollo Destination
id: 62fc4ed94dd68d0d189dc9b2
beta: true
---
```

2023-11-22 14:54 UTC, tcgilbert commented on src/connections/destinations/catalog/upollo/index.md
> +3. Choose which Source should send data to the Upollo destination.
```suggestion
2. You will be redirected to Segment to login if you are not already
3. Choose the workspace and source from which you want to send data to Upollo.
4. Click "Authorize," and the destination will be created.
```

Changing the language based off what we display for the OAuth connection: 
<img width="647" alt="Screen Shot 2023-11-22 at 9 49 54 AM" src="https://github.com/segmentio/segment-docs/assets/64277654/e1d26851-ed3b-421a-b17f-d989041f3e23">

2023-11-22 22:30 UTC, stephen-up commented on src/connections/destinations/catalog/upollo/index.md
> +3. Choose which Source should send data to the Upollo destination.
Thank you, sounds great.

2023-11-27 15:48 UTC, tcgilbert commented on src/connections/destinations/catalog/upollo/index.md
> +2. You will be redirected to Segment to login if you are not already
```suggestion
1. From the [Upollo Connections screen](https://app.upollo.ai/settings/connections), in the Segment connection, click **Configure**.
2. You will be redirected to Segment to login if you are not already.
```

2023-11-27 22:07 UTC, stephen-up commented on src/connections/destinations/catalog/upollo/index.md
> +2. You will be redirected to Segment to login if you are not already
No worries. Thanks.

2023-11-27 22:23 UTC, forstisabella approved these changes
a few small changes and we'll be ready to ship! 🚀

2023-11-27 22:23 UTC, forstisabella commented on src/connections/destinations/catalog/upollo/index.md
> +> The Upollo Destination is currently in beta, which means that Upollo still actively developing the destination. If you are interested in joining the beta program or have any feedback to help improv
```suggestion
> The Upollo Destination is currently in beta, which means that Upollo is still actively developing the destination. If you are interested in joining the beta program or have any feedback to help improve the Upollo Destination and its documentation, [let the Upollo team know](mailto:support@upollo.ai).
```

2023-11-27 22:23 UTC, forstisabella commented on src/connections/destinations/catalog/upollo/index.md
> +1. From the [Upollo Connections screen](https://app.upollo.ai/settings/connections), in the Segment connection, click **Configure**.
```suggestion
1. From the [Upollo Connections screen](https://app.upollo.ai/settings/connections){:target="_blank"}, in the Segment connection, click **Configure**.
```

2023-11-27 22:23 UTC, forstisabella commented on src/connections/destinations/catalog/upollo/index.md
> +2. You will be redirected to Segment to login if you are not already.
```suggestion
2. Upollo redirects you to Segment. If you're not already logged in to Segment, log in now. 
```

2023-11-27 22:23 UTC, forstisabella commented on src/connections/destinations/catalog/upollo/index.md
> +3. Choose the workspace and source from which you want to send data to Upollo.
```suggestion
3. Select the workspace and source from which you want to send data to Upollo.
```

2023-11-27 22:23 UTC, forstisabella commented on src/connections/destinations/catalog/upollo/index.md
> +4. Click "Authorize," and the destination will be created.
```suggestion
4. Click **Authorize**. 
```

2023-11-28 22:55 UTC, stephen-up commented on src/connections/destinations/catalog/upollo/index.md
> +> The Upollo Destination is currently in beta, which means that Upollo still actively developing the destination. If you are interested in joining the beta program or have any feedback to help improv
Hi @forstisabella, thanks for the feedback. Applying it now.

2023-11-28 23:05 UTC, merged