1flow-web actions
segmentio/segment-docs pull request #5769
Opened 2023-12-06 10:37 UTC by namit1Flow

1Flow web actions doc,we are targeting on track and identify user.

2023-12-06 15:56 UTC, forstisabella commented on src/connections/destinations/catalog/1Flow Web Actions/index.md
> +id: 62bf80378e3d0241ab190594
hi @namit1Flow - looks like this ID corresponds to the 1Flow Analytics destination. Are you looking to create docs for that destination?

2023-12-06 15:59 UTC, forstisabella commented on src/connections/destinations/catalog/1Flow Web Actions/index.md
> +---
This information is autogenerated when the docs build!
```suggestion

```

2023-12-06 16:11 UTC, forstisabella requested changes

2023-12-06 16:11 UTC, forstisabella commented on src/connections/destinations/catalog/1Flow Web Actions/index.md
> +1. Navigate to **Connections** and click **Add Destination** From the Segment web app.
```suggestion
1. From the Segment web app, navigate to **Connections** and click **Add Destination** .
```

2023-12-06 16:22 UTC, tcgilbert commented on src/connections/destinations/catalog/1Flow Web Actions/index.md
> +id: 62bf80378e3d0241ab190594
this will be the correct ID: `656773f0bd79a3676ab2733d`

2023-12-06 16:23 UTC, tcgilbert commented on src/connections/destinations/catalog/1Flow Web Actions/index.md
> +id: 62bf80378e3d0241ab190594
```suggestion
id: 656773f0bd79a3676ab2733d
```

this will be the correct ID ^

2023-12-06 20:32 UTC, forstisabella approved these changes
a few changes and we'll be good to go 🚀

2023-12-06 21:14 UTC, forstisabella commented on src/connections/destinations/catalog/actions-1flow/index.md
> +title: 1Flow Web Actions
```suggestion
title: 1Flow Web (Actions)
```

2023-12-07 06:05 UTC, namit1Flow commented
Hi @forstisabella , @tcgilbert ,

Thank you for reviewing; I have made the suggested change.

2023-12-07 14:55 UTC, tcgilbert commented
hi @namit1Flow and @forstisabella - apologies for missing this, but it appears that you did in fact submit docs for this destination previously. 

[I have created a new PR](https://github.com/segmentio/segment-docs/pull/5774) that corrects for this so I will close this one out.

2023-12-07 14:55 UTC, closed without merging