Add bucket web documentation
segmentio/segment-docs pull request #5775
Opened 2023-12-07 14:55 UTC by Munter

### Proposed changes

Add documentation for the new Bucket Web (Actions) destination.
I also made some minor updates to the previous Bucket destination, so the two can refer to each other as alternatives.

### Merge timing

ASAP, once approved, to move the Bucket Web (Actions) closer to public release

### Notes

I was unable to fetch catalog information for Bucket Web (Actions), so I have been unable to verify a correct rendering of the destination info and `components/actions-fields.html` includes. Please advise if I am supposed to do any more on my end in order to get the correct metadata into the collection

2023-12-11 08:54 UTC, Munter commented
I'm moving this to PR, since the content is done, and I need some feedback on the missing catalog metadata

2023-12-13 19:38 UTC, tcgilbert requested changes
Some minor tweaks, otherwise looks good!

2023-12-13 19:38 UTC, tcgilbert commented on src/connections/destinations/catalog/bucket-web/index.md
> +{% include content/ajs-upgrade.md %}
```suggestion
```

This now is automatically accounted for on Segment side so can remove

2023-12-13 19:38 UTC, tcgilbert commented on src/connections/destinations/catalog/bucket-web/index.md
> +- Automatically enables [Live Satisfaction](https://bucket.co/live-satisfaction) prompts in your app, giving you fully automated customer satisfaction scores and feedback on your features.
```suggestion
- Automatically enables [Live Satisfaction](https://bucket.co/live-satisfaction){:target="_blank"} prompts in your app, giving you fully automated customer satisfaction scores and feedback on your features.
```

2023-12-13 19:39 UTC, tcgilbert commented
@Munter 

> I was unable to fetch catalog information for Bucket Web (Actions)

The integration needs to be live in the catalog for this to populate. so no need to worry about this for now

2023-12-14 10:57 UTC, Munter commented
@tcgilbert Thanks for the review! I've added your suggestions.

> The integration needs to be live in the catalog for this to populate. so no need to worry about this for now

Great :)
We've submitted the catalog info for review as well, so I'm crossing my fingers that will be there shortly as well

2023-12-14 15:40 UTC, tcgilbert approved these changes

2023-12-14 15:41 UTC, tcgilbert commented
@Munter excellent, I'll have the catalog review done by EOD. And we'll just need to wait for someone from our docs to merge this PR

2023-12-14 16:48 UTC, pwseg commented
@Munter I created #5802 to deploy these docs.

2023-12-14 16:48 UTC, closed without merging

2023-12-18 13:16 UTC, Munter commented
@tcgilbert @pwseg Thank you both for the swift handling :)