Updating OneSignal Partner Source Documentation
segmentio/segment-docs pull request #5819
Opened 2023-12-19 17:36 UTC by fhboswell

### Proposed changes
Updating events and properties in the OneSignal source doc

### Merge timing
- ASAP once approved

2023-12-27 16:08 UTC, tcgilbert requested changes

2023-12-27 16:08 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/onesignal/index.md
> +| MessageEvent Kind             | Event Description                                    |
```suggestion
| Message Event Type             | Event Description                                    |
```

2023-12-27 16:09 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/onesignal/index.md
> +| MessageEvent Kind             | Event Description                                    |
@fhboswell just requested one change. If "kind" is specific to your platform you can keep that over "type"

2023-12-27 16:11 UTC, tcgilbert commented
@rchinn-segment I'm currently seeing `object cloud source` for this source. I believe this is because the last time this page was built the integration was hidden. 
![Screenshot 2023-12-27 at 11 09 53 AM](https://github.com/segmentio/segment-docs/assets/64277654/59eccaef-c7da-46e4-8255-c543477f18e0)

Running `make catalog` corrects for this locally, but just want to ensure this is corrected when merged and deployed
![Screenshot 2023-12-27 at 11 11 04 AM](https://github.com/segmentio/segment-docs/assets/64277654/29bdf429-bb07-45a8-abfe-57f4bbb56952)

2023-12-27 18:34 UTC, rchinn-segment requested changes

2023-12-27 18:34 UTC, rchinn-segment commented on src/connections/sources/catalog/cloud-apps/onesignal/index.md
> +| `message_type`             | The type of message sent, push, in-app, email, SMS                                    |
```suggestion
| `message_type`             | The type of message sent (push, in-app, email, or SMS)                                    |
```

2023-12-27 18:39 UTC, rchinn-segment commented
@tcgilbert - Thanks for calling this out. We'll run `make catalog` before deploying this along with the rest of the docs

2024-01-03 17:29 UTC, fhboswell commented on src/connections/sources/catalog/cloud-apps/onesignal/index.md
> +| MessageEvent Kind             | Event Description                                    |
Hey @tcgilbert we use "kind" in our platform.

2024-01-04 14:33 UTC, tcgilbert approved these changes
looks good 👍

2024-01-04 16:58 UTC, merged