DV360 (Actions) Docs
segmentio/segment-docs pull request #5833
Opened 2023-12-29 19:35 UTC by maryamsharif

### Proposed changes

### Merge timing

### Related issues (optional)

2024-01-26 21:48 UTC, rchinn-segment requested changes
@maryamsharif thanks for submitting this! I left some comments and suggested edits to align this a bit more with our style guide.

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +1. From your Segment workspace, go to **Engage → Engage Settings → Destinations→ Add Destination** and then Search **Display and Video 360 (Actions)**.
```suggestion
1. From your Segment workspace, navigate to **Engage > Engage Settings > Destinations > Add Destination**, then search for **Display and Video 360 (Actions)**.
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +> **Note**: The destination does not have configurable settings until you create an audience, described [here](#create-an-audience-and-finish-dv360-configuration)
```suggestion
> The destination does not have configurable settings until you create an audience, described [here](#create-an-audience-and-finish-dv360-configuration).
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +Create an [Audience](/docs/personas/audiences) in a new or existing Engage space. After you create the audience, you can select the Display & Video 360 (Actions) destination you created before.
```suggestion
[Create an audience](/docs/personas/audiences) in a new or existing Engage space. After you create the audience, you can select the Display & Video 360 (Actions) destination you created before.
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +> **Note**: These settings are tied to a single audience. Each additional audience you send to DV360 requires you to input these values.
```suggestion
> These settings are tied to a single audience. Each additional audience you send to DV360 requires you to input these values.
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +| Advertiser ID                  | The ID of your DV360 Advertiser account. Can be found in your Google Account under Advertiser Settings → Basic Details → Advertiser ID.                  {:target="_
```suggestion
| Advertiser ID                  | The ID of your DV360 Advertiser account. Can be found in your Google Account under **Advertiser Settings > Basic Details > Advertiser ID**.                                                                                                                                       |
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +> info ""
```suggestion

```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +We are disabling all existing Personas Display and Video 360 destinations. You can still access your existing configuration, but please refrain from enabling the destination, as it is set to be depre
```suggestion
Segment is disabling all existing Personas Display and Video 360 destinations. You can still access your existing configuration, but please refrain from enabling the destination, as it is set to be deprecated. You will no longer be able to create new instances of Personas Display and Video 360.
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +- To use DV360 with web traffic, you must collect `anonymous_id` through the client-side `analytics.js` Source.
```suggestion
- To use DV360 with web traffic, you must collect `anonymous_id` through the client-side `analytics.js` source.
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +#### Impact to third-party cookies: Browser Policies
```suggestion
#### Impact to third-party cookies: browser policies
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +#### Impact to third-party cookies: Adblockers
```suggestion
#### Impact to third-party cookies: adblockers
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +#### IDFA impact: Recent Apple announcements
```suggestion
#### IDFA impact: recent Apple announcements
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +#### Modifying Lists Configuration in DV360
```suggestion
#### Modifying list configuration in DV360
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +### How does third-party cookie eradication impact the DV360 Destination?
```suggestion
### How does third-party cookie eradication impact the DV360 destination?
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +The DV360 Destination works on a per-audience basis. This enables you to:
```suggestion
The DV360 destination works on a per-audience basis. This enables you to:
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +Segment's integration with DV360 enables Segment customers to sync audiences created in Engage with DV360 to enable centralized audience management and improved retargeting.
```suggestion
Segment's integration with DV360 enables Segment customers to sync audiences created in Engage with DV360 for centralized audience management and improved retargeting.
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +2. Connect your JavaScript Website source to the DoubleClick Floodlight destination, and configure the following settings:
```suggestion
2. Connect your JavaScript website source to the DoubleClick Floodlight destination, and configure the following settings:
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +   3. Your [Segment Write Key](/docs/connections/find-writekey/). You can retrieve your write key from the Settings tab on the Source.
```suggestion
   3. Your [Segment Write Key](/docs/connections/find-writekey/). You can retrieve your write key from the Settings tab in the source.
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +Extra information from the API (settings, connection modes, etc.) are automatically pulled in here.
```suggestion
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +The sole mandatory action involves **re-authenticating** for each migrated Personans Display & Video 360 Destination. While you may already possess OAuth credentials, it is essential to undergo reaut
```suggestion
The sole mandatory action involves **re-authenticating** for each migrated Personans Display & Video 360 destination. While you may already possess OAuth credentials, it is essential to undergo reauthentication. This step is necessary to seamlessly integrate new audiences or implement updates to existing ones.
```

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +> **Note**: You can connect to a Google Ad Manager account. For more information, see [4. Create an audience and finish DV360 configuration](#4-create-an-audience-and-finish-dv360-configuration) belo
Wasn't quite sure what you meant here. Took a shot at editing, but let me know if we need to adjust it further.

2024-01-26 21:48 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +## Details
Can you provide a bit more context to this section? Maybe just a sentence or two that explains what the fields and requirements listed below are used for?

2024-01-26 22:09 UTC, rvadera12 commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +> **Note**: You can connect to a Google Ad Manager account. For more information, see [4. Create an audience and finish DV360 configuration](#4-create-an-audience-and-finish-dv360-configuration) belo
@rchinn-segment for more context a user can connect to Google Ads Manager using our DV360 destination, the only difference is that a user needs to fill out the user role granted setting as `Publisher` - open on ideas to how to clearly explain this to customers

2024-01-26 22:48 UTC, rvadera12 commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +## Details
@rchinn-segment this is required to set up the whole destination, open to suggestion if we need to clarify further

2024-01-27 00:41 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +- **Audience appears as**: An audience list with the name of your Engage Audience on the **DV360 All Audiences** screen
```suggestion
Keep the following settings and requirements in mind as you set up your DV360 (Actions) destination.

- **Audience appears as**: An audience list with the name of your Engage Audience on the **DV360 All Audiences** screen
```

2024-01-27 01:18 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +Keep the following settings and requirements in mind as you set up your DV360 (Actions) destination.
```suggestion
Keep the following settings and requirements in mind as you set up your DV360 (Actions) Destination.
```

2024-01-27 01:18 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +The DV360 destination syncs audience data between Segment and Google Display & Video 360. For more information about enabling the DV360 destination, [view the setup instructions below](#set-up) below
```suggestion
The DV360 Destination syncs audience data between Segment and Google Display & Video 360. For more information about enabling the DV360 Destination, [view the setup instructions below](#set-up) below.
```

2024-01-27 01:18 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +> This step is necessary only if you want to use Google User IDs to build audiences based on website traffic. If you plan to use mobile identifiers only, continue to [Enable and configure the DV360 d
```suggestion
> This step is necessary only if you want to use Google User IDs to build audiences based on website traffic. If you plan to use mobile identifiers only, continue to [Enable and configure the DV360 Destination](enable-and-configure-the-dv360-destination).
```

2024-01-27 01:18 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +The DV360 destination works on a per-audience basis. This enables you to:
```suggestion
The DV360 Destination works on a per-audience basis. This enables you to:
```

2024-01-27 01:18 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +[Create an audience](/docs/personas/audiences) in a new or existing Engage space. After you create the audience, you can select the Display & Video 360 (Actions) destination you created before.
```suggestion
[Create an audience](/docs/personas/audiences) in a new or existing Engage space. After you create the audience, you can select the Display & Video 360 (Actions) Destination you created before.
```

2024-01-27 01:18 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +1. In your workspace, visit the **Catalog** and search for the **DoubleClick Floodlight** destination.
```suggestion
1. In your workspace, visit the **Catalog** and search for the **DoubleClick Floodlight** Destination.
```

2024-01-27 01:18 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +### Enable and configure the DV360 destination
```suggestion
### Enable and configure the DV360 Destination
```

2024-01-27 01:18 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +The sole mandatory action involves **re-authenticating** for each migrated Personans Display & Video 360 destination. While you may already possess OAuth credentials, it is essential to undergo reaut
```suggestion
The sole mandatory action involves **re-authenticating** for each migrated Personans Display & Video 360 Destination. While you may already possess OAuth credentials, it is essential to undergo reauthentication. This step is necessary to seamlessly integrate new audiences or implement updates to existing ones.
```

2024-01-27 01:18 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +### How does third-party cookie eradication impact the DV360 destination?
```suggestion
### How does third-party cookie eradication impact the DV360 Destination?
```

2024-01-30 03:53 UTC, rchinn-segment approved these changes

2024-01-30 03:53 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +## Setup
```suggestion
## Set up the DV360 Destination
```

2024-01-30 03:53 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-display-video-360/index.md
> +   3. Your [Segment Write Key](/docs/connections/find-writekey/). You can retrieve your write key from the Settings tab in the source.
```suggestion
   3. Your [Segment write key](/docs/connections/find-writekey/). You can retrieve your write key from the Settings tab in the source.
```

2024-01-30 17:14 UTC, merged