APP-94627 pendo web (actions) doc
segmentio/segment-docs pull request #5866
Opened 2024-01-10 16:42 UTC by wordythebyrd

### Proposed changes

New upgrade documentation for the Pendo Web (Actions) Destination.

### Merge timing
ASAP once approved

2024-01-10 16:48 UTC, wordythebyrd commented
Hey @joe-ayoub-segment, here's the documentation update we talked about on Monday.

2024-01-10 18:32 UTC, forstisabella approved these changes
🚀

2024-01-10 18:32 UTC, forstisabella commented on src/connections/destinations/catalog/pendo-web-actions/index.md
> +title: Pendo Web (Actions) Destination
For context: the `id` is generated by Segment's Public API - including it here autogenerates info like the actions-fields, and adds this page to the [destination catalog page](https://segment.com/docs/connections/destinations/catalog/). The `hidden` and `beta` attributes denote that this is in private beta. 

```suggestion
title: Pendo Web (Actions) Destination
id: 6501a4325a8a629197cdd691
hidden: true
beta: true
```

2024-01-10 18:32 UTC, forstisabella commented on src/connections/destinations/catalog/pendo-web-actions/index.md
> +- **Support for `track`, `identify`, and `group`**. The classic Pendo destination did not support `track`, and required an additional webhook destination be configured.
```suggestion
- **Support for Track, Identify, and Group calls**. The classic Pendo destination did not support Track calls and required users to configure an additional Webhook destination.
```

2024-01-10 18:32 UTC, forstisabella commented on src/connections/destinations/catalog/pendo-web-actions/index.md
> +- **Supports CNAME for Pendo**.  Works with subscriptions using Pendo's custom CNAME feature.
```suggestion
- **Supports CNAME for Pendo**. Works with subscriptions using Pendo's custom CNAME feature.
```

2024-01-10 18:32 UTC, forstisabella commented on src/connections/destinations/catalog/pendo-web-actions/index.md
> +Remove the classic Pendo destination and webhook destination from your Segment account before adding the Pendo Web (Actions) destination.
```suggestion
Remove the classic Pendo destination and webhook destination from your Segment workspace before adding the Pendo Web (Actions) destination.
```

2024-01-11 16:38 UTC, wordythebyrd commented
Thanks @forstisabella

2024-01-11 16:52 UTC, tcgilbert requested changes
@wordythebyrd could you please change the name of the folder to `actions-pendo-web`

- current: `pendo-web-actions`
- change to: `actions-pendo-web`

2024-01-11 17:14 UTC, wordythebyrd commented
> @wordythebyrd could you please change the name of the folder to `actions-pendo-web`
> 
> * current: `pendo-web-actions`
> * change to: `actions-pendo-web`

I've updated the folder name, thank you.

2024-01-11 17:36 UTC, tcgilbert approved these changes

2024-01-18 17:49 UTC, merged