adding prereqs to readme
segmentio/segment-docs pull request #5878
Opened 2024-01-12 16:43 UTC by cmastr

### Proposed changes

### Merge timing

### Related issues (optional)

2024-01-23 00:53 UTC, stayseesong requested changes

2024-01-23 00:53 UTC, stayseesong commented on README.md
> +1. [Create an account on GitHub](https://docs.github.com/en/get-started/quickstart/creating-an-account-on-github) if you don't have one already, or sign in with your existing Github account.
```suggestion
1. [Create an account on GitHub](https://docs.github.com/en/get-started/quickstart/creating-an-account-on-github) if you don't have one already, or sign in with your existing GitHub account.
```

2024-01-23 00:53 UTC, stayseesong commented on README.md
> +1. Add the GitHub extension to your editor (in VSC: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github)
```suggestion
1. Add the GitHub extension to your editor (in VSC: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github).
```

2024-01-23 00:53 UTC, stayseesong commented on README.md
> +1. [Clone](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository) the segment docs repo.
```suggestion
1. [Clone](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository) the Segment docs repo.
```

2024-01-23 00:53 UTC, stayseesong commented on README.md
> +1. Download and install the latest version of [node.js](https://nodejs.org/en/download). Consider using a version manager such as [ASDF](https://github.com/asdf-vm/asdf) or [nvm-windows](https://docs
```suggestion
1. Download and install the latest version of [node.js](https://nodejs.org/en/download). Consider using a version manager such as [ASDF](https://github.com/asdf-vm/asdf) or [nvm-windows](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows).
```

2024-01-23 00:53 UTC, stayseesong commented on README.md
> +1. Install [vale](https://docs.errata.ai/vale/install) (an [ASDF plugin](https://github.com/osg/asdf-vale) is also available).
```suggestion
1. Install [vale](https://docs.errata.ai/vale/install). An [ASDF plugin](https://github.com/osg/asdf-vale) is also available.
```

2024-01-23 00:54 UTC, stayseesong commented
@cmastr rather than marking this with a "fixed-site" label, I feel like it should be labeled as "back-end". wdyt?

2024-02-05 17:11 UTC, cmastr commented
> @cmastr rather than marking this with a "fixed-site" label, I feel like it should be labeled as "back-end". wdyt?

This sounds good! Changed label. And added all of your comments.

2024-02-06 16:48 UTC, stayseesong approved these changes

2024-02-16 16:33 UTC, merged