Added docs for the Gleap (Actions) destination
segmentio/segment-docs pull request #5882
Opened 2024-01-14 18:05 UTC by boehlerlukas

### Proposed changes

This PR adds the Gleap (Actions) docs as specified in https://segment.com/docs/partners/destinations/#write-documentation.
Private Gleap (Actions) url: https://app.segment.com/gleap/destinations/catalog/gleap-cloud-actions

### Merge timing
- ASAP once approved

2024-01-16 17:21 UTC, rchinn-segment requested changes

2024-01-16 17:21 UTC, rchinn-segment commented on src/connections/destinations/catalog/gleap/index.html
> +> (delete after reading) Update your company name and support email address.
```suggestion

```

2024-01-16 17:21 UTC, rchinn-segment commented on src/connections/destinations/catalog/gleap/index.html
> +> (delete after reading) The section below explains how to enable and configure the destination. Include any configuration steps not captured below. For example, obtaining an API key from your platfo
```suggestion

```

2024-01-16 17:21 UTC, rchinn-segment commented on src/connections/destinations/catalog/gleap/index.html
> +5. To use the Gleap destination, obtain an API key by signing up for at [app.gleap.io](https://app.gleap.io).
```suggestion
5. To use the Gleap destination, obtain an API key by signing up at [app.gleap.io](https://app.gleap.io){:target="_blank”}.
```

2024-01-16 17:21 UTC, rchinn-segment commented on src/connections/destinations/catalog/gleap/index.html
> +6. Once registered, navigate to Project > Settings > Security in the Gleap Dashboard.
```suggestion
6. Once registered, navigate to **Project > Settings > Security** in the Gleap dashboard.
```

2024-01-16 19:54 UTC, tcgilbert requested changes

2024-01-16 19:54 UTC, tcgilbert commented on src/connections/destinations/catalog/gleap/index.html
> +---
```suggestion
---
title: Gleap (Actions) Destination
id: 656f2474a919b7e6e4900265
beta: true
hidden: true
---
```

2024-01-17 08:20 UTC, boehlerlukas commented
@tcgilbert thanks a lot for the quick review and requested changes. I just committed them.

Once this PR is through, what are the next steps to get into public beta? We are having a few customers that would love to get their hands on the integration, but right now it seems we will need to privately invite them, so this would be greatly appriciated (If we are not missing something).

Thanks a lot for your help in moving this forward!

2024-01-17 14:21 UTC, tcgilbert commented
> @tcgilbert thanks a lot for the quick review and requested changes. I just committed them.
> 
> Once this PR is through, what are the next steps to get into public beta? We are having a few customers that would love to get their hands on the integration, but right now it seems we will need to privately invite them, so this would be greatly appriciated (If we are not missing something).
> 
> Thanks a lot for your help in moving this forward!

I checked your catalog metadata, and we have everything we need on our side to go into Public Beta once these docs are through. From here, the only thing we ask is that you have confirmed you have tested your integration and it is working as expected. Could you confirm that for me?

2024-01-17 14:49 UTC, boehlerlukas commented
@tcgilbert awesome! I just updated the path from gleap to gleap-cloud-actions.

We did test the integration ourselves and have 2 customers using it (one of them for a few weeks now). It looks good from our end :)

Thanks a lot!

2024-01-17 15:15 UTC, tcgilbert approved these changes

2024-01-17 15:18 UTC, tcgilbert commented
@boehlerlukas 

> We did test the integration ourselves and have 2 customers using it (one of them for a few weeks now). It looks good from our end :)

Great! In that case, I will move your integration into public beta tomorrow afternoon when the docs site rebuilds and these docs are live. I will follow up through email to confirm. Meanwhile, if you have any other questions or concerns, please let me know.

2024-01-17 17:20 UTC, rchinn-segment approved these changes

2024-01-17 17:20 UTC, merged

2024-01-17 18:22 UTC, boehlerlukas commented
@tcgilbert Awesome, thank you so much for the fast merging!
Have a wonderful day :)