Add a note about Chrome third-party cookie restrictions.md
segmentio/segment-docs pull request #5886
Opened 2024-01-16 14:25 UTC by prigiattiperrut

### Proposed changes

Based on recent support tickets, customers have expressed concerns about Chrome's third-party cookie restrictions and how they will impact Segment and its destinations. Therefore, we are adding a note about this in our documentation so customers can find this information online

<!-- When should this get merged/published?
- ASAP once approved

2024-01-16 18:21 UTC, stayseesong requested changes

2024-01-16 18:21 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
> +Regarding cookies set by [device-mode destinations](https://segment.com/docs/connections/destinations/#connection-modes). It's important to note, that Segment primary function is to load third-party
```suggestion
Regarding cookies set by [device-mode destinations](/docs/connections/destinations/#connection-modes), it's important to note, that Segment's primary function is to load third-party SDKs and forward events to them. As a result, the usage and management of cookies are entirely at the discretion of each individual SDK. For instance, if you have concerns about destinations setting third-party cookies, it's best to consult directly with the destination providers for detailed information. For example, Amplitude, one of the destinations in the Segment catalog, offers an informative [article on this topic](https://www.docs.developers.amplitude.com/guides/cookies-consent-mgmt-guide/#frequently-asked-questions){:target="_blank"}.
```

2024-01-16 19:10 UTC, chrisradek commented on src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
> +The short answer is no. Analytics.js will not be affected by this change. This is because Analytics.js functions as a first-party cookie. Unlike third-party cookies, which are set by external service
> It sets cookies through the user's own bundled code, thus ensuring its status as a first-party cookie

I think this implies that A.JS isn't being downloaded through cdn.segment.com. It creates a cookie on the domain/sub-domain of the page that it is loaded on and reads this cookie (So if it is loaded on foo.com, the cookies is readable only by foo.com and its subdomains). Whereas 3rd party cookies are created for a different domain than the page it is being read from (e.g. creating a cookie for facebook.com but being able to read it from any website)

2024-01-18 18:24 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
> +The short answer is no. Analytics.js will not be affected by this change. This is because Analytics.js functions as a first-party cookie. Unlike third-party cookies, which are set by external service
@chrisradek should I just take the below part out according to your comment?

> Analytics.js is integrated directly into the user's website or application. It sets cookies through the user's own bundled code, thus ensuring its status as a first-party cookie and guaranteeing its operational effectiveness despite Chrome's new policy.

2024-01-24 21:15 UTC, stayseesong approved these changes

2024-01-24 21:15 UTC, merged