Linked Audiences and Data Graph content [DRAFT]
segmentio/segment-docs pull request #5890
Opened 2024-01-16 22:18 UTC by rchinn-segment

### Proposed changes

### Merge timing

### Related issues (optional)

2024-01-29 18:48 UTC, stayseesong requested changes

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/data-graph.md
> +- An [Actions-based Destination](/docs/connections/destinations/actions/#available-actions-based-destinations).
```suggestion
- An [actions-based destination](/docs/connections/destinations/actions/#available-actions-based-destinations).
```

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/data-graph.md
> +To use the Data Graph, you'll need the following:
Does "Data Graph" need to be capitalized throughout the page?

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/data-graph.md
> +> Linked Profiles follows Zero Copy principles, and doesn't copy entities to store in Segment. Segment stores and processes all data in the United States.
should it be "zero-copy principle"?

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/data-graph.md
> +1. In your Segment workspace, navigate to **Unify**, and select **Data Graph**.
can you simplify this to say "Navigate to **Unify > Data Graph**"?

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/data-graph.md
> +### Delete and edit entities and/or relationships from your Data Graph
is it self-explanatory how to delete and edit the data graph? This section doesn't really give directions in regards to how to do that

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/data-graph.md
> +| `join_on`         |    Define relationships between two entity tables `[lefty entity name].[column name] = [right entity name].[column name]`. Note that the entity name is a reference to the alias
```suggestion
| `join_on`         |    Defines relationships between two entity tables `[lefty entity name].[column name] = [right entity name].[column name]`. Note that the entity name is a reference to the alias provided in the config and doesn't need to be the fully qualified table name. |
```

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/data-graph.md
> +#### relating entities with a junction table
```suggestion
#### Relating entities with a junction table
```

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/data-graph.md
> +     - `right_join_on`: Define relationship between the two entity tables: `[junction table column name] = [right entity name].[column name]`.
should this be put in a table?

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/linked-audiences.md
> +- `subscription.status` equals "active"
instead of writing out "equals" can you use "="?

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/linked-audiences.md
> +> At this time, Linked Audiences can't be edited or deleted. Create a new audience to update conditions. To disable an audience, navigate to the **Settings** tab of an audience and toggle the **Enabl
does the phrase "at this time" need to be included?

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/linked-audiences.md
> +> Note that you can't send events before you identify people. Ensure you're making the profile(s) known in the destination before you send events. You can do this by sending an `Audience Membership C
```suggestion
> You can't send events before you identify people. Ensure you're making the profile(s) known in the destination before you send events. You can do this by sending an `Audience Membership Changed` event first, or by creating an Identify event in Connections.
```

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/linked-audiences.md
> +Finally, you'll configure your event and select additional properties to include in the event.
```suggestion
Configure your event and select additional properties to include in the event. 
```

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/linked-audiences.md
> +Next, you'll select the destination action to call when the event happens.
```suggestion
Select the destination action to call when the event happens.
```

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/linked-audiences.md
> +Linked Audiences will send events to your destination after Segment computes the audience.
```suggestion
Linked Audiences sends events to your destination after Segment computes the audience. 
```

2024-01-29 18:48 UTC, stayseesong commented on src/unify/linked-profiles/linked-audiences.md
> +To activate your Linked Audience, you'll first need to add an action destination.
```suggestion
To activate your Linked Audience, you first need to add an action destination.
```

2024-01-30 03:59 UTC, rchinn-segment commented on src/unify/linked-profiles/data-graph.md
> +To use the Data Graph, you'll need the following:
As a product name, I believe it should be. I also received some feedback from a PM to capitalize.

2024-01-30 04:00 UTC, rchinn-segment commented on src/unify/linked-profiles/data-graph.md
> +### Delete and edit entities and/or relationships from your Data Graph
Great catch. I've actually re-worded this and moved it to the `## Edit your Data Graph` section

2024-01-30 04:01 UTC, rchinn-segment commented on src/unify/linked-profiles/data-graph.md
> +> Linked Profiles follows Zero Copy principles, and doesn't copy entities to store in Segment. Segment stores and processes all data in the United States.
Yes, good catch!

2024-01-30 17:17 UTC, stayseesong approved these changes

2024-01-30 17:17 UTC, stayseesong commented on src/unify/linked-profiles/data-graph.md
> +- A Snowflake Data Warehouse.
```suggestion
- A Snowflake data warehouse. 
```

2024-01-30 17:17 UTC, stayseesong commented on src/unify/linked-profiles/data-graph.md
> +| `materialization`     | Identify the type of materialization (`dbt`,`segment`,`none`). |
should it say "Identifies the type of materialization"?

2024-01-30 17:17 UTC, stayseesong commented on src/unify/linked-profiles/data-graph.md
> +| `name`        | A unique label which will display across Segment.                           |
```suggestion
| `name`        | A unique label which displays across Segment.                           |
```

2024-01-30 17:17 UTC, stayseesong commented on src/unify/linked-profiles/data-graph.md
> +| (Optional) `enrichment_enabled = true`      | Indicate if you plan to also reference the entity table for [Linked Events](/docs/unify/linked-profiles/linked-events/).                         |
should it say "Indicates" instead of "Indicate"?

2024-01-30 17:17 UTC, stayseesong commented on src/unify/linked-profiles/data-graph.md
> +| `related_entity`   | Reference your already defined entity. |
should it be "References your already defined entity"?

2024-01-30 17:17 UTC, stayseesong commented on src/unify/linked-profiles/data-graph.md
> +| `right_join_on`  | Define relationship between the two entity tables: `[junction table column name] = [right entity name].[column name]`. |
should it say "Defines the relationship..."?

2024-01-31 19:56 UTC, merged