Clarify self-hosted ajs and add more links.
segmentio/segment-docs pull request #5896
Opened 2024-01-17 21:33 UTC by silesky

Can be merged ASAP!

2024-01-17 22:09 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +## Self-Hosting Analytics.js, settings, and destinations
@silesky how come we need to add "settings and destinations" to the heading? Can the section just be called "Self-hosting Analytics.js"?

2024-01-17 22:34 UTC, stayseesong requested changes

2024-01-17 22:34 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +To reduce or eliminate fetching assets from Segment's CDN, you can bundle analytics.js with your own code.
```suggestion
To reduce fetching assets from Segment's CDN, you can bundle Analytics.js with your own code.
```

2024-01-17 22:34 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +Some things you can do:
```suggestion
To bundle Analytics.js with your own code, you can: 
```

2024-01-17 22:34 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +1. Use [Analytics.js as an npm package](https://github.com/segmentio/analytics-next/tree/master/packages/browser#-using-as-an-npm-package).
```suggestion
* [Use Analytics.js as an npm package](https://github.com/segmentio/analytics-next/tree/master/packages/browser#-using-as-an-npm-package){:target="_blank"}.
```

2024-01-17 22:34 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +2. Use [npm to bundle your destinations ](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#add-destinations-from-npm) with your own code instead of fetching them fro
```suggestion
* [Use npm to bundle your destinations ](/docs/connections/sources/catalog/libraries/website/javascript/#add-destinations-from-npm) with your own code instead of fetching them from the CDN.
```

2024-01-17 22:34 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +2. Use [npm to bundle your destinations ](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#add-destinations-from-npm) with your own code instead of fetching them fro
@silesky are you saying that fetching from the CDN is advanced optimization? Do we have to include that bit especially if it's generally not necessary? I would suggest taking it out. wdyt?

2024-01-17 22:34 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +3. Hardcode your settings instead of fetching from the CDN (not recommended -- bypass the Segment souce configuration GUI completely).
```suggestion
* Hardcode your settings instead of fetching from the CDN (not recommended -- bypass the Segment souce configuration GUI completely).
```

2024-01-17 22:34 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +3. Hardcode your settings instead of fetching from the CDN (not recommended -- bypass the Segment souce configuration GUI completely).
@silesky are you saying that this method of hardcoding your settings is not recommended? Or are you saying that fetching from the CDN is not recommended because it bypasses the Segment source configuration GUI completely?

2024-01-17 22:51 UTC, silesky commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +3. Hardcode your settings instead of fetching from the CDN (not recommended -- bypass the Segment souce configuration GUI completely).
This method of hardcoding is not recommended, as it kind of eliminates the UI completely and is a bit brittle, as settings can no longer evolve automatically.

2024-01-17 23:01 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +* Hardcode your settings instead of fetching from the CDN (not recommended -- bypass the Segment souce configuration GUI completely).
@silesky are you saying that this step is not recommended because it bypasses the Segment source configuration?

2024-01-18 18:15 UTC, silesky commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +* Hardcode your settings instead of fetching from the CDN (not recommended -- bypass the Segment souce configuration GUI completely).
Yes!

2024-01-18 18:15 UTC, silesky commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +## Self-Hosting Analytics.js, settings, and destinations
Good point, I changed it back.

2024-01-18 18:16 UTC, silesky reviewed
add

2024-01-18 18:19 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +* Hardcode your settings instead of fetching from the CDN (not recommended -- bypass the Segment souce configuration GUI completely).
if it's not recommended, then why should we include it in the docs?

2024-01-18 18:21 UTC, silesky commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +* Hardcode your settings instead of fetching from the CDN (not recommended -- bypass the Segment souce configuration GUI completely).
> if it's not recommended, then why should we include it in the docs?
Some users have used it in the past who absolutely do not want to depend on the segment CDN in any way, so it is the final piece of the self-hosting puzzle.

2024-01-19 23:43 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +* Hardcode your settings instead of fetching from the CDN (not recommended -- bypass the Segment souce configuration GUI completely).
Let's check with support if it makes sense to include this in there

2024-02-03 20:13 UTC, silesky commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +* Hardcode your settings instead of fetching from the CDN (not recommended -- bypass the Segment souce configuration GUI completely).
any update?

2024-02-05 20:32 UTC, stayseesong approved these changes

2024-02-05 20:32 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
> +* Hardcode your settings instead of fetching from the CDN (**not recommended** -- bypasses the Segment souce configuration GUI completely).
```suggestion
* Hardcode your settings instead of fetching from the CDN (Segment doesn't recommend this as it completely bypasses the Segment source GUI)
```

2024-02-05 20:46 UTC, merged