Feat: Add Missing Documentation for Mobile Destination Plugins [Netlify Build]
segmentio/segment-docs pull request #5910
Opened 2024-01-22 21:46 UTC by alanjcharles

### Proposed changes

- Added missing documentation for mobile plugins 

- new documentation for `Adobe Analytics`,  `Localytics`, `Intercom`, and `Nielsen`. 
- fixed a typo in the SDK index files. 

### Merge timing
- Once it is proof-read and approved by my team. 
- I can follow up with here or with Paul Wooly directly for more accurate timing info once I have it.

2024-01-25 01:11 UTC, forstisabella requested changes

2024-01-25 01:11 UTC, forstisabella commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/images/nielsen.png
should this appear in the docs for either of the kotlin nielsen plugins?

2024-01-25 01:11 UTC, forstisabella commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/images/projectstructure.png
does this need to appear in the docs for the Nielsen DCR plugin?

2024-01-29 20:31 UTC, alanjcharles commented on src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/intercom-swift.md
> +https://github.com/segment-integrations/analytics-swift-intercom
yep totally agree

2024-01-29 20:32 UTC, alanjcharles commented on src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/intercom-swift.md
> +In Intercom, an "Active" event is an event that hasn't been archived. If you archive an event, it makes it inactive and removes it from your 120 active events. If you need to bring your account back
I don't off the top of my head. This is all copied from our existing Intercom doc

2024-01-29 20:32 UTC, alanjcharles commented on src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/intercom-swift.md
> +Segment supports Intercom companies in all sources. Users can be put into multiple groups, which associate them to multiple companies in Intercom.
it supports sending Intercom's concept of `Company` from all Segment source types.

2024-01-29 20:35 UTC, alanjcharles commented on src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/localytics-swift.md
> +optional properties you want to associate with the event.
no they could be whatever the customer wants to add to their track calls- from something in our spec to a totally custom value. All we're trying to say here is that they can send anything as a property and Intercom will accept it/we don't map it to anything specific.

2024-01-29 20:36 UTC, alanjcharles commented on src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/nielsen-dcr.md
> +You must also go through a pre-certification process with your Nielsen representative before shipping this implementation to production.
Genuinely not sure. Again, this is info copied from our existing public-facing doc so I am assuming the general Segment set up will be the same

2024-01-29 20:36 UTC, alanjcharles commented on src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/nielsen-dcr.md
> +strat: swift
ah, good to know- thanks!

2024-01-29 20:38 UTC, alanjcharles commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/adobe-kotlin-android.md
> +<!--todo: rewrite this so that it doesn't rely on the screenshots to explain how to map events in Segment-->
hmmm this just accidentally got pasted from the existing docs, i think! I would be down to help but I don't believe we have access to Adobe (we contracted this out). We should also figure out what to do with this in the existing docs

2024-01-29 20:41 UTC, alanjcharles commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/intercom-kotlin-android.md
> +This limitation does not apply, however, for mapping `company` objects on [Identify calls](/docs/connections/spec/identify/). Segment continues to handle that in the same way as before. This is only
yep! (again copied from existing docs

2024-01-29 20:42 UTC, alanjcharles commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/nielsen-dcr-kotlin-android.md
> +### Adding the dependency
oops- good catch!

2024-01-29 20:44 UTC, alanjcharles commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/nielsen-dcr-kotlin-android.md
> +Content originator ID. This value is only required for distributors.
unclear what the change is here?

2024-01-29 20:45 UTC, alanjcharles commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/nielsen-dtvr-kotlin-android.md
> +Nielsen Digital Content Ratings (DCR) respond to the shifting, complex multi-platform, multi-device and multi-distribution landscape by providing comprehensive measurement of digital content consumpt
oops- good catch

2024-01-29 20:45 UTC, alanjcharles commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/nielsen-dtvr-kotlin-android.md
> +
not sure off the top of my head  (copied from existing public-facing doc)

2024-01-29 21:51 UTC, forstisabella approved these changes

2024-01-29 21:51 UTC, forstisabella commented on src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/adobe-swift.md
> +<!--todo: rewrite this so that it doesn't rely on the screenshots to explain how to map events in Segment-->
if it was copied from the original doc, I'll add a backlog item to fix this but it shouldn't be a blocker!

2024-01-29 21:51 UTC, forstisabella commented on src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/intercom-swift.md
> +Segment supports Intercom companies in all sources. Users can be put into multiple groups, which associate them to multiple companies in Intercom.
```suggestion
Segment supports Intercom `company` values sent from all source types. Users can be put into multiple groups, which associate them to multiple companies in Intercom.
```

2024-01-29 21:51 UTC, forstisabella commented on src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/nielsen-dcr-kotlin-android.md
> +Content originator ID. This value is only required for distributors.
I think if we put context about each option above the code snippet, the code snippet would be more clear!

2024-02-06 16:50 UTC, alanjcharles commented
Hi @forstisabella! I think we're all good here so feel free to make any additional changes you think are necessary and release whenever it's convenient.

2024-02-06 16:57 UTC, forstisabella commented
@alanjcharles sweet! I'll release it this morning with our regular docs release cadence. Thanks for the great work you did on this!

2024-02-06 16:57 UTC, merged