added-surveysparrow-source-and-destination-doc
segmentio/segment-docs pull request #5911
Opened 2024-01-23 09:55 UTC by surveysparrowuser

added SurveySparrow source and destination document

2024-01-23 15:47 UTC, cmastr commented on src/connections/destinations/catalog/surveysparrow/index.md
> +[SurveySparrow](https://surveysparrow.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} is an end to end omnichannel experience management platform that bundles Custo
```suggestion
[SurveySparrow](https://surveysparrow.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} is an end-to-end omnichannel experience management platform that bundles Customer Experience and Employee Experience tools such as NPS, Offline, Chat, Classic, and 360 Surveys which are mobile-first, highly engaging, and user-friendly. 
```

2024-01-23 15:47 UTC, cmastr commented on src/connections/destinations/catalog/surveysparrow/index.md
> +4. Login to your [SurveySparrow](https://app.surveysparrow.com/) account, navigate to **Settings > Apps and Integrations > Create a Custom app**.
```suggestion
4. Log in to your [SurveySparrow](https://app.surveysparrow.com/) account, then navigate to **Settings > Apps and Integrations > Create a Custom app**.
```

2024-01-23 15:47 UTC, cmastr commented on src/connections/destinations/catalog/surveysparrow/index.md
> +5. Fill in the details for custom app and choose **Select all** under Scope. Later, you can remove the scopes which are not required.
```suggestion
5. Fill in the details for the custom app and choose **Select all** under Scope. Later, you can remove any scopes that are not required.
```

2024-01-23 15:47 UTC, cmastr commented on src/connections/sources/catalog/cloud-apps/surveysparrow/index.md
> +[SurveySparrow](https://surveysparrow.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} is an end to end omnichannel experience management platform that bundles Custo
```suggestion
[SurveySparrow](https://surveysparrow.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} is an end-to-end omnichannel experience management platform that bundles Customer Experience and Employee Experience tools such as NPS, Offline, Chat, Classic, and 360 Surveys which are mobile-first, highly engaging, and user-friendly. 
```

2024-01-23 15:47 UTC, cmastr commented on src/connections/sources/catalog/cloud-apps/surveysparrow/index.md
> +3. On the next screen, give the Source a name configure any other settings.
```suggestion
3. On the next screen, give the Source a name, then configure any other settings.
```

2024-01-23 15:47 UTC, cmastr commented on src/connections/sources/catalog/cloud-apps/surveysparrow/index.md
> +The default behavior is for SurveySparrow to pass the hash value of email and mobile number of respondent as the anonymousId. There are cases in which SurveySparrow does not have an associated email
```suggestion
The default behavior is for SurveySparrow to pass the hash value of the email address and mobile number of the respondent as the `anonymousId`. There are cases in which SurveySparrow does not have an associated email address or mobile number, in which case a random hash will be passed in as the `anonymousId`.
```

2024-01-23 15:47 UTC, cmastr commented on src/connections/sources/catalog/cloud-apps/surveysparrow/index.md
> +The table below list the properties included in the events listed above.
```suggestion
The table below lists the properties included in the events listed above.
```

2024-01-23 15:47 UTC, cmastr commented on src/connections/sources/catalog/cloud-apps/surveysparrow/index.md
> +Log into your downstream tools and check to see that your events appear as expected, and that they contain all of the properties you expect. If your events and properties don't appear, check the [Eve
```suggestion
Log in to your downstream tools and check to see that your events appear as expected, and that they contain all of the properties you expect. If your events and properties don't appear, check the [Event Delivery](/docs/connections/event-delivery/) tool, and refer to the Destination docs for each tool for troubleshooting.
```

2024-01-24 18:55 UTC, cmastr approved these changes

2024-01-24 19:43 UTC, tcgilbert requested changes

2024-01-24 19:43 UTC, tcgilbert commented on src/connections/destinations/catalog/surveysparrow/index.md
> +---
```suggestion
---
title: SurveySparrow (Actions) Destination
hidden: true
beta: true
---
```

2024-01-24 19:43 UTC, tcgilbert commented on src/connections/destinations/catalog/surveysparrow/index.md
> +| `contact_type`  | string        | Type of contact [contact,employee] |
Could you explain the use case for having these tables? It's likely you can remove this as `{% include components/actions-fields.html %}` will populate all the information about the Actions you created and its fields

2024-01-24 19:43 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/surveysparrow/index.md
> +---
```suggestion
---
title: SurveySparrow Source
id: di2sOHoscX
hidden: true
beta: true
---
```

2024-01-24 19:43 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/surveysparrow/index.md
> +   - The name is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The name can be anything, but we recommend using something that reflects the source i
```suggestion
   - The name is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The name can be anything, but we recommend using something that reflects the source itself and distinguishes amongst your environments (eg. SurveySparrow_Prod, SurveySparrow_Staging, SurveySparrow_Dev).
```

2024-01-24 19:46 UTC, tcgilbert requested changes
@surveysparrowuser one more thing is that you will need to change the folder name for the destination: 

- current: `surveysparrow/index.md`
- change to: `actions-surveysparrow/index.md`

2024-01-25 14:32 UTC, tcgilbert approved these changes

2024-01-26 16:49 UTC, merged