Added userguiding documentation
segmentio/segment-docs pull request #5922
Opened 2024-01-24 07:53 UTC by ozzy-cox

### Proposed changes
I have added documentation for userguiding integration.

### Merge timing
Any time

2024-01-24 20:01 UTC, tcgilbert requested changes

2024-01-24 20:01 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/userguiding/index.md
> +   - The name is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The name can be anything, but we recommend using something that reflects the source i
```suggestion
   - The name is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The name can be anything, but we recommend using something that reflects the source itself and distinguishes amongst your environments (eg. UserGuiding_Prod, UserGuiding_Staging, UserGuiding_Dev).
```

2024-01-24 20:01 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/userguiding/index.md
> +6. Log in to your UserGuiding account - navigate to Settings > Integrations > Segment Integration and paste the key in the API Key textbox in the *Userguiding as a source* section to connect.
```suggestion
6. Log in to your UserGuiding account - navigate to Settings > Integrations > Segment Integration and paste the key in the API Key textbox in the *UserGuiding as a source* section to connect.
```

2024-01-25 17:13 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/userguiding/index.md
> +This is an [Event Cloud Source](/docs/sources/#event-cloud-sources) which can not only export data into your Segment warehouse, but can also federate the exported data into your other enabled Segment
We can remove this line - when this integration goes live the site will populate a `success` box with info about event cloud sources!

example attached: 
![Screenshot 2024-01-25 at 12 13 22 PM](https://github.com/segmentio/segment-docs/assets/92472883/005e16c5-b14f-40cb-9a05-7859c7425867)


```suggestion
```

2024-01-25 17:14 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/userguiding/index.md
> +UserGuiding uses our stream Source component to send Segment event data. It uses a server-side `track` method to send data to Segment. These events are then available in any destination that accepts
```suggestion
UserGuiding uses their stream Source component to send Segment event data. It uses a server-side `track` method to send data to Segment. These events are then available in any destination that accepts server-side events, and available as a schema in your data warehouse so you can query using SQL.
```

2024-01-25 17:17 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/userguiding/index.md
> +| Survey question answer (userguiding)                   | It means a survey question was answered by a user
It may be simpler for users to understand if we add "UserGuiding" to the header row and remove the parentheticals here!

```suggestion
| UserGuiding Event Name                                             | Description                                                                                                                                            |
| ------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------ |  |
| Guide started                         | It means that a user previews the first step of a Guide                                                                                                |
| Guide completed                          | It means that the user has completed all steps of a Guide                                                                                              |
| Hotspot interacted                      | It means that the user interacted with a Hotspot group and saw a Hotspot as content. (remember, Hotspot groups can have multiple Hotspots as contents) |
| Checklist item trigger                     | It means that the user triggers a Checklist Guide                                                                                                      |
| Checklist item url click                | It means that the user clicks a URL item on a Checklist                                                                                                |
| Checklist completed                      | It means that the user completed a Checklist                                                                                                           |
| Resource center guide trigger             | It means that the user triggered a Resource Center Guide                                                                                               |
| Resource center checklist guide trigger  | It means that a Guide in a Checklist put in a Resource Center as a module is triggered by a user                                                       |
| Resource center checklist item url click | It means that a URL item in a Checklist put in a Resource Center as a module is clicked by a user                                                      |
| Resource center external URL click     | It means that a user clicks an external URL in a Resource Center                                                                                       |
| Resource center article link click        | It means that a user clicks a search article in a Resource Center                                                                                      |
| Resource center survey trigger           | It means that a user has triggered a survey in a Resource Center                                                                                       |
| Survey shown                          | It means a survey was shown to a user                                                                                                                  |
| Survey question answer                  | It means a survey question was answered by a user                                                                                                      |
```

2024-01-25 17:17 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/userguiding/index.md
> +Now that your Source is set up, you can connect it with Destinations.
```suggestion
Now that your Source is set up, you can connect it to Destinations.
```

2024-02-05 15:20 UTC, tcgilbert approved these changes

2024-02-05 17:02 UTC, merged