Update index.md
segmentio/segment-docs pull request #5927
Opened 2024-01-25 04:28 UTC by pthorat-twilio

### Proposed changes

###
**What**: In the public doc, added new section as [FAQ](https://segment.com/docs/connections/storage/catalog/aws-s3/#create-a-new-destination)

**AWS S3 destination connection error “Multiple instance of AWS S3 are not allowed for this source"**

Before inspecting the AWS S3 configurations (i.e.: IAM role and trust policy), it’s worth checking if you already have an S3 destination connected to the source in question. Segment only supports one AWS S3 destination per source.

**Why**: The customer wanted to add multiple instance of the AWS S3 for the same source, which is not possible. 

Zendesk: 

https://segment.zendesk.com/agent/tickets/533718

https://segment.zendesk.com/agent/tickets/510242

Slack: https://twilio.slack.com/archives/C8AA794FN/p1706136425243499

### Merge timing

### Related issues (optional)

2024-01-25 18:01 UTC, cmastr commented
@pthorat-twilio if this PR is ready for review, please move it from draft to ready for review and tag someone from your own department to check accuracy.

2024-01-29 01:26 UTC, pthorat-twilio commented on src/connections/storage/catalog/aws-s3/index.md
> +##**FAQ**
Can I change the section name from FAQ to "Troubleshooting" please? @grazilenehan

2024-01-29 01:59 UTC, pthorat-twilio reviewed
Can I change the section name from FAQ to "Troubleshooting" please? @grazilenehan

2024-01-29 17:17 UTC, forstisabella requested changes

2024-01-29 17:17 UTC, forstisabella commented on src/connections/storage/catalog/aws-s3/index.md
> +##**FAQ**
```suggestion
## Troubleshooting
```

2024-01-29 17:17 UTC, forstisabella commented on src/connections/storage/catalog/aws-s3/index.md
> +Before inspecting the AWS S3 configurations (i.e.: IAM role and trust policy), it’s worth checking if you already have an S3 destination connected to the source in question. Segment only supports one
```suggestion
You might encounter this error if you already have a S3 destination connected to the source in question. Segment only supports one AWS S3 destination per source.
```

2024-01-29 17:17 UTC, forstisabella commented on src/connections/storage/catalog/aws-s3/index.md
> +**
```suggestion
### AWS S3 destination connection error “Multiple instance of AWS S3 are not allowed for this source"
```

2024-01-30 19:38 UTC, forstisabella commented
Hi @pthorat-twilio - I'm happy to review this again after you accept/reject the suggestions I made on the last review. If you have any questions/concerns about the suggestions, I'm happy to address them with you!

2024-01-30 22:26 UTC, pthorat-twilio commented
Hi @forstisabella Do I just need to "Commit Change" if I am happy with the change, is that correct? I just committed all the changes. Please let me know what's the next step of action. Sorry, this is first time I am making the change using GitHub.

2024-01-30 22:27 UTC, forstisabella commented on src/connections/storage/catalog/aws-s3/index.md
> +##**FAQ**
```suggestion
## FAQ
```

2024-01-30 22:32 UTC, forstisabella commented
> Hi @forstisabella Do I just need to "Commit Change" if I am happy with the change, is that correct? I just committed all the changes. Please let me know what's the next step of action. Sorry, this is first time I am making the change using GitHub.

No worries! Yes, you go through each change in the UI and either "commit suggestion" or "resolve conversation". If a member of the docs team has approved your PR, generally once you go through and approve/reject each suggestion you can merge the PR!

2024-01-30 22:32 UTC, forstisabella approved these changes

2024-02-01 07:01 UTC, pthorat-twilio commented
@forstisabella are there any action pending from my end?

2024-02-01 14:33 UTC, forstisabella commented
nope, I'll go ahead and merge. Thanks! @pthorat-twilio

2024-02-01 14:33 UTC, merged