Avo destination docs
segmentio/segment-docs pull request #6003
Opened 2024-02-07 09:46 UTC by bjornj12

### Proposed changes

Adding documentation for new Avo destination

### Merge timing
- ASAP once approved? Yes

2024-02-08 14:44 UTC, bjornj12 commented
Our slug in the destination is actions-avo https://app.segment.com/goto-my-workspace/destinations/catalog/actions-avo

However we'd love it if we could have `/docs/connections/destinations/catalog/avo` somehow, is that possible?

2024-02-08 20:09 UTC, tcgilbert requested changes

2024-02-08 20:09 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-avo/index.md
> +---
```suggestion
---
title: Avo Destination
id: 65c2465d0d7d550aa8e7e5c6
beta: true
hidden: true
---
```

2024-02-08 20:09 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-avo/index.md
> +[Inspector](https://www.avo.app/data-observability) lets you find, triage, fix, and prevent data quality issues in your product analytics. Launch Inspector to discover all your data quality issues an
```suggestion
With [Avo](https://avo.app){:target="_blank”} Inspector, data quality is no longer a dream, it’s a workflow.

[Inspector](https://www.avo.app/data-observability){:target="_blank”} lets you find, triage, fix, and prevent data quality issues in your product analytics. Launch Inspector to discover all your data quality issues and systematically work towards better data, one resolved issue at a time.
```

2024-02-08 20:09 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-avo/index.md
> +<!-- This template is meant for Actions-based destinations that do not have an existing Classic or non-Actions-based version. For Actions Destinations that are a new version of a classic destination,
```suggestion
```

2024-02-08 20:09 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-avo/index.md
> +<!-- The line below renders a table of connection settings (if applicable), Pre-built Mappings, and available actions. -->
```suggestion
```

2024-02-08 20:09 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-avo/index.md
> +-->
```suggestion
```

2024-02-08 20:13 UTC, tcgilbert commented
> Our slug in the destination is actions-avo https://app.segment.com/goto-my-workspace/destinations/catalog/actions-avo
> 
> However we'd love it if we could have `/docs/connections/destinations/catalog/avo` somehow, is that possible?

@bjornj12 Within the Segment App UI, we link out to a hardcoded version of the docs url using the slug. But you could add a redirect to the markdown frontmatter: 

```
redirect_from:
  - '/docs/connections/destinations/catalog/actions-avo/'
```

Additionally you would need to change the name of the parent folder from `actions-avo/index.md` to `avo/index.md`

2024-02-09 10:23 UTC, bjornj12 commented
> > Our slug in the destination is actions-avo https://app.segment.com/goto-my-workspace/destinations/catalog/actions-avo
> > However we'd love it if we could have `/docs/connections/destinations/catalog/avo` somehow, is that possible?
> 
> @bjornj12 Within the Segment App UI, we link out to a hardcoded version of the docs url using the slug. But you could add a redirect to the markdown frontmatter:
> 
> ```
> redirect_from:
>   - '/docs/connections/destinations/catalog/actions-avo/'
> ```
> 
> Additionally you would need to change the name of the parent folder from `actions-avo/index.md` to `avo/index.md`

This sounds exactly like what i want, ill check this out thanks!

2024-02-09 13:06 UTC, bjornj12 commented
This is ready now then i belive, @tcgilbert 🙌

2024-02-09 23:33 UTC, forstisabella requested changes
A few changes and we'll be good to go!

2024-02-09 23:33 UTC, forstisabella commented on src/connections/destinations/catalog/avo/index.md
> +![Select a source](images/issues-dashboard.png)
```suggestion
```

2024-02-09 23:33 UTC, forstisabella commented on src/folders.txt
> +connections/destinations/catalog/avo
Hi @bjornj12, no need to add this line to the folders file - the navigation pulls information from Segment's Public API and updates automatically when the source is publicly available.  

```suggestion
```

2024-02-09 23:33 UTC, forstisabella commented on src/connections/destinations/catalog/avo/index.md
> +This track call is translated into a event signature that is sent to the Inspector API
```suggestion
This Track call is translated into a event signature that is sent to Avo's Inspector API. 
```

2024-02-09 23:33 UTC, forstisabella commented on src/connections/destinations/catalog/avo/index.md
> +Currently the Integration only receives `Track` events.
```suggestion
The Avo destination supports Track events.
```

2024-02-09 23:33 UTC, forstisabella commented on src/connections/destinations/catalog/avo/index.md
> +3. Click **Configure Avo**.
```suggestion
3. Select Avo from the list of destinations, then click **Add destination**.
```

2024-02-09 23:33 UTC, forstisabella commented on src/connections/destinations/catalog/avo/index.md
> +4. Select a source to connect to **Avo** (Actions).
```suggestion
4. Select a source to connect to Avo (Actions) and click **Next**. 
5. Enter a name for your Avo (Actions) destination and click **Create destination**. 
```

2024-02-09 23:33 UTC, forstisabella commented on src/connections/destinations/catalog/avo/index.md
> +### Track events
```suggestion
## Supported methods

### Track events
```

2024-02-09 23:33 UTC, forstisabella commented on src/connections/destinations/catalog/avo/index.md
> +Example of track call:
```suggestion
Example of Track call:
```

2024-02-09 23:33 UTC, forstisabella commented on src/connections/destinations/catalog/avo/index.md
> +   ![Copy API key](images/api-key.png)
I switched the order of the Getting Avo API key and Destination Settings sections so that you instruct users how to create their API key before they need to enter it anywhere!

```suggestion
## Getting Avo API key
Before connecting the segment source to Avo, you will need an API key for your source.

1. Create your Avo workspace at avo.app (If you don’t have one already).
2. From the Avo workspace sidebar, select **Sources**.
3. Select an existing source or create a new one. (We recommend naming your Avo sources the same as your Segment sources, for example "Web", "iOS", "Android")
   ![Select a source](images/select-source.png)
4. Click the **Inspector Setup** tab in the Avo source
5. Copy the API Key
   ![Copy API key](images/api-key.png)

## Destination settings
1. Copy the **API Key** from Avo into the field `API Key` in settings.
2. Select an environment you'd like the data to go to within Avo. It should reflect from what environment the source is receiving data from. (**Production** / **Development** / **Staging**)
3. **(Optional):** If you have an event property describing the app release version of your source you can provide it under App Version. By default the destination attempts to extract your app release version from `{context.app.version}` which defaults to `unversioned` if that does not exist. Having accurate app release versions in Avo Inspector will help you identify which releases an issue is impacting, and monitor for regressions in future releases after you’ve resolved the issue.

![Select a source](images/avo-destination.png)
```

2024-02-12 15:53 UTC, tcgilbert approved these changes

2024-02-12 17:10 UTC, forstisabella approved these changes
I just have one small change and we'll be ok to merge!

2024-02-13 14:14 UTC, bjornj12 commented
@forstisabella is this ready to be merged? 🙌

2024-02-13 17:11 UTC, merged