Rename file and add placeholders for Intercom destination
segmentio/segment-docs pull request #6005
Opened 2024-02-07 13:05 UTC by niallzato

### Proposed changes
Adding placeholder for Intercom destination (once internal naming issues are sorted)  and renaming file. This returns a 404 atm: https://segment.com/docs/connections/sources/catalog/libraries/mobile/apple/destination-plugins/nielsen-dcr-swift/

2024-02-08 16:50 UTC, rchinn-segment requested changes

2024-02-08 16:50 UTC, rchinn-segment commented on src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/index.md
> +  #   url: connections/sources/catalog/libraries/mobile/apple//destination-plugins/intercom-swift/
```suggestion
  #   url: connections/sources/catalog/libraries/mobile/apple/destination-plugins/intercom-swift/
```

2024-02-08 21:01 UTC, alanjcharles approved these changes

2024-02-09 16:50 UTC, rchinn-segment approved these changes

2024-02-09 16:50 UTC, merged