Documentation for StackAdapt destination
segmentio/segment-docs pull request #6016
Opened 2024-02-07 23:38 UTC by AlliterativeAlice

### Proposed changes

This PR adds documentation for the StackAdapt destination merged in https://github.com/segmentio/action-destinations/pull/1828

### Merge timing
As long as our destination will remain hidden from the catalog listing until our destination completes private beta and reaches general availability, the docs can be merged ASAP after approval.

### Related issues (optional)

https://github.com/segmentio/action-destinations/pull/1828 (PR that added destination this documentation is for)

2024-02-08 11:46 UTC, joe-ayoub-segment requested changes
Hi @AlliterativeAlice thanks for putting together this doc. The Segment Docs team will do a proper review. I noticed a reference to TikTok which we should change.

2024-02-08 11:46 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +4. Select an existing JavaScript Source to connect to TikTok Pixel.
hi @AlliterativeAlice we should remove the reference to TikTok Pixel ;)

2024-02-08 18:19 UTC, rchinn-segment requested changes
Thanks for submitting this, @AlliterativeAlice! I left a few minor edits to align this a bit more with our style guide.

2024-02-08 18:19 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +### Getting Your StackAdapt Universal Pixel ID
```suggestion
### Getting your StackAdapt Universal Pixel ID
```

2024-02-08 18:19 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +2. Above the list of pixels, click the "Install StackAdapt Pixel" link.
```suggestion
2. Above the list of pixels, click **Install StackAdapt Pixel**.
```

2024-02-08 18:19 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +2. Search for "StackAdapt" in the search bar, then click on the Destination "StackAdapt".
```suggestion
2. Search for and select the "StackAdapt" destination.
```

2024-02-08 18:19 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +1. From the Segment web app, click **Catalog**, then click **Destinations**.
```suggestion
1. From the Segment web app, navigate to **Connections > Catalog > Destinations**.
```

2024-02-08 18:19 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +4. Select an existing Source to connect to the StackAdapt destination.
```suggestion
4. Select an existing source to connect to the StackAdapt destination.
```

2024-02-08 18:19 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +5. Give the Destination a name.
```suggestion
5. Give the destination a name.
```

2024-02-08 18:19 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +7. Toggle on the Destination using the **Enable Destination** toggle.
```suggestion
7. Toggle on the destination using the **Enable Destination** toggle.
```

2024-02-08 18:19 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +### StackAdapt Pixel Setup
```suggestion
### StackAdapt Pixel setup
```

2024-02-08 18:19 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +### Event Rules
```suggestion
### Event rules
```

2024-02-08 18:19 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +#### Ecommerce Events
```suggestion
#### Ecommerce events
```

2024-02-08 18:19 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +For events that can involve multiple products, such as checkout events, we forward a JSON array of product objects with a `products` key and fields that map by default to following Segment product ar
```suggestion
For events that can involve multiple products, such as checkout events, StackAdapt forwards a JSON array of product objects with a `products` key and fields that map by default to following Segment product array fields:
```

2024-02-08 18:19 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +### URL Rules
```suggestion
### URL rules
```

2024-02-08 18:19 UTC, rchinn-segment commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +## Data and Privacy
```suggestion
## Data and privacy
```

2024-02-08 20:02 UTC, tcgilbert requested changes
Just a couple of changes for me

2024-02-08 20:02 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +---
```suggestion
---
title: StackAdapt (Actions) Destination
hide-boilerplate: true
hide-dossier: true
beta: true
id: 61d8859be4f795335d5c677c
hidden: true
---
```

2024-02-08 20:02 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-stackadapt/index.md
> +{% include content/ajs-upgrade.md %}
```suggestion
```

This is no longer needed

2024-02-09 20:46 UTC, rchinn-segment approved these changes
lgtm! I'll leave this open for any final feedback, and be sure to include it in our next deploy (2/13)

2024-02-12 16:16 UTC, tcgilbert approved these changes

2024-02-12 23:39 UTC, merged