obtain OAuth access token [DOC-821]
segmentio/segment-docs pull request #6040
Opened 2024-02-12 18:46 UTC by stayseesong

### Proposed changes

### Merge timing

### Related issues (optional)

2024-02-12 19:02 UTC, pwseg approved these changes

2024-02-12 19:02 UTC, pwseg commented on src/connections/oauth.md
> +* Oregon - https://oauth2.segment.io
```suggestion
* Oregon - `https://oauth2.segment.io` 
```

2024-02-12 19:02 UTC, pwseg commented on src/connections/oauth.md
> +* Dublin - https://oauth2.eu1.segmentapis.com
```suggestion
* Dublin - `https://oauth2.eu1.segmentapis.com`
```

2024-02-12 19:02 UTC, pwseg commented on src/connections/oauth.md
> +2. Send a form-url-encoded POST request to the regional authorization server with the following parameters:
```suggestion
2. Send a form-url-encoded `POST` request to the regional authorization server with the following parameters:
```

2024-02-12 19:29 UTC, srikanth-mohan requested changes

2024-02-12 19:29 UTC, srikanth-mohan commented on src/connections/oauth.md
> +3. Include the access token in the Authorization header as a Bearer token. For example:
Bullet point 3. is about using the access token. Since the section heading is about **Obtain the access token**  we should stop at 2 and create a separate section called "Using the access token". 

Can we change it to 
3. Include the access token in the Authorization header as a Bearer token to the resource server. For example to use access token in [HTTP API Source](https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/) use access_token in the header and write_key in the payload

Have you looked at my second request in the [doc](https://docs.google.com/document/d/1DTU-pOY4VR0hI8gsY8og2d0ZIniJHRzeLdZZGfAITb0/edit#heading=h.syq96apub9u2) to update http-api as well

2024-02-12 22:02 UTC, stayseesong commented
@srikanth-mohan how's this? I included your suggestions

2024-02-13 17:23 UTC, srikanth-mohan requested changes

2024-02-13 17:23 UTC, srikanth-mohan commented on src/connections/sources/catalog/libraries/server/http-api/index.md
> +Choose between [basic authentication](#basic-authentication) and [OAuth](#oauth) to authenticate headers.
Can we call it `authenticate requests` instead of `authenticate headers`

2024-02-13 17:23 UTC, srikanth-mohan commented on src/connections/sources/catalog/libraries/server/http-api/index.md
> +Include the access token in the Authorization header as a Bearer token to the resource server. For example:
Include the access token in the Authorization header as Bearer token along with your project's **Write Key** in the payload of the request. Authorization with Bearer token will look like:

2024-02-13 17:25 UTC, stayseesong commented on src/connections/sources/catalog/libraries/server/http-api/index.md
> +Choose between [basic authentication](#basic-authentication) and [OAuth](#oauth) to authenticate headers.
```suggestion
Choose between [basic authentication](#basic-authentication) and [OAuth](#oauth) to authenticate requests. 
```

2024-02-13 18:01 UTC, stayseesong commented on src/connections/sources/catalog/libraries/server/http-api/index.md
> +Include the access token in the Authorization header as a Bearer token to the resource server. For example:
```suggestion
Include the access token in the Authorization header as a Bearer token along with your project's write key in the payload of the request. For example, Authorization with Bearer token looks like:
```

2024-02-13 18:06 UTC, merged