Update guide to add a note about Consent Mode.md
segmentio/segment-docs pull request #6080
Opened 2024-02-16 18:27 UTC by prigiattiperrut

### Proposed changes

Adding a note to our Google destinations about our current work on Consent Mode.

### Merge timing

ASAP once approved

### Related issues (optional)

Slack: https://twilio.slack.com/archives/CC97A542H/p1708101546856579

2024-02-16 22:54 UTC, rchinn-segment requested changes

2024-02-16 22:54 UTC, rchinn-segment commented on src/connections/destinations/catalog/google-ads-classic/index.md
> +> Consent Mode: Segment is currently building Consent Mode functionally for all affected Google destinations. We expect this functionally to be available by March 1, 2024.
```suggestion
> Segment is currently building Consent Mode functionally for all affected Google destinations. Segment expects this functionally to be available by March 1, 2024.
```

2024-02-16 22:54 UTC, rchinn-segment commented on src/connections/destinations/catalog/google-ads-classic/index.md
> +> info ""
```suggestion
> info "Consent Mode"
```

2024-02-20 17:27 UTC, stayseesong approved these changes

2024-02-20 17:27 UTC, merged