[SECFEAT-1484] Adds Twilio Sign up section
segmentio/segment-docs pull request #6093
Opened 2024-02-20 20:02 UTC by JairAviles

### Proposed changes

With the Unified Sign Up experiment, and eventual 100% rollout, update Segment Docs to include information for customers.

![twilio_sign_up](https://github.com/segmentio/segment-docs/assets/178258/6cfbc433-5815-4a2f-8631-ca97d11cff8e)

### Merge timing
- ASAP once approved

### Related issues (optional)

- https://segment.atlassian.net/browse/SECFEAT-1484

2024-02-20 20:05 UTC, rexatsegment approved these changes

2024-02-20 20:20 UTC, simpixelated approved these changes

2024-02-20 21:21 UTC, forstisabella requested changes

2024-02-20 21:21 UTC, forstisabella commented on src/segment-app/iam/index.md
> +Any existing Segment user will adhere to existing password requirements and 2FA settings at the Workspace level.
```suggestion
Any existing Segment user must adhere to existing password requirements and 2FA settings set at the Workspace level.
```

2024-02-20 21:21 UTC, forstisabella commented on src/segment-app/iam/index.md
> +Segment sign ups and invitations that are re-directed to Twilio's sign up page adheres to [Twilio's minimum password requirements and 2FA](https://help.twilio.com/articles/115012261968). The intentio
```suggestion
Segment invitations and sign ups that are redirected to Twilio's sign up page must adhere to Twilio's [minimum password and 2FA requirements](https://help.twilio.com/articles/115012261968){:target="_blank”}. You can also use [Sign in With Google](https://developers.google.com/identity/gsi/web/guides/overview){:target="_blank”} to sign in to your Twilio account. To learn more, view Twilio's [Account Management](https://support.twilio.com/hc/en-us/sections/205104908-Account-Management?_gl=1*1xa50pg*_ga*OTUyMjQ4OTU5LjE2NjM2ODQzMDE.*_ga_3JKYB4GBBY*MTcwNzc2ODE1OC4xNDkuMS4xNzA3NzY4MjUzLjAuMC4w){:target="_blank”} documentation.
```

2024-02-20 23:02 UTC, JairAviles commented on src/segment-app/iam/index.md
> +Segment sign ups and invitations that are re-directed to Twilio's sign up page adheres to [Twilio's minimum password requirements and 2FA](https://help.twilio.com/articles/115012261968). The intentio
The copy on the auth0 button for signing up with Google is `Sign Up with Google`. That said, we adhere to this text and prefer not to include the overview page to prevent confusion with the end user because of this.

<img width="976" alt="Screenshot 2024-02-20 at 2 55 17 PM" src="https://github.com/segmentio/segment-docs/assets/178258/3f58ba7e-5c0b-4d3e-ad19-ff655d0733e1">

2024-02-20 23:10 UTC, forstisabella commented on src/segment-app/iam/index.md
> +Segment sign ups and invitations that are re-directed to Twilio's sign up page adheres to [Twilio's minimum password requirements and 2FA](https://help.twilio.com/articles/115012261968). The intentio
okay that makes sense! thanks

2024-02-21 01:31 UTC, cv approved these changes

2024-02-21 23:37 UTC, forstisabella approved these changes

2024-02-22 20:06 UTC, merged