Add Peaka Destination Documentation
segmentio/segment-docs pull request #6112
Opened 2024-02-22 11:57 UTC by kobalski

### Proposed changes
Documentation for Direct Destination integration for Peaka.

### Merge timing
- ASAP once approved.

2024-02-22 15:39 UTC, tcgilbert requested changes

2024-02-22 15:39 UTC, tcgilbert commented on src/connections/destinations/catalog/peaka/index.md
> +---
```suggestion
---
title: Peaka Destination
id: 651ea97b7982672f1d66b93c
beta: true
---
```

2024-02-22 15:39 UTC, tcgilbert commented on src/connections/destinations/catalog/peaka/index.md
> +[Peaka](https://peaka.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="\_blank”} is a Zero-ETL platform that connects to any source. Ingest high-volume event and streaming da
```suggestion
[Peaka](https://peaka.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank”} is a Zero-ETL platform that connects to any source. Ingest high-volume event and streaming data. Replace batch with real-time access.
```

2024-02-22 15:39 UTC, tcgilbert commented on src/connections/destinations/catalog/peaka/index.md
> +1. From your workspace's [Destination catalog page](https://app.segment.com/goto-my-workspace/destinations/catalog){:target="\_blank”} search for **Peaka**
```suggestion
1. From your workspace's [Destination catalog page](https://app.segment.com/goto-my-workspace/destinations/catalog){:target="_blank”} search for **Peaka**
```

2024-02-22 15:39 UTC, tcgilbert commented on src/connections/destinations/catalog/peaka/index.md
> +4. Go to the [Peaka](https://peaka.studio/){:target="\_blank"}, create your Segment Catalog and copy the **API key**.
```suggestion
4. Go to the [Peaka](https://peaka.studio/){:target="_blank"}, create your Segment Catalog and copy the **API key**.
```

2024-02-22 15:39 UTC, tcgilbert commented on src/connections/destinations/catalog/peaka/index.md
> +<!-- /code_chunk_output -->
Not sure where you got this? But I would remove unless you had something specific in mind

2024-02-23 06:10 UTC, kobalski commented on src/connections/destinations/catalog/peaka/index.md
> +<!-- /code_chunk_output -->
@tcgilbert This table of contents section is auto generated by a VSCode markdown extension that I use. It is not important so I deleted it. Could you check again?

2024-02-23 14:26 UTC, tcgilbert approved these changes

2024-02-26 20:02 UTC, stayseesong approved these changes

2024-02-26 20:03 UTC, merged