Connections Alerting beta [DOC-809]
segmentio/segment-docs pull request #6198
Opened 2024-03-06 20:46 UTC by forstisabella

### Proposed changes
Added docs for connections alerting beta

### Merge timing
After eng for Connections Alerting is complete (which is TBD)

### Related issues (optional)
https://segment.atlassian.net/browse/DOC-809

2024-03-07 00:38 UTC, stayseesong requested changes

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +On the Alerts tab, you can create alerts and view all active alerts for this connection. You can only edit or delete the alerts that you've created.
```suggestion
On the Alerts tab, you can create alerts and view all active alerts for this connection. You can only edit or delete the alerts that you create.
```

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +You can create an alert that notifies you when the volume of events received by your source in the last 24 hours changes beyond a percentage you set. For example, if you set a change percentage of 4%
```suggestion
You can create an alert that notifies you when the volume of events received by your source in the last 24 hours changes beyond a percentage you set. For example, if you set a change percentage of 4%, Segment notifies you when your source ingests less than 96% or more than 104% of the typical event volume. 
```

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +To receive a source volume alert in a Slack channel, you must create a Slack webhook first. For more information about Slack webhooks, see the [Sending messages using incoming webhooks](https://api.s
```suggestion
To receive a source volume alert in a Slack channel, you must first create a Slack webhook. For more information about Slack webhooks, see the [Sending messages using incoming webhooks](https://api.slack.com/messaging/webhooks){:target="_blank”} documentation.
```

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +1. Open your workspace and navigate to the [event streaming source](/docs/connections/sources/#event-streams-sources) you'd like to configure alerts for.
```suggestion
1. Navigate to the [event streams source](/docs/connections/sources/#event-streams-sources) you'd like to configure alerts for. 
```

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +1. Open your workspace and navigate to the [event streaming source](/docs/connections/sources/#event-streams-sources) you'd like to configure alerts for.
Maybe you can also add steps for how to access the event streams source such as
1. Navigate to Connections > Sources and select the Event streams tab.
2. Select the source you'd like to configure alerts for

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +4. Select one or more channels you'd like to receive alerts in.
```suggestion
4. Select one or more channels you'd like to receive alerts in. You can choose from:
```

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +To delete a source volume alert that you created, select the icon in the Actions column for the alert and click **Delete**.
do we need to include "that you created" for each of these lines? Do only the alerts you create show up, or do alerts that other users create also show up?

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +You can create an alert that notifies you when the volume of events successfully received by your destination in the last 24 hours falls below a percentage you set. For example, if you set a percenta
```suggestion
You can create an alert that notifies you when the volume of events successfully received by your destination in the last 24 hours falls below a percentage you set. For example, if you set a percentage of 99%, Segment notifies you if your destination had a successful delivery rate of 98% or below. 
```

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +To receive a successful delivery rate alert in a Slack channel, you must create a Slack webhook first. For more information about Slack webhooks, see the [Sending messages using incoming webhooks](ht
```suggestion
To receive a successful delivery rate alert in a Slack channel, you must first create a Slack webhook. For more information about Slack webhooks, see the [Sending messages using incoming webhooks](https://api.slack.com/messaging/webhooks){:target="_blank”} documentation.
```

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +1. Open your workspace and navigate to the [cloud-mode destinations](/docs/connections/destinations/#event-streams-destinations) you'd like to configure alerts for.
```suggestion
1. Navigate to the [cloud-mode destinations](/docs/connections/destinations/#event-streams-destinations) you'd like to configure alerts for. 
```

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +1. Open your workspace and navigate to the [cloud-mode destinations](/docs/connections/destinations/#event-streams-destinations) you'd like to configure alerts for.
Maybe you can also add steps for how to access the cloud-mode destinations

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +1. Open your workspace and navigate to the [cloud-mode destinations](/docs/connections/destinations/#event-streams-destinations) you'd like to configure alerts for.
is the user supposed to navigate to cloud-mode destinations? The link leads to event-streams destinations

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +4. Select one or more channels you'd like to receive alerts in.
```suggestion
4. Select one or more channels you'd like to receive alerts in. You can choose from:
```

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +To make changes to a successful delivery rate alert that you created, select the icon in the Actions column for the alert and click **Edit**.
Same comment as above: do we need to include "that you created" for each of these lines? Do only the alerts you create show up, or do alerts that other users create also show up?

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +To delete a successful delivery rate alert that you created, select the icon in the Actions column for the alert and click **Delete**.
Same comment as above: do we need to include "that you created" for each of these lines? Do only the alerts you create show up, or do alerts that other users create also show up?

2024-03-07 00:38 UTC, stayseesong commented on src/guides/how-to-guides/set-up-notifications-alerts.md
> +> info "Connections Alerting is currently in beta"
```suggestion
> info "Connections Alerting is in beta"
```

2024-03-07 00:38 UTC, stayseesong commented on src/guides/how-to-guides/set-up-notifications-alerts.md
> +> This means that the Connections Alerting feature is in active development, and some functionality may change before it becomes generally available. During the beta, Connections Alerting supports ev
```suggestion
> The Connections Alerting feature is in active development, and some functionality may change before it becomes generally available. During the beta, Connections Alerting supports event-streaming connections: [event streaming sources](/docs/connections/sources/#event-streams-sources) and [cloud-mode destinations](/docs/connections/destinations/#event-streams-destinations).
```

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +> info "Connections Alerting is currently in beta"
```suggestion
> info "Connections Alerting is in beta"
```

2024-03-07 00:38 UTC, stayseesong commented on src/connections/alerting.md
> +> This means that the Connections Alerting feature is in active development, and some functionality may change before it becomes generally available. During the beta, Connections Alerting supports ev
```suggestion
> The Connections Alerting feature is in active development, and some functionality may change before it becomes generally available. During the beta, Connections Alerting supports event-streaming connections: [event streaming sources](/docs/connections/sources/#event-streams-sources) and [cloud-mode destinations](/docs/connections/destinations/#event-streams-destinations).
```

2024-03-07 16:13 UTC, forstisabella commented on src/connections/alerting.md
> +To delete a source volume alert that you created, select the icon in the Actions column for the alert and click **Delete**.
Alerts that other users create do show up, but you can only edit/delete those that you created.

2024-03-07 17:40 UTC, stayseesong approved these changes

2024-04-09 20:28 UTC, forstisabella commented on src/connections/alerting.md
> +> The Connections Alerting feature is in active development, and some functionality may change before it becomes generally available. During the beta, Connections Alerting supports event-streaming co
```suggestion
```

2024-04-09 20:31 UTC, merged