adding changes to GA4 topics
segmentio/segment-docs pull request #6262
Opened 2024-03-21 15:33 UTC by cmastr

https://segment.atlassian.net/browse/DOC-840

2024-03-21 16:00 UTC, cmastr commented on src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
> +Google Analytics 4 advises for the use of [Recommended events](https://support.google.com/analytics/answer/9267735){:target="_blank"} and properties to power certain built-in reports. Segment’s Googl
```suggestion
Google Analytics 4 advises for the use of [Recommended events](https://support.google.com/analytics/answer/9267735){:target="_blank"} and properties to power certain built-in reports. Segment’s Google Analytics 4 Web destination provides prebuilt mappings to automatically map your Segment spec events to the corresponding Google Analytics 4 events and properties. If your Segment events don’t follow the Segment spec exactly, you can modify the mappings. or example, Segment maps `Order Completed` events to the Google Analytics 4 `Purchase` event when you add the `Purchase` action to your mappings. If your company uses `Products Purchase` to indicate a purchase, you can map it in the Purchase action’s Event Trigger instead.
```

2024-03-21 17:57 UTC, jsabor requested changes
I added several comment for changes and there are two missing links.  Any changes I suggested for consent mode do not need to be included in this update.

2024-03-21 17:57 UTC, jsabor commented on src/connections/destinations/catalog/actions-google-analytics-4-web/ga4-faq-and-troubleshooting
> +With Google Analytics 4 Web, events are sent from the browser (client-side) to GA4. If you use Segment’s [Google Analytics 4 Cloud destination](/docs/connections/destinations/catalog/actions-google-a
Edit:
```With Google Analytics 4 Web, events are sent from the browser (client-side) to GA4. If you use Segment’s [Google Analytics 4 Cloud destination](/docs/connections/destinations/catalog/actions-google-analytics-4/#benefits-of-google-analytics-4-cloud) to send events through the Measurement Protocol API and want to tie data between client-side and server-side, you need to pass the same Client ID from the browser and the server for GA4 to merge events around a distinct user.  Furthermore, if you want the server-side event to be tied to the client-side session, you must pass the session_id in the server side event.```

2024-03-21 17:57 UTC, jsabor commented on src/connections/destinations/catalog/actions-google-analytics-4-web/ga4-faq-and-troubleshooting
> +If your _ga_M12454XDR cookie is GS1.1.1710342977.347.1.1710343074.0.0.0 then 1710342977 is you session_id
Edit typo:
`If your _ga_M12454XDR cookie is GS1.1.1710342977.347.1.1710343074.0.0.0 then 1710342977 is your session_id`

2024-03-21 17:57 UTC, jsabor commented on src/connections/destinations/catalog/actions-google-analytics-4-web/ga4-faq-and-troubleshooting
> +
Remove space

2024-03-21 17:57 UTC, jsabor commented on src/connections/destinations/catalog/actions-google-analytics-4-web/ga4-faq-and-troubleshooting
> +3. Send data with an event, typically this is a page_view as your first event. Note: If you toggled “On” Page Views in your Settings, then the page_view event will automatically send when Set Configu
Add link... my notes were a placeholder

2024-03-21 17:57 UTC, jsabor commented on src/connections/destinations/catalog/actions-google-analytics-4-web/ga4-faq-and-troubleshooting
> +If you are sending multiple `gtag(‘config’)` commands called from Set Configuration mapping on one page before a new DOM has loaded, and you have defined `send_page_view: true` with each ‘Config’ eve
Typo after "events sent to your GA4 measurement id."  There are two periods.

2024-03-21 17:57 UTC, jsabor commented on src/connections/destinations/catalog/actions-google-analytics-4-web/ga4-faq-and-troubleshooting
> +By default, if the UTM values are found in the `page_location` parameter, GA4 will automatically map the campaign parameters to their appropriate value. There is no additional configuration required,
Typo, add period end of paragraph.

2024-03-21 17:57 UTC, jsabor commented on src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
> +4. Select the web source that will send data to Google Analytics 4 and follow the steps to name your destination. The web source chosen must use [Analytics.js 2.0](/docs/connections/sources/catalog/l
insert link to Segment Firebase Destination

2024-03-21 17:57 UTC, jsabor commented on src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
> +Some events automatically populate in Google Analytics. For example, there are some [Automatically Collected] (https://support.google.com/analytics/answer/9234069){:target=”_blank”} events collected
Edit using markdown to highlight, do not add ticks to final:
`Some events automatically populate in Google Analytics. For example, there are some [Automatically Collected] (https://support.google.com/analytics/answer/9234069){:target=”_blank”} events collected by triggering the Set Configuration Mapping. Additionally, calling gtag(‘config’), and enabling [Enhanced Measurement events](https://support.google.com/analytics/answer/9216061){:target=”_blank”}, which are controlled by toggling “on” in your GA4 Admin panel, will use event listeners to send events; moreover, all events tracked via GA4 Web, populate some commonly used parameters like page_location without additional configuration. Review Google’s documents for more information found [here](https://support.google.com/analytics/table/13594742){:target=”_blank”}`

2024-03-21 17:57 UTC, jsabor commented on src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
> +3. Click the toggle on for **Enable Consent Mode**, this calls gtag(‘consent’,’default’) with the defined parameters when the gtag library loads.
I added a note not to modify this section.  I'm not confident in my knowledge of what changes were made; therefore, remove any edits from Consent Mode section.

2024-03-21 17:57 UTC, jsabor commented on src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
> +4. Set the following fields with your organization’s determination of granted or denied:
Remove change

2024-03-21 17:57 UTC, jsabor commented on src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
> +    Ad Personalization Consent State | Granted or Denied
Remove changes on 92-95

2024-03-21 17:57 UTC, jsabor commented on src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
> +7. As soon as the page loads and the set configuration fires to the Google Analytics SDK, Segment issues a consent mode update command. Map the properties you defined to collect consent state changes
Remove

2024-03-21 17:57 UTC, jsabor commented on src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
> +        5. *(Option 2)* Under the **Select mappings** section, create an event variable to directly grab the value from the payload. For example, `properties.adStorageConsentState`. Ensure it transla
remove

2024-03-21 17:57 UTC, jsabor commented on src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
> +When these properties are available, they send to the `update` command.
remove

2024-03-22 19:01 UTC, forstisabella requested changes
A couple of changes and I think we'll be good to go. If you have any questions about my suggestions, let me know! @rvadera12

2024-03-25 22:42 UTC, rvadera12 commented on src/connections/destinations/catalog/actions-google-analytics-4-web/ga4-faq-and-troubleshooting
> +All in all, the Set Configuration Mapping is a crucial part of your GA4 Web setup. It provides the “handshake” between your site and the gtag library. If no events are not sending to your GA4 instanc
Both - you can use the google debugging tools or our event delivery

2024-03-25 23:24 UTC, forstisabella approved these changes

2024-03-26 00:05 UTC, forstisabella commented on src/connections/destinations/catalog/actions-google-analytics-4-web/ga4-faq-and-troubleshooting
> +If you are sending multiple `gtag(‘config’)` commands called from Set Configuration mapping on one page before a new DOM has loaded, and you have defined `send_page_view: true` with each ‘Config’ eve
```suggestion
If you are sending multiple `gtag(‘config’)` commands called from Set Configuration mapping on one page before a new DOM has loaded, and you have defined `send_page_view: true` with each ‘Config’ event, you may see duplicate `page_view` events sent to your GA4 measurement id. If this is the case, please refer to Google's documentation on [Ignoring duplicate instances of on-page configuration](https://support.google.com/analytics/answer/9973999?hl=en#:~:text=as%20described%20below.-,Ignore%20duplicate%20instances%20of%20on%2Dpage%20configuration,Click%20Save.,-Give%20feedback%20about){:target="_blank"}. 
```

2024-03-26 17:10 UTC, merged