create docs
segmentio/segment-docs pull request #6314
Opened 2024-03-28 23:09 UTC by Romani-Ramzi

### Proposed changes

### Merge timing

### Related issues (optional)

2024-04-01 21:31 UTC, forstisabella requested changes

2024-04-01 21:31 UTC, forstisabella commented on src/connections/destinations/catalog/actions-optimizely-data-platform/index.md
> +8. Toggle the **Status** to **Enabled** for the custom event you created.
The note messes with the markdown lists - this should fix the numbering issue. 

```suggestion
In Twilio Segment, on the **Mappings** tab of the Optimizely Data Platform destination, Segment displays a list of pre-built mappings that you can enable or disable. For example, if you enabled the **Email Opened** mapping, each email opened event Segment ingested after you enabled the mapping would sync to ODP.

If you want to map an event that is not listed:
1. Click **New Mapping > Custom Event**.
2. _(Optional)_: Enter a descriptive name for the event.
3. Select the event that you want to send to ODP.
4. Click **Load Test Event from Source**. This generates the raw data for the selected event and populates your mappings. The ID and timestamp field mappings auto-populate, but you can edit them as desired.
5. Select the event type and, optionally, the event action. For example, if you are configuring a custom event to track button clicks, select _button_ for the event type and _click_ for the event action.

> info "Required fields"
> In ODP, each event requires an ID, timestamp, and event type. The event action is optional. See ODP's [Events](https://docs.developers.optimizely.com/optimizely-data-platform/docs/thebasics-events) documentation for more details.

<ol style="counter-reset: none;">
  <li value="6" markdown=1>
  _(Optional)_: To ensure the custom event is configured correctly, click **Send test event to destination**.
  </li>
  <li value="7" markdown=1>
  Click **Save**.
  </li>
  <li value="8" markdown=1>
  Toggle your custom event's status to **Enabled**.
  </li>
</ol>	
```

2024-04-02 15:36 UTC, forstisabella approved these changes

2024-04-02 15:43 UTC, tcgilbert requested changes
just two changes for me. lmk if you have any questions!

2024-04-02 15:43 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-optimizely-data-platform/index.md
> +
```suggestion

{% include components/actions-fields.html %}
```

This snippet will populate the available action on the docs page^

2024-04-02 15:43 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-optimizely-data-platform/index.md
> +After you set up your Optimizely Data Platform destination, Segment syncs your customer data to ODP in near real-time.
```suggestion
After you set up your Optimizely Data Platform destination, Segment syncs your customer data to ODP in near real-time.

This destination is maintained by Optimizely. For any issues with the destination, [contact their Support team](mailto:support@<integration_name>.com).
```

2024-04-02 18:03 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/actions-optimizely-data-platform/index.md
> +After you set up your Optimizely Data Platform destination, Segment syncs your customer data to ODP in near real-time.
the mailto should be optimizely or segment?

2024-04-02 18:04 UTC, forstisabella commented on src/connections/destinations/catalog/actions-optimizely-data-platform/index.md
> +After you set up your Optimizely Data Platform destination, Segment syncs your customer data to ODP in near real-time.
It should be Optimizely, if you all are owning it!

2024-04-02 18:05 UTC, Romani-Ramzi commented
> just two changes for me. lmk if you have any questions!

currently we would like to go with your suggestions, as you have more experience on what customers understand when reading through segment docs.

but our doc team will have to go through that as well, and raise what they think is good, hopefully they like your suggestions :).

2024-04-02 18:07 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/actions-optimizely-data-platform/index.md
> +After you set up your Optimizely Data Platform destination, Segment syncs your customer data to ODP in near real-time.
got it, I will update now

2024-04-02 18:54 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-optimizely-data-platform/index.md
> +After you set up your Optimizely Data Platform destination, Segment syncs your customer data to ODP in near real-time.
Customers are usually well versed enough to differentiate where to send their support queries. If something is wrong within the Segment UI they will almost always reach out to us. 

Additionally, our support team is always available to assist in customer queries if insight is needed from the Segment side of things. You can always reach out to partner-support@segment.com for help

2024-04-02 18:57 UTC, Romani-Ramzi commented on src/connections/destinations/catalog/actions-optimizely-data-platform/index.md
> +After you set up your Optimizely Data Platform destination, Segment syncs your customer data to ODP in near real-time.
perfect, we updated the required part, please check

2024-04-05 12:32 UTC, joe-ayoub-segment commented
hi @forstisabella - Romani and Alex are keen to get this doc pushed live. We're going to move the Integration to Public Beta today. Does anything else need to be changed in this PR before it can go live?

2024-04-05 15:41 UTC, forstisabella commented
no worries, @Romani-Ramzi! I'm going to go ahead and merge this. Thanks for your collaboration on this! :)

2024-04-05 15:42 UTC, merged

2024-04-05 15:49 UTC, Romani-Ramzi commented
Thanks alot @forstisabella, its was a pleasure going through all this with you and the team. :D