Add Moloco MCM destination beta doc
segmentio/segment-docs pull request #6399
Opened 2024-04-17 00:53 UTC by samir-moloco

### Proposed changes
Adds the documentation for our platform's Segment Destination (Moloco MCM).

### Merge timing
- ASAP once approved

2024-04-17 16:56 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/images/mcm-destination-monitoring.png
Hi @samir-moloco - we avoid screenshots in our documentation when possible, as they're hard to maintain, add to site load time, and are not accessible for those that use assistive technologies. Are you able to remove the screenshot if we link to Delivery Overview documentation in the Monitoring section?

2024-04-17 16:57 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/images/mcm-mappings.png
Hi @samir-moloco - same with this screenshot. Can we link to the Actions destinations documentation here instead of including a screenshot?

2024-04-17 16:57 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/images/page-identifier-token-example.png
Hi @samir-moloco - are we able to convert this to text? This is important information and I want to make sure folks using assistive technologies are able to access this information too!

2024-04-19 15:09 UTC, samir-moloco commented on src/connections/destinations/catalog/moloco-rmp/images/mcm-mappings.png
Hi @forstisabella not sure what link you are talking about in the Actions destinations doc, is it also a different doc I should prepare?

2024-04-19 15:14 UTC, samir-moloco commented on src/connections/destinations/catalog/moloco-rmp/images/mcm-destination-monitoring.png
Removed the screenshots and added a link to the delivery overview

2024-04-19 15:14 UTC, samir-moloco commented on src/connections/destinations/catalog/moloco-rmp/images/page-identifier-token-example.png
Removed the screenshot and replaced by text :)

2024-04-19 18:29 UTC, forstisabella requested changes
Thank you for finding alternatives to your screenshots! 

If you have any questions or comments about my review, please feel free to tag me in a comment!

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +For more details about the monitoring tool, take a look at the [Delivery Overview](https://segment.com/docs/connections/delivery-overview/) docs.
```suggestion
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +Once the mappings are configured correctly, you can verify the flow of events from your source to Moloco’s destination in the “**Delivery Overview**” tab. If things are configured correctly, it shoul
```suggestion
Once the mappings are configured correctly, you can verify the flow of events from your source to Moloco’s destination in the [Delivery Overview](/docs/connections/delivery-overview/) tab of your Moloco destination. If you correctly configured your destination, you should see a growing **Successful delivery** count.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +If you are using **the default fields in a custom way**, please confirm that your mapping meets Moloco's requirements.
I might need more context on this: what would using the default fields in a custom way look like? Where could a user read more about Moloco's requirements?

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +In the mappings tab, some fields are chosen by default if some common fields map to Moloco Event’s fields. If the mapped key does not exist in the input data, it won’t trigger an error and will just
```suggestion
In the Mappings tab, some fields are chosen by default if some common fields map to Moloco Event’s fields. If the mapped key does not exist in the input data, it won’t trigger an error. Instead, the mapping will not pass any value.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +_Note_: if you decided to use the **Page Identifier Token** in your mobile app, please make sure you reuse the same **Page Identifier Token** in place of page_id when calling other Moloco’s APIs like
```suggestion
> info " "
> if you decide to use the Page Identifier Token in your mobile app, reuse the same Page Identifier Token in place of page_id when calling Moloco’s APIs.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +```
```suggestion
The tokens are stringified in the format of the above example because they are key-value pairs concatenated by a semicolon (;). 
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +The tokens be stringified into:
```suggestion
The tokens are stringified into the following:
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +Here’s an example of **Page Identifier Token** that could be tracked in a mobile app.
```suggestion
Here’s an example of a Page Identifier Token that could be tracked in a mobile app.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +As page_id has a higher priority, **Page Identifier Token** will be ignored if page_id is passed
```suggestion
Moloco Commercial Media ignores the Page Identifier Token if page_id is passed, as page_id has a higher priority.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +This field accepts key:value pairs of strings that can identify the page.
```suggestion
The Page Identifier Token field accepts key:value pairs of strings that can identify the page.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +In Moloco Commercial Media, the [page_id](https://mcm-docs.moloco.com/docs/51-user-event-data-specifications#page_view-event-type) attribute is required for the PAGE_VIEW event. Using the Web SDK, th
```suggestion
Moloco Commercial Media requires the [page_id](https://mcm-docs.moloco.com/docs/51-user-event-data-specifications#page_view-event-type){:target="_blank”} attribute for a PAGE_VIEW event. Using the Web SDK, the page_id can be associated with the path attribute. However for iOS/Android, Moloco Commercial Media recommends using the Page Identifier Token field.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +However for iOS and Android, it won’t collect page information.
Is this sentence referring to mobile browsers, or for mobile app screen views?

```suggestion
Mobile app users should use the [Screen](/docs/connections/spec/screen/) call to collect information about mobile screen views, which are the equivalent of browser "page" views.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +If you are using the Segment’s Web SDK, this call will automatically collect the page information. Here’s an example of page info automatically collected using the Segment’s Web SDK.
```suggestion
If you use Segment’s Web SDK, this call automatically collects the page information. Here’s an example of page information automatically collected using Segment’s Web SDK.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +```
```suggestion
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +If you’re not familiar with the Segment Specs, take a look to understand what the [Page method](https://segment.com/docs/connections/spec/page/) does.
```suggestion
If you’re not familiar with the Segment Spec, take a look to understand what the [Page method](/docs/connections/spec/page/) does. 
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +  image_url: "https://www.example.com/iamge.png"
```suggestion
  image_url: "https://www.example.com/image.png"
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +Please find below an example call to track a product detail page (PDP) view event:
```suggestion
If you’re not familiar with the Segment Spec, take a look to understand what the [Track method](/docs/connections/spec/track/) does. The mappings in the Moloco Commerce Media destination are built based on the Segment [Ecommerce Spec](/docs/connections/spec/ecommerce/v2/). 

Please find below an example call to track a product detail page (PDP) view event:
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +</table>
```suggestion
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +## Moloco Commerce Media’s available presets
Hi @samir-moloco - this content will be automatically generated from the information you provided to the actions-destination folks when your destination enters public beta, so there's no need to include this here! Here's an example of what it will look like ([Braze Cloud Mode (Actions) - Available Presets](https://segment.com/docs/connections/destinations/catalog/braze-cloud-mode-actions/#available-presets))

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +beta: true
```suggestion
id: 65f05e455b125cddd886b793
beta: true
private: true
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +[Moloco Commerce Media](https://www.moloco.com/products/moloco-retail-media-platform) (MCM) is a technology solution that empowers marketplaces and online retailers to build and scale a retail media
```suggestion
[Moloco Commerce Media](https://www.moloco.com/products/moloco-retail-media-platform){:target="_blank”} (MCM) is a technology solution that empowers marketplaces and online retailers to build and scale a retail media business (for example, sponsored ads). Moloco’s solution helps platforms leverage and activate their first-party data to deliver highly relevant and performant ads, automate ad decision-making, and scale their ads business.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +This Moloco Commerce Media destination can send user events collected using the Segment SDK to Moloco’s platform for simplified performance ads integration.
```suggestion
The Moloco Commerce Media destination can send user events collected using the Segment SDK to Moloco’s platform for a simplified performance ads integration.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +4. In the Moloco MCM destination settings page, fill the Platform ID and API key fields with the previously collected information and select “APP or SITE” depending on your source endpoint (mobile or
```suggestion
## Getting started

### Prerequisites 
Before you configure the Moloco Commerce Media destination, add a source to Segment and use the [Source Debugger](/docs/connections/sources/debugger/) to verify Segment is receiving events. 

Before you configure the Moloco Commerce Media destination, reach out to your Moloco representative about the following account information: 
- Moloco Platform ID
- Moloco Event Service API key

After you obtain that account information, you can move on to the Segment app.

### Set up your Moloco destination
1. From the Segment web console, click **Catalog**.
2. On the Catalog page, search for “Moloco”, select it, and click **Add destination**.
3. Choose which of your sources to connect the destination to.
4. In the Moloco MCM destination settings page, fill the Platform ID and API key fields with your Moloco Platform ID and Event Service API key. 
5. Select “APP" if your source endpoint is a mobile app, and "SITE" if it is a website.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +Once a user is identified, each call to the [Track method](https://segment.com/docs/connections/spec/track/) will automatically record the user ID.
```suggestion
Once a user is identified, each call to Segment's [Track method](/docs/connections/spec/track/) automatically records the user ID.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +Please find below an example call to identify:
```suggestion
Please find an example Identify call below:
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +We strongly recommend that you identify your logged-in users using the [Identify method provided by Segment](https://segment.com/docs/connections/spec/identify/). We also recommended hashing the user
```suggestion
Moloco strongly recommends that you identify your logged-in users using Segment's [Identify method](/docs/connections/spec/identify/) and that you hash the user ID before sending it to Moloco.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +_Note_: if you decided to hash the user ID before sending it to Moloco for event tracking, please make sure you reuse the same hashed ID when calling other Moloco’s APIs like Decision API.
```suggestion
> info" "
> If you hash the user ID before sending it to Moloco, ensure you reuse the same hashed ID when calling other Moloco APIs.
```

2024-04-19 18:29 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +For non logged-in users, you can still track them using an [anonymous ID](https://segment.com/docs/connections/spec/identify/#anonymous-id) (something like UUID as recommended by Segment) but on the
Hi @samir-moloco - if MCM doesn't use an anonymousID, what would that look like for the user data that contains an anonymousID? Is it not accepted by MCM, but could be accepted by other destinations?

```suggestion
Users that are not logged in can be tracked using an [anonymousID](/docs/connections/spec/identify/#anonymous-id). Moloco Commerce Media does not use anonymousIDs for users that are not logged in. Segment recommends formatting your anonymousID in UUID format.
```

2024-04-22 15:45 UTC, forstisabella commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +> info" "
```suggestion
> info " "
```

2024-04-22 21:03 UTC, tcgilbert requested changes
Two things: 

1. add the requested snippet (this will autopopulate details about each action and it's field in your docs
2. you need to rename the folder name from `moloco-rmp` to `actions-moloco-rmp` as the slug of your integration is used to autogenerate links out to your docs from other parts of our application

2024-04-22 21:03 UTC, tcgilbert commented on src/connections/destinations/catalog/moloco-rmp/index.md
> +
```suggestion

{% include components/actions-fields.html %}
```

2024-04-25 16:34 UTC, samir-moloco commented
> Two things:
> 
> 1. add the requested snippet (this will autopopulate details about each action and it's field in your docs
> 2. you need to rename the folder name from `moloco-rmp` to `actions-moloco-rmp` as the slug of your integration is used to autogenerate links out to your docs from other parts of our application

2024-04-25 16:58 UTC, merged

2024-04-29 23:43 UTC, samir-moloco commented
Hi team, I could find the doc to this URL (https://segment.com/docs/connections/destinations/catalog/actions-moloco-rmp/) but it is not indexed and listed in https://segment.com/docs/connections/destinations/catalog
How can we make sure it's listed in the list of destination and categorised under advertising?

2024-04-30 00:37 UTC, forstisabella commented
Hi @samir-moloco: the `private: true` attribute in the frontmatter of this document makes it only accessible by direct link and keeps the page from being indexed + listed in autogenerated content on segment.com/docs, like the destinations catalog you linked! When the Moloco RMP integration enters public beta we will remove that attribute and it will populate into our autogenerated content.

@tcgilbert - is there a way to tell which categories this destination will populate into? I can't see anything in PAPI!

2024-04-30 12:25 UTC, tcgilbert commented
@samir-moloco can you send me your email address? 

Essentially, the last step you need to complete to get your destination live is to add the integrations catalog metadata in our developer portal. This is where you will select categories, add logos, etc. Once done, and your integration is in public beta, the docs will populate correctly.

2024-04-30 13:32 UTC, samir-moloco commented
> @samir-moloco can you send me your email address?
> 
> Essentially, the last step you need to complete to get your destination live is to add the integrations catalog metadata in our developer portal. This is where you will select categories, add logos, etc. Once done, and your integration is in public beta, the docs will populate correctly.

@tcgilbert my email address is samirh@moloco.com
Not sure if I have access to that developer portal. Maybe should I sync with the eng team that built the Moloco destination on Segment?

2024-04-30 13:52 UTC, tcgilbert commented
I just sent a developer portal invitation to your email address, as well as heonjang.lee@moloco.com. Once accepted, you should be able to access the developer portal here: https://app.segment.com/dev-portal/overview. 

Please ensure you're logged into a Segment account associated with the same email address to which the invitation was sent (You may have to create your segment account). In case you use a Segment account tied to a different email address, just let me know, and I'll send an invitation to the correct address.

2024-04-30 14:30 UTC, samir-moloco commented
> @samir-moloco I just sent a developer portal invitation to your email address, as well as [heonjang.lee@moloco.com](mailto:heonjang.lee@moloco.com). Once accepted, you should be able to access the developer portal here: https://app.segment.com/dev-portal/overview.
> 
> Please ensure you're logged into a Segment account associated with the same email address to which the invitation was sent (You may have to create your segment account). In case you use a Segment account tied to a different email address, just let me know, and I'll send an invitation to the correct address.

Thanks got the invite but I noticed I previously used samir.hammoudi@moloco.com for my Segment account so would appreciate if you resend an invite to this email address instead, thank you!!
Will work on the dev portal to get what's needed to get to public beta ;)

2024-05-15 23:44 UTC, samir-moloco commented
Hi @tcgilbert we did all the required steps on the developer portal and submitted for review to move to public beta. Hopefully this get approved soon. Thanks again for your review on this doc!

2024-05-16 13:59 UTC, tcgilbert commented
hey @samir-moloco - great! looks like we have everything needed on our end to move your destiantion into public beta. 

Have you completed testing the Integration, and are confident it behaves as expected? If so, I'll go ahead and make the destination live.

Also just sent another dev portal invite to samir.hammoudi@moloco.com

2024-05-17 00:20 UTC, samir-moloco commented
Hi @tcgilbert excellent! yes I have tested the integration and it works great! thanks in advance to making it public beta!!

2024-05-17 16:46 UTC, tcgilbert commented
@samir-moloco 

I have gone ahead and made your integration live. Twilio Segment is excited to move your new integration into the Public Catalog! The mappings on your docs page will populate once our docs site rebuilds on Tuesday. 
 
To move out of beta, you can write back into partner-support@segment.com once you have at least one customer using the integration, and you are confident that the beta status is no longer applicable.
 
If you have any questions or concerns, please let me know

2024-05-22 01:26 UTC, samir-moloco commented
@tcgilbert Thank you for promoting our destination to Public Beta!
I waited Tuesday for the docs site to rebuild but it seems like we have a broken link.

I go under https://segment.com/docs/connections/destinations/catalog/#advertising and click on the Moloco MCM destination. I get a 404 instead of getting to https://segment.com/docs/connections/destinations/catalog/actions-moloco-rmp/

Let me know if we miss some configuration or if we should wait for something to rebuild on your side. Thanks!

2024-05-22 16:06 UTC, tcgilbert commented
hey @samir-moloco - thanks for flagging! 

[I just put in a patch for this](https://github.com/segmentio/segment-docs/pull/6586). This will be fixed when the site rebuilds tomorrow afternoon. 

If there is anything else I can assist with let me know

2024-05-24 00:54 UTC, samir-moloco commented
Confirmed it's now fixed, thank you @tcgilbert !