Wisepops - Documentation for the new goal tracking
segmentio/segment-docs pull request #6401
Opened 2024-04-17 10:06 UTC by boris-hocde

### Proposed changes

Wisepops is introducing a new way of [tracking goals](https://support.wisepops.com/article/mx3z8na6yb-set-up-goal-tracking). See [the action-destination PR](https://github.com/segmentio/action-destinations/pull/1998). We're updating the doc to reflect these changes.

### Merge timing
Depending on a specific project: If possible, when [the action-destination PR](https://github.com/segmentio/action-destinations/pull/1998) is merged

2024-04-17 16:03 UTC, forstisabella requested changes
a few small changes and we'll be good to go!

2024-04-17 16:03 UTC, forstisabella commented on src/connections/destinations/catalog/actions-wisepops/images/wisepops-goal-mapping.png
Hi @boris-hocde - I think we can replace "appropriate field" and the screenshot with just the "Goal Name" field!

2024-04-17 16:03 UTC, forstisabella commented on src/connections/destinations/catalog/actions-wisepops/index.md
> +To track a JavaScript goal through Segment:
```suggestion
The Track Goal action is not mapped by default. You can enable it to track [goal completion and revenue](https://support.wisepops.com/article/mx3z8na6yb-set-up-goal-tracking){:target='_blank'} on Wisepops.

To track a JavaScript goal through Segment:
```

2024-04-17 16:03 UTC, forstisabella commented on src/connections/destinations/catalog/actions-wisepops/index.md
> +3. In Segment, create a new mapping, with the action "Track Goal".
```suggestion
3. In Segment, create a new mapping with the action "Track Goal".
```

2024-04-17 16:03 UTC, forstisabella commented on src/connections/destinations/catalog/actions-wisepops/index.md
> +5. In the third section, paste the goal identifier in the appropriate field:
```suggestion
5. In the third section, paste the goal identifier in the Goal Name field:
```

2024-04-17 16:03 UTC, forstisabella commented on src/connections/destinations/catalog/actions-wisepops/index.md
> +   ![Wisepops goal mapping](images/wisepops-goal-mapping.png)
```suggestion
```

2024-04-18 09:12 UTC, boris-hocde commented on src/connections/destinations/catalog/actions-wisepops/images/wisepops-goal-mapping.png
@forstisabella Thanks for spotting this. This field name is actually changed to "Goal Identifier". I'm updating the text and screenshot. I think that the screenshot is still valuable, as it shows that the `"` shouldn't be included. And that it can be pasted as is, without using a Segment event variable. What do you think?

2024-04-19 18:35 UTC, forstisabella commented on src/connections/destinations/catalog/actions-wisepops/index.md
> +5. In the third section, paste the goal identifier in the **Goal Identifier** field:
```suggestion
5. In the third section, paste the goal identifier, without quotes, into the **Goal Identifier** field:
```

2024-04-19 18:36 UTC, forstisabella commented on src/connections/destinations/catalog/actions-wisepops/index.md
> +To track a JavaScript goal through Segment:
```suggestion
To track a JavaScript goal using Segment:
```

2024-04-19 18:36 UTC, forstisabella commented on src/connections/destinations/catalog/actions-wisepops/images/wisepops-goal-mapping.png
Hi @boris-hocde - I would still recommend replacing the screenshot with written text. None of the technical writers on the team have access to Wisepops, so if the UI or format of the identifier were to change, we'd have no way of updating this content. 

Would the comment that I proposed adequately cover that you can copy the identifier, without the double quotes, into Segment?

Thanks!

2024-04-22 13:49 UTC, boris-hocde commented on src/connections/destinations/catalog/actions-wisepops/images/wisepops-goal-mapping.png
Ok for me. I took this occasion to update the existing screenshots.

2024-04-22 13:53 UTC, boris-hocde commented on src/connections/destinations/catalog/actions-wisepops/images/wisepops-goal-mapping.png
@forstisabella Ready for new review :bow:

2024-04-22 15:30 UTC, forstisabella approved these changes

2024-04-22 15:30 UTC, forstisabella commented
This looks beautiful - thank you so much for all the work you did on this!!!

2024-04-22 15:30 UTC, merged