Add events.win destination docs
segmentio/segment-docs pull request #6485
Opened 2024-05-02 03:04 UTC by megancooper

### Proposed changes
* Adds documentation for the **events.win** destination

### Merge timing
ASAP once approved

2024-05-03 18:21 UTC, tcgilbert requested changes
Just need to make the requested change, as well as change the folder name from `events.win` to `events-win`

2024-05-03 18:21 UTC, tcgilbert commented on src/connections/destinations/catalog/events.win/index.md
> +---
```suggestion
---
title: events.win Destination
beta: true
id: 662d3328d029f89724a0c294
---
```

2024-05-03 23:49 UTC, megancooper commented
@tcgilbert Thank you! The folder name has been updated 🙏🏾

2024-05-06 13:53 UTC, tcgilbert approved these changes

2024-05-06 16:36 UTC, forstisabella approved these changes
a few small changes and we'll be ready to ship this 🚀

2024-05-06 16:36 UTC, forstisabella commented on src/connections/destinations/catalog/events-win/index.md
> +6. That's it! events.win will start to receive data from Segment, there may be a delay before data is visible in the events.win dashboard.
hi @megancooper - do you have a feel for how long the maximum delay would be? 

```suggestion
1. From your workspace's [Destination catalog page](https://app.segment.com/goto-my-workspace/destinations/catalog){:target="\_blank”} search for "events.win".
2. Select events.win and click **Add Destination**.
3. Select an existing Source to connect to events.win.
4. Go to the [events.win dashboard](https://app.events.win/developers){:target="\_blank"}, find and copy the **Developer key**.
5. Return to Segment and enter the **Developer Key** in the events.win destination settings.
6. events.win starts to receive data from Segment. There may be a delay before data is visible in the events.win dashboard.
```

2024-05-06 16:36 UTC, forstisabella commented on src/connections/destinations/catalog/events-win/index.md
> +[Track](/docs/connections/spec/track) calls are consumed and validated against the tracking plan you've defined in events.win. We don't store the data, but we do provide a detailed report on how corr
```suggestion
events.win consumes and validates [Track](/docs/connections/spec/track) calls against the tracking plan you've previously defined in events.win. events.win doesn't store the data, but instead provides a detailed report on how correct your data is.
```

2024-05-06 16:36 UTC, forstisabella commented on src/connections/destinations/catalog/events-win/index.md
> +events.win supports the following methods, as specified in the [Segment Spec](/docs/connections/spec).
```suggestion
events.win supports Segment's [Track](/docs/connections/spec/track) method, as specified in the [Segment Spec](/docs/connections/spec).
```

2024-05-06 16:36 UTC, forstisabella commented on src/connections/destinations/catalog/events-win/index.md
> +You can use the [@events.win/cli](https://www.npmjs.com/package/@events.win/cli) to generate type-safe tracking code for your events.
```suggestion
You can use the [@events.win/cli](https://www.npmjs.com/package/@events.win/cli){:target="\_blank”} to generate type-safe tracking code for your events.
```

2024-05-07 03:39 UTC, megancooper commented on src/connections/destinations/catalog/events-win/index.md
> +6. That's it! events.win will start to receive data from Segment, there may be a delay before data is visible in the events.win dashboard.
The delay at most would be a few minutes. I can add that detail in

2024-05-07 16:36 UTC, merged