schematic documentation
segmentio/segment-docs pull request #6525
Opened 2024-05-09 22:40 UTC by jasdeepg

### Proposed changes

### Merge timing

### Related issues (optional)

2024-05-10 18:15 UTC, forstisabella commented on src/connections/destinations/catalog/schematic/index.md
hi @jasdeepg - please update the file folder to match the slug that this integration has in the app: `actions-schematic`.

2024-05-10 19:31 UTC, jasdeepg commented on src/connections/destinations/catalog/schematic/index.md
just did both - thanks!

2024-05-10 20:18 UTC, forstisabella requested changes

2024-05-10 20:18 UTC, forstisabella commented on src/connections/destinations/catalog/actions-schematic/index.md
> +---
hi @jasdeepg - the beta/hidden attributes denote that this integration is in private beta and the ID autogenerates some of the actions content when this integration enters public beta. 
```suggestion
---
title: Schematic (Actions) Destination
hidden: true
beta: true
id: 65b8e9eca1b5903a031c6378
---
```

2024-05-10 20:18 UTC, forstisabella commented on src/connections/destinations/catalog/actions-schematic/index.md
> +2. Search for *Schematic* and select **Add Destination**
```suggestion
2. Search for *Schematic*, select the Schematic destination, and click **Add destination**.
```

2024-05-10 20:18 UTC, forstisabella commented on src/connections/destinations/catalog/actions-schematic/index.md
> +3. Select the source that will send data to Schematic and follow the steps to name your destination. The web source chosen must use [Analytics.js 2.0](https://segment.com/docs/connections/sources/cat
As of March 2023, [Segment upgraded all sources to Analytics.js 2.0](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/), so I'll remove that sentence (and update the template!)

```suggestion
3. Select the source that will send data to Schematic, give your destination a name, then click **Create destination**.
```

2024-05-10 20:18 UTC, forstisabella commented on src/connections/destinations/catalog/actions-schematic/index.md
> +4. On the Settings tab, input your API Key which can be found in your Schematic workspace settings under **Settings > API Keys**.
```suggestion
4. On the destination's Settings tab, input your Schematic API Key. To generate an API key, navigate to your Schematic workspace settings under **Settings > API Keys**.
```

2024-05-10 20:18 UTC, forstisabella commented on src/connections/destinations/catalog/actions-schematic/index.md
> +5. Once connected, you can configure how you want to send data to Schematic in the **Mappings** tab.
```suggestion

Once you've connected Schematic to Segment, you can configure how you want to send data to Schematic in the Schematic destination's **Mappings** tab.
```

2024-05-10 20:18 UTC, forstisabella commented on src/connections/destinations/catalog/actions-schematic/index.md
> +For track events, Schematic only accepts event names that contain alphanumeric characters, dashes, and underscores. If Segment event names have, for instance, spaces, the Schematic destination will a
```suggestion
Schematic only accepts Track event names that contain alphanumeric characters, dashes, and underscores. If Segment event names have other characters, like spaces, the Schematic destination automatically snake_cases the event name before passing to Schematic. Segment passes the raw event name as an event trait.
```

2024-05-10 21:16 UTC, jasdeepg commented on src/connections/destinations/catalog/actions-schematic/index.md
> +---
hi @forstisabella ! 1 customer has tested this integration successfully. would be great if we could have this in public beta / GA if possible.

2024-05-13 13:08 UTC, tcgilbert requested changes

2024-05-13 13:08 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-schematic/index.md
> +---
@jasdeepg I see you have submitted all the needed materials to go live as well. With that in mind, I removed the hidden property. You will still need to add th beta and id props

2024-05-14 12:28 UTC, jasdeepg commented
hi - i believe all changes are in, but let me know if i missed anything.

2024-05-14 14:06 UTC, tcgilbert approved these changes

2024-05-14 15:01 UTC, forstisabella approved these changes

2024-05-14 15:01 UTC, merged

2024-05-14 17:15 UTC, tcgilbert commented
@jasdeepg 
 
I have gone ahead and made your integration live. Twilio Segment is excited to move your new integration into the Public Catalog! 
 
To move out of beta, you can write back into partner-support@segment.com once you have at least one customer using the integration, and you are confident that the beta status is no longer applicable.
 
If you have any questions or concerns, please let me know.