Add Xtremepush (Actions) Destination docs.
segmentio/segment-docs pull request #6528
Opened 2024-05-10 13:09 UTC by vii07

### Proposed changes
Add the new docs page for Xtremepush (Actions) Destination.

### Merge timing
ASAP once approved.

2024-05-10 18:02 UTC, forstisabella requested changes

2024-05-10 18:02 UTC, forstisabella commented on src/connections/destinations/catalog/actions-xtremepush/index.md
> +If a trait does not match a custom Xtremepush User Profile Attribute and is not recognized as a User Identifier it will be ignored.
```suggestion
If a trait does not match a custom Xtremepush User Profile Attribute and is not recognized as a User Identifier, Xtremepush ignores the trait.
```

2024-05-10 18:02 UTC, forstisabella commented on src/connections/destinations/catalog/actions-xtremepush/index.md
> +Track calls will be sent to Xtremepush as a `event hits`, so you can use it to [trigger a campaign](https://docs.xtremepush.com/docs/campaign-events){:target="_blank"} for a user.
```suggestion
Track calls are sent to Xtremepush as a `event hits` and you can use them to [trigger a campaign](https://docs.xtremepush.com/docs/campaign-events){:target="_blank"} for a user.
```

2024-05-10 18:02 UTC, forstisabella commented on src/connections/destinations/catalog/actions-xtremepush/index.md
> +To enable Xtremepush push and in-app notifications you will also need to to install the relevant Xtremepush SDKs.
```suggestion
To enable Xtremepush push and in-app notifications you must also install the relevant Xtremepush SDKs.
```

2024-05-13 08:15 UTC, vii07 commented on src/connections/destinations/catalog/actions-xtremepush/index.md
> +---
@forstisabella Thanks for your suggestions and I'll apply all of them soon. But a note for this one is that we want to make our new Xtremepush (Actions) Destination public beta after merging this doc, so I will pass `hidden: false` instead.

2024-05-13 13:04 UTC, tcgilbert approved these changes
lgtm

2024-05-13 15:31 UTC, forstisabella approved these changes

2024-05-13 15:31 UTC, forstisabella commented on src/connections/destinations/catalog/actions-xtremepush/index.md
> +hidden: false
```suggestion
```

2024-05-13 15:32 UTC, forstisabella commented on src/connections/destinations/catalog/actions-xtremepush/index.md
> +hidden: false
we can remove this attribute if hidden is not set to true, as it's not hidden by default!

2024-05-14 15:01 UTC, merged