Add Survicate (Actions) Destination README
segmentio/segment-docs pull request #6532
Opened 2024-05-13 10:07 UTC by cieniawska

This PR adds Survicate Action Destination README

2024-05-29 19:21 UTC, cmastr commented on src/connections/destinations/catalog/actions-survicate/index.md
> +id: 5c922eae1761cd0001a71707
@tcgilbert  can you help here?

2024-05-29 20:42 UTC, tcgilbert requested changes

2024-05-29 20:42 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-survicate/index.md
> +---
```suggestion
---
rewrite: true
title: Survicate (Actions) Destination
id: 65a6ac19ea6d3ced628be00b
---
```

2024-05-29 20:42 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-survicate/index.md
> +2. Search for "Survicate" in the Catalog, select it, and choose which of your sources to connect the destination to.
```suggestion
2. Search for "Survicate (Actions)" in the Catalog, select it, and choose which of your sources to connect the destination to.
```

2024-05-29 20:42 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-survicate/index.md
> +
```suggestion
{% include components/actions-fields.html %}
```

This will populate details on the Actions you have created

2024-05-29 20:42 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-survicate/index.md
> +id: 5c922eae1761cd0001a71707
@cieniawska  just added in my review

2024-06-05 14:25 UTC, cmastr approved these changes

2024-06-06 18:05 UTC, merged