Pushwoosh Source doc
segmentio/segment-docs pull request #6580
Opened 2024-05-22 09:03 UTC by artkry

Adding Pushwoosh Source integration doc

2024-05-22 15:37 UTC, tcgilbert requested changes

2024-05-22 15:37 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/pushwoosh/index.md
> +---
```suggestion
---
title: Pushwoosh Source
id: MW9K4HgBZz
beta: true
---
```

2024-05-22 15:37 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/pushwoosh/index.md
> +Pushwoosh passes the user identifier as the `user_id` property by default.
> Pushwoosh passes the user identifier as the `user_id` property by default.

Could you rewrite this to provide more clarity on the following: 

- is "user identifier" specific to pushwoosh?
- What happens if there is no "user identifier" present, do you send anonymous data with an anonymousId? If so, what is used for anonymousId?

2024-05-22 15:37 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/pushwoosh/index.md
> +The table below lists events that Pushwoosh sends to Segment. These events appear as tables in your warehouse, and as regular events in other Destinations. Pushwoosh includes the `user_id` if availab
> Pushwoosh includes the `user_id` if available.

If referring to the Segment `userId` please change from `user_id` to userId`. What happens when userId is not available, is the event still sent?

2024-05-22 15:53 UTC, cmastr approved these changes

2024-05-23 02:58 UTC, artkry commented on src/connections/sources/catalog/cloud-apps/pushwoosh/index.md
> +Pushwoosh passes the user identifier as the `user_id` property by default.
- "is "user identifier" specific to pushwoosh?" - yes, its Pushwoosh User ID (i've fixed it in the doc)
- "What happens if there is no "user identifier" present, do you send anonymous data with an anonymousId? If so, what is used for anonymousId?" - yes, Pushwoosh sent Pushwoosh HWID as the Segment anonymousId (i've noted it in the doc also)

2024-05-23 02:59 UTC, artkry commented on src/connections/sources/catalog/cloud-apps/pushwoosh/index.md
> +The table below lists events that Pushwoosh sends to Segment. These events appear as tables in your warehouse, and as regular events in other Destinations. Pushwoosh includes the `user_id` if availab
Fixed
as i answered in above conversation, If userId not available, Pushwoosh sent Pushwoosh HWID as Segment anonymousId
So, yes, the event still sent

2024-05-24 17:28 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/pushwoosh/index.md
> +In other case, if Pushwoosh does not have an associated `userId`, Pushwoosh HWID will be passed as the Segment `anonymousId`.
```suggestion
By default, Pushwoosh passes the Pushwoosh User ID as the Segment userId property. If there is no associated User ID, Pushwoosh will pass the HWID as the Segment anonymousId.
```

2024-05-28 13:08 UTC, tcgilbert approved these changes

2024-05-29 19:51 UTC, merged