Adding ConfigCat source documentation
segmentio/segment-docs pull request #6596
Opened 2024-05-23 10:15 UTC by laliconfigcat

### Proposed changes

Adding the ConfigCat source documentation to be able to publish our integration.

### Merge timing

ASAP once approved

2024-05-28 13:36 UTC, tcgilbert requested changes
If you have any questions do let me know.

2024-05-28 13:36 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/configcat/index.md
> +---
```suggestion
---
title: ConfigCat Source
id: nEjnxv4kbB
beta: true
---
```

2024-05-28 13:36 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/configcat/index.md
> +| featureFlagChanged   | Feature flag changed   |
```suggestion
| Feature Flag Evaluated | Feature flag evaluated |
| Feature Flag Changed   | Feature flag changed   |
```

Could you provide just a bit more of a description for what these events are? 

Additionally, Looking at the events in your [source's debugger](https://app.segment.com/configcat/sources/configcat/debugger), I am seeing that you are using `camelCasing` for both event names and event properties. [We actually recommend](https://segment.com/academy/collecting-data/naming-conventions-for-clean-data/) that this is configured to use `Proper Case` for event names, and `snake_case` for event properties. 

Could you update the naming conventions for your source's event payloads? If not, could you please provide some details as to why?

2024-05-28 13:36 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/configcat/index.md
> +| `user`           | The user object used during feature flag evaluation              |
```suggestion
| `feature_flag_key` | The feature flag's key                                           |
| `value`          | The evaluated feature flag's value or Variation ID               |
| `variation_id`    | The evaluated feature flag's Variation ID                        |
| `user`           | The user object used during feature flag evaluation              |
```
I noticed that you included `userId` within the properties object. Within the Segment spec, this is a key property that is only to be placed at the top level of the payload. So please ensure that you have removed `userId` or `anonymousId` from the properties object. 

[We actually recommend](https://segment.com/academy/collecting-data/naming-conventions-for-clean-data/) that this is configured to use `Proper Case` for event names, and `snake_case` for event properties.

Could you update the naming conventions for your source's event payloads? If not, could you please provide some details as to why?

2024-05-28 13:36 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/configcat/index.md
> +| `user`            | The user object used during feature flag evaluation              |
```suggestion
| `details`         | A brief summary of the change                                    |
| `user_email`       | The ConfigCat user's email who made the changes                  |
| `user_full_name`    | The ConfigCat user's full name who made the changes              |
| `product_id`       | The product's ID where the change happened                       |
| `product_name`     | The product's name where the change happened                     |
| `config_id`        | The config's ID where the change happened                        |
| `config_name`      | The config's name where the change happened                      |
| `environment_id`   | The environment's ID where the change happened                   |
| `environment_name` | The environment's name where the change happened                 |
| `url`             | A direct link to the config/feature flag                         |
| `user`            | The user object used during feature flag evaluation              |
```

I noticed that you included `userId` and `timestamp` within the properties object. Within the Segment spec, these are key properties that are only to be placed at the top level of the payload. So please ensure that you have removed `userId` or `anonymousId` and `timestamp` from the properties object. 

[We actually recommend](https://segment.com/academy/collecting-data/naming-conventions-for-clean-data/) that this is configured to use `Proper Case` for event names, and `snake_case` for event properties.

Could you update the naming conventions for your source's event payloads? If not, could you please provide some details as to why?

2024-05-29 08:17 UTC, laliconfigcat commented
> If you have any questions do let me know.

Hello @tcgilbert , many thanks for your review. I will fix these mistakes, but i'll be OOO this week, so probably i will do it early next week.

2024-06-03 13:35 UTC, tcgilbert requested changes

2024-06-03 13:35 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/configcat/index.md
> +The default behavior is for ConfigCat to pass the user object's identifier property used during the feature flag evaluation as the userId or sending the ConfigCat User's ID who made the changes as th
What happens when there is no user object identifier? Is the default to send `ConfigCat User's ID`as the Segment userId in it's place? 

Will there every be a situation where nothing is used as the Segment `userId`, and you send an event with only with `anonymousId`? If so what is used for `anonymousId`

2024-06-03 13:35 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/configcat/index.md
> +The table below lists events that ConfigCat sends to Segment. These events appear as tables in your warehouse, and as regular events in other Destinations. ConfigCat includes the `userId` if availabl
```suggestion
The table below lists events that ConfigCat sends to Segment. These events appear as tables in your warehouse, and as regular events in other Destinations.
```

"ConfigCat includes the `userId` if available." can be removed as this will be clarified in the section above

2024-06-03 15:10 UTC, laliconfigcat commented on src/connections/sources/catalog/cloud-apps/configcat/index.md
> +The default behavior is for ConfigCat to pass the user object's identifier property used during the feature flag evaluation as the userId or sending the ConfigCat User's ID who made the changes as th
There are two ways how we are sending data to Segment. They are totally different and they have nothing in common related to User ID handling. 

The feature flag evaluated event is sent from ConfigCat's customer's application with a code snippet we provide in our documentation. The user object's identifier is our customer's application's user's identifier. If that is not provided we are sending an empty string. However it seems to be pointless at first glance, but in ConfigCat terminology it totally makes sense to not have an user object during feature flag evaluation. But we would like to send events in this case too. We don't send explicitly anything in this case as anonymusId, but the code snippets we provide are using Segment's SDKs. Is it handled there? What is your suggestion in this case? Should we generate a GUID and send it as the anonymusid? These applications don't know anything about `ConfigCat User's ID`.

The feature flag changed event is sent from ConfigCat's backend and we always provide the userId there (`ConfigCat User's ID`).

2024-06-04 14:16 UTC, tcgilbert requested changes

2024-06-04 14:16 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/configcat/index.md
> +The default behavior is for ConfigCat to pass the user object's identifier property used during the feature flag evaluation as the userId or sending the ConfigCat User's ID who made the changes as th
```suggestion
In the "Feature Flag Evaluation" event, the default behavior for ConfigCat is to use the user-object's identifier property as the Segment `userId`. If no identifier is present, the event will be sent with a randomly generated `anonymousId`.

For "Feature Flag Changed" events, the ConfigCat User's ID who made the changes will be sent as the Segment userId.
```

2024-06-04 14:16 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/configcat/index.md
> +The default behavior is for ConfigCat to pass the user object's identifier property used during the feature flag evaluation as the userId or sending the ConfigCat User's ID who made the changes as th
@laliconfigcat thanks for clarifying. Could you please update to the following^

2024-06-04 14:16 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/configcat/index.md
> +The default behavior is for ConfigCat to pass the user object's identifier property used during the feature flag evaluation as the userId or sending the ConfigCat User's ID who made the changes as th
thanks for clarifying. no need for any changes, just need to change the copy in the documentation. please see my suggestion below.

2024-06-04 14:16 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/configcat/index.md
> +The table below lists events that ConfigCat sends to Segment. These events appear as tables in your warehouse, and as regular events in other Destinations. ConfigCat includes the `userId` if availabl
@laliconfigcat 
could you make this update as well^

2024-06-04 14:21 UTC, tcgilbert requested changes
last minor tweak and I'll approve!

2024-06-04 14:21 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/configcat/index.md
> +For "Feature Flag Changed" events, the ConfigCat User's ID who made the changes will be sent as the Segment userId.
```suggestion
For "Feature Flag Changed" events, the ConfigCat User's ID who made the changes will be sent as the Segment `userId`.
```

2024-06-05 07:09 UTC, laliconfigcat commented
> last minor tweak and I'll approve!

Thank you very much for your review!

2024-06-05 13:04 UTC, tcgilbert approved these changes

2024-06-13 04:36 UTC, merged