add yotpo as a source docs
segmentio/segment-docs pull request #6665
Opened 2024-06-05 07:58 UTC by vladimir-marinov-yotpo

### Proposed changes

Adding new docs for the Yotpo as a source 

### Merge timing
I will update it a bit.

### Related issues (optional)

2024-06-05 15:59 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +---
```suggestion
---
title: Yotpo Source
beta: true
---
```

2024-06-05 15:59 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +[Yotpo](https://yotpo.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners) is a retention marketing platform that helps turn one-time shoppers into customers for life and maximize custome
```suggestion
[Yotpo](https://yotpo.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners) {:target="_blank”} is a retention marketing platform that helps turn one-time shoppers into customers for life and maximize customer value. It enables you to collect and showcase customer reviews, offer loyalty programs and SMS and email marketing solutions.
```

2024-06-05 15:59 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +Take your company’s customer engagement to the next level by adding Yotpo as a Source to Segment. Segment automatically collects engagement events like SMS sent, SMS clicked and Email opened, forward
```suggestion
Take your company’s customer engagement to the next level by adding Yotpo as a Source to Segment. Segment automatically collects engagement events (like SMS sent, SMS clicked and Email opened) forwards them to your destinations, and loads them into your data warehouse.
```

2024-06-05 15:59 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +
```suggestion
```

2024-06-05 15:59 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +2. On the next screen, give the Source a name.
```suggestion
2. On the next screen, give the Source a name. You can also apply labels to the source and connect the source to your warehouses. When you've finished setting up your source, click **Add Source**. 
```

2024-06-05 15:59 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +3. The next page (“Overview”) will surface your Segment write key for Yotpo. Copy this write key.
```suggestion
3. Segment redirects you to the Overview page and surfaces your Segment write key for Yotpo. Copy this write key.
```

2024-06-05 15:59 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +4. In your Yotpo integration center, search for "Segment" and click on Connect.
```suggestion
4. In your Yotpo integration center, search for "Segment" and click **Connect**.
```

2024-06-05 15:59 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +7. Go back to Segment and click **Add Destinations** in your Yotpo source to add the destinations where you want to see SMS and email events.
```suggestion
7. Return to Segment and click **Add Destinations** in your Yotpo source to add the destinations where you want to send your SMS and email events.
```

2024-06-05 15:59 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +Log into your downstream tools and check to see that your events appear as expected, and that they contain all of the properties you expect. If your events and properties don’t appear, check the Even
```suggestion
Log into your downstream tools and check to see that your events appear as expected, and that they contain all of the properties you expect. If your events and properties don’t appear, check the Event Delivery tool, and refer to the docs for each destination for troubleshooting.
```

2024-06-05 15:59 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +Now that your Source is set up, you can connect it with Destinations.
```suggestion
Now that your source is set up, you can connect it to destinations.
```

2024-06-05 15:59 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +The table below lists events that Yotpo sends to Segment. These events appear as tables in your warehouse, and as regular events in other Destinations. Yotpo includes the `userId` if available.
```suggestion
The table below lists events that Yotpo sends to Segment. These events appear as tables in your warehouse, and as regular events in other destinations. Yotpo includes the `userId` if available.
```

2024-06-05 15:59 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +1. From your workspace's [Sources catalog page](https://app.segment.com/goto-my-workspace/sources/catalog) click **Add Source**.
```suggestion
1. From your workspace's [Sources catalog page](https://app.segment.com/goto-my-workspace/sources/catalog) click **Add source**.
```

2024-06-06 05:20 UTC, vladimir-marinov-yotpo commented
@forstisabella, I have reviewed and applied the suggested comments. Feel free to let me know if there is anything else you need me to do.

2024-06-06 12:50 UTC, tcgilbert requested changes

2024-06-06 12:50 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +---
```suggestion
---
title: Yotpo Source
beta: true
id: q4JbVJwmrg
---
```

2024-06-06 12:50 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +The table below lists events that Yotpo sends to Segment. These events appear as tables in your warehouse, and as regular events in other destinations. Yotpo includes the `userId` if available.
> The table below lists events that Yotpo sends to Segment. These events appear as tables in your warehouse, and as regular events in other destinations. Yotpo includes the `userId` if available.

- Could you explain what identifier is used for the Segment `userId` value (is it a yotpo id, or a user id that comes from customer)? 
- If there is no `userId` available, will you send data with an Segment `anonymousId`? If so, what will be used for `anonymousId`?

2024-06-06 12:50 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +| Email subscribed   | User subscribed to receive emails.                       |
```suggestion
| SMS Sent           | An SMS was sent.                                         |
| SMS Clicked        | User clicked a short link in an SMS message.             | 
| SMS Unsubscribed   | User clicked the unsubscribe link in an SMS.             | 
| SMS Subscribed     | User subscribed to receive SMS messages.                 |
| Email Sent         | An email was sent to the user.                           |
| Email Delivered    | An email was successfully delivered to the user's inbox. |
| Email Opened       | User opened an email.                                    |
| Email Clicked      | User clicked a link within an email.                     |
| Email Bounced      | An email could not be delivered to the user.             |
| Email Unsubscribed | User clicked the unsubscribe link in an email.           |
| Email Subscribed   | User subscribed to receive emails.                       |
```

Per our event naming conventions, please convert your event names to `Proper Casing`: https://segment.com/docs/partners/sources/#naming-conventions

2024-06-06 12:50 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +
Please add a table outlining the properties that can be expected to be in these events: 

```
## Event Properties

The table below list the properties included in the events listed above.

| Property Name   | Description               |
| --------------- | ------------------------- |
| `email_id`      | ID of the email           |
| `from_id`        | Sender email ID           |
| `email_subject` | Subject line of the email |
| `link`          | URL of the link clicked   |
etc...
```

2024-06-11 05:45 UTC, vladimir-marinov-yotpo commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +The table below lists events that Yotpo sends to Segment. These events appear as tables in your warehouse, and as regular events in other destinations. Yotpo includes the `userId` if available.
Hi, 
`UserId` will be an id that comes from the customer. If that is not present, we don't send it.
We always send the `AnonymousId`, which is either a phone number or email based on the type of the event.

2024-06-11 05:45 UTC, vladimir-marinov-yotpo commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +
Sure.

2024-06-11 06:27 UTC, vladimir-marinov-yotpo commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +
I am waiting for the descriptions to be approved, and I will update the PR.

2024-06-11 07:39 UTC, vladimir-marinov-yotpo commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +
Done.

2024-06-11 07:39 UTC, vladimir-marinov-yotpo commented
@tcgilbert could you recheck the PR?

2024-06-11 13:23 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +The table below lists events that Yotpo sends to Segment. These events appear as tables in your warehouse, and as regular events in other destinations. Yotpo includes the `userId` if available.
@vladimir-marinov-yotpo one more change, and then I will approve ^

2024-06-12 05:06 UTC, vladimir-marinov-yotpo commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +The table below lists events that Yotpo sends to Segment. These events appear as tables in your warehouse, and as regular events in other destinations. Yotpo includes the `userId` if available.
Done.

2024-06-12 14:23 UTC, tcgilbert commented
@vladimir-marinov-yotpo I've approved the documentation. To get the source live in the catalog, please navigate to the dev portal and submit the source for final review: 

https://app.segment.com/dev-portal/integrations/source/yotpo/status
![Screenshot 2024-06-12 at 10 22 45 AM](https://github.com/segmentio/segment-docs/assets/64277654/ec1d8093-e738-47c3-9d09-cab8ee47cfff)

2024-06-12 16:00 UTC, forstisabella approved these changes

2024-06-12 16:00 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +5. On the Provide API Key stage of the integration process, enter the **Segment Write Key** in the right place.
```suggestion
5. On the Provide API Key stage of the integration process, enter the **Segment Write Key**.
```

2024-06-12 16:00 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +1. From your workspace's [Sources catalog page](https://app.segment.com/goto-my-workspace/sources/catalog) click **Add source**.
```suggestion
1. From your workspace's [Sources catalog page](https://app.segment.com/goto-my-workspace/sources/catalog){:target="_blank”} click **Add source**.
```

2024-06-12 16:00 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +Take your company’s customer engagement to the next level by adding Yotpo as a Source to Segment. Segment automatically collects engagement events (like SMS sent, SMS clicked, and Email opened) forwa
```suggestion
Take your company’s customer engagement to the next level by adding Yotpo as a Source to Segment. Segment automatically collects engagement events (like SMS sent, SMS clicked, and Email opened), forwards them to your destinations, and loads them into your data warehouse.
```

2024-06-12 16:00 UTC, forstisabella commented on src/connections/sources/catalog/cloud-apps/yotpo/index.md
> +[Yotpo](https://yotpo.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners) {:target="_blank”} is a retention marketing platform that helps turn one-time shoppers into customers for life a
```suggestion
[Yotpo](https://yotpo.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank”} is a retention marketing platform that helps turn one-time shoppers into customers for life and maximize customer value. It enables you to collect and showcase customer reviews, offer loyalty programs and SMS and email marketing solutions.
```

2024-06-14 15:05 UTC, merged