Add section about auto-migration for legacy Google Ads Conversions mappings [DOC-934]
segmentio/segment-docs pull request #6666
Opened 2024-06-05 16:37 UTC by forstisabella

### Proposed changes
See title.

### Merge timing
Before June 7, 2024

### Related issues (optional)
https://segment.atlassian.net/browse/DOC-934

2024-06-05 20:56 UTC, rvadera12 requested changes

2024-06-05 20:56 UTC, rvadera12 commented on src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
> +> Segment will automatically migrate all enabled Upload Enhanced Conversion (Legacy) actions to the updated Upload Conversion Adjustment mappings on June 7th, 2024. For more information, see the [Aut
```suggestion
> Segment will automatically migrate all enabled Upload Enhanced Conversion (Legacy) mappings to the updated Upload Conversion Adjustment mappings on June 7th, 2024. For more information, see the [Automatic migration from Upload Enhanced Conversion (Legacy) Action](#automatic-migration-from-upload-enhanced-conversion-legacy-action) documentation.
```

2024-06-05 20:56 UTC, rvadera12 commented on src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
> +> Segment will automatically migrate all enabled Upload Enhanced Conversion (Legacy) actions to the updated Upload Conversion Adjustment mappings on June 7th, 2024. For more information, see the [Aut
Could we add some verbiage to emphasis these are required steps. Also add a note to disable the the legacy mapping.

2024-06-05 20:56 UTC, rvadera12 commented on src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
> +> Segment will automatically migrate all enabled Upload Enhanced Conversion (Legacy) actions to the updated Upload Conversion Adjustment mappings on June 7th, 2024. For more information, see the [Aut
Can we also remove the June 7th - don't want any committed dates depending on when the migration runs/is completed and any issues

2024-06-05 20:56 UTC, rvadera12 commented on src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
> +1. Navigate to the Google Ads Conversions destination in your warehouse and select the **Settings** tab.
Would it be possible to add these screenshots, I know we don't like having screenshots since they may go out of date, but we can make a plan to remove this whole section. 
![Screenshot 2024-06-05 at 12 04 17 PM](https://github.com/segmentio/segment-docs/assets/89420099/1c816566-b177-4cae-a81f-920f1334e74e)
![Screenshot 2024-06-05 at 12 21 16 PM](https://github.com/segmentio/segment-docs/assets/89420099/af93bc9d-7b8b-46a1-ad26-2d692ee57429)
![Screenshot 2024-06-05 at 12 22 59 PM](https://github.com/segmentio/segment-docs/assets/89420099/56128cd2-2701-4041-a081-a8616cc54b47)
![Screenshot 2024-06-05 at 12 26 59 PM](https://github.com/segmentio/segment-docs/assets/89420099/4b33e99c-6e92-4611-84b3-6324ca607ca9)

2024-06-05 20:56 UTC, rvadera12 commented on src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
> +1. Navigate to the Google Ads Conversions destination in your warehouse and select the **Settings** tab.
Include the last step of disabling and enabling

2024-06-06 16:07 UTC, forstisabella commented on src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
> +Starting on June 7, 2024, Segment will migrate all enabled legacy Upload Enhanced Conversion mappings to the new Upload Conversion Adjustment mapping, preserving as many mapping fields as possible.
```suggestion
On June 7, 2024, Segment will begin migrating all enabled legacy Upload Enhanced Conversion mappings to the new Upload Conversion Adjustment mapping, preserving as many mapping fields as possible. 
```

2024-06-06 17:45 UTC, pwseg approved these changes

2024-06-06 18:02 UTC, merged