Updated FL0 documentation to use Direct destination template
segmentio/segment-docs pull request #6674
Opened 2024-06-06 16:39 UTC by james-fl0

### Proposed changes

Switched to use Direct documentation template instead of Action template.

### Merge timing
ASAP once approved

2024-06-06 16:42 UTC, james-fl0 commented
FYI the link we received in the Zendesk ticket contained a link to the Action template. If you're using canned responses, it might be useful to update this based on which destination type the partner is using so they don't accidentally use the wrong template like we did.

Thanks!

![Screenshot 2024-06-06 at 9 40 28 AM](https://github.com/segmentio/segment-docs/assets/88681427/d2e3fd64-e55d-4d6d-906a-fee2f2474a31)

2024-06-07 14:33 UTC, tcgilbert requested changes

2024-06-07 14:33 UTC, tcgilbert commented on src/connections/destinations/catalog/fl0/index.md
> +1. From your workspace's [Destination catalog page](https://app.segment.com/goto-my-workspace/destinations/catalog){:target="_blank”} search for "FL0"
```suggestion
1. From your workspace's [Destination catalog page](https://app.segment.com/goto-my-workspace/destinations/catalog){:target="_blank”} search for "FL0".
```

2024-06-07 14:33 UTC, tcgilbert commented on src/connections/destinations/catalog/fl0/index.md
> +3. Select an existing source to connect to FL0 (Actions)
```suggestion
3. Select an existing source to connect to FL0.
```

2024-06-12 13:22 UTC, tcgilbert approved these changes

2024-06-13 04:38 UTC, pwseg approved these changes

2024-06-13 04:38 UTC, merged