Add Sendgrid Marketing Campaigns Source docs
segmentio/segment-docs pull request #6678
Opened 2024-06-06 18:20 UTC by FirstWhack

### Proposed changes

Adds a new Source doc for Sendgrid Marketing Campaigns

### Merge timing
<!-- When should this get merged/published?
Release date is scheduled for Monday June 17

### Related issues (optional)
https://github.com/twilio-internal/docs/pull/1721

2024-06-06 18:21 UTC, FirstWhack commented
I'm confused by the syntax at the very top of the template (with `title`), looking for some help understanding if this is right

2024-06-06 18:21 UTC, FirstWhack commented on src/connections/sources/catalog/cloud-apps/sendgrid-marketing-campaigns/index.md
> +---
What is this syntax?

2024-06-06 18:27 UTC, FirstWhack commented on src/connections/sources/catalog/cloud-apps/sendgrid-marketing-campaigns/index.md
> +[SendGrid Marketing Campaigns](https://yourintegration.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank”} enables you to automatically stream your email events directl
This link is not yet available and needs to be updated before merging

2024-06-10 15:15 UTC, tcgilbert requested changes

2024-06-10 15:15 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/sendgrid-marketing-campaigns/index.md
> +---
```suggestion
---
title: SendGrid Marketing Campaigns Source
id: GCeG0vmcDW
beta: true
---
```

2024-06-10 15:15 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/sendgrid-marketing-campaigns/index.md
> +---
frontmatter for markdown: https://mystmd.org/guide/frontmatter

2024-06-10 15:15 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/sendgrid-marketing-campaigns/index.md
> +   - The name is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The name can be anything, but we recommend using something that reflects the source i
```suggestion
   - The name is used as a label in the Segment app, and Segment creates a related schema name in your warehouse. The name can be anything, but we recommend using something that reflects the source itself and distinguishes amongst your environments (eg. Sendgrid_Prod, Sendgrid_Staging, Sendgrid_Dev).
```

2024-06-10 15:15 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/sendgrid-marketing-campaigns/index.md
> +| Email Marked as Spam    | Recipient [reported the email as spam](https://www.twilio.com/docs/sendgrid/ui/analytics-and-reporting/spam-reports)        |
```suggestion
| Email Machine Opened    | Email was [opened anonymously](https://www.twilio.com/docs/sendgrid/for-developers/tracking-events/understanding-apple-mail-privacy-protection-and-open-events){:target="_blank”} |
| Email Link Clicked      | Recipient clicked the [tracking link](https://www.twilio.com/docs/sendgrid/ui/account-and-settings/tracking#click-tracking){:target="_blank”} |
| Email Dropped           | Email was [dropped by Sendgrid](https://www.twilio.com/docs/sendgrid/glossary/drops){:target="_blank”}                                        |
| Email Bounced           | Email servers [rejected the email](https://www.twilio.com/docs/sendgrid/ui/sending-email/bounces){:target="_blank”}                           |
| Unsubscribed            | Recipient [unsubscribed globally](https://www.twilio.com/docs/sendgrid/ui/sending-email/global-unsubscribes){:target="_blank”}                |
| Unsubscribed From Group | Recipient [unsubscribed from a group](https://www.twilio.com/docs/sendgrid/ui/sending-email/group-unsubscribes){:target="_blank”}             |
| Resubscribed To Group   | Recipient resubscribed to a group                                                                                           |
| Email Marked as Spam    | Recipient [reported the email as spam](https://www.twilio.com/docs/sendgrid/ui/analytics-and-reporting/spam-reports){:target="_blank”}        |
```

2024-06-10 15:15 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/sendgrid-marketing-campaigns/index.md
> +| `categories`                | [Categories](https://www.twilio.com/docs/sendgrid/for-developers/sending-email/categories) associated to the email              |
```suggestion
| `test_phase`                | `true` if the Single Send is an [A/B Test](https://www.twilio.com/docs/sendgrid/ui/sending-email/a-b-testing){:target="_blank”} in the test phase |
| `unsubscribe_group_id`      | ID of the unsubscribe group, when available                                                                                     |
| `link_url`                  | URL of the link clicked                                                                                                         |
| `categories`                | [Categories](https://www.twilio.com/docs/sendgrid/for-developers/sending-email/categories){:target="_blank”} associated to the email              |
```

2024-06-14 15:16 UTC, tcgilbert approved these changes

2024-06-14 15:16 UTC, tcgilbert commented
@cmastr if we can get this included in tuesday's deploy that would be great!

2024-06-14 15:34 UTC, pwseg approved these changes

2024-06-14 15:34 UTC, merged

2024-06-14 15:35 UTC, pwseg commented
>  if we can get this included in tuesday's deploy that would be great!

Merged!  It'll go out on Tuesday.