Create actions-jimo
segmentio/segment-docs pull request #6719
Opened 2024-06-18 16:25 UTC by imsamdez

Documentation for the Jimo Browser Destination

### Proposed changes

Added an index.md in `src/connections/destinations/catalog/actions-jimo/index.md`

### Merge timing
- ASAP once approved?

2024-06-18 16:31 UTC, forstisabella commented on src/connections/destinations/catalog/actions-jimo/index.md
> +[Jimo](https://usejimo.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank”} helps you to publish personalized product experiences to elevate adoption and user engagement
```suggestion
[Jimo](https://usejimo.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank”} helps you to publish personalized product experiences to elevate adoption and user engagement without code as a layer on top of your app.
```

2024-06-18 16:33 UTC, forstisabella requested changes

2024-06-18 16:33 UTC, forstisabella commented on src/connections/destinations/catalog/actions-jimo/index.md
> +3. Select an existing Source to connect to <Jimo (Actions).
```suggestion
3. Select an existing Source to connect to Jimo (Actions).
```

2024-06-18 16:33 UTC, forstisabella commented on src/connections/destinations/catalog/actions-jimo/index.md
> +4. Go to the [Jimo dashboard](https://i.usejimo.com/settings/general){:target="_blank"}, find and copy your **project id**.
```suggestion
4. Open your [Jimo dashboard](https://i.usejimo.com/settings/general){:target="_blank"}, find and copy your **project id**.
```

2024-06-18 16:33 UTC, forstisabella commented on src/connections/destinations/catalog/actions-jimo/index.md
> +5. Enter the **project id** in the Jimo destination settings in Segment.
```suggestion
5. Return to Segment and open the destination settings for the Jimo (Actions) destination that you just created. Enter your Jimo **project id**.
```

2024-06-20 21:32 UTC, tcgilbert requested changes
just a couple changes, but lgtm

2024-06-20 21:32 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-jimo/index.md
> +---
```suggestion
---
title: Jimo (Actions) Destination
id: 652d4cf5e00c0147e6eaf5e7
beta: true
---
```

2024-06-20 21:32 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-jimo/index.md
> +5. Return to Segment and open the destination settings for the Jimo (Actions) destination that you just created. Enter your Jimo **project id**.
```suggestion
1. From your workspace's [Destination catalog page](https://app.segment.com/goto-my-workspace/destinations/catalog){:target="_blank”} search for "Jimo (Actions)".
2. Select Jimo (Actions) and click **Add Destination**.
3. Select an existing Source to connect to Jimo (Actions).
4. Open your [Jimo dashboard](https://i.usejimo.com/settings/general){:target="_blank"}, find and copy your **project id**.
5. Return to Segment and open the destination settings for the Jimo (Actions) destination that you just created. Enter your Jimo **project id**.
```

2024-06-25 14:52 UTC, imsamdez commented
Committed, thanks for the suggestions!

2024-06-25 15:03 UTC, tcgilbert approved these changes

2024-06-25 15:06 UTC, forstisabella approved these changes

2024-06-25 15:26 UTC, tcgilbert commented
@imsamdez since you have submitted your documentation. If you have tested the integration, and are certain it behaves as expected, we can make your integration live. Is that the case, or would you like to wait?

2024-07-01 11:25 UTC, imsamdez commented
> @imsamdez since you have submitted your documentation. If you have tested the integration, and are certain it behaves as expected, we can make your integration live. Is that the case, or would you like to wait?

Hey @tcgilbert, you can make it live yes, thanks!

2024-07-01 14:24 UTC, tcgilbert commented
@imsamdez great! this will go live tomorrow afternoon when the docs site rebuilds. I'll send an update to you then

2024-07-01 15:04 UTC, merged