UserMotion docs
segmentio/segment-docs pull request #6729
Opened 2024-06-20 13:32 UTC by namirali

### Proposed changes
UserMotion Catalog Documentation

### Merge timing
ASAP

2024-06-20 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-usermotion/index.md
> +[UserMotion](https://usermotion.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="\_blank”} is AI-powered predictive lead scoring software discovers intention signals and scor
```suggestion
[UserMotion](https://usermotion.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="\_blank”} is AI-powered predictive lead scoring software that discovers intention signals and scores leads on potential to buy, expand, or churn.
```

2024-06-20 21:30 UTC, tcgilbert requested changes
just a couple changes, but lgtm

2024-06-20 21:30 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-usermotion/index.md
> +---
```suggestion
---
title: UserMotion (Actions) Destination
id: 6537b5da8f27fd20713a5ba8
beta: true
---
```

2024-06-20 21:30 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-usermotion/index.md
> +6. Save your changes and enable the destination.
```suggestion
1. From your workspace's [Destination catalog page](https://app.segment.com/goto-my-workspace/destinations/catalog){:target="\_blank”} search for "UserMotion (Actions)".
2. Select UserMotion (Actions) and click **Add Destination**.
3. Select an existing Source to connect to UserMotion (Actions).
4. Go to the [UserMotion dashboard](https://app.usermotion.com/?returnPath=/settings/integrations?provider=api){:target="\_blank"}, find and copy the **API key**.
5. Enter the **API Key** in the UserMotion destination settings in Segment.
6. Save your changes and enable the destination.
```

2024-06-20 22:22 UTC, namirali reviewed
docs updated

2024-06-20 22:25 UTC, forstisabella approved these changes

2024-06-21 20:41 UTC, tcgilbert approved these changes

2024-06-24 15:51 UTC, merged