redoing the braze LA docs [netlify-build]
segmentio/segment-docs pull request #6748
Opened 2024-06-25 16:33 UTC by cmastr

https://segment.atlassian.net/browse/DOC-923

2024-06-25 16:34 UTC, cmastr commented on src/engage/audiences/linked-audiences-braze.md
> +The following table helps translate your payload data into Liquid syntax:
Table giving me heartburn. @pwseg

2024-06-26 15:15 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +        <td>Example Properties</td>
```suggestion
        <th>Reference Data Definition</th>
        <th>Liquid Syntax</th>
        <th>Example Properties</th>
```

2024-06-26 22:55 UTC, forstisabella requested changes

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +- Created a Braze profile, for campaign testing, with an email address you can access.
```suggestion
- Created a Braze profile that has an email address you can access. You'll use this profile for campaign testing in a later step.
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +- Familiarity with the [Liquid templating syntax](https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid){:target="_blank"} to manually type out the code using dot notation.
What's dot notation?

```suggestion
- Familiarity with the [Liquid templating syntax](https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid){:target="_blank"}.
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +To take advantage of Linked Audiences, you must now take some additional steps in Braze to set up an action-based delivery campaign.
```suggestion
To use Linked Audiences you must first set up an action-based delivery campaign in Braze. 
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +1. Create a new [email Campaign](https://www.braze.com/docs/user_guide/engagement_tools/campaigns/building_campaigns/creating_campaign){:target="_blank"}.
Should we link directly to the email docs, or should we link to the docs that contain all of the campaigns you can create?

```suggestion
1. Create a new [email Campaign](https://www.braze.com/docs/user_guide/message_building_by_channel/email){:target="_blank"}. 
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +2. [Create an email using the HTML Editor](https://www.braze.com/docs/user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign/){:target="_blank"} to begin [personalizing w
```suggestion
2. [Create an email using the HTML Editor](https://www.braze.com/docs/user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign/){:target="_blank"} and [personalize it using Liquid tags](https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid){:target="_blank"}. 
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +    - Translate the Segment event properties in the payload schema into [liquid syntax](https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid/using_liquid/#using-liquid-1){
```suggestion
    - Translate the Segment event properties in the payload schema into Liquid syntax for [custom events](https://www.braze.com/docs/user_guide/data_and_analytics/custom_data/custom_events){:target="_blank"}, and enter it in the Braze HTML editor. See the following personalization [examples](#liquid-examples-to-use-in-braze) for more details on how you can personalize your campaign.
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +2. [Create an email using the HTML Editor](https://www.braze.com/docs/user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign/){:target="_blank"} to begin [personalizing w
Also, do these substeps need to be completed in order? If so, they should probably be an ordered list

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +    - Choose Delivery Controls > [Allow users to become re-eligible to receive campaigns](https://www.braze.com/docs/user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibil
~~The style guide suggests bold-ing the names of UI elements that a user will need to interact with~~.

Unofficially,  we bold the names of UI elements a user would need to interact with. Up to you if this is a style-guide worthy item or not!

```suggestion
3. Next, [schedule your campaign delivery](https://www.braze.com/docs/user_guide/engagement_tools/campaigns/building_campaigns/delivery_types){:target="_blank"}:
    1. Select [Action-based delivery](https://www.braze.com/docs/user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/#step-1-select-a-trigger-event){:target="_blank"} > [**New Trigger Action**](https://www.braze.com/docs/user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/#step-1-select-a-trigger-event){:target="_blank"}: [**Perform Custom Event**](https://www.braze.com/docs/user_guide/data_and_analytics/custom_data/custom_events){:target="_blank"} > **Add Trigger**. 
    2. Search for and select the name of the Segment custom event you previously set up and tested in Segment.
    3. Select **Delivery Controls** > [**Allow users to become re-eligible to receive campaigns**](https://www.braze.com/docs/user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility/#campaigns){:target="_blank"} checkbox, and select 0 minutes. This is necessary for [Step 2: Test your campaign flow](#step-2-test-your-campaign-flow) so that you don’t have to wait for a user to become re-eligible while testing. You can adjust these settings after you have finished testing.
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +    - Select ‘more than 0 times’ as the timeframe for this filter.
```suggestion
    1. Add a filter to [target users without a segment](https://www.braze.com/docs/user_guide/engagement_tools/campaigns/building_campaigns/targeting_users/#without-segment){:target="_blank"}. 
    2. Search for and select the name of the Segment custom event you previously set up and tested in Segment.
    3. Select **More than 0 times** as the timeframe for this filter. 
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +5. Choose any additional settings that apply to your campaign, then [review and deploy](https://www.braze.com/docs/user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign/
```suggestion
5. Update any additional settings that apply to your campaign, then [review and deploy](https://www.braze.com/docs/user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign/#step-5-review-and-deploy){:target="_blank"} your campaign and continue to [Step 2: Test your campaign flow](#step-2-test-your-campaign-flow). 
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +In Segment, finish setting up your destination campaign by sending yourself a test email for review. Add your Braze user id and click **[Send test event to destination](/docs/engage/audiences/linked-
Where would someone add their Braze user ID? 

```suggestion
Open the Segment app and send yourself a test email for review. Add your Braze user id and click **[Send test event to destination](/docs/engage/audiences/linked-audiences/#step-3-send-a-test-event-to-your-destination)**. Review the email you received, and ensure it is formatted properly. 
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +You will see a `“message”: “success”` response in Segment if the event is sent successfully to Braze.
```suggestion
If the event is sent successfully to Braze, you will see a `“message”: “success”` response in Segment.
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +Check your [campaign dashboard](https://www.braze.com/docs/user_guide/message_building_by_channel/email/reporting_and_analytics/email_reporting){:target="_blank"} (Braze > *[Your Unique Campaign]* >
```suggestion
Open Braze and check your [campaign dashboard](https://www.braze.com/docs/user_guide/message_building_by_channel/email/reporting_and_analytics/email_reporting){:target="_blank"} (Braze > *[Your Unique Campaign]* > Analytics) to confirm that Braze sent the message. It can take up to 15 minutes for Braze to send the email. 
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +If your email doesn’t look the way you want it to, adjust the [liquid syntax](https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid/using_liquid/#using-liquid-1){:target="_
```suggestion
If your email doesn’t look the way you want it to, adjust the [liquid syntax](https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid/using_liquid/#using-liquid-1){:target="_blank"} in Braze and send another test event in Segment. See the following [personalization examples](#liquid-examples-to-use-in-braze) for more specific details.
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +When an email is sent, it will list the specific product, and its related price in your customer’s shopping cart. It might look like the following:
```suggestion
When an email is sent, it lists the specific product and its related price in your customer’s shopping cart. It might look like the following screenshot: 
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +![A screenshot of an email example.](/docs/engage/images/braze-cart-simple.png)
```suggestion
![A screenshot of an email, with the name, item, and price personalized.](/docs/engage/images/braze-cart-simple.png)
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +This is an example of what your email using [HTML ](https://www.braze.com/docs/user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign/){:target="_blank"} and[ liquid tags
```suggestion
This is an example of what your email formatted using [HTML](https://www.braze.com/docs/user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign/){:target="_blank"} and [Liquid](https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid){:target="_blank"} might look like in Braze:
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +![A screenshot of the basic email](/docs/engage/images/braze_basic_email.png)
I got the code snippets to work by adding a {% raw %} tag right before the code snippet, and an {% endraw %} tag right after. I can't figure out how to escape the already-escaped characters, or I'd add it directly as a review comment. I think that would be a preferable way to approach this, if it'll work, as it's much more accessible (and it's easier to update!)

```suggestion
```

Screenshots for proof: 
![Screenshot 2024-06-26 at 6 43 21 PM](https://github.com/segmentio/segment-docs/assets/92472883/9eb95315-af6b-443f-a36b-4d5d23136ff8)
![Screenshot 2024-06-26 at 6 45 56 PM](https://github.com/segmentio/segment-docs/assets/92472883/63c38056-ca9e-4a2d-85ff-63b129c284cd)

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +![A screenshot of the advanced email](/docs/engage/images/braze_advanced_email.png)
See above comment re adding this as a code snippet - that would be preferable, I think!

2024-06-26 22:55 UTC, forstisabella commented on src/engage/images/braze_advanced_email.png
remove in lieu of adding code snippet directly to the page

2024-06-26 22:55 UTC, forstisabella commented on src/engage/images/braze_basic_email.png
remove in lieu of adding code snippet directly to the page

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +Use the Segment payload data you [copied when setting up your Linked audience](/docs/engage/audiences/linked-audiences#showhide-preview) to build an abandoned cart email campaign where you can use an
```suggestion
Use the Segment payload data you [copied when setting up your Linked audience](/docs/engage/audiences/linked-audiences#showhide-preview) to build an abandoned cart email campaign where you can use an [iteration tag](https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags/#iteration-tags){:target="_blank"} to run a block of code repeatedly. In this example, you can use a for loop to list all of the products and their related prices in a customer’s shopping cart.
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +When an email is sent, it will list all of the products and their related prices in your customer’s shopping cart. It might look like the following:
```suggestion
When an email is sent, it lists all of the products and their related prices in your customer’s shopping cart. It might look like the following: 
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +This is an example of what your email using [HTML ](https://www.braze.com/docs/user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign/){:target="_blank"} and[ liquid tags
```suggestion
This is an example of what your email formatted using [HTML](https://www.braze.com/docs/user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign/){:target="_blank"} and [Liquid](https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid){:target="_blank"} might look like in Braze:
```

2024-06-26 22:55 UTC, forstisabella commented on src/engage/audiences/linked-audiences-braze.md
> +![A screenshot of an email example.](/docs/engage/images/braze-cart-advanced.png)
```suggestion
![A screenshot of an abandoned cart email, with a personalized name, two items, and prices for those items.](/docs/engage/images/braze-cart-advanced.png)
```

2024-06-27 13:10 UTC, cmastr commented on src/engage/audiences/linked-audiences-braze.md
> +## Supported Braze Engagement Tools
Yes, there are plans to add more before GA, so was prepping this for more.

2024-06-27 14:17 UTC, cmastr commented on src/engage/audiences/linked-audiences-braze.md
> +![A screenshot of the basic email](/docs/engage/images/braze_basic_email.png)
Okay thank you! I turned this back into code and running a preview to double check.

2024-06-27 14:18 UTC, cmastr commented on src/engage/images/braze_basic_email.png
DONE

2024-06-27 14:18 UTC, cmastr commented on src/engage/images/braze_advanced_email.png
DONE

2024-06-27 16:13 UTC, pwseg approved these changes

2024-06-27 16:13 UTC, pwseg commented on src/engage/audiences/linked-audiences-braze.md
> +4. If your email doesn’t look the way you want it to, adjust the [liquid syntax](https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid/using_liquid/#using-liquid-1){:target
```suggestion
4. If your email doesn’t look the way you want it to, adjust the [Liquid syntax](https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid/using_liquid/#using-liquid-1){:target="_blank"} in Braze and send another test event in Segment. See the following [personalization examples](#liquid-examples-to-use-in-braze) for more specific details.
```

2024-06-27 16:13 UTC, pwseg commented on src/engage/audiences/linked-audiences-braze.md
> +## Liquid Examples to use in Braze
```suggestion
## Liquid examples to use in Braze
```

2024-06-27 16:13 UTC, pwseg commented on src/engage/audiences/linked-audiences-braze.md
> +### Basic Email Example
```suggestion
### Basic email example
```

2024-06-27 16:13 UTC, pwseg commented on src/engage/audiences/linked-audiences-braze.md
> +### Advanced Email Example
```suggestion
### Advanced email example
```

2024-06-27 16:33 UTC, merged