Added userguiding destination documentation
segmentio/segment-docs pull request #6791
Opened 2024-07-04 15:23 UTC by ozzy-cox

### Proposed changes

Added documentation for using the userguiding destination documentation

### Merge timing

Any time.

2024-07-05 15:36 UTC, tcgilbert approved these changes

2024-07-08 21:28 UTC, forstisabella commented on src/connections/destinations/catalog/user_guiding/index.md
> +Using the [Track method](/docs/connections/spec/track/) will trigger a call to `userGuiding.track` method. You can get more information about tracking user actions from [here](https://help.userguidin
```suggestion
Using the [Track method](/docs/connections/spec/track/) triggers a call to UserGuiding's `userGuiding.track` method. For more information about tracking user action in UserGuiding, see UserGuiding's [Sending user attributes and tracking user actions](https://help.userguiding.com/en/articles/5562847-sending-user-attributes-and-tracking-user-actions){:target="_blank”}  documentation.
```

2024-07-08 21:29 UTC, forstisabella requested changes

2024-07-08 21:29 UTC, forstisabella commented on src/connections/destinations/catalog/user_guiding/index.md
> +If you're not familiar with the Segment Specs, take a look to understand what the [Track method](/docs/connections/spec/track/) does. An example call would look like:
```suggestion
If you're not familiar with the Segment Spec, take a look to understand what the [Track method](/docs/connections/spec/track/) does. An example call would look like:
```

2024-07-08 21:29 UTC, forstisabella commented on src/connections/destinations/catalog/user_guiding/index.md
> +Using the [Identify method](/docs/connections/spec/identify/) will trigger a call to UserGuiding's [Identify](https://panel.userguiding.com/settings/installation) method. You can get more information
```suggestion
Using the [Identify method](/docs/connections/spec/identify/) triggers a call to UserGuiding's [Identify](https://panel.userguiding.com/settings/installation){:target="_blank”} method. For more information about user identification in UserGuiding, see UserGuiding's [Sending user attributes and tracking user actions](https://help.userguiding.com/en/articles/5562847-sending-user-attributes-and-tracking-user-actions){:target="_blank”} documentation.
```

2024-07-08 21:29 UTC, forstisabella commented on src/connections/destinations/catalog/user_guiding/index.md
> +If you're not familiar with the Segment Specs, take a look to understand what the [Identify method](/docs/connections/spec/identify/) does. An example call would look like:
```suggestion
If you're not familiar with the Segment Spec, take a look to understand what the [Identify method](/docs/connections/spec/identify/) does. An example call would look like:
```

2024-07-08 21:29 UTC, forstisabella commented on src/connections/destinations/catalog/user_guiding/index.md
> +6. Pick the data residency region for your UserGuiding account.
```suggestion
6. Select the data residency region for your UserGuiding account.
```

2024-07-08 21:29 UTC, forstisabella commented on src/connections/destinations/catalog/user_guiding/index.md
> +5. Enter the API key provided in the [UserGuiding integrations page](https://panel.userguiding.com/settings/integrations/segment).
```suggestion
5. Enter the API key provided in the [UserGuiding integrations page](https://panel.userguiding.com/settings/integrations/segment){:target="_blank”}.
```

2024-07-08 21:29 UTC, forstisabella commented on src/connections/destinations/catalog/user_guiding/index.md
> +This destination is maintained by UserGuiding. For any issues with the source, [contact their Support team](mailto:assist@userguiding.com).
```suggestion
This destination is maintained by UserGuiding. For any issues with the source, [contact the UserGuiding Support team](mailto:assist@userguiding.com).
```

2024-07-09 15:15 UTC, forstisabella submitted a review, later dismissed

2024-07-09 15:15 UTC, forstisabella commented on src/connections/destinations/catalog/user_guiding/index.md
> +Using the [Track method](/docs/connections/spec/track/) triggers a call to UserGuiding's `userGuiding.track` method. For more information about tracking user action in UserGuiding, see UserGuiding's
```suggestion
Using the [Track method](/docs/connections/spec/track/) triggers a call to UserGuiding's `userGuiding.track` method. For more information about tracking user action in UserGuiding, see UserGuiding's [Sending user attributes and tracking user actions](https://help.userguiding.com/en/articles/5562847-sending-user-attributes-and-tracking-user-actions){:target="_blank”} documentation.
```

2024-07-09 15:15 UTC, forstisabella approved these changes

2024-07-09 18:19 UTC, merged