Taboola Action Destination docs
segmentio/segment-docs pull request #6826
Opened 2024-07-17 08:30 UTC by eden-ohana

### Proposed changes

Taboola Action Destination docs

### Merge timing

### Related issues (optional)

2024-07-17 08:32 UTC, eden-ohana commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +The **Taboola (Actions)** destination supports syncing Audiences to Taboola using either the `userId` and/or the `Mobile Device ID`.
@joe-ayoub-segment Isn't this supposed to be the user's email? Does the user need to configure something for it to be included?

2024-07-17 08:52 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +The **Taboola (Actions)** destination supports syncing Audiences to Taboola using either the `userId` and/or the `Mobile Device ID`.
Hi @eden-ohana yes that's correct! It should be `email`. Thanks for catching!

2024-07-17 09:07 UTC, eden-ohana commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +The **Taboola (Actions)** destination supports syncing Audiences to Taboola using either the `userId` and/or the `Mobile Device ID`.
Yes, I'll finish and let you know when to review. 
Thanks!

2024-07-17 13:09 UTC, eden-ohana commented
Hi @joe-ayoub-segment ready for review
Thanks

2024-07-18 11:06 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +> To view the audience on the Taboola platform, navigate to the [Tbaoola Ads audience page](https://ads.taboola.com/audiences), select "Custom Audience" and search for the audience you have just conn
```suggestion
> To view the audience on the Taboola platform, navigate to the [Taboola Ads audience page](https://ads.taboola.com/audiences), select "Custom Audience" and search for the audience you have just connected.
```

2024-07-18 11:07 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +1. Your Engage Space's Identify Resolution rules will need to be configured for `android.id` and `ios.id` identifiers. This can be configured by navigating to `Unify` >> `Unify Settings`.
```suggestion
1. Your Engage Space's identity resolution rules will need to be configured for `android.id` and `ios.id` identifiers. This can be configured by navigating to `Unify` >> `Unify Settings`. 
```

2024-07-18 13:23 UTC, joe-ayoub-segment commented
hi @cmastr - could someone from the team please review this PR?

2024-07-22 13:54 UTC, tcgilbert requested changes
A couple changes to make.

And a couple of things that stood out to me as well: 
- The screenshots submitted show the `dev` logo. Note that your integration will have the Taboola logo present once you submit your catalog metadata in the developer portal: https://app.segment.com/dev-portal/overview. 

- The name for the destination is currently `Taboola (actions)`, but the standard is to have actions capitalized: `Taboola (Actions)`. Would you like for me to process this name change?

2024-07-22 13:54 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +---
```suggestion
---
title: Taboola Actions Destination
id: 66684ba89c0523461d8bb7f3
beta: true
---
```

2024-07-22 13:54 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +
```suggestion
   {% include components/actions-fields.html %}
```

Add this snippet so the actions are populated^

2024-07-22 15:08 UTC, eden-ohana commented
> A couple changes to make.
> 
> And a couple of things that stood out to me as well:
> 
> * The screenshots submitted show the `dev` logo. Note that your integration will have the Taboola logo present once you submit your catalog metadata in the developer portal: https://app.segment.com/dev-portal/overview. Not a dealbreaker, but if you want to come back and change these, you can.
> * The name for the destination is currently `Taboola (actions)`, but the standard is to have actions capitalized: `Taboola (Actions)`. Would you like for me to process this name change?

@tcgilbert 
Could you send me an invitation to join the Segment Developer Portal to add the metadata? 

I'd appreciate it if you could make the name change.

Thanks.

2024-07-22 15:43 UTC, tcgilbert commented
> @tcgilbert Could you send me an invitation to join the Segment Developer Portal to add the metadata?

Looks like you should already have access. Are you able to log into Segment with eden.o@taboola.com, and navigate to the portal here: https://app.segment.com/dev-portal/overview

<img width="519" alt="Screenshot 2024-07-22 at 11 34 58 AM" src="https://github.com/user-attachments/assets/cd83630a-094a-4732-ad29-9909fc6cae78">

If your Segment account is associated with a different email address, let me know and I can send an invite to it. 

 
> I'd appreciate it if you could make the name change.

Copy that, I've opened a PR for this here: https://github.com/segmentio/action-destinations/pull/2204. No action needed from you

2024-07-23 09:41 UTC, eden-ohana commented
Hi @tcgilbert I submitted the metadata for review

2024-07-23 13:36 UTC, tcgilbert commented
@eden-ohana @joe-ayoub-segment 
 
I've approved your catalog info submission, and this metadata will go live along with your integration. 

Do you know when you would like to move the integration into Public Beta? We have all the materials needed on our end, so if you are done testing the destination, and are confident it is working as expected, I can go ahead and make the integration live.

2024-07-24 09:49 UTC, eden-ohana commented
Hi @tcgilbert
I updated the screenshots with the Taboola logo. 
Our beta testers want to start using the integration, and I want to send them the documentation link. 
I would appreciate it if we could deploy this PR soon.

Regarding the private or public beta @joe-ayoub-segment, WDYT? I can send the beta users the private link but need the documentation to be public.

Thanks

2024-07-24 13:55 UTC, cmastr commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +`email` will be automatically included if present. Additional configuration steps are required in order to sync `Mobile Device ID` values. To sync `Mobile Device ID` values ensure the following confi
```suggestion
`email` will be automatically included if present. Additional configuration steps are required to sync `Mobile Device ID` values. To sync `Mobile Device ID` values ensure the following is  configured:  
```

2024-07-24 13:55 UTC, cmastr commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +1. Your Engage Space's identity resolution rules will need to be configured for `android.id` and `ios.id` identifiers. This can be configured by navigating to `Unify` >> `Unify Settings`.
```suggestion
1. Configure your Engage Space's identity resolution rules for `android.id` and `ios.id` identifiers by navigating to `Unify` >> `Unify Settings`. 
```

2024-07-24 13:55 UTC, cmastr commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +2. Ensure that both the `android.id` and `ios.id` identifiers are configured exactly as per the image below. This configuration step takes place when the Destination is being connected to an Audience
Should probably list out the identifiers in case this image is unreadable to some.

2024-07-24 13:55 UTC, cmastr commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +   * [Taboola Ads](https://ads.taboola.com) - Use the account's alphanumeric name without spaces and in lowercase. For example, 'My Account - Name' would become 'myaccountname'
```suggestion
   * [Taboola Ads](https://ads.taboola.com){:target="_blank"} - Use the account's alphanumeric name without spaces and in lowercase. For example, 'My Account - Name' would become 'myaccountname'
```

2024-07-24 13:55 UTC, cmastr commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +   * [API](https://developers.taboola.com/backstage-api/reference/get-account-details) - Retrieve Account Details using the Get Account Details API.
```suggestion
   * [API](https://developers.taboola.com/backstage-api/reference/get-account-details){:target="_blank"} - Retrieve Account Details using the Get Account Details API.
```

2024-07-24 13:55 UTC, cmastr commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +> To view the audience on the Taboola platform, navigate to the [Taboola Ads audience page](https://ads.taboola.com/audiences), select "Custom Audience" and search for the audience you have just conn
```suggestion
> To view the audience on the Taboola platform, navigate to the [Taboola Ads audience page](https://ads.taboola.com/audiences){:target="_blank"}, select "Custom Audience" and search for the audience you have just connected.
```

2024-07-24 14:21 UTC, eden-ohana commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +2. Ensure that both the `android.id` and `ios.id` identifiers are configured exactly as per the image below. This configuration step takes place when the Destination is being connected to an Audience
The identifiers are android.id and ios.id and are listed. I can add a table like the images, but then it will look duplicated when the image is presented

2024-07-24 14:47 UTC, tcgilbert requested changes
One last change from me, other than that looks good

2024-07-24 14:47 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-taboola-actions/index.md
> +This destination is maintained by Taboola. For any issues with the destination, contact their Support team or your account manager.
```suggestion
This destination is maintained by Taboola. For any issues with the destination, contact their [Support team](mailto:support@taboola.com) or your account manager.
```

Do you have a support email address you can add?

2024-07-24 15:06 UTC, tcgilbert approved these changes

2024-07-24 19:09 UTC, eden-ohana commented
Hi @cmastr can you please review

2024-07-24 21:16 UTC, cmastr approved these changes

2024-07-24 21:17 UTC, cmastr commented
Merging now, will go live on Thursday.

2024-07-24 21:17 UTC, merged