Adding a new topic about duplicate events
segmentio/segment-docs pull request #6843
Opened 2024-07-22 14:43 UTC by prigiattiperrut

### Proposed changes

Adding a solution for customers to avoid GTM tags firing on duplicate events.

### Merge timing
ASAP once approved

2024-07-24 16:10 UTC, forstisabella requested changes

2024-07-24 16:10 UTC, forstisabella commented on src/connections/destinations/catalog/google-tag-manager/index.md
> +This solution has been shared by other customers. Please test it before implementing it with production data. If you have any questions regarding the GTM setup, consult the [GTM documentation](https:
```suggestion
```

2024-07-24 16:10 UTC, forstisabella commented on src/connections/destinations/catalog/google-tag-manager/index.md
> +3. Add the newly created variable to your GTM trigger so that only events containing `eventModel = GTM will` trigger the tag.
```suggestion
3. Add the newly created variable to your GTM trigger so that only events containing `eventModel = GTM` trigger the tag.
```

2024-07-24 16:10 UTC, forstisabella commented on src/connections/destinations/catalog/google-tag-manager/index.md
> +In reviewing the "dataLayer" tab for each event in GTM, it was observed that the `eventModel` field, which is an internal Google field, is only present in events captured by the Google Ads SDK. To pr
```suggestion
On the dataLayer, you might find the `eventModel` field, which is an internal Google field only present in events captured by the Google Ads SDK. To prevent GTM tags from creating duplicate events, you can create a GTM variable and use `eventModel` as a condition to filter events.

> warning "The following solution was shared by a Segment customer and is not officially endorsed by Segment"
> Please test this solution before implementing it with production data. If you have any questions about the GTM setup, consult the [GTM documentation](https://support.google.com/tagmanager/answer/6103657?hl=en){:target="_blank"}.
```

2024-07-24 16:10 UTC, forstisabella commented on src/connections/destinations/catalog/google-tag-manager/index.md
> +### Duplicate Events triggering GTM tags multiple times
```suggestion
```

2024-07-30 15:45 UTC, forstisabella commented on src/connections/destinations/catalog/google-tag-manager/index.md
> +In reviewing the "dataLayer" tab for each event in GTM, it was observed that the `eventModel` field, which is an internal Google field, is only present in events captured by the Google Ads SDK. To pr
@prigiattiperrut - can you double-check this language before I merge this PR? I just want to be sure we're on the same page 😄

2024-08-14 09:08 UTC, prigiattiperrut commented on src/connections/destinations/catalog/google-tag-manager/index.md
> +In reviewing the "dataLayer" tab for each event in GTM, it was observed that the `eventModel` field, which is an internal Google field, is only present in events captured by the Google Ads SDK. To pr
That's great! Thanks, @forstisabella!

2024-08-14 15:29 UTC, forstisabella approved these changes

2024-08-14 15:29 UTC, merged