Documentation for Plotline Direct Destination
segmentio/segment-docs pull request #6879
Opened 2024-07-31 10:03 UTC by plotline-insights

### Proposed changes

Added documentation for Plotline Direct Destination

### Merge timing

ASAP

2024-07-31 19:51 UTC, tcgilbert requested changes

2024-07-31 19:51 UTC, tcgilbert commented on src/connections/destinations/catalog/plotline/index.md
> +[Plotline](https://www.plotline.so/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners) is a mobile adoption platform that helps product and marketing teams launch experiences like Stories, V
```suggestion
[Plotline](https://www.plotline.so/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank”} is a mobile adoption platform that helps product and marketing teams launch experiences like Stories, Videos, Animations, Streaks, Floating buttons and more inside the app - without taking engineering effort.
```

2024-07-31 19:51 UTC, tcgilbert commented on src/connections/destinations/catalog/plotline/index.md
> +---
```suggestion
---
title: Plotline Destination
id: 669f7b835aae8164929d000e
beta: true
---
```

2024-07-31 19:51 UTC, tcgilbert commented on src/connections/destinations/catalog/plotline/index.md
> +3. Select an existing Source to connect to .
```suggestion
3. Select an existing Source to connect to.
```

2024-07-31 19:51 UTC, tcgilbert commented on src/connections/destinations/catalog/plotline/index.md
> +4. Go to [Plotline's dashboard](app.plotline.so), navigate to "Credentials" and copy the API key.
```suggestion
4. Go to [Plotline's dashboard](app.plotline.so){:target="_blank”}, navigate to "Credentials" and copy the API key.
```

2024-08-02 14:01 UTC, tcgilbert approved these changes

2024-08-06 14:44 UTC, pwseg approved these changes

2024-08-06 14:44 UTC, merged