feat: added topsort events destination docs
segmentio/segment-docs pull request #6952
Opened 2024-08-19 14:23 UTC by agustinespildora

>[!NOTE]  
>READY FOR REVIEW

### Proposed changes

This is the docs entry for the new Topsort Destination. Any comment, syntax or anything I missed please let me know.

### Merge timing

Not urgent at the moment. The sooner the better though.

2024-08-19 16:35 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +This is a destination for eCommerce sites that want to use Segment, or are already using it, to Track actions on their site. It helps you seamlessly integrate Topsort events for sponsored listings.
```suggestion
```

2024-08-19 16:35 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +
```suggestion
[Topsort](https://www.topsort.com){:target="_blank"} is an AI-powered retail media platform enabling retailers and marketplaces to build their own high-performing ad networks, rivaling Google and Amazon. With its advanced auto-bidding algorithm and fast integration, Topsort provides an advertising solution that delivers exceptional returns on ad spend (ROAS) while respecting users privacy by being cookie-less.

This is a destination for eCommerce sites that want to use Segment or are already using it to Track actions on their site. It helps you seamlessly integrate Topsort events for sponsored listings.
```

2024-08-19 16:35 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +Events integration is one of the 3 steps to integrate with Topsort (see [Integration Overview](https://docs.topsort.com/reference/integration-overview){:target="_blank"} for more details). It allows
```suggestion
Setting up an events integration is one of the 3 steps to integrate with Topsort (see [Integration Overview](https://docs.topsort.com/reference/integration-overview){:target="_blank"} for more details). It allows marketplaces to have a full metrics report available through Topsort's Reporting API or directly in the [Topsort Manager Platform](https://app.topsort.com){:target="_blank"} dashboards. It also provides the necessary information for the Topsort team to display relevant ads, optimize budget consumption, attribute purchases and accomplish sellers' conversion goals.
```

2024-08-19 16:35 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +<!-- The section below explains how to enable and configure the destination. Include any configuration steps not captured below. For example, obtaining an API key from your platform and any configura
```suggestion
```

2024-08-19 16:35 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +This destination will help you track the 3 main events Topsort needs to serve the most relevant ads and accomplish attribution for sponsored listings: `impressions`, `clicks` and `purchases`. Here is
```suggestion
This destination helps you track the 3 main events Topsort needs to serve the most relevant ads and accomplish attribution for sponsored listings: `impressions`, `clicks` and `purchases`. Here is an explanation of what each one of these means to Topsort:
```

2024-08-19 16:35 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +3. **Purchase**: Finally, when an order is completed and confirmed to be successful, a `purchase` event should be reported to Topsort. You can report a purchase whether it has promoted products or no
```suggestion
- **Impression**: Every time a user sees a promoted product in a listing page (PLP) or section, you should trigger an `impressions` event.
- **Click**: If the user then clicks or adds the promoted product to a cart, you should trigger a `click` event.
- **Purchase**: When an order is completed and confirmed to be successful, report a `purchase` event to Topsort. You can report a purchase whether it has promoted products or not. Topsort takes care of filtering relevant promoted products inside the completed order given the information about promoted clicks.
```

2024-08-19 16:35 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +This destination has 3 default presets that map the Track events `'Product Viewed'`, `'Product Clicked'` and `'Order Completed'` to Topsort's `impression`, `click` and `purchase` events respectively.
```suggestion
This destination has 3 default presets that map the Track events `'Product Viewed'`, `'Product Clicked'` and `'Order Completed'` to Topsort's `impression`, `click` and `purchase` events, respectively. If you’re not familiar with the Segment Spec, take a look to understand what the [Track method](/docs/connections/spec/track/) does. 

The mappings in the Topsort destination are built based on the Segment [Ecommerce Spec](/docs/connections/spec/ecommerce/v2/). If you have different Segment Track events mapped to these action definitions, then Topsport can adapt this destination to your case. Once the destination is configured, activate only the mappings relevant to your site. See point 5 of the [set up](#set-up-your-topsort-destination) for more details.
```

2024-08-19 16:35 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +You don't need to change anything about the way you report Track events to segment. The only extra field you need to provide, only for the `impression` and `click` events, is the `resolvedBidId` give
```suggestion
You don't need to change anything about the way you report Track events to Segment. The only extra field you need to provide, only for the `impression` and `click` events, is the `resolvedBidId` given in the winner promoted product (whether it is from the [Auctions API](https://docs.topsort.com/reference/createauctions){:target="_blank"} or the [proxy](https://docs.topsort.com/reference/listings-low-code){:target="_blank"} response). Please find below an example call to track a product listing page (PLP) click event with the `resolvedBidId` included:
```

2024-08-19 16:35 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +3. In the [Topsort Manager Platform](https://app.topsort.com){:target="_blank"}, go to [Settings > API Integration](https://app.topsort.com/new/es/marketplace/account-settings/api-integration){:targe
```suggestion
3. In the [Topsort Manager Platform](https://app.topsort.com){:target="_blank"}, go to [Settings > API Integration](https://app.topsort.com/new/es/marketplace/account-settings/api-integration){:target="_blank"} to find or create your **Marketplace API Key** for auctions and events.
```

2024-08-19 16:35 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +4. Go back to the Topsort destination on the segment app and enter the value for your **Marketplace API Key**.
```suggestion
4. Return to the Topsort destination in the Segment app and enter the value for your **Marketplace API Key**.
```

2024-08-19 16:35 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +5. Make sure to enable only the Track events relevant to your site and so that the events do not get duplicated with a single user action. For example: If you always trigger a `Product Clicked` event
```suggestion
5. Enable only the Track events relevant to your site and so that the events do not get duplicated with a single user action. For example, if you always trigger a `Product Clicked` event together with the `Product Added` event when a user makes a click in the "Add to cart" button, then you should enable only the `Product Clicked` event for the Topsort Destination.
```

2024-08-19 16:35 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +Topsort strongly recommends that you identify your logged-in users using Segment's [Identify method](/docs/connections/spec/identify/) and that you hash the user ID before sending it to Topsort.
```suggestion
Topsort recommends that you identify your logged-in users using Segment's [Identify method](/docs/connections/spec/identify/) and that you hash the user ID before sending it to Topsort.
```

2024-08-21 13:22 UTC, tcgilbert requested changes
Some changes and questions. Please address all of @forstisabella' s suggestions as well

2024-08-21 13:22 UTC, tcgilbert commented on src/connections/destinations/catalog/topsort/index.md
> +Users that are not logged in can be tracked using an [anonymousID](/docs/connections/spec/identify/#anonymous-id).
```suggestion
```

This is only true for analytics.js sources (browser sources). It's possible that they may collect their events from a server side source in which this is not true. 

that being the case I would remove this

2024-08-21 13:22 UTC, tcgilbert commented on src/connections/destinations/catalog/topsort/index.md
> +Topsort recommends that you identify your logged-in users using Segment's [Identify method](/docs/connections/spec/identify/) and that you hash the user ID before sending it to Topsort.
```suggestion
Topsort recommends that you identify your logged-in users using Segment's [Identify method](/docs/connections/spec/identify/) and that you hash the user ID before sending it to Topsort.
```

Hashing userId's for one specific destination is not something users would do lightly. If their users are not already hashed, then this would double the amount of users in their Segment workspace which has billing and other downstream destination consequences. 

Is having a hased userId in Topsort required? If so, then I would update the integration code to hash the identifier used rather assuming that it is hashed already

2024-08-21 13:22 UTC, tcgilbert commented on src/connections/destinations/catalog/topsort/index.md
> +
```suggestion
{% include components/actions-fields.html %}
```

add snippet to populate action tables

2024-08-21 18:15 UTC, agustinespildora commented on src/connections/destinations/catalog/topsort/index.md
> +Topsort recommends that you identify your logged-in users using Segment's [Identify method](/docs/connections/spec/identify/) and that you hash the user ID before sending it to Topsort.
Hi @tcgilbert thanks for the comment. No, it is not necessary to hash the identifier actually. One question though, what happens if a 'Product Clicked' event is triggered, then the user is identified with segment's method, and then an 'Order Completed' is triggerd afterwards. Would the anonymousId change between the 'Product Clicked' and the 'Order Completed' events? How is this anonymousId set exactly?
I want to understand if it would persist in case a user logs in.

2024-08-21 20:53 UTC, agustinespildora commented on src/connections/destinations/catalog/topsort/index.md
> +Users that are not logged in can be tracked using an [anonymousID](/docs/connections/spec/identify/#anonymous-id).
Changed it so that is explicit that we refer to mobile and browser sources with analytics.js

2024-08-21 20:54 UTC, agustinespildora commented on src/connections/destinations/catalog/topsort/index.md
> +Topsort recommends that you identify your logged-in users using Segment's [Identify method](/docs/connections/spec/identify/) and that you hash the user ID before sending it to Topsort.
Removed the part that refers to hashing the user ID

2024-08-21 22:20 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +The mappings in the Topsort destination are built based on the Segment [Ecommerce Spec](/docs/connections/spec/ecommerce/v2/). If you have different Segment Track events mapped to these action defini
```suggestion
The mappings in the Topsort destination are built based on the Segment [Ecommerce Spec](/docs/connections/spec/ecommerce/v2/). If you have different Segment Track events mapped to these action definitions, then Topsort can adapt this destination to your case. Once the destination is configured, activate only the mappings relevant to your site. See point 5 of the [set up](#set-up-your-topsort-destination) for more details.
```

2024-08-21 22:21 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +{% include components/actions-fields.html %}
This `include` needs a blank line before and after it for it to run properly afaik
```suggestion

{% include components/actions-fields.html %}
```

2024-08-21 22:22 UTC, forstisabella commented on src/connections/destinations/catalog/topsort/index.md
> +If you use a server side source please provide one of both options, anonymousId or userId.
```suggestion
If you use a server side source please provide one or more identifiers: `anonymousId` or `userId`.
```

2024-08-21 22:23 UTC, forstisabella reviewed
a few small comments and we'll be ready to ship this!

2024-08-21 23:01 UTC, agustinespildora commented
Ready! Thanks so much for the reviews @tcgilbert @forstisabella

2024-08-22 17:24 UTC, forstisabella approved these changes

2024-08-22 17:44 UTC, tcgilbert requested changes
In addition to these changes, can you update the folder name to "actions-topsort". 
- `topsort/index.md` -> `actions-topsort/index.md`

This needs to be the same as the slug for your destination

2024-08-22 17:44 UTC, tcgilbert commented on src/connections/destinations/catalog/topsort/index.md
> +```
```suggestion
```

2024-08-22 17:44 UTC, tcgilbert commented on src/connections/destinations/catalog/topsort/index.md
> +```
moved this down next to ### Identify

2024-08-22 17:44 UTC, tcgilbert commented on src/connections/destinations/catalog/topsort/index.md
> +
```suggestion
### Track

You don't need to change anything about the way you report Track events to Segment. The only extra field you need to provide, only for the `impression` and `click` events, is the `resolvedBidId` given in the winner promoted product (whether it is from the [Auctions API](https://docs.topsort.com/reference/createauctions){:target="_blank"} or the [proxy](https://docs.topsort.com/reference/listings-low-code){:target="_blank"} response). Please find below an example call to track a product listing page (PLP) click event with the `resolvedBidId` included:

```js
analytics.track("Product Clicked", {
  product_id: product.id,
  name: product.name,
  resolvedBidId: product.resolvedBidId
});
```
```

2024-08-22 17:44 UTC, tcgilbert commented on src/connections/destinations/catalog/topsort/index.md
> +beta: true
```suggestion
```

the integration status is actually automated now, so can remove

2024-08-23 13:28 UTC, tcgilbert approved these changes

2024-08-23 13:30 UTC, tcgilbert commented
@agustinespildora thanks for the changes. We have everything on our side to make the integration live. 

If you have tested your destination and confirmed it is working as expected, we can get this live on the next docs deployment next week.

2024-08-23 15:50 UTC, forstisabella approved these changes

2024-08-28 12:39 UTC, agustinespildora commented
Hi team! Do you know when is the next deploy?

2024-08-28 15:35 UTC, forstisabella commented
hi @agustinespildora - I'll merge this PR today, and the changes will be live tomorrow after 11AM Pacific time. Thanks!

2024-08-28 15:35 UTC, merged