Added FAQ Section Including Common Question/Answer Regarding Timestamp Discrepancies
segmentio/segment-docs pull request #6980
Opened 2024-08-26 14:15 UTC by prigiattiperrut

### Proposed changes
* Introduced a new FAQ section in the documentation.
* Included a detailed explanation of common causes for timestamp discrepancies when using Segment's client-side libraries.

### Merge timing
ASAP once approved

### Related issues (optional)

Slack: https://twilio.slack.com/archives/CALA7QMJQ/p1724679975057569

2024-08-26 14:17 UTC, alanjcharles approved these changes
amazing- thank you!!

2024-08-27 04:31 UTC, silesky approved these changes

2024-08-27 17:16 UTC, stayseesong requested changes

2024-08-27 17:16 UTC, stayseesong commented on src/connections/spec/common.md
> +   - [Internet Bots](https://segment.com/docs/guides/ignore-bots/#whats-a-bot) can sometimes send requests with unusual timestamps, either intentionally or due to incorrect settings, leading to discr
```suggestion
* **Overriding Timestamp Value:**  When a manual timestamp is set in the payload with a date in the past, it can cause events to appear as if they were sent earlier than they actually were.
* **Analytics.js Source with Retries Enabled:** The [Retries](/docs/connections/sources/catalog/libraries/website/javascript/#retries) feature supports offline traffic by queuing events in Analytics.js. These events are sent or retried later when an internet connection is available, keeping the original timestamp intact.
* **Mobile App Backgrounded or Closed:** If a user closes the app, events may be queued within the app. These queued events won't send until the app is re-opened, potentially in the future, leading to timestamp discrepancies.
* **Inaccurate Browser/Device Clock Settings:** Timestamps can be incorrect if the client's device time is inaccurate, as the `originalTimestamp` relies on the client device's clock, which can be manually adjusted.
* **Traffic from Internet Bots:**  [Internet Bots](/docs/guides/ignore-bots/#whats-a-bot) can sometimes send requests with unusual timestamps, either intentionally or due to incorrect settings, leading to discrepancies.
```

2024-08-27 17:17 UTC, stayseesong approved these changes

2024-08-27 17:17 UTC, merged