Mappings 2.0 [DOC-990]
segmentio/segment-docs pull request #7006
Opened 2024-09-04 16:58 UTC by forstisabella

### Proposed changes
Added content to RETL and Destinations pages about Simplified Mappings functionality

### Merge timing
9/10/2024

### Related issues (optional)
DOC-974

2024-09-09 18:14 UTC, stayseesong requested changes

2024-09-09 18:14 UTC, stayseesong commented on src/connections/destinations/index.md
> +In September 2024, Segment released a new sync modes capability that allows users to define how changes in the source should be sent downstream to your destination. Depending on which destinations yo
```suggestion
In September 2024, Segment released a new sync mode capability that allows users to define how changes in the source should send downstream to your destination. Depending on which destinations you set up in Segment, you may need to choose a sync mode for your data. This configuration determines how Segment updates your destination based on the source data. 
```

2024-09-09 18:14 UTC, stayseesong commented on src/connections/destinations/index.md
> +In September 2024, Segment released a new sync modes capability that allows users to define how changes in the source should be sent downstream to your destination. Depending on which destinations yo
Do we need to say "In September 2024, Segment released..."? Just wondering because for every new feature or update, we don't say when it came out.

2024-09-09 18:14 UTC, stayseesong commented on src/connections/reverse-etl/setup.md
> +5. In the Define sync behavior section, select the **Action** you want to sync.
Is "Define sync behavior" the name of the section in the app? Should it be bolded then?

2024-09-09 18:14 UTC, stayseesong commented on src/connections/reverse-etl/setup.md
> +   * As of September 2024, some destinations have [sync modes](/docs/connections/destinations/#sync-modes), which let you specify how Segment should send data to the destination. Sync modes are uniqu
Do we need to put the date in there "As of September 2024..." I think it'll be better without it. Can just say, "Some destinations have sync modes"

2024-09-09 21:33 UTC, forstisabella commented on src/connections/destinations/index.md
> +In September 2024, Segment released a new sync modes capability that allows users to define how changes in the source should be sent downstream to your destination. Depending on which destinations yo
yeah, fair point - I did this to match with the Destination Actions section that's above it, but it's probably overkill

2024-09-09 21:37 UTC, forstisabella commented on src/connections/reverse-etl/setup.md
> +5. In the Define sync behavior section, select the **Action** you want to sync.
Name of the section

2024-09-09 21:37 UTC, forstisabella commented on src/connections/reverse-etl/setup.md
> +   * As of September 2024, some destinations have [sync modes](/docs/connections/destinations/#sync-modes), which let you specify how Segment should send data to the destination. Sync modes are uniqu
```suggestion
   * Some destinations have [sync modes](/docs/connections/destinations/#sync-modes), which let you specify how Segment should send data to the destination. Sync modes are unique to each destination. 
```

2024-09-09 21:39 UTC, forstisabella commented on src/connections/reverse-etl/setup.md
> +5. In the Define sync behavior section, select the **Action** you want to sync.
```suggestion
5. In the **Define sync behavior** section, select the **Action** you want to sync.
```

2024-09-09 21:41 UTC, forstisabella commented on src/connections/destinations/index.md
> +- **Insert**: Add new records without altering existing data.
```suggestion
```

2024-09-09 22:51 UTC, stayseesong approved these changes

2024-09-09 22:51 UTC, stayseesong commented on src/connections/destinations/index.md
> +Segment released a new sync mode capability that allows users to define how changes in the source should send downstream to your destination. Depending on which destinations you set up in Segment, yo
```suggestion
Sync mode capability allows users to define how changes in the source should send downstream to your destination. Depending on which destinations you set up in Segment, you may need to choose a sync mode for your data. This configuration determines how Segment updates your destination based on the source data. 
```

2024-09-10 14:14 UTC, stayseesong approved these changes

2024-09-10 17:16 UTC, merged