Retl 2.0 feedback
segmentio/segment-docs pull request #7015
Opened 2024-09-09 20:33 UTC by forstisabella

### Proposed changes
Implemented fast-follow feedback from the Reverse ETL 2.0 post-launch group. 

Changes made to individual files are for RETL catalog fixes, as the docs catalog was missing two destinations that the in-app catalog had (Sprig (Actions) and StackAdapt (Actions))

### Merge timing
9/10/24 during the regular docs release

### Related issues (optional)
#6571

2024-09-09 23:01 UTC, stayseesong requested changes

2024-09-09 23:01 UTC, stayseesong commented on src/connections/reverse-etl/setup.md
> +In the field dropdown selection, disable the Sync null values toggle.
```suggestion
To opt out of including null values in your downstream syncs:
1. Navigate to Connections > Destinations and select the Reverse ETL tab.
2. Select the destination and the mapping you want to edit.
3. Click Edit mapping.
4. Under **Optional fields**, select the field you want to edit.
5. In the field dropdown selection, disable the **Sync null values** toggle.
```

2024-09-10 13:31 UTC, forstisabella commented on src/connections/reverse-etl/reverse-etl-catalog.md
> +Reverse ETL supports the entire Segment destination catalog - Actions destinations are natively supported and all other destinations are supported through the [Segment Connections](#segment-connectio
```suggestion
Reverse ETL supports the Actions destinations listed in this catalog. Most destinations not listed here are supported through the [Segment Connections](#segment-connections-destination) destination. 
```

2024-09-10 13:56 UTC, forstisabella commented on src/connections/reverse-etl/system.md
> +Record count | The maximum number of records a single sync will process. Note: This is the number of records extracted from the warehouse not the limit for the number of records loaded to the destina
```suggestion
Record count | The maximum number of records a single sync will process. If a sync would contain more than 150 million records, Segment separates the data into multiple syncs, each containing no more than 150 million records. 
 <br><br> Note: This is the number of records extracted from the warehouse, not the limit for the number of records loaded to the destination (for example, new/update/deleted). | <sup>*</sup>150 million records
```

2024-09-10 13:57 UTC, forstisabella commented on src/connections/reverse-etl/system.md
> + <br><br> Note: This is the number of records extracted from the warehouse, not the limit for the number of records loaded to the destination (for example, new/update/deleted). | <sup>*</sup>150 mill
```suggestion
Record count | The maximum number of records a single sync will process. If a sync would contain more than 150 million records, Segment separates the data into multiple syncs, each containing no more than 150 million records <br><br> Note: This is the number of records extracted from the warehouse, not the limit for the number of records loaded to the destination (for example, new/update/deleted). | <sup>*</sup>150 million records
```

2024-09-10 14:12 UTC, stayseesong approved these changes

2024-09-10 17:16 UTC, merged