Add documentation for Recombee (Actions) destination
segmentio/segment-docs pull request #7049
Opened 2024-09-19 15:08 UTC by mstieranka

### Proposed changes

Hello,

Here at Recombee, we were asked to develop a new version of our existing [Recombee AI](https://segment.com/docs/connections/destinations/catalog/recombee-ai/) destination that would use the new Action Destinations framework.

This pull request contains the documentation to this new destination, called _Recombee (Actions)_, as well as changes to the old destination (such as deprecating it and changing the wording in some places).

### Merge timing

Probably should be merged after the implementation pull request in the **action-destinations** repository is merged:

https://github.com/segmentio/action-destinations/pull/2429

2024-09-19 15:48 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +- *The following change only affects users that were relying on the `name` property to set their **Item ID**:* In presets, the **Item ID** property is now determined differently - in the default sett
Could we move this section to the top?

2024-09-19 15:48 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +You can inform Recombee that a specific interaction resulted from a successful recommendation (meaning the recommendations were presented to a user, and the user clicked on one of the items) by setti
```suggestion
You can inform Recombee that a specific interaction resulted from a successful recommendation (meaning the recommendations were presented to a user, and the user clicked on one of the items) by setting the ID of the successful recommendation request in the `Recommendation ID` field of the action (this is the `recomm_id` property by default). You can read more about this setting in Recombee's [Reported Metrics documentations](https://docs.recombee.com/admin_ui.html#reported-metrics){:target="_blank"}
```

2024-09-19 15:48 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +  - Click the ID of an Item (or User) in the Items (or Users) catalog section in the Admin UI to view a specific ingested interaction.
We use "select" for items where you pick something from a list

```suggestion
  - Select the ID of an Item (or User) in the Items (or Users) catalog section in the Admin UI to view a specific ingested interaction.
```

2024-09-19 15:48 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +  - Go to the KPI console of the [Recombee Admin UI](https://admin.recombee.com){:target="_blank"} to see the numbers of the ingested interactions (updated in Real-time)
```suggestion
  - Open the KPI console of the [Recombee Admin UI](https://admin.recombee.com){:target="_blank"} to see the numbers of the ingested interactions (updated in realtime).
```

2024-09-19 15:48 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +6. Back in the Segment web app, go to the Recombee destination settings.
```suggestion
6. Back in the Segment app, navigate to the settings page of the Recombee destination you created.
```

2024-09-19 15:48 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +Use this Segment destination to send your interaction data (views, purchases, plays, etc.) to Recombee.
We avoid using Latin phrases like e.g. and etc. in the docs, as they're not universally understood. 
```suggestion
Use this Segment destination to send your interaction data (for example, views, purchases, and plays) to Recombee.
```

2024-09-19 15:48 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +5. Go to the [Recombee Admin UI](https://admin.recombee.com){:target="_blank"}:
```suggestion
5. Navigate to the [Recombee Admin UI](https://admin.recombee.com){:target="_blank"} and complete the following actions:
```

2024-09-20 14:06 UTC, tcgilbert requested changes
just need to add `hidden` as the destination has not been reviewed yet

2024-09-20 14:06 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-recombee/index.md
> +---
```suggestion
---
title: Recombee (Actions) Destination
hidden: true
versions:
  - name: Recombee AI
    link: /docs/connections/destinations/catalog/recombee-ai     
---
```

2024-09-20 16:35 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-recombee/index.md
> +---
@forstisabella not yet

2024-09-30 14:50 UTC, mstieranka commented on src/connections/destinations/catalog/actions-recombee/index.md
> +Use this Segment destination to send your interaction data (views, purchases, plays, etc.) to Recombee.
Fixed, but used `or` instead of `and` as it's up to the customers to select what types of data they want to send.

2024-09-30 14:51 UTC, mstieranka commented on src/connections/destinations/catalog/actions-recombee/index.md
> +- *The following change only affects users that were relying on the `name` property to set their **Item ID**:* In presets, the **Item ID** property is now determined differently - in the default sett
Moved.

2024-10-02 15:00 UTC, tcgilbert requested changes
just need to add the id

2024-11-19 14:59 UTC, mstieranka commented
Hi @tcgilbert @forstisabella , I don't mean to bother, but I fixed all of the issues that you brought up.

Would it be possible to do a final review and merge? Thanks.

---

By the way, we have also prepared the catalog info from our side, but we haven't yet submitted it for review, since I'm not sure which one of these things to do first.

2024-11-19 15:44 UTC, forstisabella approved these changes

2024-11-19 15:44 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +- **Streamlined Configuration**. You can now create mappings in a dedicated tab in the Segment web app, as opposed to needing to edit this in the settings. This allows you to configure the mappings o
```suggestion
- **Streamlined Configuration**: You can now create mappings in a dedicated tab in the Segment web app, as opposed to needing to edit this in the settings. This allows you to configure the mappings on a per-event basis and makes it easier to verify that your mappings work as intended.
```

2024-11-19 15:44 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +- **Removing Bookmarks is now possible**. You can now configure a mapping to send a *Delete Bookmark* Action, which will remove the bookmark interaction from the Recombee database.
```suggestion
- **Removable Bookmarks**: You can now configure a mapping to send a *Delete Bookmark* Action, which removes the bookmark interaction from the Recombee database.
```

2024-11-19 15:44 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +It is recommended that for each source, the Recombee (Actions) destination and the classic Recombee AI destination are not enabled at the same time in order to prevent errors.
```suggestion
Recombee recommends ensuring that a Recombee (Actions) destination and a classic Recombee AI destination connected to the same source are not enabled at the same time in order to prevent errors.
```

2024-11-19 15:44 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +Compared to the classic Recombee AI destination, the following changes were made with regards to the configuration:
```suggestion
Compared to the classic Recombee AI destination, the following configuration changes were made:
```

2024-11-19 15:44 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +- In the destination settings, the **API Key** setting has been renamed to **Private Token** to better reflect the type of token used.
```suggestion
- In the destination settings, the **API Key** setting was renamed **Private Token** to better reflect the type of token used.
```

2024-11-19 15:44 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +- The **Track Events Mapping** setting has been removed. If you want to map custom events to Recombee interactions, make sure to create your own mappings in the Mappings tab in the Segment web app.
```suggestion
- The **Track Events Mapping** setting has been removed. If you want to map custom events to Recombee interactions, create your own mappings in the Mappings tab in the Segment app.
```

2024-11-19 15:44 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +Once you send the data from Segment to the Recombee destination you can:
```suggestion
Once you send the data from Segment to the Recombee destination, you can:
```

2024-11-19 15:44 UTC, forstisabella commented
> Hi @tcgilbert @forstisabella , I don't mean to bother, but I fixed all of the issues that you brought up.
> 
> Would it be possible to do a final review and merge? Thanks.
> 
> By the way, we have also prepared the catalog info from our side, but we haven't yet submitted it for review, since I'm not sure which one of these things to do first.

It's no bother!

2024-11-19 18:14 UTC, forstisabella submitted a review, later dismissed

2024-11-25 20:16 UTC, tcgilbert commented
@forstisabella feel free to merge this

2024-12-02 15:56 UTC, tcgilbert requested changes
@mstieranka please add these changes in regards to removing (Actions) from the title, as discussed in the support ticket

2024-12-02 15:56 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-recombee/index.md
> +title: Recombee (Actions) Destination
```suggestion
title: Recombee Destination
```

2024-12-02 15:56 UTC, tcgilbert commented on src/connections/destinations/catalog/recombee-ai/index.md
> +maintenance: true
```suggestion
maintenance: true
maintenance-content: This destination is no longer available in the Segment catalog but will remain active in workspaces where it has already been installed. Recombee has developed an updated destination built on the Actions framework. See [Recombee Destination](/docs/connections/destinations/catalog/actions-recombee/) for more information.
```

2024-12-02 15:56 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-recombee/index.md
> +Recombee (Actions) provides the following benefits over the classic Recombee destination:
```suggestion
The new Recombee destination built on the Segment Actions framework provides the following benefits over the classic Recombee AI destination:
```

2024-12-03 14:37 UTC, mstieranka commented
@tcgilbert I committed the suggestions, I also saw there are still some mentions of "Recombee (Actions)" in the text itself, but it seems like a good shorthand for the new destination, so I chose to keep it the way it is now

2024-12-04 13:17 UTC, tcgilbert requested changes

2024-12-04 13:17 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-recombee/index.md
> +3. Select **Recombee (Actions)** and click **Add Destination**.
```suggestion
3. Select **Recombee** and click **Add Destination**.
```

2024-12-04 13:17 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-recombee/index.md
> +4. Select an existing Source to connect to Recombee (Actions).
```suggestion
4. Select an existing Source to connect to Recombee.
```

2024-12-04 13:18 UTC, tcgilbert commented
@mstieranka 
> I committed the suggestions, I also saw there are still some mentions of "Recombee (Actions)" in the text itself, but it seems like a good shorthand for the new destination, so I chose to keep it the way it is now

I requested changing it in too more spots, as this clarifies what name will actually be shown in the app. But yes, I agree showing (Actions) is a good shorthand everywhere else in the doc

2024-12-18 21:48 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +- **Streamlined Configuration**: You can now create mappings in a dedicated tab in the Segment web app, as opposed to needing to edit this in the settings. This allows you to configure the mappings o
```suggestion
- **Streamlined Configuration**: You can now create mappings in a dedicated tab in the Segment web app, as opposed to needing to edit this in the destination's settings. This allows you to configure the mappings on a per-event basis and makes it easier to verify that your mappings work as intended.
```

2024-12-18 21:48 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +- **Removable Bookmarks**: You can now configure a mapping to send a *Delete Bookmark* Action, which removes the bookmark interaction from the Recombee database.
```suggestion
- **Removable Bookmarks**: You can now use the [Delete Bookmark Action](#delete-bookmark) to remove the bookmark interaction from the Recombee database.
```

2024-12-18 21:48 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +Compared to the classic Recombee AI destination, the following configuration changes were made:
```suggestion
Recombee made the following configuration changes when setting up the new destination:
```

2024-12-18 21:48 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +- *The following change only affects users that were relying on the `name` property to set their **Item ID**:* In presets, the **Item ID** property is now determined differently - in the default sett
```suggestion
- Renamed the API Key setting to Private Token: This better reflects the type of token required.
- **Removed the Track Events Mapping setting**: If you want to map custom events to Recombee interactions, create your own mappings on the Mappings tab in the Segment app.
- **Removed the Item ID Property Name setting**: This functionality is now available in Segment's native Mappings tab. Ensure that your mappings use the desired property for the **Item ID** action field.
- **In presets, the **Item ID** property is determined differently**: In the default settings, the `asset_id` property (or `sku` for Ecommerce events) is now the fallback property, instead of `name`. The `name` property is never used by default, as it may not conform to the required **Item ID** format. The property `content_asset_id` (or the first ID in `content_asset_ids`,) is now the default **Item ID** only in Video events, where they are always present. 
```

2024-12-18 21:48 UTC, forstisabella commented on src/connections/destinations/catalog/actions-recombee/index.md
> +You can inform Recombee that a specific interaction resulted from a successful recommendation (meaning the recommendations were presented to a user, and the user clicked on one of the items) by setti
```suggestion
You can inform Recombee that a specific interaction resulted from a successful recommendation (meaning the recommendations were presented to a user and the user clicked on one of the items) by setting the ID of the successful recommendation request in the `Recommendation ID` field of the action (this is the `recomm_id` property by default). You can read more about this setting in Recombee's [Reported Metrics documentation](https://docs.recombee.com/admin_ui.html#reported-metrics){:target="_blank"}
```

2024-12-18 21:48 UTC, forstisabella commented on src/connections/destinations/catalog/recombee-ai/index.md
> +maintenance-content: This destination is no longer available in the Segment catalog but will remain active in workspaces where it has already been installed. Recombee has developed an updated destina
```suggestion
maintenance-content: This destination is no longer available in the Segment catalog, but will remain active in workspaces where it has already been configured. Recombee has developed an updated destination built on the Actions framework. See [Recombee Destination](/docs/connections/destinations/catalog/actions-recombee/) for more information.
```

2024-12-18 21:48 UTC, forstisabella commented on src/connections/destinations/catalog/recombee-ai/index.md
> +Use this Segment destination to send your interaction data (views, purchases, plays, etc.) to Recombee.
```suggestion
Use this Segment destination to send your interaction data, like views, purchases, or plays, to Recombee.
```

2025-01-14 13:08 UTC, mstieranka commented
Hi @tcgilbert ,

I'm looking at this before sending it over for review, and I just noticed the directory of the new documentation is `actions-recombee` instead of the destination ID, which is `recombee`.

I assume that I should change that before this is merged? Will that affect the generated ID?

2025-01-15 14:24 UTC, forstisabella approved these changes

2025-01-15 14:25 UTC, merged