Add cookie implementation details for the NPM package
segmentio/segment-docs pull request #7051
Opened 2024-09-19 15:47 UTC by niallzato

### Proposed changes
Add cookie implementation details for the NPM package.

2024-09-19 16:53 UTC, stayseesong requested changes

2024-09-19 16:53 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
> +To set these values via the [NPM package](https://github.com/segmentio/analytics-next/tree/master/packages/browser), you can set these cookie values like so:
```suggestion
To set the values using the [NPM package](https://github.com/segmentio/analytics-next/tree/master/packages/browser){:target="_blank"}, set the cookie values like to:
```

2024-11-08 16:08 UTC, niallzato commented
Hi @stayseesong apologies missed the change request, and it's no longer appearing. Good to approve/merge?

2024-11-18 13:50 UTC, niallzato commented
@stayseesong good to merge?

2024-12-18 21:53 UTC, forstisabella approved these changes

2024-12-18 23:34 UTC, stayseesong approved these changes

2024-12-18 23:34 UTC, merged