Google Campaign Manager 360 destination docs.
segmentio/segment-docs pull request #7121
Opened 2024-10-07 23:43 UTC by seg-leonelsanches

### Proposed changes

Adding docs for Google Campaign Manager 360.

### Merge timing

Whenever possible.

2024-12-16 22:26 UTC, tcgilbert submitted a review, later dismissed

2024-12-18 00:43 UTC, stayseesong requested changes

2024-12-18 00:43 UTC, stayseesong commented on src/connections/destinations/catalog/actions-google-campaign-manager-360/index.md
> +* **Required ID**: The identifier that identifies a user for the conversion. Only one value at a time can be provided, from the following fields:
```suggestion
* **Required ID**: The identifier that identifies a user for the conversion. Only one value at a time can be provided from the following fields:
```

2024-12-18 00:43 UTC, stayseesong commented on src/connections/destinations/catalog/actions-google-campaign-manager-360/index.md
> +* **Value**: The value of the conversion;
```suggestion
* **Timestamp**: The time the conversion occurred.
* **Value**: The value of the conversion.
```

2024-12-18 00:43 UTC, stayseesong commented on src/connections/destinations/catalog/actions-google-campaign-manager-360/index.md
> +  * Encrypted User ID Candidates;
@seg-leonelsanches is it necessary to include all of these fields?

2024-12-18 00:43 UTC, stayseesong commented on src/connections/destinations/catalog/actions-google-campaign-manager-360/index.md
> +* **Value**: The value of the conversion;
```suggestion
* **Timestamp**: The time the conversion occurred.
* **Value**: The value of the conversion.
```

2024-12-18 00:43 UTC, stayseesong commented on src/connections/destinations/catalog/actions-google-campaign-manager-360/index.md
> +  * Impression ID;
@seg-leonelsanches is it necessary to include all of these?

2024-12-18 16:33 UTC, seg-leonelsanches commented on src/connections/destinations/catalog/actions-google-campaign-manager-360/index.md
> +  * Encrypted User ID Candidates;
Hi @stayseesong 👋 

They are part of one field called "Required ID". Only one of them can be provided for each mapping.

2024-12-18 16:33 UTC, seg-leonelsanches commented on src/connections/destinations/catalog/actions-google-campaign-manager-360/index.md
> +  * Impression ID;
Hi @stayseesong 👋 

They are part of one field called "Required ID". Only one of them can be provided for each mapping.

2025-01-09 17:29 UTC, stayseesong approved these changes

2025-01-09 17:29 UTC, merged