Add faqs about null values
segmentio/segment-docs pull request #7143
Opened 2024-10-15 03:33 UTC by muhammadatifjav

### Proposed changes
Add FAQ about nullifying trait values in Engage

### Merge timing
- ASAP once approved

### Related issues (optional)
https://segment.atlassian.net/browse/KCS-1525

2024-11-04 21:56 UTC, stayseesong requested changes

2024-11-04 21:56 UTC, stayseesong commented on src/unify/faqs.md
> +## Can I remove a trait from a User profile?
```suggestion
## Can I remove a trait from a user profile?
```

2024-11-04 21:56 UTC, stayseesong commented on src/unify/faqs.md
> +To remove a trait from a user profile, you can send in an identify event with null as the value for the trait in the traits object from one of the connected sources. E.g. `"traits": {"trait1": null,
```suggestion
To remove a trait from a user profile, send an identify event with null as the value for the trait in the traits object from one of the connected sources. For example, `"traits": {"trait1": null, ..}, ...`. Note that sending in an empty string such as,`"traits": {"trait2": "", ..}, ...` updates the trait to be an 'empty' string and won't remove the trait from the user profile.
```

2024-11-04 21:58 UTC, stayseesong requested changes

2024-11-04 21:58 UTC, stayseesong commented on src/unify/faqs.md
> +## Can I remove a trait from a user profile?
```suggestion
### Can I remove a trait from a user profile?
```

2024-11-18 01:18 UTC, pwseg approved these changes

2024-12-18 23:30 UTC, stayseesong approved these changes

2024-12-18 23:31 UTC, merged