Add FAQ for IPv6 Collection in Analytics.js
segmentio/segment-docs pull request #7199
Opened 2024-11-05 18:10 UTC by prigiattiperrut

### Proposed changes
This PR adds an FAQ explaining that Analytics.js doesn’t automatically collect IPv6 and provides guidance on manually configuring IPv6 collection when available.

### Merge timing
ASAP once approved

2024-11-06 01:17 UTC, silesky requested changes

2024-11-06 01:17 UTC, silesky commented on src/connections/sources/catalog/libraries/website/javascript/faq.md
> +Currently, Analytics.js does not automatically collect IPv6 addresses. If IPv6 is available on the user’s device or network, the IPv6 address must be manually sent to Segment. You’ll need to configur
Can we add a link to this: https://github.com/segmentio/segment-docs/blob/develop/src/connections/sources/catalog/libraries/website/javascript/identity.md#L218

2024-11-07 23:12 UTC, silesky approved these changes

2024-11-08 18:01 UTC, stayseesong requested changes

2024-11-08 18:16 UTC, stayseesong approved these changes

2024-11-08 18:17 UTC, stayseesong approved these changes

2024-11-08 18:17 UTC, stayseesong commented on src/connections/sources/catalog/libraries/website/javascript/faq.md
> +Analytics.js doesn't automatically collect IPv6 addresses. If IPv6 is available on the user’s device or network, you must [manually send](/docs/connections/sources/catalog/libraries/website/javascrip
```suggestion
Analytics.js doesn't automatically collect IPv6 addresses. If IPv6 is available on the user’s device or network, you must [manually send](/docs/connections/sources/catalog/libraries/website/javascript/identity/#anonymizing-ip) the IPv6 address to Segment. Configure your setup to capture and pass the IPv6 address in your event payloads, as the library doesn’t collect it by default.
```

2024-11-08 18:28 UTC, stayseesong approved these changes

2024-11-08 18:28 UTC, merged