[Facebook Custom Audiences (Actions)] Updates auth prerequisites
segmentio/segment-docs pull request #7202
Opened 2024-11-06 17:55 UTC by nick-Ag

### Proposed changes

In response to this ticket: https://segment.atlassian.net/browse/STRATCONN-4137
Adding a pre-requisite for OAuth setups to the docs.

### Merge timing
ASAP once approved?

### Related issues (optional)

2024-11-06 18:00 UTC, marinhero approved these changes

2024-11-07 17:41 UTC, stayseesong requested changes

2024-11-07 17:41 UTC, stayseesong commented on src/connections/destinations/catalog/actions-facebook-custom-audiences/index.md
> +- Ensure that the user connecting to the destination via OAuth has at least an "Advertiser" or "Admin" role on the ad account. To manage permissions and roles for an ad account reference this [Facebo
```suggestion
- Ensure that the user connecting to the destination using OAuth has at least an *Advertiser* or *Admin* role on the ad account. To manage permissions and roles for an ad account, reference [Facebook's documentation](https://www.facebook.com/business/help/186007118118684?id=829106167281625){:target="_blank"}.
```

2024-11-07 17:42 UTC, stayseesong approved these changes

2024-11-07 17:42 UTC, merged