Rokt Audience Set to Publicly Available
segmentio/segment-docs pull request #7214
Opened 2024-11-11 15:59 UTC by GoodmanBen

### Proposed changes
Set the Rokt Audiences Destination docs to public.

### Merge timing
- ASAP once approved

### Related issues
N/A

2024-11-26 17:29 UTC, stayseesong commented
@GoodmanBen is this meant to be kept in draft mode?

2024-11-27 17:45 UTC, GoodmanBen commented
Hi @stayseesong thank you for checking. Yes the corresponding changes have been merged in for the linked PR, but not yet deployed due to a deploy freeze around Thanksgiving. It sounds like the changes will be deployed on the 3rd of December, at which point we will test in private beta and then release this to public beta. Will ping here once that is complete and we can move this PR out of draft mode.

2024-12-09 22:42 UTC, GoodmanBen commented
Hi @stayseesong, this has now been tested and validated in our private beta deployment and is ready for review.

2024-12-10 23:22 UTC, stayseesong requested changes

2024-12-10 23:22 UTC, stayseesong commented on src/connections/destinations/catalog/actions-rokt-audiences/index.md
> +12. Within the same panel view, select "Default Setup". You may now hit  Click **Save** in the top right corner.
```suggestion
11. Click **Add Destinations** and select the Rokt Audience (Actions) destination you created.
12. In the settings that appear on the right-hand side, toggle on the **Send Track** and **Send Identify** option.
13. Select **Default Setup**. 
14. Click **Save** in the top right corner.
```

2024-12-11 15:02 UTC, tcgilbert commented
@stayseesong can we get this included in tomorrow's deployment?

2024-12-12 01:56 UTC, stayseesong approved these changes

2024-12-12 01:56 UTC, merged