Update LinkedIn Audiences
segmentio/segment-docs pull request #7220
Opened 2024-11-13 01:22 UTC by marinhero

### Proposed changes

- Added a note specific to Linked Audiences + LinkedIn Audiences to clarify that Auto Detect is not supported for DMP User Action, and users must manually set this field to "Add" or "Remove."

- Included an additional note for Profile Audiences to provide further guidance on configuration.

### Merge timing

- ASAP once approved

### Related issues (optional)

https://segment.atlassian.net/browse/STRATCONN-4304?atlOrigin=eyJpIjoiMGMzYzIxMjI1NjE5NDRkZWIxZDcwZjFkZWY4YzRlMzUiLCJwIjoiaiJ9

2024-11-14 17:28 UTC, stayseesong requested changes

2024-11-14 17:28 UTC, stayseesong commented on src/connections/destinations/catalog/actions-linkedin-audiences/index.md
> +## Note for Segment Linked Audiences
```suggestion
## Linked Audiences
```

2024-11-14 17:28 UTC, stayseesong commented on src/connections/destinations/catalog/actions-linkedin-audiences/index.md
> +For Linked Audiences, you must set "Add" or "Remove" as the value for the **DMP User Action** field, as the **Auto Detect** option is not supported.
```suggestion
If you're using Linked Audiences, you must set *Add* or *Remove* as the value for the **DMP User Action** field, as Linked Audiences doesn't support the **Auto Detect** option.
```

2024-11-14 17:28 UTC, stayseesong commented on src/connections/destinations/catalog/actions-linkedin-audiences/index.md
> +This error occurs when the **DMP User Action** field is not set to "Add" or "Remove" in the mapping. Or it's set to "Auto Detect," which comes with a couple of caveats:
```suggestion
This error occurs when the **DMP User Action** field isn't set to *Add* or *Remove* in the mapping, or it's set to *Auto Detect,* which comes with a couple of caveats:
```

2024-11-14 17:28 UTC, stayseesong commented on src/connections/destinations/catalog/actions-linkedin-audiences/index.md
> +- For Linked Audiences, you must set "Add" or "Remove" as the value for the **DMP User Action** field, as the **Auto Detect** option is not supported.
```suggestion
- For Linked Audiences, you must set *Add* or *Remove* as the value for the **DMP User Action** field, as the **Auto Detect** option isn't supported.
```

2024-11-14 17:28 UTC, stayseesong commented on src/connections/destinations/catalog/actions-linkedin-audiences/index.md
> +- For Profile Audiences, it must match the default "Enter Event" names set in the destination settings at the Audience level. Those defaults are "Audience Entered" and "Audience Exited."
```suggestion
- For Profile Audiences, it must match the default *Enter Event* names set in the destination settings at the Audience level. Those defaults are *Audience Entered* and *Audience Exited*.
```

2024-11-15 19:34 UTC, marinhero commented
Thanks for the review @stayseesong. Your comments have been addressed 🙇🏽

2024-11-19 18:28 UTC, stayseesong approved these changes

2024-11-19 18:39 UTC, merged