csharp singleton update
segmentio/segment-docs pull request #7226
Opened 2024-11-14 12:32 UTC by niallzato

### Proposed changes
Add warning about singleton management

2024-11-14 15:10 UTC, wenxi-zeng approved these changes

2024-11-14 15:10 UTC, wenxi-zeng commented on src/connections/sources/catalog/libraries/server/csharp/index.md
> +>When using the library with a scoped lifetime, be aware of potential consequences. Our SDK is designed to be stateless, meaning objects are disposed of when the analytics instance is disposed. We av
probably better to replace stateless to disposable to avoid confusion, because stateless could mean different things especially on server side
```suggestion
>When using the library with a scoped lifetime, be aware of potential consequences. Our SDK is designed to be disposable, meaning objects are disposed of when the analytics instance is disposed. We avoid using singletons for configurations or HTTP clients to prevent memory management issues. Instead, if customers wish to use singletons, we recommend customers create their own HTTP client provider with a singleton HTTP client for better control and management.
```

2024-11-14 16:23 UTC, wenxi-zeng submitted a review, later dismissed

2024-11-20 11:48 UTC, niallzato commented
@pwseg  are we good to merge this? Thanks!

2024-12-10 12:03 UTC, niallzato commented
@pwseg or @forstisabella  are we good to merge this? Thanks!

2024-12-10 14:26 UTC, forstisabella requested changes

2024-12-10 14:26 UTC, forstisabella commented
> @pwseg or @forstisabella are we good to merge this? Thanks!

Once a few small changes are made we'll be g2g 🚀

2024-12-18 21:50 UTC, forstisabella approved these changes

2024-12-18 21:50 UTC, merged