Add postscript destination doc
segmentio/segment-docs pull request #7230
Opened 2024-11-15 21:14 UTC by julesbravo

### Proposed changes
Added Postscript destination docs

### Merge timing
At your convenience

### Related issues (optional)
None

2024-11-15 21:16 UTC, julesbravo commented
I'm seeing closing quotes for all my quotes so I'm not sure what is going on here. Please provide more info.

2024-11-18 12:44 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-postscript/index.md
> +[<Postscript>](https://postscript.io/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} empowers ecommerce brands to drive incremental revenue through SMS marketing. With
hi @julesbravo - thanks for raising this PR. 
The Segment Docs team will also review and will then push live. 

I'll just add some preliminary feedback. 

Could we add a short description to explain what this Integration does for the customer please?
i.e Enables Segment Engage Audiences to be sync to Postscript...

2024-11-18 12:45 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-postscript/index.md
> +9. Copy this private key and paste it into the **Secret Key** field in the Postscript destination settings in Segment.
Can we also add a couple of lines to explain that the customer needs to configure the 'Sync Audiences' Action before Audience data can be synced?

2024-11-18 12:46 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-postscript/index.md
> +[<Postscript>](https://postscript.io/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} empowers ecommerce brands to drive incremental revenue through SMS marketing. With
It might also be worth explaining that identifiers which can be used to sync to Postscript are: email, phone only.

2024-11-18 18:00 UTC, pwseg commented on src/connections/destinations/catalog/actions-postscript/index.md
> +[<Postscript>](https://postscript.io/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} empowers ecommerce brands to drive incremental revenue through SMS marketing. With
```suggestion
[Postscript](https://postscript.io/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank"} empowers ecommerce brands to drive incremental revenue through SMS marketing. With tools for subscriber growth, personalized messaging, and performance tracking, Postscript helps businesses engage their audience and boost conversions.
```

@julesbravo 

I think the angle brackets is triggering the quote error.  Can you try removing them from around the word Postscript in this link?

2024-11-18 18:01 UTC, pwseg commented
> I'm seeing closing quotes for all my quotes so I'm not sure what is going on here. Please provide more info.

I'm guessing that the chevrons/angle brackets around `Postscript` are causing that error.  Could you remove them?

2024-11-18 22:50 UTC, stayseesong commented on src/connections/destinations/catalog/actions-postscript/index.md
> +2. Select <YOURINTEGRATION> and click **Add Destination**.
```suggestion
2. Select **Postscript** and click **Add Destination**.
```

2024-11-18 22:50 UTC, stayseesong commented on src/connections/destinations/catalog/actions-postscript/index.md
> +1. From your workspace's [Destination catalog page](https://app.segment.com/goto-my-workspace/destinations/catalog){:target="_blank"} search for "Postscript".
```suggestion
1. From your workspace's [Destination catalog page](https://app.segment.com/goto-my-workspace/destinations/catalog){:target="_blank"} search for *Postscript*.
```

2024-11-18 22:50 UTC, stayseesong commented on src/connections/destinations/catalog/actions-postscript/index.md
> +7. **Add a label** of "Segment" to your API key so you can track where this API key is used.
Is **Add a label** a button users can click?

2024-11-18 22:50 UTC, stayseesong commented on src/connections/destinations/catalog/actions-postscript/index.md
> +1. From your workspace's [Destination catalog page](https://app.segment.com/goto-my-workspace/destinations/catalog){:target="_blank"} search for "Postscript".
@joe-ayoub-segment will the destination be called Postscript (Actions) in Segment?

2024-11-19 10:15 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-postscript/index.md
> +1. From your workspace's [Destination catalog page](https://app.segment.com/goto-my-workspace/destinations/catalog){:target="_blank"} search for "Postscript".
Hi @stayseesong it's just called 'Postscript'. The Slug is actions-postscript

2024-11-21 15:25 UTC, julesbravo commented on src/connections/destinations/catalog/actions-postscript/index.md
> +7. **Add a label** of "Segment" to your API key so you can track where this API key is used.
It is a placeholder on an input 
![image](https://github.com/user-attachments/assets/e0ddabf0-f7fa-4b92-b97b-bc7a57984af5)

2024-11-25 20:24 UTC, tcgilbert requested changes
@julesbravo just one more thing to add. Otherwise, looks good to me. 

> I'm still seeing the error on closing quotes, but when I ran it through a markdown validator it came back clean.

the bot comments are new to me, not sure if this is an issue that would prevent this from being merged. @stayseesong  is there anything left to change from the docs team POV?

2024-11-25 20:24 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-postscript/index.md
> +---
```suggestion
---
title: Postscript Destination
id: 66f2b0818aa856d4d2d87f90
---
```

2024-11-26 16:15 UTC, julesbravo commented
Added the ID

2024-11-27 21:47 UTC, tcgilbert approved these changes

2024-12-02 15:57 UTC, julesbravo commented
How long should I expect this to take to review/merge?

2024-12-02 16:16 UTC, tcgilbert commented
@julesbravo we deploy these on Tuesdays and Thursdays. I'll ping our docs team to make sure this gets included in tomorrows deploy. 

With this complete, once you are ready for the destination to go live in the catalog please submit it for final review from the dev portal here: https://app.segment.com/dev-portal/integrations/destination/actions-postscript/status

2024-12-06 17:34 UTC, pwseg approved these changes

2024-12-06 17:35 UTC, merged

2024-12-06 18:01 UTC, pwseg commented
@julesbravo Thanks for submitting this and working with the team to get it updated.  

Here's the live link in our docs:

[Postscript Destination](https://segment.com/docs/connections/destinations/catalog/actions-postscript/)