Create Drip documentation index.md
segmentio/segment-docs pull request #7241
Opened 2024-11-20 18:50 UTC by jacobpmeyer

### Proposed changes

Adding docs for the Drip Actions Destination

### Merge timing
Whenever works for y'all

2024-11-25 20:19 UTC, tcgilbert requested changes
just a couple changes, otherwise looks good

2024-11-25 20:19 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-drip/index.md
> +---
```suggestion
--
title: Drip (Actions) Destination
id: 673b62169b3342fbe0fc28da
---
```

2024-11-25 20:19 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-drip/index.md
> +> (delete after reading) The section below explains how to enable and configure the destination. Include any configuration steps not captured below. For example, obtaining an API key from your platfo
```suggestion
```

2024-11-25 20:19 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-drip/index.md
> +1. From your workspace's [Destination catalog page](https://app.segment.com/goto-my-workspace/destinations/catalog){:target="_blank”} search for "Drip".
```suggestion
1. From your workspace's [Destination catalog page](https://app.segment.com/goto-my-workspace/destinations/catalog){:target="_blank”} search for "Drip (Actions)".
```

2024-11-25 20:19 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-drip/index.md
> +2. Select Drip and click **Add Destination**.
```suggestion
2. Select Drip (Actions) and click **Add Destination**.
```

2024-11-26 18:06 UTC, jacobpmeyer commented
Thanks @tcgilbert! I pushed up those changes just now

2024-12-04 22:02 UTC, pwseg approved these changes

2024-12-04 22:03 UTC, merged