Initial Commit
segmentio/segment-docs pull request #7242
Opened 2024-11-20 22:38 UTC by mayur-pitale

### Proposed changes

### Merge timing

### Related issues (optional)

2024-12-03 21:50 UTC, stayseesong commented
@mayur-pitale is this still being drafted or is it ready for review?

2024-12-03 23:06 UTC, mayur-pitale commented
@stayseesong - ready for review

2024-12-04 13:13 UTC, tcgilbert requested changes

2024-12-04 13:13 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-s3/index.md
> +title: S3 (Actions) Destination
```suggestion
title: AWS S3 (Actions) Destination
```

This is the integration name on our backend. If you need to update this lmk

2024-12-04 17:03 UTC, tcgilbert submitted a review, later dismissed

2024-12-04 21:06 UTC, stayseesong requested changes

2024-12-04 21:06 UTC, stayseesong commented on src/connections/destinations/catalog/actions-s3/index.md
> +To setup the IAM role to properly authorize Segment with the AWS S3 (Actions) destination, follow the steps below.
```suggestion
To set up the IAM role to properly authorize Segment with the AWS S3 (Actions) destination:
```

2024-12-04 21:06 UTC, stayseesong commented on src/connections/destinations/catalog/actions-s3/index.md
> +4. Provide the following policy permissions for the IAM that was just created:
```suggestion
1. Log in to your AWS account. 
2. Create a new or use an existing bucket with `PutObject`, `GetObject`, `ListObject` access to the S3 bucket.
3. Navigate to **IAM > Roles > Create Role**.
4. Provide the following policy permissions for the IAM that was just created: 
```

2024-12-04 21:06 UTC, stayseesong commented on src/connections/destinations/catalog/actions-s3/index.md
> +5. Click on the Trust Relationships tab and edit the trust policy to allow the IAM user to assume the role (If a user is not already created, please refer to the AWS documentation to create a user)
```suggestion
5. Click on the Trust Relationships tab and edit the trust policy to allow the IAM user to assume the role. If a user is not already created, refer to the AWS documentation to create a user.
```

2024-12-04 21:06 UTC, stayseesong commented on src/connections/destinations/catalog/actions-s3/index.md
> +## Add AWS S3 (Actions) Destination in Segment
```suggestion
## Step 2: Add the AWS S3 (Actions) Destination in Segment
```

2024-12-04 21:06 UTC, stayseesong commented on src/connections/destinations/catalog/actions-s3/index.md
> +To finish configuration, enable the AWS S3 (Actions) Destination in your workspace.
```suggestion
To finish the configuration, enable the AWS S3 (Actions) Destination in your workspace. 
```

2024-12-04 21:06 UTC, stayseesong commented on src/connections/destinations/catalog/actions-s3/index.md
> +6. Verify Segment data is stored in the S3 bucket by navigating to the `<your_S3_bucket>/` in the AWS console.
```suggestion
1. Add the **AWS S3 (Actions)** destination from the Destinations tab of the catalog.
2. Select the data source you want to connect to the destination.
3. Provide a unique name for the destination.
4. Complete the destination settings:
   * Enter the name of the region in which the bucket you created above resides.
   * Enter the name of the bucket you created above. Be sure to enter the bucket's **name** and not URI.
   * Enter the ARN of the IAM role you created above. The ARN should follow the format `arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME.`
   * Enter the IAM External ID, which is a value set in the Trust Relationship under your AWS IAM Role.
5. Enable the destination.
6. Verify the Segment data is stored in the S3 bucket by navigating to the `<your_S3_bucket>/` in the AWS console. 
```

2024-12-05 17:18 UTC, stayseesong commented on src/connections/destinations/catalog/actions-s3/index.md
> +- [Sync to S3](#sync-to-s3)
@mayur-pitale sorry, one last thing, where is this linking to? there is no #syn-to-s3 section on this page

2024-12-05 18:47 UTC, stayseesong commented
@mayur-pitale also wanted to confirm, this integration is in beta?

2024-12-05 18:49 UTC, mayur-pitale commented
> @mayur-pitale also wanted to confirm, this integration is in beta?

@stayseesong - I removed the Actions section. I believe including the actions-fields.html should include any actions connected to this destination, correct?

2024-12-05 18:51 UTC, stayseesong commented
correct, adding actions-fields.html includes any actions connected to the destination. 

But is this integration in beta?

2024-12-05 18:57 UTC, mayur-pitale commented
> correct, adding actions-fields.html includes any actions connected to the destination.
> 
> But is this integration in beta?

@stayseesong - Yes it is in private beta

2024-12-05 19:05 UTC, stayseesong approved these changes

2024-12-05 19:05 UTC, merged