Unify space removal info on A&DD page [DOC-1014]
segmentio/segment-docs pull request #7257
Opened 2024-11-22 22:05 UTC by forstisabella

### Proposed changes
Added sections for Unify space disable/deletion

### Merge timing
After Atit's approval

### Related issues (optional)
Blocker for DOC-1011

2024-11-22 22:06 UTC, forstisabella commented on src/privacy/account-deletion.md
> +### Disable an Engage space
```suggestion
### Delete an Engage space
```

2024-11-22 23:43 UTC, stayseesong requested changes

2024-11-22 23:43 UTC, stayseesong commented on src/privacy/account-deletion.md
> +You can remove a Unify space from your workspace by disabling it, which hides the space from the Segment UI, or by deleting it, which removes all data about that space from Segment's servers. Disable
```suggestion
You can remove a Unify space from your workspace by disabling it, which hides the space from the Segment UI, or by deleting it, which removes all data about that space from Segment's servers. Disabled or deleted spaces don't count toward your [Unify limits](/docs/unify/product-limits/). 
```

2024-11-22 23:43 UTC, stayseesong commented on src/privacy/account-deletion.md
> +> warning "You cannot reuse space names"
```suggestion
> warning "You can't reuse space names"
```

2024-11-22 23:43 UTC, stayseesong commented on src/privacy/account-deletion.md
> +> Do not use the names of previously disabled or deleted spaces for new Unify spaces.
```suggestion
> Don't use the names of previously disabled or deleted spaces for new Unify spaces.
```

2024-11-22 23:43 UTC, stayseesong commented on src/privacy/account-deletion.md
> +Disabled spaces are not accessible from the Segment app UI, but all data from your space remains on Segment's servers. Disabled spaces do not count toward your Unify space limit, and can be re-enable
```suggestion
Disabled spaces aren't accessible from the Segment app UI, but all data from your space remains on Segment's servers. Disabled spaces don't count toward your Unify space limit, and can be re-enabled by sending an email to the Customer Success team [(friends@segment.com)](mailto:friends@segment.com).
```

2024-11-22 23:43 UTC, stayseesong commented on src/privacy/account-deletion.md
> +Deleted spaces, and all data associated with a deleted space, are permanently removed from Segment's servers. You cannot recover a deleted space.
```suggestion
Deleted spaces, and all data associated with a deleted space, are permanently removed from Segment's servers. You can't recover a deleted space. 
```

2024-12-03 21:49 UTC, stayseesong approved these changes

2024-12-03 22:00 UTC, merged