MVP of SingleStore documentation
segmentio/segment-docs pull request #7258
Opened 2024-11-25 01:14 UTC by ugpeter

### Proposed changes

Created the first version of the SingleStore documentation.

### Merge timing
ASAP once approved

### Related issues (optional)

None

2024-11-27 21:46 UTC, tcgilbert requested changes
just one thing to add for me

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +[<SingleStore>](https://singlestore.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank”} is a high-performance, cloud-native database designed for real-time analytics an
```suggestion
[SingleStore](https://singlestore.com/?utm_source=segmentio&utm_medium=docs&utm_campaign=partners){:target="_blank”} is a high-performance, cloud-native database designed for real-time analytics and applications. By integrating SingleStore and Segment, you can ingest, analyze, and act on your customer data instantly, unlocking faster insights for your business.
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +This destination is maintained by SingleStore. For any issues with the destination, [contact SingleStore Support team](https://support.singlestore.com/).
```suggestion
This destination is maintained by SingleStore. For any issues with the destination, [contact the SingleStore Support team](https://support.singlestore.com/){:target="_blank”}.
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +5. Click "Save"
The docs site automatically has sequential numbering, so combining these steps won't have an impact on the way this list appears on the site!

```suggestion
4. Enter a name for your SingleStore (Actions) destination, update any additional settings, then click **Save**. 
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +6. Now go to your "Mappings" and click "New Mapping"
```suggestion
6. Navigate to the Mappings tab for your SingleStore destination and click **New Mapping**.
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +7. Select "Send Data"
```suggestion
7. Select **Send Data**. 
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +8. Within "Map fields", select your database from the list presented
```suggestion
8. In the Map fields section, select your database from the list presented.
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +9. Click "Next" and then "Save"
```suggestion
9. Click **Next** and then **Save**.  
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +10. Voila!  Your data should start flowing into your SingleStore database within moments.
```suggestion
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +You can generally find your SingleStore connection settings by heading to the [SingleStore Portal](https://portal.singlestore.com) and following these steps:
```suggestion
To find your SingleStore connection settings, head to the [SingleStore Portal](https://portal.singlestore.com){:target="_blank”} and complete the following steps:
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +4. Choose Connect to your own app and that will provide the key settings
Do you need to enter these settings during the process in the Segment app? If so, we should probably make this a prerequisite section and move it above the steps under Getting started 

cc @ugpeter 

```suggestion
1. Select **Deployments**.
2. Choose your Workspace and Database within the list of Deployments
3. From the Connect dropdown, select **Connect to your own app**. SingleStore will display the the key settings you need to connect your SingleStore database to Segment. 
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +## The database structure
```suggestion
## Database structure
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +|`type`|	VARCHAR(255)|	The type of the event (e.g., identify, track, page, group)|
```suggestion
Segment creates a table called `segment_raw_data` and writes data to your SingleStore database using the following schema:

| Column |	Type	| Description |
| -------- | ------ |  ----------- |
| `message` |	JSON (utf8_bin) |	The entire message received from Segment, in JSON format |
| `timestamp` |	datetime |	The timestamp of when the event was generated |
| `event` |	VARCHAR(255) |	The event name (for Track events) |
| `messageId` |	VARCHAR(255) |	The unique identifier of the event to ensure there is no duplication |
| `type` |	VARCHAR(255) |	The type of the event (for example, Identify, Track, Page, Group) |
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +This query retrieves the properties object from the JSON message, allowing you to work with nested event data.
````suggestion
### Accessing nested data
To query specific data from the Segment event within SingleStore, you can de-reference the JSON pointer within the message column. For example:

```sql
SELECT message::properties FROM segment_raw_data;
```

This query retrieves the properties object from the JSON message, allowing you to work with nested event data.
````

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +**Solution:**
```suggestion
If you're unable to connect to the SingleStore database:
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +**Solution:**
```suggestion
If you encounter authentication errors when Segment attempts to connect:
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +**Solution:**
```suggestion
If events are not recorded in the `segment_raw_data` table:
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +By default, the mapping is predefined to store the complete raw Segment events in the segment_raw_data table. If you prefer, within the mapping, you can choose to selectively include or exclude speci
```suggestion
By default, the mappings store the complete raw Segment events in the `segment_raw_data` table. If you prefer, within the mapping, you can choose to selectively include or exclude specific fields to be sent and written into SingleStore.
```

2024-12-02 16:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +All event data is stored natively as JSON within the message column. This allows for flexible schema management and easy access to nested properties using SQL queries.  SingleStore's ability to dynam
```suggestion
All event data is stored natively as JSON in the message column. This allows for flexible schema management and easy access to nested properties using SQL queries.  SingleStore's ability to dynamically and quickly parse the JSON allows all types of complex events to be queried or used in notebooks.
```

2024-12-06 00:47 UTC, ugpeter commented
Thanks so much for the feedback.  I have accepted all code changes requested and believe this is good to go.  @tcgilbert @forstisabella - Please feel free to merge this PR into the mainline.  Thanks so much.

2024-12-06 00:48 UTC, ugpeter commented on src/connections/destinations/catalog/actions-singlestore/index.md
> +4. Choose Connect to your own app and that will provide the key settings
In answer to your question, you don't _need to_ do these steps.  These are additional, in case the user doesn't know how to find their credentials.

2024-12-06 15:28 UTC, tcgilbert approved these changes

2024-12-06 15:32 UTC, tcgilbert commented
@forstisabella, you can include this in the next docs deployment.

@ugpeter, since the catalog metadata has been submitted, we’re ready to move the integration to Public Beta once the docs are live. If you’d prefer to wait for a specific date, please let me know. Otherwise, I’ll proceed with making the integration live.

2024-12-10 14:41 UTC, forstisabella approved these changes

2024-12-10 14:41 UTC, merged