[RETL] add content for RETL cancel syncs
segmentio/segment-docs pull request #7273
Opened 2024-11-27 20:44 UTC by reneewang21

### Proposed changes

This PR updates the RETL `Manage Reverse ETL Syncs` tab with the new canceling syncs functionality.

### Merge timing
ASAP once approved?

### Related issues (optional)

2024-12-04 18:10 UTC, stayseesong commented
@reneewang21 I'm going through the steps in what you drafted, but I don't see the 3 dots or the Cancel Syncs button within Segment.

2024-12-05 18:05 UTC, reneewang21 commented
> @reneewang21 I'm going through the steps in what you drafted, but I don't see the 3 dots or the Cancel Syncs button within Segment. Let's discuss this when you come back from OOO

Hey @stayseesong, the `Cancel sync` option will only be available if a sync is extracting/loading in progress, and won't show up for any finished syncs since there will be no-op for those situations. I attached a screenshot from Prod app for your reference. LMK if you have any other questions.

![Screenshot 2024-12-05 at 10 03 13 AM](https://github.com/user-attachments/assets/9a8c6bb8-ea04-41ca-a766-5cad71f0a4e3)

2024-12-06 18:36 UTC, stayseesong requested changes

2024-12-06 18:36 UTC, stayseesong commented on src/connections/reverse-etl/manage-retl.md
> +Once a sync is canceled, the record count under 'Extraction Results' reflects the records already processed, which will not be included in future syncs. To reprocess these records, you can reset or r
```suggestion
You can cancel syncs when your sync is currently running during the extraction and load phase. 

To cancel a sync:
1. Navigate to **Connections > Destinations > Reverse ETL**.
2. Select the mapping with a sync that is in progress.
3. Select the sync that is in progress.
4. Click **Cancel sync** to cancel the sync. 
5. Select the reason for canceling the sync. 

Your canceled syncs with have a status as *Canceled,* and any syncs that are in the process of being canceled will have a status of *Canceling*. 

Once you cancel a sync, the record count under **Extraction Results** reflects the records already processed. These records won't be included in future syncs. To reprocess these records, you can reset or replay the sync.
```

2024-12-10 19:37 UTC, stayseesong approved these changes

2024-12-10 19:38 UTC, merged