Antavo Source documentation
segmentio/segment-docs pull request #7275
Opened 2024-11-29 10:53 UTC by bbantavo

### Proposed changes

Added Antavo Source documentation files.

### Merge timing

asap

### Related issues (optional)

2024-12-02 16:32 UTC, tcgilbert requested changes

2024-12-02 16:32 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/antavo/index.md
> +Any customer attribute in Antavo can be selected as "external customer ID".
```suggestion
## Events

Antavo syncs two main types of events to Segment: Profile Updates and Loyalty Events. Profile Updates are sent as Segment Identify events, while Loyalty Events are sent as Segment Track events.

Both event types include a `userId`, which can be configured in Antavo. You can designate any customer attribute as the "external customer ID" to use as the Segment `userId`.
```

2024-12-02 16:32 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/antavo/index.md
> +- Customer attributes are included in `traits` object.
```suggestion
### Profile updates

Profile Updates occur when a customer attribute, added to the Antavo **Customer field sync***, updates. Customer attributes are included in the traits object.
```

2024-12-02 16:32 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/antavo/index.md
> +- Event properties are included in `properties` object.
```suggestion
### Loyalty events

Loyalty Events occur when a built-in or custom event, added to the Antavo Event sync, is triggered. The event data is then sent to the Segment Antavo Source. Event properties are included in the properties object.
```

2024-12-02 16:32 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/antavo/index.md
> +- Event properties are included in `properties` object.
@bbantavo What are the different event names a customer can expect to be sent into Segment? Is there a standard list of events, or is this all configured in a custom way by the user? If there is a standardized list, we ask that partner provide a table of the expected events: 

e.g., 

```
| Event Name         | Description                           |
| ------------------ | ------------------------------------- |
| Email Sent         | Email was sent successfully           |
| Email Opened       | Prospect opened the email             | 
| Link Clicked       | Prospect clicked the tracking link    | 
| Email Replied      | Prospect replied to email sent        | 
| Email Bounced      | Email servers rejected the email      | 
| Email Unsubscribed | Prospect clicked the unsubscribe link | 
```

2024-12-05 14:08 UTC, bbantavo commented on src/connections/sources/catalog/cloud-apps/antavo/index.md
> +Any customer attribute in Antavo can be selected as "external customer ID".
hi @tcgilbert 

thanks, this is now applied

2024-12-05 14:08 UTC, bbantavo commented on src/connections/sources/catalog/cloud-apps/antavo/index.md
> +- Customer attributes are included in `traits` object.
hi @tcgilbert 

thanks for the suggestion, this is now applied

2024-12-05 15:59 UTC, bbantavo commented on src/connections/sources/catalog/cloud-apps/antavo/index.md
> +- Event properties are included in `properties` object.
Hi @tcgilbert 

Our Source integration requires our clients to configure which events they want to sync to Segment. By default no event is synced.

Our clients have a start set of built-in events which are fully customizable, and they also have the ability the define custom events.

We can provide information about our built-in events, but their meaning could differ from client to client.

2024-12-06 15:49 UTC, tcgilbert requested changes
just one last thing, but lgtm

2024-12-06 15:49 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/antavo/index.md
> +```
```suggestion
---
title: Antavo Source
id: WXNgKpZMsd
---
```

2024-12-11 10:16 UTC, bbantavo commented on src/connections/sources/catalog/cloud-apps/antavo/index.md
> +```
hi @tcgilbert 

this is now updated, please check

2024-12-11 14:58 UTC, tcgilbert approved these changes

2025-01-06 20:14 UTC, tcgilbert requested changes

2025-01-06 20:14 UTC, tcgilbert commented on src/connections/sources/catalog/cloud-apps/antavo/index.md
> +
### Integrations Object

Antavo automatically filters data from being sent to Salesforce destinations ([Salesforce (Actions)](/docs/connections/destinations/catalog/actions-salesforce), [Salesforce Marketing Cloud (Actions)](/docs/connections/destinations/catalog/actions-salesforce-marketing-cloud)) and the [Antavo](/docs/connections/destinations/catalog/antavo) destination. This is achieved by adding these destinations to the [Integrations object](/docs/guides/filtering-data/#filtering-with-the-integrations-object) in the event payloads. Since Antavo has a dedicated Salesforce integration, this filtering helps prevent infinite loops.

2025-01-08 07:59 UTC, bbantavo commented on src/connections/sources/catalog/cloud-apps/antavo/index.md
> +
hi @tcgilbert !

thanks for the suggestion! we'll apply it shortly

quick note: the links seems to be pointing to `github.com` domain (throwing 404s), but I'm guessing it should be to `segment.com` instead

2025-01-08 12:24 UTC, bbantavo commented on src/connections/sources/catalog/cloud-apps/antavo/index.md
> +
Hi @tcgilbert !

Updated this section, please check!

2025-01-08 19:19 UTC, tcgilbert approved these changes

2025-01-09 06:21 UTC, pwseg approved these changes

2025-01-09 06:22 UTC, merged