Antavo Destination documentation
segmentio/segment-docs pull request #7276
Opened 2024-11-29 15:21 UTC by bbantavo

Proposed changes
Added Antavo Destination documentation files.

Merge timing
asap

Related issues (optional)

2024-12-05 13:24 UTC, bbantavo commented on src/connections/destinations/catalog/antavo/index.md
> +7. If you haven’t configured the Segment integration in Antavo, please go to the Modules menu and enable Twilio Segment Extension
hi @stayseesong 

thanks for the suggestions, we have applied them, please check them

2024-12-06 15:46 UTC, tcgilbert commented
@bbantavo @stayseesong - we can merge this as hidden once my requested changes are in. The destination is still pending review, so there is no destination id for this yet

2024-12-13 23:11 UTC, stayseesong commented
@tcgilbert I don't see your requested changes

2024-12-16 22:43 UTC, tcgilbert requested changes

2024-12-16 22:43 UTC, tcgilbert commented
> @tcgilbert I don't see your requested changes

@stayseesong sorry was left in pending! added my review now @bbantavo

2024-12-18 14:37 UTC, bbantavo commented on src/connections/destinations/catalog/antavo/index.md
> +7. If you haven’t configured the Segment integration in Antavo, go to the **Modules** menu and enable the Twilio Segment Extension in Antavo.
hi @tcgilbert 

we've applied the changes, please check

2024-12-18 15:08 UTC, tcgilbert approved these changes

2024-12-18 21:41 UTC, stayseesong commented
@tcgilbert is this good to merge in even though there's no destination ID?

2024-12-19 17:49 UTC, stayseesong approved these changes

2024-12-19 17:50 UTC, merged