Attentive
segmentio/segment-docs pull request #7288
Opened 2024-12-04 20:57 UTC by wtnelso

### Proposed changes

### Merge timing

### Related issues (optional)

2024-12-04 21:17 UTC, forstisabella commented
hi @wtnelso - is this for a new Attentive (Actions) destination, or are you adding Actions to an existing documentation? 

cc: @tcgilbert

2024-12-05 18:30 UTC, wtnelso commented
Hi @forstisabella, i'm adding to existing documentation, but this is the first time we're rolling out action destinations.

2024-12-05 19:00 UTC, forstisabella commented
> Hi @forstisabella, i'm adding to existing documentation, but this is the first time we're rolling out action destinations.

Okay great! if you're rolling out an Actions destination for the first time, you'll need to create a new folder named `actions-attentive` in the src/connections/destinations/catalog folder and add the content included in this PR to an `index.md` file.

2024-12-05 19:59 UTC, wtnelso commented
Hi @forstisabella I just made the requested updates and committed those changes.

2024-12-06 15:40 UTC, tcgilbert requested changes

2024-12-06 15:40 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-attentive/index.md
> +[Attentive](https://www.attentive.com/?utm_source=partner-generated&utm_medium=partner-marketing-&utm_campaign=partner-generated-4.15.22-segment.io){:target="_blank"} with Segment makes it easy to sy
```suggestion
---
title: Attentive (Actions) Destination
id: 674f2453916dadbd36d899dc
---

[Attentive](https://www.attentive.com/?utm_source=partner-generated&utm_medium=partner-marketing-&utm_campaign=partner-generated-4.15.22-segment.io){:target="_blank"} with Segment makes it easy to sync customer and event data from Segment to Attentive so that you can send highly personalized and timely messages.
```

2024-12-06 15:40 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-attentive/index.md
> +### Destination Actions
```suggestion
## Getting Started
```

2024-12-06 15:40 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-attentive/index.md
> +Attentive (Actions) Destination
```suggestion
```

2024-12-06 15:40 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-attentive/index.md
> +This destination is maintained by Attentive. For any issues with the destination, contact their [Support team](mailto:whiteglove@attentivemobile.com).
```suggestion
```

2024-12-06 15:40 UTC, tcgilbert commented on src/connections/destinations/catalog/actions-attentive/index.md
> +(delete after reading) Additional Context
```suggestion
```

2024-12-06 15:40 UTC, tcgilbert commented on src/connections/destinations/catalog/attentive/index.md
Can you remove this file from the PR? 
- There is a better way to indicate that there is a new attentive destination, and I can submit a separate PR for this
- The folder name needs to stay as `attentive-mobile` as that is the unique slug for this integration.

2024-12-09 14:43 UTC, wtnelso commented
Hi @tcgilbert I made the requested updates, I think, could you please review?

2024-12-10 14:38 UTC, forstisabella requested changes

2024-12-10 14:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-attentive/index.md
> +(delete after reading) Additional Context
```suggestion
```

2024-12-10 14:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-attentive/index.md
> +{% include content/plan-grid.md name="actions" %}
```suggestion
```

2024-12-10 14:38 UTC, forstisabella commented on src/connections/destinations/catalog/actions-attentive/index.md
> +
```suggestion
The Attentive's (Actions) Destination leverages Attentive's APIs. For more information on the APIs, see [Attentive's Developer Site](https://docs.attentivemobile.com/){:target="_blank"}. 

```

2024-12-10 17:55 UTC, wtnelso reviewed
Requested changes made.

2024-12-10 18:04 UTC, forstisabella approved these changes

2024-12-10 18:51 UTC, tcgilbert approved these changes

2024-12-10 19:00 UTC, merged