[Twilio Messaging] - adding docs for new Twilio Messaging Destination
segmentio/segment-docs pull request #7306
Opened 2024-12-09 13:41 UTC by joe-ayoub-segment

Docs for new Twilio Messaging Actions Destination. 

### Proposed changes

Docs for new Twilio Messaging Actions Destination. 

### Merge timing
I'll add a comment to this PR when the PR should be deployed. 

### Related issues (optional)

2024-12-12 01:54 UTC, stayseesong requested changes

2024-12-12 01:54 UTC, stayseesong commented on src/connections/destinations/catalog/actions-twilio-messaging/index.md
> +5. Enable the Destination then click the **Save Changes** button.
```suggestion
To create the Twilio Messaging destination:
1. From your Segment workspace's [Destination catalog page](https://app.segment.com/goto-my-workspace/destinations/catalog){:target="_blank”} search for *Twilio Messaging*.
2. Select the *Twilio Messaging* and click **Add Destination**.
3. Select an existing Source to connect to Twilio Messaging.
4. On the Settings page, provide the **Twilio Account SID**, **Twilio API Key SID** and **Twilio API Key Secret** values.
5. Enable the Destination then click **Save Changes**. 
```

2024-12-12 01:54 UTC, stayseesong commented on src/connections/destinations/catalog/actions-twilio-messaging/index.md
> +### Create the Twilio Messaging Destination
```suggestion
### Create the Twilio Messaging destination 
```

2024-12-12 01:54 UTC, stayseesong commented on src/connections/destinations/catalog/actions-twilio-messaging/index.md
> +### Configure the Send message Mapping
```suggestion
### Configure the Send message mapping
```

2024-12-12 01:54 UTC, stayseesong commented on src/connections/destinations/catalog/actions-twilio-messaging/index.md
> +3. Provide Mapping Trigger and Field values to configure the Mapping. Then Save and Enable the Mapping.
```suggestion
To configure the Send message mapping:
1. From the Twilio Messaging Destination's **Settings** page, navigate to **Mapping > New Mapping**.  
2. Select the **Send message** Action. 
3. Provide Mapping Trigger and Field values to configure the Mapping. 
4. Save and enable the Mapping. 
```

2024-12-12 01:54 UTC, stayseesong commented on src/connections/destinations/catalog/actions-twilio-messaging/index.md
> +Messages can be sent via SMS, MMS, WhatsApp and Facebook Messenger channels.
```suggestion
You can send messages using SMS, MMS, WhatsApp and Facebook Messenger channels. 
```

2024-12-12 01:54 UTC, stayseesong commented on src/connections/destinations/catalog/actions-twilio-messaging/index.md
> +The following Twilio Content Template types are supported: **Text**, **Media**, **Quick reply**, **Call to action**, **List picker**, **Card**, **WhatsApp card**, **WhatsApp Authentication** and **Ca
```suggestion
Segment supports these Twilio Content Template types: Text, Media, Quick reply, Call to action, List picker, Card, WhatsApp card, WhatsApp Authentication and Catalog.
```

2024-12-12 01:54 UTC, stayseesong commented on src/connections/destinations/catalog/actions-twilio-messaging/index.md
> +Messages can also be sent without referencing a Twilio Content Template. In this case the message body, Media URLs, and variables can be defined directly in Mapping fields. Segment then constructs th
```suggestion
You can send messages without referencing a Twilio Content Template. In this case the message body, Media URLs, and variables can be defined directly in Mapping fields. Segment then constructs the final message body by combining the provided body and variables before sending it through Twilio.
```

2024-12-12 01:54 UTC, stayseesong commented on src/connections/destinations/catalog/actions-twilio-messaging/index.md
> +4. Define variables using the **Inline Variables** field. Make sure to define variables for every variable included in the message body.
```suggestion
1. Select **Inline** from the *Content Template Type* mapping field. 
2. Provide the message body in **Inline Template**. You can include variables using Handlebars notation. For example, `{{first_name}}`.
3. Provide Media URLs in **Inline Media URLs**. 
4. Define variables using the **Inline Variables**. Make sure to define variables for every variable included in the message body. 
```

2024-12-12 01:54 UTC, stayseesong commented on src/connections/destinations/catalog/actions-twilio-messaging/index.md
> +1. Phone Number - An E.164 formatted phone number. Check in the Twilio Console to ensure that the selected number supports the selected Channel type.
```suggestion
1. Phone Number - An E.164 formatted phone number. Check the Twilio Console to ensure that the selected number supports the selected Channel type. 
```

2024-12-12 01:54 UTC, stayseesong commented on src/connections/destinations/catalog/actions-twilio-messaging/index.md
> +2. Messenger Sender ID - Supported only when the **Facebook Messenger** channel type is selected.
```suggestion
2. Messenger Sender ID - This is supported only when the **Facebook Messenger** channel type is selected.
```

2024-12-12 01:54 UTC, stayseesong commented on src/connections/destinations/catalog/actions-twilio-messaging/index.md
> +3. Twilio Messaging Service - Supported for all channels.
```suggestion
3. Twilio Messaging Service - This is supported for all channels. 
```

2024-12-12 18:54 UTC, stayseesong commented on src/connections/destinations/catalog/actions-twilio-messaging/index.md
> +title: [Twilio Messaging] Destination
we just need to add the destination ID

2024-12-13 11:18 UTC, joe-ayoub-segment commented on src/connections/destinations/catalog/actions-twilio-messaging/index.md
> +title: [Twilio Messaging] Destination
hi @stayseesong here is the destination ID
674f23ece330374dc1ecc874

2024-12-13 14:21 UTC, tcgilbert approved these changes
lgtm. @joe-ayoub-segment feel free to add 

```
---
...
hidden: true
...
---
```

to go ahead and get this merged, but remain hidden

2024-12-13 18:13 UTC, stayseesong commented
@joe-ayoub-segment lmk when you would like this merged in

2025-01-09 17:32 UTC, stayseesong commented
@joe-ayoub-segment is this ready to be merged in?

2025-01-10 10:19 UTC, joe-ayoub-segment commented
hi @stayseesong let's hold off on this for now. The code needs a major refactor. Thanks for following up.

2025-01-24 22:49 UTC, kylee699 approved these changes

2025-07-03 04:55 UTC, pwseg commented
@joe-ayoub-segment Thanks for opening this; I ended up pulling it into a new PR, #7727, which captures pretty much everything you wrote here.  Going to close this one out now since the docs are live.

2025-07-03 04:55 UTC, closed without merging