Rabble AI Destination Documentation
segmentio/segment-docs pull request #7309
Opened 2024-12-10 19:22 UTC by TravisHRabble

### Proposed changes

This is the initial commit for Rabble AI Destination Documentation

### Merge timing
ASAP once approved

### Related issues (optional)

2024-12-11 14:59 UTC, tcgilbert requested changes
just one change for me

2024-12-11 14:59 UTC, tcgilbert commented on src/connections/destinations/catalog/rabble-ai/index.md
> +## title: Rabble AI Destination
```suggestion
---
title: Rabble AI Destination
id: 65c0426487cd2bfcaaae517c
---
```

2024-12-12 18:36 UTC, pwseg commented
> just one change for me

Went ahead and committed this so we can deploy today.

2024-12-12 18:37 UTC, pwseg approved these changes

2024-12-12 18:57 UTC, merged